### ISSUE TITLE
Filter Option For Multi Dimensional Array

### ISSUE THREAD

**Issue by keyurptl** [xaksis/vue-good-table#100]
Thanks for such great plugin. Superb work. 

I have installed and it works like charm.  Now my question is how to handle filter option on value which is coming from multi dimensional array.

Like There is list of user and also displaying all projects which is assigned  to that user. So how can i provide filter for project list.

https://www.screencast.com/t/vm65S7VOT

Please help me on this. Much appreciated. 
Thank you so much.

**Comment by xaksis** [comment]
hey @keyurptl, thank you for using the plugin. regarding your question: columns support an option called filter which takes in a function in the following format: 
```javascript
filter: function(data, filterString) {
  var x = parseInt(filterString)
    return data >= x-5 && data <= x+5
  }
```
as you can see, filter can take a function that takes in row data and the filter string, you can then use this function to return the rows that match your criteria. Let me know if this doesn't solve your issue, and i'll re-open it.

**Comment by keyurptl** [comment]
Okay Thanks for help. It Really helps me.
