### ISSUE TITLE
Column header alignment

### ISSUE THREAD

**Issue by focussing** [xaksis/vue-good-table#101]
When the column definition contains `type: 'text',` only the header is right-aligned. Because 'text' is default, left-aligned would be expected. When I leave out the 'type: text' line it is left-aligned.

1) why is only the column header responding to this, and not all rows?
2) could 'text' be set to left-aligned as would be expected as it is the default setting?
3) despite this; how could I set 'right-aligned' for 'text' columns if I wanted to?

It could be related to this function? But that would not explain item 1)
```
      getDataStyle(index, type) {
        var classString = '';
        switch (this.columns[index].type) {
          case 'number':
          case 'percentage':
          case 'decimal':
          case 'date':
          case 'text':
            classString += 'right-align ';
          break;
          default:
            classString += 'left-align ';
            break;
        }
        if (typeof type !== 'undefined' && this.columns[index].hasOwnProperty(type + 'Class')) {
          classString += ' ';
          classString = this.columns[index][type + 'Class'];
        }
        return classString;
      },
```

**Comment by xaksis** [comment]
@focussing ... yeah that's definitely a bug. text should be left-aligned. thank you for identifying it. it seemed to have been introduced in this commit: 
https://github.com/xaksis/vue-good-table/commit/5773f32538b644a9e8531e2be92c8d0f7b6441c2

will fix tonight.

**Comment by xaksis** [comment]
@focussing v1.15.2 now has the fix for this.
