### ISSUE TITLE
Empty cells in each row when using table-row-before and table-row-after

### ISSUE THREAD

**Issue by shamotj** [xaksis/vue-good-table#102]
I use both slots **table-row-before** and **table-row-after**. Header was two columns short, so I added two empty columns `{ label: '', field: '' }`. This solves column count in header, but it resulted in empty cells in each row at the beginning and at the end of row. 

I believe this is bug and we can either automatically add header columns when table-row-before/after is used or somehow filter empty columns (those with empty field) when rendering rows.

**Comment by xaksis** [comment]
@shamotj can you modify: https://jsfiddle.net/aks9800/mn27rd7b/ to show me what you're trying to do? I suspect there's a misunderstanding in how to use table-row-before/after here.

**Comment by shamotj** [comment]
I modified jsfiddle but it works different. I noticed you use different **vue-good-table.min.js** file (from . I use this one https://raw.githubusercontent.com/xaksis/vue-good-table/master/dist/vue-good-table.min.js.

**Comment by xaksis** [comment]
it's the same file. Can you share the modified jsfiddle so i can see it? btw, as documentation states (https://github.com/xaksis/vue-good-table#additional-columns), when you use the table-row-before/after slots, you'd need to provide appropriate columns in data. 

for example, if i were adding a checkbox to the beginning of my table i'd have: 
```html
<vue-good-table
  :columns="columns"
  :rows="rows">
<template slot="table-row-before" slot-scope="props">
  <td><input type="checkbox" /></td>
</template>
<!-- all the regular row items will be populated here-->
</vue-good-table>
```
and in column definition i'd have to add: 
```javascript
columns: [
  {
    label: 'checkbox',
    field: ''
  },
  // rest of the columns here
  ...
]
```

**Comment by xaksis** [comment]
oh whoops! it is not the same file... i actually shared an older jsfiddle. my apologies. let me share a new one!! 
https://jsfiddle.net/aks9800/Lhowhqnk/

**Comment by shamotj** [comment]
Here is modified jsfiddle with wrong behavior https://jsfiddle.net/Lhowhqnk/1/

**Comment by xaksis** [comment]
@shamotj thank you so much. that certainly looks wrong. I'll debug this today.

**Comment by xaksis** [comment]
@shamotj v1.15.2 now has the fix for this. Thank you for pointing it out.

**Comment by oslislo-owl** [comment]
I had a similar issue, I was accidentally setting a value for `field`


```
columns: [
  {
    label: 'checkbox',
    field: ''
  },
  // rest of the columns here
  ...
]
```
