### ISSUE TITLE
how can i set perpage value to 5 instead of 10 globally?

### ISSUE THREAD

**Issue by rvasoya** [xaksis/vue-good-table#105]

**Comment by rvasoya** [comment]
I want to set default per page value to 5 instead of 10.
If i set :perPage=5 it's no longer give me dropdown to change value

**Comment by xaksis** [comment]
@rvasoya ah yeah. if you manually set a perPage, it removes the option to change it to one of the pre-determined once. I can look into keeping that functionality.

**Comment by xaksis** [comment]
@rvasoya v1.16.0 adds custom perPage to existing defaults. should fix your issue.
