### ISSUE TITLE
How to separate sorting from view?

### ISSUE THREAD

**Issue by Hellek** [xaksis/vue-good-table#106]
Hi, at first, thanks for this good plugin!

Is there way to separate sorting algoritm from view template? Few examples of problem
--- we have DESC id's of pages (201, 200, 107, 100, 99)
we want to show them like a links to pages <a href="page/99">99</a>
But after wrapping it becomes a string and sorting stop works as expected (like for integers).
DESC becomes (99, 201, 200, 107, 100)!! 200 between 90 and 100, because first chars

Another thing we have 3 strings "0_mustBeSecond", "1_mustBeFirst", "2_mustBethird"
If we sort it like strings "1_mustBeFirst" always will be on the middle.
In the life we meet with this, for example, when we have statuses like "Opened, Closed and Suspend". We have 20 rows for each, and 20 rows for page. If we press on column title for sorting by this column, we newer will see "Opened" rows, they alway would be on the second page

--------------
Imho, obvious solutin add custom sorting param. If we don't have it, we apply default sorting rules (strings, integers, dates). If we have this param we sort by it. Maybe adding custom sorting function would be a great solution https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by xaksis** [comment]
@Hellek good idea. I'll look into adding custom sort function.

**Comment by eric-naguras** [comment]
Are there any plans on implementing custom sort per column? I really need this. If there is no work being done on this I will try myself but if someone working on this, I'd rather spend my time on other things.

**Comment by xaksis** [comment]
Hi @eric-naguras This is in the plans, but I haven't started working on it yet. I will be very happy to review a PR if you want to work on it.

**Comment by eric-naguras** [comment]
I have never done a PR but I'm willing to try.
It would be nice to give something back.

I looked already in the sources how the clickrow is done.
I guess I need to do something simular except it should be a choice.
If no sort function is given as a prop, it should still do a regular sort.

Cheers,
Eric

**Comment by xaksis** [comment]
@eric-naguras yeah! I know first PR is always a little nerve-wracking. You can try it, or if you want to wait till tonight, I'll take a look at it and if it's simple enough I'll implement it tonight.

**Comment by eric-naguras** [comment]
@xaksis It will take a few days before I can start anyway.
So if you can take a look that would be great.
It’s only a pointer to a custom function, right?

**Comment by xaksis** [comment]
@Hellek @eric-naguras this is now available in v1.19.0 you can provide your own custom function via `sortFn` column property. @eric-naguras feel free to take a look at the changelog to see how I did it. 

closing.

**Comment by eric-naguras** [comment]
@xaksis Thank you very much. I'll try it right away.
I did look at the change log already but need to play with the debugger a while to fully understand it.
