### ISSUE TITLE
How to solve styling - support for CSS frameworks

### ISSUE THREAD

**Issue by shamotj** [xaksis/vue-good-table#107]
We are using Foundation CSS Framework and right now table looks non-native. I can override some CSS properties but some needs to be removed. So I see two options now: either remove styling all together or allow someway to override/inject custom styling. 

I can make fork and modify code for Foundation but I'm not convinced it is the best way. @xaksis do you have any suggestions or opinion on this matter?

**Comment by xaksis** [comment]
@shamotj can you create a jsfiddle so we can see what it looks like if you supply foundation class, in styleClass property?
you can use: https://jsfiddle.net/aks9800/Lhowhqnk/ as a base

**Comment by shamotj** [comment]
I made changes to JS Fiddle https://jsfiddle.net/Lhowhqnk/2/ . Actually I overlooked option *styleClass* and it did the trick. I think we can consider this issue as resolved. Once we set styleClass to empty only css for <table> applies, which is harmless.
