### ISSUE TITLE
Add sortable setting for columns

### ISSUE THREAD

**Issue by shamotj** [xaksis/vue-good-table#109]
In some cases it is desirable to turn off sorting for some columns. It can be set up by adding option sortable  to columns (same way as  filterable is made).

**Comment by xaksis** [comment]
@shamotj yeah... there's a pull request for this that I reviewed. I think i'll make the change myself for this soon.

**Comment by zietbukuel** [comment]
Yeah, I was trying to do this too, it would be good to have a sortable option for columns because for example, we don't want to sort 'actions' (view, edit, delete buttons), because it doesn't make any sense.

**Comment by Dalex96** [comment]
Se puede agregar un botón sin traerlo de rows?

`{
            label:'',
            htmlContent: '<button>Hello</button>',
            html: true,
          }`

**Comment by VitorLuizC** [comment]
i've already made a PR (#89) fixing this and changed things @xaksis asks, so now he just need to merge it

**Comment by VitorLuizC** [comment]
Also, this issue is a duplicate of #86

**Comment by xaksis** [comment]
this is now available in v1.16.0 thanks to @VitorLuizC for the work!
