### ISSUE TITLE
Suggestion: binding the search query string

### ISSUE THREAD

**Issue by vinnybod** [xaksis/vue-good-table#11]
I'm not sure if this is currently possible, looking through the docs I don't believe it is.

It would be great to have the ability to pass in a string as a prop to the table component.
I have two use cases for this
1. It makes it possible to use a search bar other than the provided one or in a different location than the provided one 
2. I have a case where when I type in a search string, I am emitting an event. 

```html
<vue-good-table>
  :search="searchQuery"
  :columns="columns"
  :rows="items"
  :paginate="false"
/>
```

Edit: I've mocked something up that doesn't cause any breaking changes, I want to make a few improvements then I will push it for you to see (hopefully by tonight, otherwise tomorrow)

**Comment by xaksis** [comment]
Cool! Please create a pull request and i'll review it. just a note - please call the option 'searchString' instead of just 'search' to avoid potential confusion.

**Comment by vinnybod** [comment]
I created a PR https://github.com/xaksis/vue-good-table/pull/12

I went with `searchQuery.` Unfortunately my additions did create somewhat of a breaking change. I didn't want to mess too much with the logic of column filters vs global search so I kept that functioning the same way, so the property `globalSearch` stayed the same, but it the table just needs an additional prop of either `searchQuery` or `embeddedSearch` to use their own input or to get the built in version.

The PR looks bigger than it is because we had some conflicts with line endings.

The big thing I noticed was that in `dist/vue-good-table.js` there seems to be an absolute path, but I'm not really sure where it is used or how to remove that from the bundle process.

**Comment by vinnybod** [comment]
Example usage for using embedded search
```
<vue-good-table
              :global-search="true"
              :embedded-search="search"
              :columns="headers"
              :rows="items"
              :paginate="false"
              :lineNumbers="false"
              styleClass="table table-condensed"
              >
```
Example for external search
```
<vue-good-table
              :global-search="true"
              :search-query="search"
              :columns="headers"
              :rows="items"
              :paginate="false"
              :lineNumbers="false"
              styleClass="table table-condensed"
              >
```

**Comment by xaksis** [comment]
hey @vinnybod so I looked at your changes and I don't think we need to create a breaking change for this. I created a branch with a version that seems to be doing what you wanted it to do: 

basically I created 1 new property - externalSearchQuery the presence of this property ignores globalSearch and allows search through your external field.

Could you review this?
https://github.com/xaksis/vue-good-table/tree/external-search

example usage: 
```html
<input type="text" v-model="searchTerm" />
    <vue-good-table
      :columns="columns"
      :paginate="true"
      :externalSearchQuery="searchTerm"
      :rows="rows"/>
```

```javascript
data(){
      return {
        searchTerm: '',
        // rows, columns etc...
      };
  }
```

if you think this is ok, I'll merge it into master.

**Comment by vinnybod** [comment]
@xaksis looks like a good solution to me

**Comment by xaksis** [comment]
merged. v1.8.0
