### ISSUE TITLE
CDN?

### ISSUE THREAD

**Issue by kwerle** [xaksis/vue-good-table#110]
Ugh.  If this were minified published to a CDN I'd be using it 15 minutes ago.

https://hackernoon.com/how-to-publish-your-package-on-npm-7fc1f5aae600

> But if you’re going to publish something for the browser there are more fields to know.
> For example the unpkg field. If you publish your lib on npm it will be available over unpkg. It's a CDN so people can pull your scripts into their scripts without installing them over npm.
> https://unpkg.com/package@version/file
> In the unpkg field you can define the default file, which get served if someone includes https://unpkg.com/package.

Yes, I'm begging.

**Comment by xaksis** [comment]
heh :) 
https://rawgit.com/xaksis/vue-good-table/master/dist/vue-good-table.min.js ?

**Comment by kwerle** [comment]
Spectacular - though it might be nice to add unpkg - and document it in the readme.

I'll take it for a spin in a bit.

**Comment by kwerle** [comment]
But this looks like it works.
