### ISSUE TITLE
Custom td contents

### ISSUE THREAD

**Issue by kwerle** [xaksis/vue-good-table#111]
vue-good-table is awesome.

I would like to display some custom content for a column.  I suppose I can do that by passing a function and rendering the html - but that makes me sad.

I would like to be able to supply the td contents using a template:

```
<vue-good-table :columns='columns' :rows='modems' lineNumbers='true' paginate='true' title='Modems'>
  <template scope='props' slot='table-cell-**field**'>
    <btn v-click='action'>
      {{ field }}
    </btn>
  </template>
</vue-good-table>
```
where \*\*field** is the column field string.  I'm not sure if the template should be responsible for the td tags or not...

**Comment by xaksis** [comment]
if it is at the beginning or at the end of the columns, you can use 'template-row-before', 'template-row-after'... as described here: https://github.com/xaksis/vue-good-table#additional-columns

if it is in the middle somewhere, then i'm afraid you have to provide a template for all tds

```html
<vue-good-table
  :columns="columns"
  :rows="rows">
  <template slot="table-row" scope="props">
    <td>{{ props.row.name }}</td>
    <td class="fancy">{{ props.row.age }}</td>
    <td>{{ props.formattedRow.date }}</td>
    <td>{{ props.index }}</td>
  </template>
</vue-good-table>
```

**Comment by xaksis** [comment]
closing this. Let me know if above hasn't resolved your issue and i'll reopen it.

**Comment by mgd722** [comment]
@xaksis just to confirm: 'template-row-before' and 'template-row-after' got nixed somewhere along the line to the current version, right?

**Comment by xaksis** [comment]
hey @mgd722 yeah. you don't need them anymore. Just supply the column names and then provide the row-template: 
https://jsfiddle.net/aks9800/hsf0sqf8/
