### ISSUE TITLE
Dynamic tdClass?

### ISSUE THREAD

**Issue by techytuppers** [xaksis/vue-good-table#114]
Hello!

Loving your good-table component, thank you very much for the time and effort put in to it.

I was wondering if it was possible to utilise the tdClass property of a column, in a more dynamic way? A trivial example, if the data value was "red", and I wanted the class to be "colour--red", is there a way of doing that via the column attribute tdClass? The example just shows a single string directly referenced, but dynamicaly it could be something like:

```
data(){
    return {
        columns: [
            {
                label: '',
                field: 'Colour',
                tdClass: this.displayColour
            },
        ],
    };
},
methods : {
    displayColour(rowObj) {
        let classColour = rowObj.Colour;
        return 'colour--' + classColour;
    }
}
```
Any advice on if this is possible now and I'm just getting it wrong, would be appreciated - many thanks!

Update: I'm unable to set tdClass to just a string either, it doesn't get added to the `<td>` ...? thClass works fine!

Investigation: in `Table.vue` line 78 `<td v-for="(column, i) in columns" :class="getDataStyle(i, 'td')" v-if="!column.hidden && column.field">` - the `getDataStyle` function gets run (I've console logged the result) and returns the string assigned to tdClass, but this doesn't then appear in the rendered `<td>` in browser (where it does for `thClass`)

**Comment by xaksis** [comment]
I'll investigate this shortly... sorry for the delay.

**Comment by xaksis** [comment]
@techytuppers seems to be working fine for me: 
https://jsfiddle.net/aks9800/y4egud23/

closing this. If you continue to see the problem, let me know and I'll reopen the issue.

**Comment by WendySYNIN** [comment]
Hi, This is a perfect component thank you for sharing.
I have the same question. Could you reopen it? ( https://jsfiddle.net/aks9800/y4egud23/)  
thank you very much.

**Comment by SciManJD** [comment]
Is there solution about the dynamic tdClass? I desperately need it...
