### ISSUE TITLE
Total Row?

### ISSUE THREAD

**Issue by T-Bod** [xaksis/vue-good-table#115]
Love good table, thanks for all of your effort on it!

This may be somewhat related to #81 but is there a suggested method for populating a total row? Strictly a sum or possibly a count of the column data, no additional manipulation or grouping.

**Comment by xaksis** [comment]
Hey @T-Bod, the new major version 2.0 (which is now in beta) now allows grouped tables! you can check out a basic example here: 
https://jsfiddle.net/aks9800/wtwwkcgm/
you can also create summary rows with totals: 
https://jsfiddle.net/aks9800/0t820euy/

to upgrade to 2.0, please use [the upgrade guide](https://github.com/xaksis/vue-good-table/wiki/Guide-to-upgrade-from-1.x-to-v2.0)

and you can see the [full documentation here](https://github.com/xaksis/vue-good-table/tree/new-build)

**Comment by xaksis** [comment]
whoops didn't mean to close it. Will close when the new build is out of beta.

**Comment by xaksis** [comment]
closing

**Comment by T-Bod** [comment]
Hey @xaksis, thanks for your work on this, the new version has been great!  

Quick question and maybe I'm just misunderstanding the docs / being dumb, but what is the recommended handling if there are no sub-categories as shown in the grouped-summary example but instead I just want a single summary/total row?  

For example, if I wanted a single "total row" at the bottom which was simply a sum of the numbers above it, would I really need to explicitly list out the children for each?

**Comment by T-Bod** [comment]
Got it, thanks!

**Comment by infinitetrinity** [comment]
Hi, looking to implement this but your example in jsfiddle aren't loading and the documentation doesn't seems to mention this. Any chance for you to show another example? Thank you

**Comment by xaksis** [comment]
@infinitetrinity examples seem to be loading find for me, but here is the code: 
markup
```html
<div id="app">
  <vue-good-table
    :columns="columns"
    :rows="rows"
    :group-options="{
      enabled: true,
      headerPosition: 'bottom',
    }"
    :search-options="{
      enabled: true
    }"> 
  </vue-good-table>                  
</div>
```
javascript
```javascript
new Vue({
  el: '#app',
  data() {
  	return{
    	columns: [
        {
          label: 'Name',
          field: 'name',
        },
        {
          label: 'Diet',
          field: 'diet',
          type: 'text',
        },
        {
          label: 'Count',
          field: 'count',
          headerField: this.sumCount,
          type: 'number',
        },
      ],
      rows: [
        {
          name: 'Animals Total',
          diet: '',
          count: '',
          children: [
            { name: 'Elephant', diet: 'herbivore', count: 5 },
            { name: 'Cat', diet: 'carnivore', count: 28 },
            { name: 'Dog', diet: 'omnivore', count: 12 },
            { name: 'Dolphin', diet: 'carnivore', count: 9 },
            { name: 'Snake', diet: 'carnivore', count: 40 },
            { name: 'lizard', diet: 'insectivore', count: 34 },
            { name: 'crocodile', diet: 'carnivore', count: 22 },
            { name: 'turtles', diet: 'herbivore', count: 29 },
                        { name: 'Shark', diet: 'carnivore', count: 2 },
            { name: 'koi', diet: 'omnivore', count: 14 },
            { name: 'guppy', diet: 'omnivore', count: 35 },
            
          ],
        },
      ],
    };
  },
  methods: {
  	sumCount(rowObj) {
    	console.log(rowObj);
    	let sum = 0;
      for (let i = 0; i < rowObj.children.length; i++) {
        sum += rowObj.children[i].count;
      }
      return sum;
    },
  },
});
```
