### ISSUE TITLE
Bundle component

### ISSUE THREAD

**Issue by VitorLuizC** [xaksis/vue-good-table#116]
Apparently all those webpack and build stuff does nothing since you're exposing source version of this module instead of a compile one.

https://github.com/xaksis/vue-good-table/blob/37b321dd2ab0037436d3cd1492f607eba2d17620/package.json#L5

Bundling it down to ES5 will solve some issues, like #95 #83 #72 #80 #48.

**Comment by VitorLuizC** [comment]
Okay, they are closed. But I'm looking at this right now and I really don't want to add a lot of babel modules to my environment...

Also, https://github.com/egoist/bili and https://github.com/egoist/poi are nice replacements to all that webpack and build stuff.

**Comment by xaksis** [comment]
@VitorLuizC the build does create an es5 version of the module: 
https://rawgit.com/xaksis/vue-good-table/master/dist/vue-good-table.js

the primary intent of the plugin is to be used with the vue-cli project setup that already sets up your environment with the proper babel modules. 

I am confused as to why you have to delete your .babelrc every time you have to install vue-good-table. Can you expand on that?

**Comment by xaksis** [comment]
I'll look into exposing the es5 bundle for npm as opposed to the source one.

**Comment by VitorLuizC** [comment]
> @VitorLuizC the build does create an es5 version of the module:
> https://rawgit.com/xaksis/vue-good-table/master/dist/vue-good-table.js

That's a UMD version, it includes other compiled dependencies. Would be better to provide, also, a CommonJS module that exposes ES5 sources & require dependencies.

> I am confused as to why you have to delete your .babelrc every time you have to install vue-good-table. Can you expand on that?

I'm using babel 7, because syntax-optional-chaining and some optimizations. So, I have `@babel/babel-preset-env` instead of `babel-preset-env`. So, when `babel-loader` recursively look into included module's `.babelrc` it won't find babel requested modules and that`s why I have to delete it everytime to use mine instead.

> I'll look into exposing the es5 bundle for npm as opposed to the source one.

I can help you with that.

**Comment by xaksis** [comment]
closing
