### ISSUE TITLE
Ignore files

### ISSUE THREAD

**Issue by VitorLuizC** [xaksis/vue-good-table#117]
Can you add build, test and other files in .npmignore? I really don't want to download all those files every time I install my project's dependencies.

![captura de tela 2017-11-14 as 14 59 22](https://user-images.githubusercontent.com/9027363/32793260-872acd86-c94c-11e7-82f8-fd838e19b7c9.png)

**Comment by xaksis** [comment]
This is now done with v1.18.2. closing.
