### ISSUE TITLE
`originalIndex` is losed when `globalSearchAllowed` is enabled

### ISSUE THREAD

**Issue by tonimc** [xaksis/vue-good-table#122]
When `globalSearchAllowed` is enabled the filter is made directly on `this.rows` without adding the `originalIndex` (https://github.com/xaksis/vue-good-table/blob/master/src/components/Table.vue#L457), to avoid that I create this PR with the fix https://github.com/xaksis/vue-good-table/pull/121.

**Comment by tonimc** [comment]
@xaksis you can see it quickly in the first example in https://xaksis.github.io/vue-good-demos/#/dynamic-table When you write something on the filter, the original index column becomes empty.

**Comment by xaksis** [comment]
@tonimc good catch! I'll merge this in tonight. Thank you so much for the PR!

**Comment by corbosman** [comment]
Did you end up merging this? I dont see it in the code. Im running into the same issue. I need to make api calls and then update the row, but after search I dont have a row index in the row object.

**Comment by xaksis** [comment]
@tonimc @corbosman sorry for the delay, I was on vacation. This is now available in v1.17.0

**Comment by tonimc** [comment]
thanks @xaksis and dont worry.
