### ISSUE TITLE
Option to completely leave out styles?

### ISSUE THREAD

**Issue by davidohlin** [xaksis/vue-good-table#125]
Great component, thanks for your hard work! 👍 

I would like to completely omit the `<style>` tag and its contents. Is there a way to do that right now? If not, is it possible to implement?

**Comment by tonimc** [comment]
@davidohlin `vue-good-table` give you the prop styleClass which overwrite the styles for the table. Using `<vue-good-table styleClass="">` the table will be without styles. Only, the pagination will have them.

@xaksis one possibility would be moving `styleClass` to the main div instead put it on the table? It will be a breaking change but it could be good.

**Comment by egoist** [comment]
CSS should not be bundled into JS anyways, it's better that you can extract CSS from `dist/vue-good-table.js`

**Comment by blak3r** [comment]
+1 would be nice to completely omit.  I used the styleClass attributes I set `table table-sm table-condensed` and those are already defined by my CSS and your built in ones are overriding some of it's css.

**Comment by bjh81782** [comment]
+1 for me on this.  I would rather the bootstrap styles apply directly.  The built in ones seem to override.  Specifically .table-sm

**Comment by xaksis** [comment]
@bjh81782 @blak3r @davidohlin this now exists in the next major version (currently in beta) you can read the documentation here: 
https://github.com/xaksis/vue-good-table/tree/new-build

upgrade guide: 
https://github.com/xaksis/vue-good-table/wiki/Guide-to-upgrade-from-1.x-to-v2.0

**Comment by xaksis** [comment]
closing.
