### ISSUE TITLE
Global search by submit

### ISSUE THREAD

**Issue by DaniloPolani** [xaksis/vue-good-table#13]
Hi,
it would be great to choose if search in the whole table on each character typed or on submit (enter key).

I have a 15k+ table and it's impossible to search "live".

**Comment by xaksis** [comment]
@DaniloPolani v1.7 supports this now. just add `searchTrigger="enter"` to the table. 

I also made some efficiency improvements and tested live search with 15k+ tables and it worked well. So maybe want to give that a try again?

Also, Thanks for your submission on tdClass/thClass ... very useful.
