### ISSUE TITLE
search doesn't match sub string

### ISSUE THREAD

**Issue by corbosman** [xaksis/vue-good-table#131]
The search in column search does not match substrings correctly. This can easily be tested by going to your demo and searching for "ane". It does not return the Jane row.

Interestingly the globalsearch does work correctly.

**Comment by VitorLuizC** [comment]
There's already a PR (#118) to fix it. @xaksis was revising it and, I guess, will merge soon.

**Comment by y-kushnir** [comment]
You can use custom 'filter' function as temporary solution
`filter: function(data, filterString){
            if (_.isUndefined(data)) return;
            return _.includes(data.toLowerCase(), filterString.toLowerCase());
        }`

**Comment by xaksis** [comment]
@VitorLuizC @corbosman this should now be available in 1.17.0. Sorry for the delay.
