### ISSUE TITLE
option to disable filtering on a column when using globalsearch

### ISSUE THREAD

**Issue by corbosman** [xaksis/vue-good-table#133]
It would be nice if you can configure a column to never match when using globalsearch. Maybe even use "filterable" for that, or even nicer, allow for filter method (which could always return false).

use case, i would like to prevent some columns from matching a search string because they are never relevant to the searches.

**Comment by xaksis** [comment]
@corbosman this is now available in v 1.18.2. use `globalSearchDisabled` property on the column

1.18.2 also introduces custom filter function that you can supply to the table with `globalSearchFn` property
