### ISSUE TITLE
Select all checkbox on header

### ISSUE THREAD

**Issue by sarath49** [xaksis/vue-good-table#134]
How to setup to allow select all checkbox in <th> using this library.

```
<vue-good-table
  :columns="columns"
 :rows="rows"
 :paginate="true"
:lineNumbers="true">
     <template slot="table-column" scope="props">
      	<span v-if="props.column.field =='checkbox'">
          <input type="checkbox" v-model="checkboxMultiple" /></td>
       </span>
     </template>
     <template  slot="table-row" slot-scope="props">
      <td v-if="showCheckbox">
          <input type="checkbox" @click="checkboxAction(props)" v-model="selected" />
     </td>
    </template>
</vue-good-table>

```
Where checkboxAction(props) will select only one item at time on click action (currently when I click on one item all checkboxes are triggered to store and check date in an array.

And using computed property to get all values when checkboxMulitple modle is triggered.

As shown in fiddle [https://jsfiddle.net/thanhmabo/atxj3786/](https://jsfiddle.net/thanhmabo/atxj3786/).

Though I am not getting it working up.

I have other fields but such as ids, name as I think not required to be mentioned here to save space.

Also, how to remove that sortable criteria for this checkbox column. I have set sortable to false in columns data, still its filtering the rows when checkbox is clicked.

Thanks

**Comment by xaksis** [comment]
@sarath49 I created a checkbox example here: 
https://xaksis.github.io/vue-good-demos/#/dynamic-table

closing.

**Comment by u007** [comment]
updated here
https://xaksis.github.io/vue-good-table/guide/advanced/checkbox-table.html
