### ISSUE TITLE
SyntaxError: Unexpected token import - ??

### ISSUE THREAD

**Issue by ruslankonev** [xaksis/vue-good-table#135]
How I can see this on fronted? and what I need to config?
![image](https://user-images.githubusercontent.com/2588730/33724310-2a974f0e-db80-11e7-9970-ef521172186f.png)

**Comment by xaksis** [comment]
hey @ruslankonev v1.18.2 should have fixed this for you as it exposes a UMD es5 bundle file as opposed to the component src. Give that a try and let me know. If it doesn't solve your issue, i'll re-open it. 

closing for now.
