### ISSUE TITLE
Search Icon

### ISSUE THREAD

**Issue by Yezuz05** [xaksis/vue-good-table#137]
The search icon doesn't load, so I usually copy the file to wherever the app expects to find it. Is there a way I can specify the src attribute of the image?

**Comment by arivera12** [comment]
You need to add the folder static/img. Take a look of the folder structure [dist](https://github.com/xaksis/vue-good-table/tree/master/dist)

**Comment by xaksis** [comment]
@Yezuz05 v1.17.1 has a css icon instead of a png. This should solve your issue.
