### ISSUE TITLE
Custom row templates don't work in IE

### ISSUE THREAD

**Issue by arivera12** [xaksis/vue-good-table#138]
This plugin doesnt work on IE11. 
I added the polyfills for includes and entries to fix this and still doesn't work. 
Take a look of these threads in stackoverflow.

[Link Includes](https://stackoverflow.com/questions/31340868/includes-not-working-in-all-browsers)
[Link Entries](https://stackoverflow.com/questions/42446062/object-doesnt-support-property-or-method-entries)

![image](https://user-images.githubusercontent.com/5600102/33906113-4980dd24-df57-11e7-9281-c542778510dd.png)

Any solution for this?

**Comment by arivera12** [comment]
I think that these polyfills aren't working maybe cause the object's type are not set correctly. The method includes is on a string context and the method entries is on an object's context. Does this makes any sense or I am wrong?

**Comment by arivera12** [comment]
I was wrong with the polyfills I where using after reading the code. 
The polyfills needed are based on Arrays rather than string or object so I added this polyfills and now the errors has gone but data isn't being displayed correctly.
This is how it should work (google chrome screenshot)
![image](https://user-images.githubusercontent.com/5600102/33908054-8ba266ae-df5d-11e7-955c-7d1b4b8a4da9.png)

This is how is working on (IE11 screenshot)
![image](https://user-images.githubusercontent.com/5600102/33907972-4eb72ea0-df5d-11e7-9827-76d3685dabf5.png)

Why this isn't working yet on IE11? I need this very rush please help :cry: 

Here is the source of the polyfills of includes and entries I am using:
```
if (!Array.prototype.includes) {
    Object.defineProperty(Array.prototype, 'includes', {
        value: function (searchElement, fromIndex) {

            if (this == null) {
                throw new TypeError('"this" is null or not defined');
            }

            // 1. Let O be ? ToObject(this value).
            var o = Object(this);

            // 2. Let len be ? ToLength(? Get(O, "length")).
            var len = o.length >>> 0;

            // 3. If len is 0, return false.
            if (len === 0) {
                return false;
            }

            // 4. Let n be ? ToInteger(fromIndex).
            //    (If fromIndex is undefined, this step produces the value 0.)
            var n = fromIndex | 0;

            // 5. If n ≥ 0, then
            //  a. Let k be n.
            // 6. Else n < 0,
            //  a. Let k be len + n.
            //  b. If k < 0, let k be 0.
            var k = Math.max(n >= 0 ? n : len - Math.abs(n), 0);

            function sameValueZero(x, y) {
                return x === y || (typeof x === 'number' && typeof y === 'number' && isNaN(x) && isNaN(y));
            }

            // 7. Repeat, while k < len
            while (k < len) {
                // a. Let elementK be the result of ? Get(O, ! ToString(k)).
                // b. If SameValueZero(searchElement, elementK) is true, return true.
                if (sameValueZero(o[k], searchElement)) {
                    return true;
                }
                // c. Increase k by 1. 
                k++;
            }

            // 8. Return false
            return false;
        }
    });
};
```

```
(function (exports) {
    'use strict';

    function ToObject(val) {
        if (val === null || val === undefined) {
            throw new TypeError('can\'t convert ' + val + ' to object');
        }

        return Object(val);
    }

    function AssertProperty(obj, key) {
        if (!obj.hasOwnProperty(key)) {
            throw new TypeError('ArrayIterator next called on incompatible ' + String(obj));
        }
    }

    function NonEnumerable(obj) {
        Object.keys(obj).forEach(function (key) {
            Object.defineProperty(obj, key, {
                enumerable: false
            });
        });
        return obj;
    }


    function ArrayIterator(obj) {
        this.iteratedObject = ToObject(obj);
        this.index = 0;
        this.kind = 'key+value';
    }

    ArrayIterator.prototype.next = function next() {
        var self, object, index, kind;

        self = ToObject(this);
        AssertProperty(self, 'iteratedObject');
        AssertProperty(self, 'index');
        AssertProperty(self, 'kind');

        if (self.iteratedObject === undefined) {
            return { value: undefined, done: true };
        }

        object = self.iteratedObject;
        index = self.index;
        kind = self.kind;

        if (index >= (object.length || 0)) {
            self.iteratedObject = undefined;
            return { value: undefined, done: true };
        }

        self.index += 1;

        if (kind === 'key') {
            return { value: index, done: false };
        }

        if (kind === 'value') {
            return { value: object[index], done: false };
        }

        if (kind === 'key+value') {
            return { value: [index, object[index]], done: false };
        }

        throw new TypeError('Invalid ArrayIterationKind');
    };


    if (typeof Array.prototype.entries !== 'function') {
        Array.prototype.entries = function entries() {
            return NonEnumerable(new ArrayIterator(this));
        };
    }

    exports.arrayEntries = Function.prototype.call.bind(Array.prototype.entries);

}(typeof exports !== 'undefined' ? exports : this));
```

**Comment by arivera12** [comment]
This is the template I am using for this
```
<vue-good-table title="Areas de Necesidades o Adiestramientos"
                            :columns="[
                            { label:'Área Necesidad o Adiestramiento' },
                            { label:'Acciones'}
                            ]"
                            :rows="rows"
                            :paginate="true"
                            :line-numbers="true"
                            style-class="table table-bordered table-striped condensed">
                <template slot="table-row" slot-scope="props">
                    <td v-text="props.row.NeedAreaOrTrainingDescription"></td>
                    <td>
                        <button class="btn btn-default btn-xs" v-on:click="view(props.row.NeedAreaOrTrainingID, $event)"><i class="fa fa-eye"></i></button>
                        <button class="btn btn-primary btn-xs" v-on:click="edit(props.row.NeedAreaOrTrainingID, $event)"><i class="fa fa-edit"></i></button>
                        <button class="btn btn-danger btn-xs" v-on:click="del(props.row.NeedAreaOrTrainingID, $event, props.index)"><i class="fa fa-remove"></i></button>
                    </td>
                </template>
            </vue-good-table>
```

**Comment by arivera12** [comment]
Digging more deeper into this I found 2 things on this on IE11.

If I change this 
`<td v-text="props.row.NeedAreaOrTrainingDescription"></td>`
into this
`<td>{{ props.row.NeedAreaOrTrainingDescription }}</td>`

The props data gets rendered correctly. 

So vuejs directives like v-text and v-html aren't working as expected on slots on IE11.

The second thing is that I found that props aren't being inserted in the <td> elements.

Please take a look of this screenshot in IE11.

![image](https://user-images.githubusercontent.com/5600102/33919182-9e3b2262-df8d-11e7-837e-1abb71172a6e.png)
![image](https://user-images.githubusercontent.com/5600102/33919362-b7835e32-df8e-11e7-9253-3550360ab124.png)


There is no `<td>` element inside the `<tr>` element.

I don't know if there anyone facing this problem as me but anyone who gets into any version of IE maybe fall in the error as me. 

I have been 2 days trying to fix this but still can't find any solution. 

Please help @xaksis :cry:

**Comment by xaksis** [comment]
@arivera12 sorry Ive been sick last few days. This is happening because IE doesn't allow <slots> tag inside tables: https://github.com/vuejs/vue/issues/3028
I will need to write up a fix for this later today. I apologize for the inconvenience.

**Comment by arivera12** [comment]
@xaksis  I have been sick too these days :cry:  there is something in the air that everyone is getting sick I got my kids and my brother sick too. 
I hope you get well soon! 
In the meantime this plugin isn't working with any IE version since. 
I have test it on IE9, IE10, IE11.
I looked at the referenced issue you added to this thread and I went over it yesterday I knew after various test that this was a bug cause I couldn't fix it in any way.
I tried to edit span tag for td tag but still does't work.
I was looking at the source code I think the error is on these lines over here.
![image](https://user-images.githubusercontent.com/5600102/34000305-44d28152-e0c3-11e7-91ef-aba6d276c782.png)

**Comment by arivera12** [comment]
@xaksis  I have been sick too these days :cry:  there is something in the air that everyone is getting sick I got my kids and my brother sick too. 
I hope you get well soon! 
In the meantime this plugin isn't working with any IE version since. 
I have test it on IE9, IE10, IE11.
I looked at the referenced issue you added to this thread and I went over it yesterday I knew after various test that this was a bug cause I couldn't fix it in any way.
I tried to edit span tag for td tag but still does't work.
I was looking at the source code I think the error is on these lines over here.
![image](https://user-images.githubusercontent.com/5600102/34000305-44d28152-e0c3-11e7-91ef-aba6d276c782.png)

**Comment by arivera12** [comment]
I think you should state that for using this plugin with IE include the 2 polyfills I added here so this plugin can work on IE for other users of this plugin.

**Comment by arivera12** [comment]
@xaksis  any update on this?

**Comment by xaksis** [comment]
@arivera12 i was able to solve it by adding babel-polyfill to my projects. Just install babel-polyfill
`npm i --save-dev babel-polyfill`
then, if you're using webpack build for your vue project, add babel-polyfill to your webpack.base.config:
```javascript
entry: {
    app: [
      'babel-polyfill',
      './src/main.js'
    ]
},
```
(don't forget to remove the earlier polyfills that you added, babel takes care of all those)
closing.

**Comment by arivera12** [comment]
Babel-polyfill at least makes the table render but not to render correctly on IE.

IE still doesn't render correctly take a look:
![image](https://user-images.githubusercontent.com/5600102/34072295-e6629ec4-e25a-11e7-9394-99333cce30ba.png)

IE doesn't put `<td>` inside`<tr>` as expected on the template slot
![image](https://user-images.githubusercontent.com/5600102/34072303-25e6cd22-e25b-11e7-88b3-8ad114305b11.png)

![image](https://user-images.githubusercontent.com/5600102/34072316-6ace4b68-e25b-11e7-884a-be085397be60.png)

**Comment by arivera12** [comment]
v-text and v-html directives aren't even working on the template scope they just render blank on IE.

**Comment by xaksis** [comment]
@arivera12  can you try https://xaksis.github.io/vue-good-demos/#/dynamic-table on your browser and paste a screenshot here?

**Comment by arivera12** [comment]
The demo site works as expected. The problem that I have is that on my project this doesn't render correctly. I updated vuejs, this plugin and still doesn't work.
I will share my code here so if u can see anything is wrong  with it cause I don't see anything wrong with this.
```
<vue-good-table title="Areas de Necesidades o Adiestramientos"
                            :columns="[
                            { label:'Área Necesidad o Adiestramiento' },
                            { label:'Acciones' }
                            ]"
                            :rows="rows"
                            :paginate="true"
                            :line-numbers="true"
                            style-class="table table-bordered table-striped condensed">
                <template slot="table-row" slot-scope="props">
                    <td v-text="props.row.NeedAreaOrTrainingDescription"></td>
                    <td>
                        <button class="btn btn-default btn-xs" v-on:click="view(props.row.NeedAreaOrTrainingID, $event)"><i class="fa fa-eye"></i></button>
                        <button class="btn btn-primary btn-xs" v-on:click="edit(props.row.NeedAreaOrTrainingID, $event)"><i class="fa fa-edit"></i></button>
                        <button class="btn btn-danger btn-xs" v-on:click="del(props.row.NeedAreaOrTrainingID, $event, props.index)"><i class="fa fa-remove"></i></button>
                    </td>
                </template>
            </vue-good-table>
```
The `<td>` element never gets rendered and both cells are inside the `<tr>`.

This is what it gets rendered using this code.
![image](https://user-images.githubusercontent.com/5600102/34080223-0ba34ac4-e311-11e7-832b-a5cbe17cb408.png)

This is what is inside the table row
![image](https://user-images.githubusercontent.com/5600102/34080239-55ce7e5c-e311-11e7-9a14-7eb635251ab4.png)

I saw for a moment that your example uses the mustache tag for example {{ props.row.NeedAreaOrTrainingDescription }} and at least data gets displayed but still gets rendered out of the `<td>`.

using v-text works on chrome and other browsers without any problems but it seems that IE doesn't understand the v-text directive don't know what is wrong with this on IE.

@xaksis is there anything wrong with my source?

**Comment by arivera12** [comment]
Can you share vue-good-table code that is being used on the demo to see what's difference with my source? Thanks.

**Comment by xaksis** [comment]
@arivera12 if you weren't able to fix your build... try updating to v1.18.2 I have added the polyfills to the built plugin so hopefully you don't need to do anything else. 

the source to vue-good-demo is available on github: https://github.com/xaksis/vue-good-demos

**Comment by leonardochen30** [comment]
Hi bro, i really need your help. i just create a new project with command **npm install --global vue-cli** and them **vue init webpack my-project**, them import the plugin and works great, but when a test it on IE10 it din't work. just launch a syntax error.
is not necessary create a component that use the tables, just import it and the error appear. Please help mem IE10 is the minimun browser that i need support. I read about es6 transpile, but google it and nothing found.

**Comment by arivera12** [comment]
@leonardochen30  Use latest version of vue-good-table. I am still having the same rendering issue on the tables on IE which td elements doesn't gets render. Please let me know if you have the same problem as me so we can reopen this thread.

**Comment by leonardochen30** [comment]
Hi, i use the last version of vue-good-table yesterday with npm.

**Comment by leonardochen30** [comment]
On IE11 works great and chromiun based browser, on IE10 not load.

**Comment by arivera12** [comment]
@leonardochen30 can you please share with me your vuejs version and the sample you are using for vue-good-table. I don't know why code doesn't work on IE11. Thanks in advance.

**Comment by leonardochen30** [comment]
I resolve the issue adding this resolve('node_modules/vue-good-table/src') to the babel-loader include section.
On IE10 was my issue, IE11 work fine.

**Comment by arivera12** [comment]
I am not using babel or webpack either. Just wanted a working template of vue-good-table....

**Comment by arivera12** [comment]
@xaksis I just tried the new build and I am still having the same issue...

**Comment by arivera12** [comment]
@xaksis  # This works on IE11

data () {
    return {
      columns: [
          {
            label: 'Name',
            field: 'name',
          },
          {
            label: 'Age',
            field: 'age',
            type: 'number',
          },
          {
            label: 'Joined On',
            field: 'joined',
            type: 'date',
            inputFormat: 'YYYYMMDD',
            outputFormat: 'MMM Do YYYY',
          },
        ],
      rows: [
        {name:"John", age:20, joined: '20120201'},
        {name:"Jane", age:24, joined: '20120305'},
        {name:"Susan", age:16, joined: '20140823'},
        {name:"Chris", age:55, joined: '20161109'},
        {name:"Dan", age:40, joined: '20170612'},
      ],
    };
  }

<vue-good-table
  title="Simple Table"
  :columns="columns"
  :rows="rows"/>

# This doesn't work on IE11
data () {
    return {
      columns: [
          {
            label: 'Name',
            field: 'name',
          },
          {
            label: 'Age',
            field: 'age',
            type: 'number',
          },
          {
            label: 'Joined On',
            field: 'joined',
            type: 'date',
            inputFormat: 'YYYYMMDD',
            outputFormat: 'MMM Do YYYY',
          },
        ],
      rows: [
        {name:"John", age:20, joined: '20120201'},
        {name:"Jane", age:24, joined: '20120305'},
        {name:"Susan", age:16, joined: '20140823'},
        {name:"Chris", age:55, joined: '20161109'},
        {name:"Dan", age:40, joined: '20170612'},
      ],
    };
  }
<vue-good-table title="Simple Table"
                            :columns="columns"
                            :rows="rows">
                <template slot="table-row" slot-scope="props">
                    <td>{{ props.row.name }}</td>
                    <td>{{ props.row.age }}</td>
                    <td>{{ props.row.joined }}</td>
                </template>
            </vue-good-table>

# Working with slot templates doesn't work on IE

**Comment by leonardochen30** [comment]
@arivera12 are you using it via CDN? I Try your example in IE10 and IE11 and it worked correctly. I do use a project via vue-cli with webpack and babel.

**Comment by arivera12** [comment]
@leonardochen30 please try the second example that I say it doesn't work first and confirm that this is working or not. I have all my files are locally.

**Comment by arivera12** [comment]
@leonardochen30  
Try this and tell me whats is your output on IE?

```
data () {
    return {
      columns: [
          {
            label: 'Name',
            field: 'name',
          },
          {
            label: 'Age',
            field: 'age',
            type: 'number',
          },
          {
            label: 'Joined On',
            field: 'joined',
            type: 'date',
            inputFormat: 'YYYYMMDD',
            outputFormat: 'MMM Do YYYY',
          },
        ],
      rows: [
        {name:"John", age:20, joined: '20120201'},
        {name:"Jane", age:24, joined: '20120305'},
        {name:"Susan", age:16, joined: '20140823'},
        {name:"Chris", age:55, joined: '20161109'},
        {name:"Dan", age:40, joined: '20170612'},
      ],
    };
  }
<vue-good-table title="Simple Table"
                            :columns="columns"
                            :rows="rows">
                <template slot="table-row" slot-scope="props">
                    <td>{{ props.row.name }}</td>
                    <td>{{ props.row.age }}</td>
                    <td>{{ props.row.joined }}</td>
                </template>
            </vue-good-table>
```

**Comment by leonardochen30** [comment]
Yes, i tried the last example and it works:

IE10:

![ie10](https://user-images.githubusercontent.com/35241410/34896327-6dac55ca-f7b7-11e7-9b3d-2d7883d9a96d.png)

IE11:

![ie11](https://user-images.githubusercontent.com/35241410/34896344-73d1f93c-f7b7-11e7-9e3c-ae7d01563478.png)

**Comment by arivera12** [comment]
@leonardochen30 
OMG!!!! Why it doesn't work on my browser!!!! Please send me a build of your project to see if I can make this work out of the box! I tried the new build on the dist folder vue-good-table.min.js and still doesn't work on my browser. Please help me I have struggling on this over exactly one month!!!!!

**Comment by leonardochen30** [comment]
Hi bro, attached a demo project. Execute:

npm install
npm run dev.

[Test.zip](https://github.com/xaksis/vue-good-table/files/1628481/Test.zip)

**Comment by leonardochen30** [comment]
What error gave to you?
Nmp install? 
Npm run dev?

**Comment by arivera12** [comment]
I am not using vue-loader or webpack or any module bundler. I am just using the https://github.com/xaksis/vue-good-table/blob/master/dist/vue-good-table.min.js into my project and thats all. 

This seems to be working on the module bundle but the standalone lib doesn't work on IE. 

If you just add the vue.min.js &  vue-good-table.min.js without any module bundle you will run into my problem. 

This plugin using the vue-good-table.min.js as standalone lib work everywhere but no on IE. I am thinking we are on different channels regarding on this based the way we are integrating this on the project. 

Can you try a new clean project ONLY without any module bundle using vue.js & vue-good-table.js and a sample index.html and adding the static files into it?

If this works for you  just don't know what in hell in going on!!!!!

**Comment by khe817** [comment]
@arivera12 Did you figure it out or find a fix for it yet? I've encountered the same issue with <td> tags not being rendered at all.

**Comment by arivera12** [comment]
No I could never figure it out. This plugins only works out of the box if you are packaging it using webpack. If you use this as standalone version it won't work. @xaksis any update on this?

**Comment by xaksis** [comment]
@khe817 how are you incorporating the plugin? what version are you using?

**Comment by khe817** [comment]
I did the same thing @arivera12 did here in my project:

> @arivera12 said: "Can you try a new clean project ONLY without any module bundle using vue.js & vue-good-table.js and a sample index.html and adding the static files into it?"

To clarify, I include `vue.js` and `vue-good-table.js` directly as `<script>` tags in my project. No webpack, nor bundle anything.

I am using the newest versions for `vue` and `vue-good-table` downloaded from `npm` (`2.5.13` and `1.20.0` respectively).

When I try to use `<template slot="table-row" slot-scope="props">` to customise the content of `<tr>` rows, the `<td>` tags are not rendered in IE 11 for me. The code I use is the same as @arivera12 's  : 

```
data () {
    return {
      columns: [
          {
            label: 'Name',
            field: 'name',
          },
          {
            label: 'Age',
            field: 'age',
            type: 'number',
          },
          {
            label: 'Joined On',
            field: 'joined',
            type: 'date',
            inputFormat: 'YYYYMMDD',
            outputFormat: 'MMM Do YYYY',
          },
        ],
      rows: [
        {name:"John", age:20, joined: '20120201'},
        {name:"Jane", age:24, joined: '20120305'},
        {name:"Susan", age:16, joined: '20140823'},
        {name:"Chris", age:55, joined: '20161109'},
        {name:"Dan", age:40, joined: '20170612'},
      ],
    };
  }
<vue-good-table title="Simple Table"
                            :columns="columns"
                            :rows="rows">
                <template slot="table-row" slot-scope="props">
                    <td>{{ props.row.name }}</td>
                    <td>{{ props.row.age }}</td>
                    <td>{{ props.row.joined }}</td>
                </template>
            </vue-good-table>
```

**Comment by xaksis** [comment]
I'm going to re-open this issue. This is only happening in the case of custom template because IE doens't allow anything inside tr other than td. So the `slot` gets removed before Vue has had a chance to parse it. Unfortunately, I cannot provide a workaround for this without introducing breaking changes. so a fix will come in the new major version (v2.0.0) which is in alpha right now. 

I'll update here when the fix is part of the alpha.

**Comment by arivera12** [comment]
@xaksis thanks I will wait for this!

**Comment by xaksis** [comment]
alright I think the alpha is finally ready for IE

There are quite a few changes, so make sure you read the upgrade guide: 
https://github.com/xaksis/vue-good-table/wiki/Guide-to-upgrade-from-1.x-to-v2.0

You can read the full documentation here: 
https://github.com/xaksis/vue-good-table/tree/new-build

If you're using the CDN version, these links will get you the latest alpha
**js file**: https://unpkg.com/vue-good-table@alpha/dist/vue-good-table.js
**css file**: https://unpkg.com/vue-good-table@alpha/dist/vue-good-table.css

**Comment by arivera12** [comment]
@xaksis I will try this on these days, I am little busy for the moment. I will give you feedback about it. @khe817 try to give feedback on this.

**Comment by khe817** [comment]
@xaksis I have tested it in my project. It works beautifully in all major browsers (firefox, chrome, Edge, IE 11).

There a small bug in IE 11 and Edge though: When the page loads initially, in pagination, "Rows per page" is set to `All` instead of `10` like it should. However, clicking on `Next`, or select a different "Rows per page" will set it back to being functional normally.

**Comment by xaksis** [comment]
💥 ! good news that this is now working in IE. and @khe817 thank you so much for spending time testing the new version out!! I'll make fixes to this and update once they're in.

**Comment by xaksis** [comment]
@khe817 v2.0.0-alpha.7 should now have the fix for 

- correct index for the dynamic rows
- no columnFilter errors on table update.

**Comment by khe817** [comment]
@xaksis v2.0.0-alpha.7 works as expected.

Another note for the pagination bug in IE 11 and Edge. If I specify `:per-page` and `:custom-rows-per-page-dropdown`, then the Rows per page will display correctly on the first page load.

**Comment by xaksis** [comment]
closing.
