### ISSUE TITLE
Creating progress-bar dynamically

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [xaksis/vue-good-table#143]
Hi @xaksis,

   I am stuck in very strange issue, I actually want to create bootstrap 'progress-bar' dynamically based on some condition.
For example: let's say I have a value of 43. now I want to make it to red progress-bar if the value is less than 50, and blue progress-bar if in between 50 - 60 else > 60 to green progress-bar.

The code for progress bar is as follow:

```
<template slot="table-row" slot-scope="props">
        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="70"  aria-valuemin="0" aria-valuemax="100" style="width:70%">
                   <span class="sr-only">70% Complete</span>
            </div>
      </div>
</template>
```

Note: `aria-valuenow` will be dynamic value, also `style =" width:70%"` too.

**Comment by xaksis** [comment]
@kashifullahwebdeveloper you need to put the progress bar within a <td> for this to work. I am not sure what your question is here? Can you create a jsfiddle for me to take a look?

**Comment by kashifullahwebdeveloper** [comment]
Thank you, so much for quick reply, let me make one for you.

**Comment by xaksis** [comment]
you can use: https://jsfiddle.net/aks9800/80dj8vug/ as a base

**Comment by kashifullahwebdeveloper** [comment]
I think I can't make it very clear by using jsfiddle, but using your example as base, I need to make bootstrap progressbar http://bootstrapdocs.com/v3.0.3/docs/components/#progress, based on age with the following logic:
if( age <= 50) {
// show red progress bar 
} else if (age > 50 && age <=80) {
 // show yellow progress bar
} else if (age >80 && age <= 100) {
// show green progress bar
}

Let me know if it still not clear to you.

**Comment by xaksis** [comment]
closing this. please create a jsfiddle to illustrate the issue and i'll re-open.
