### ISSUE TITLE
Getting a Warning: Avoid using non-primitive value as key, use string/number value instead.

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [xaksis/vue-good-table#144]
Hi @xaksis, 

   I am getting this error when using field as function where I getting an html for that field, could you please tell me why I am getting this?

![non-primitive](https://user-images.githubusercontent.com/12660951/34105681-1d67a3fc-e417-11e7-8aa6-6c102cd171d1.png)

My code is : 

```
{
          label: 'Activated',
          field: this.activatedFn,
          filterable: false,
          sortable: false,
          width: '15%',
          html:true
        },
```
```
activatedFn(row) {
      return '<div class="progress"><div class="progress-bar progress-bar-'+row.activatedClass+'" role="progressbar" aria-valuenow="'+row.activated+'"  aria-valuemin="0" aria-valuemax="100" style="width:'+row.activated+'%"><span>'+row.activated+'%</span></div></div>'
```

**Comment by xaksis** [comment]
@kashifullahwebdeveloper good catch! that is indeed a bug, I'll add a fix to remove this shortly.

**Comment by xaksis** [comment]
@kashifullahwebdeveloper this is now fixed in v1.18.2

**Comment by kashifullahwebdeveloper** [comment]
That's great, thank you.

But could you please tell me how to update only this package in my package.json, I am new to this thing? Sorry for stupid question

**Comment by xaksis** [comment]
following should get you the latest: 
`npm uninstall vue-good-table`
`npm install vue-good-table`

**Comment by kashifullahwebdeveloper** [comment]
Perfect. Thank you so much :)
