### ISSUE TITLE
Search multiple items and out of order?

### ISSUE THREAD

**Issue by CentristPhilosopher** [xaksis/vue-good-table#146]
Wondering if this is possible - I would like to be able search in a way that will give me back the correct rows even if I search terms out of order.

For instance, I currently have a 'Name' field, and an 'Instruments' field.

I would like 'Bob Piano Guitar' and 'Guitar Bob Piano' to come up with the same results.

Is there anything built in to do this, or an easy way I could perhaps modify the current search functionality to make this happen?

**Comment by xaksis** [comment]
@CentristPhilosopher currently theres no way of doing it. however i do think adding a custom search function is very useful for global search. will look into adding that shortly. thank you for bringing this up.

**Comment by xaksis** [comment]
@CentristPhilosopher v1.18.2 introduces custom filter function that you can supply to the table with `globalSearchFn` property. Readme contains usage information.
