### ISSUE TITLE
Table jumps back to first page

### ISSUE THREAD

**Issue by eric-naguras** [xaksis/vue-good-table#147]
After clicking on a row, I display an edit form with info from the row clicked.
But directly after the click, the table jumps back to the first page even if you were a few pages further when clicked on a row.

My table definition is:

```
<vue-good-table
        title="Shows"
        :columns="columns"
        :rows="rows"
        :paginate="true"
        :perPage="15"
        :paginateOnTop="true"
        :lineNumbers="false"
        :onClick="onRowClick"
        rowStyleClass="row-class"
        styleClass="table condensed table-bordered"/>
```

In the rowClick event I get some data from an API server like this:

```
rowClick (row, index) {
      // Get Show from DB by id and set als store value
      const rowval = JSON.stringify(row)
      this.$modal.show('new-edit')
      this.error = this.data = null
      this.loading = true
      this.$http.get('api/shows/' + row.id,
        {
          headers: {
            'Authorization': this.loggedinUser.token,
            'Accept': 'application/json'
          }
        })
        .then(response => {......})
}
```

I have no idea why the table jumps to the first page and how to prevent this.
I hope someone can help.

If really needed I can create a small project to replicate this behaviour.
But this means some extra work, I hope a fix can be found without doing this.

Cheers,
Eric.

**Comment by xaksis** [comment]
hi @eric-naguras ! thank you for using the library. Can you tell me what you do with the response once you receive it?

**Comment by eric-naguras** [comment]
Hi.
What I’ll do with a response?
I’ll use the guidance to make my app work the way it’s expected to work.

Cheers
Eric.

**Comment by xaksis** [comment]
haha... no i meant... 
```javascript
rowClick (row, index) {
      //...
      this.$http.get('api/shows/' + row.id,
        {
          headers: {
            'Authorization': this.loggedinUser.token,
            'Accept': 'application/json'
          }
        })
        .then(response => {......}) //<-- here what do you do with this response
}
```
what do you do with the response above. do you manipulate row data?

**Comment by eric-naguras** [comment]
Hahaha, sorry for the confusion.

I don't manipulate the row data itself.
The row data contains a summary of data plus the id of the record.
So I get the whole record from the server and show that in an edit form.
But the row data itself is not changed.

**Comment by eric-naguras** [comment]
So far good-table is a very nice component. I really like it.
When I'm done with my project I'll extract some examples because the manual and examples could be a bit more verbose.

I'll send you the text so you can put it on your site to help other users.

**Comment by xaksis** [comment]
@eric-naguras sorry for the delay on this. I have been trying to reproduce this table jump on my end but so far I haven't been able to. I have a feeling that maybe as a result of fetching data etc, the component is updated somehow. Were you able to make any progress or figure out why this was happening?

**Comment by eric-naguras** [comment]
@xaksis I haven't made any progress on this as I have no idea what to do.
the same thing is also happening with column sorts and filters.
Basically the whole page table gets reset.

What I will do is make the smallest possible project whit a table and a
fetch and publish that on Github.
I'll try do have that done this weekend.

Thanks for your reply and concern.

**Comment by xaksis** [comment]
@eric-naguras That would be really helpful! you can also do this on jsfiddle, using 
https://jsfiddle.net/aks9800/Lhowhqnk/ as base and then using https://jsonplaceholder.typicode.com/ for your rest api calls.

**Comment by xaksis** [comment]
@eric-naguras closing this, please comment here if you're still experiencing an issue with an example, and i'll re-open.
