### ISSUE TITLE
How to have a new row appear in the correct (sorted) order?

### ISSUE THREAD

**Issue by eric-naguras** [xaksis/vue-good-table#148]
When I add a new row to a table, it does not show up in the expected sorted place.
I have to sort a column to see the new row show up where it should be.
How can I do this the correct way?

This is my table definition:
```
<vue-good-table
        title="Shows"
        :columns="columns"
        :rows="rows"
        :paginate="true"
        :perPage="15"
        :paginateOnTop="true"
        :lineNumbers="false"
        :onClick="onRowClick"
        rowStyleClass="row-class"
        styleClass="table condensed table-bordered"/>
```
I assign values to the rows property after I get data from a server:

`this.rows = this.$store.state.showsList`

When I add a new row via a different component I add it to a vue store collection that is also assigned to the row property of the table by pushing it to the store collection.

```
addShow: (state, payload) => {
  state.showsList.push(payload)
}
```
I can see in the debugger that the row is added to the rows property and to the store collection.
But how do I make it appear in the correct location?

Thanks,
Eric

**Comment by VitorLuizC** [comment]
JS uses references. You need to create a new Array instead of assign this one, like the example below.
```js
this.rows = [ ...this.$store.state.showsList ]
```

> Just a tip: Use `getters` instead of direct assign Store's state, it avoid a lot of issues coming from mutable methods (ex. Array.sort) and reference assignments.

**Comment by eric-naguras** [comment]
Vitor,
Thanks for your reply.

I'll try to use Getters like you suggested.
Creating a new array would be inefficient as the showList is very large.
I don't want to double the memory footprint of my app as I have 4 of these
large list.

Cheers,
Eric

**Comment by xaksis** [comment]
@eric-naguras I'm going to close this for now. Please re-open if you are still experiencing a problem with this.
