### ISSUE TITLE
Help wanted: Timezone Date format to Local time

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [xaksis/vue-good-table#149]
Hi @xaksis, 

   Thank you for date format support, it's amazing. But I am stuck in converting a timezone date into local time zone for that date: **2017-10-11 17:59:40+05** with local timezone.

So far, I have tried this: 
```
          type: 'date',
          inputFormat: 'YYYY-MM-DD HH:mm:ss',
          outputFormat: 'DD-MM-YYYY HH:mm:ss Z'
```
But no luck, Could you please tell me what am I doing wrong?

**Comment by xaksis** [comment]
@kashifullahwebdeveloper 
can you paste sample input for this date column? and expected output?

**Comment by kashifullahwebdeveloper** [comment]
Thank you, @xaksis for your valuable time.

Here is my sample fiddle: `https://jsfiddle.net/aks9800/Lhowhqnk/`

And I need to convert a timezone date into local time zone for example **2017-10-11 17:59:40+05** into exact DateTime along with which timezone it belongs to.

**Comment by xaksis** [comment]
@kashifullahwebdeveloper looks like you forgot to update the fiddle sample before sending me the link :) 
so your input is 2017-10-11 17:59:40+05? and the output you're looking for is? can you paste a sample output?

**Comment by kashifullahwebdeveloper** [comment]
Oh, I changed your jsfiddle but I think I forgot to update, sorry for that, here is my updated jsfiddle: `https://jsfiddle.net/kashifullah/x9mqfy5y/`

And I want the output to be UTC for example, **Dec 26 2017 20:35:30 GMT+0500 (Local Standard Time)**

**Comment by xaksis** [comment]
ah... UTC functions are WIP with datefns. You can follow the progress here: 
https://github.com/date-fns/date-fns/milestone/7

However, you can convert the date to local time yourself in your rows like they do here: 
https://github.com/date-fns/date-fns/issues/556

Unfortunately there isn't much vue-good-table can do in this regard so I'm going to close this for now.

**Comment by kashifullahwebdeveloper** [comment]
No problem, I will look into it. 

thank you for time :)

**Comment by dcrystalj** [comment]
@ikashifullah https://jsfiddle.net/kashifullah/x9mqfy5y/ your example throws exception in console.log.
Looks like Vue good table has some issues using date-fns properly
