### ISSUE TITLE
Broken pagination with all rows per page

### ISSUE THREAD

**Issue by kjakobson** [xaksis/vue-good-table#15]
![broken-pagination](https://user-images.githubusercontent.com/5407169/27471574-7547e2a4-57f8-11e7-8a3d-6fb4272b8e57.gif)

It seems when you choose **All** from **Rows per page** option it somehow breaks the pagination. You can then paginate and it only adds rows. I would expect that when I choose **All** the pagination should either disappear or be disabled, but still display the correct text ("all records", ...).

**Comment by xaksis** [comment]
ooh thank you for pointing this out! I'll look into it tomorrow morning.

**Comment by xaksis** [comment]
v1.6.1 fixed
