### ISSUE TITLE
i18n support for column label (and format)

### ISSUE THREAD

**Issue by species7213uv** [xaksis/vue-good-table#151]
When changing the current language, everything changes except the table.
Please add an optional field e.g. label_i18n which results in $t('keyword').
Or a more flexible way with label_bind which has to have the complete expression as a value.
(Same for date formats.)

**Comment by paulocr** [comment]
+1

**Comment by xaksis** [comment]
@species7213uv can you explain this a bit more. I don't have much experience with i18n. What exactly is not translating?

**Comment by plehnen** [comment]
i18n for column names and some other texts can be done like this:
```
<vue-good-table
                    :columns="table.columns"
                    :rows="table.rows"
                    :rowsPerPageText="$t('navigation.tablePerPage')"
                    :ofText="$t('navigation.tableOf')"
                    :prevText="$t('navigation.tablePrev')"
                    :nextText="$t('navigation.tableNext')">
              <template slot="table-column" slot-scope="props">
                {{ $t(props.column.label) }}
              </template>
            </vue-good-table>
```

Unfortunately it doesn't work for placeholders and filterOptions. 
So whenever the language is changed, those texts will not update.
I currently don't have any clue how to solve this...

**Comment by xaksis** [comment]
global search placeholder can be defined by `globalSearchPlaceholder` property. column filter placeholders can be defined by `placeholder` property within columns and filterOptions are texts provided by the users. you can provide each one of them accordingly: 
```
     {
          label: 'Name',
          field: 'name',
          filterable: true,
          placeholder: $t('my placeholder')
        }
```
if it doesn't work on input fields, then it's more of a i18n issue rather than vue-good-table's. closing for now.
