### ISSUE TITLE
Customize global search template

### ISSUE THREAD

**Issue by sergiocastrovale** [xaksis/vue-good-table#156]
Right now global search fills the whole width of the table by being placed on a `tr > td`.

Now in terms of layout organization this is rarely useful - we usually don't need a search input that spans across so much space. More often than not you end up adding action buttons, grid toggling or filters right next to the search bar. Is there anyway we can do that with the current build?

**Comment by xaksis** [comment]
@sergiocastrovale good point... but it really depends on the width of your device where the table is showing. For now, the table doesn't allow adding elements next to the search bar, however If you want to add action buttons etc, you can use the 
```html
<slot name="table-actions">
</slot>
```
this appears on the top right of the table. this is good feedback though, so i'll think about a responsive solution for the global search space.

**Comment by sergiocastrovale** [comment]
What I would suggest is that the global search stepped out of the table and became a slot on its own. So, instead of being in a `thead > tr > td`, it would be a "top" slot where we could override things in the same way we override columns. It could even look like it belongs to the table by default (borders and such). Does that make sense?

It's very uncommon to see search inputs span across the whole area of the table. I just googled "datatables" and there's basically no image where that UI comes into place. From [really old UIs](https://www.codeproject.com/KB/scripting/JQuery-DataTables/editable-datatable-java-edit.png) to [more modern looking](http://csharpcorner.mindcrackerinc.netdna-cdn.com/article/Asp-Net-mvc5-datatables-plugin-server-side-integration/Images/image001.png), they follow the same UX pattern all across - small search with a bunch other stuff in the same line.

**Comment by xaksis** [comment]
search moved out of the table and the same row is now used for action-items-slot. closing.
