### ISSUE TITLE
Error in ./node_modules/vue-good-table/src/components/Table.vue

### ISSUE THREAD

**Issue by deanilvincent** [xaksis/vue-good-table#157]
Good day,

It's my first time to install this package in my project. 

I just simply imported the package above my js. `import VueGoodTable from "vue-good-table"`

But I'm having an error.

Here's what it says:

![capture](https://user-images.githubusercontent.com/10904957/34869238-3e7e3fd4-f7c1-11e7-8465-cac35958573e.PNG)

I'm using webpack anyway.

**Comment by xaksis** [comment]
Hi @deanilvincent! how did you create your project? did you use vue-cli?

**Comment by deanilvincent** [comment]
No, I didn't use vue-cli in creating my ASP.NET Core project @xaksis  but it has package.json and I have a webpack + babel too. The other packages are working. These packages are stored in my node_modules. It's weird why it's error in calling the Table.vue from the components.

**Comment by xaksis** [comment]
this plugin is for vuejs framework. if you aren't using vue, this library will not work. 

closing for now. Let me know if you need me to re-open this.

**Comment by deanilvincent** [comment]
But I'm using vue.js framework in my project. @xaksis 

In fact, I'm pulling Vue in node_modules

**Comment by deanilvincent** [comment]
Hold on let me try.

**Comment by deanilvincent** [comment]
@xaksis yeah it's working like a charm now. :) Thank you so much for the support and quick response. Thank you for this cool plugin as well. It helps a lot of developers! You may close this issue. Have a great weekend! 👍
