### ISSUE TITLE
Global search colspan is incorrect when a table-row-after is present

### ISSUE THREAD

**Issue by sergiocastrovale** [xaksis/vue-good-table#160]
Case in point: my table has 4 columns and one extra slot `table-row-after` for actions.

However, when the search bar is rendered, instead of filling 100% of the screen, it stops at the actions column since it only spans by the "regular" columns.

![screenshot_1](https://user-images.githubusercontent.com/8822036/34965331-237b560e-fa4b-11e7-9f19-02e159600c2d.png)

**Comment by xaksis** [comment]
you are missing placeholder column definitions in your columns data for your table-row-after columns. refer to: https://xaksis.github.io/vue-good-demos/#/dynamic-table (checkbox example).
