### ISSUE TITLE
[Bug] Sorting decimal values isn't working properly

### ISSUE THREAD

**Issue by maurocasas** [xaksis/vue-good-table#165]
I have a dataset with a column with values
100.00
0.00
1.12
17.5

And when I sort, it's not doing 0.00 towards 100.00, but sorting them strangely. Not even following a regular order.

My column has "decimal" type setting.

**Comment by xaksis** [comment]
hey @maurocasas 
jsfiddle seems to be working fine: https://jsfiddle.net/aks9800/1t1czL6f/
can you reproduce the behavior in a fiddle? what is your column definition?

**Comment by thelowellgallery** [comment]
Search for 'James' here comes up empty

https://jsfiddle.net/5fzdm30y/5/

**Comment by xaksis** [comment]
closing. let me know if this is still an issue and we'll take a look.

**Comment by maurocasas** [comment]
This is actually still happening.

I have defined my columns properly, and I'm getting an indexOf() error from the console.
As if it's not finding the next/prev value to arrange it.
