### ISSUE TITLE
warn:  Computed property "paginated" was assigned to but it has no setter.

### ISSUE THREAD

**Issue by rayets123** [xaksis/vue-good-table#167]
Computed property "paginated" was assigned to but it has no setter.

found in

---> <VueGoodTable> at /Users/akshay/Projects/learn/vue/plugins/vue-good-table/src/components/Table.vue

When I remove paginate="true",  the error still remains

**Comment by rayets123** [comment]
OOOOPPPSSS!!!wtf
I use https://github.com/TahaSh/vue-paginate in my project end when I import it like this : 
import VuePaginate from 'vue-paginate'
	Vue.use(VuePaginate)
i have error : Computed property "paginated" was assigned to but it has no setter.
Рow can I solve this conflict?

**Comment by rayets123** [comment]
I find this issues in #39 , but it without solution

**Comment by rayets123** [comment]
My quick and dirty solution:
in node_modules/vue-paginate/dist/vue-paginate.js
find method: paginated: function paginated (listName) {.....
and rename this method
after all works without errors

**Comment by xaksis** [comment]
@rayets123 as you've discovered this seems to be a problem of name conflict with a different library. Unfortunately I cannot do much about it. However I suggest you import these components locally as apposed to using it globally in the app, that might help. 

closing for now.
