### ISSUE TITLE
Fuzzy filtering

### ISSUE THREAD

**Issue by imbolc** [xaksis/vue-good-table#17]
Hey, thanks for really good table :) It would be great to have option for fuzzy or maybe regexp filtering.

**Comment by happyDemon** [comment]
http://fusejs.io/ would be great for this

**Comment by xaksis** [comment]
@imbolc thanks! I have been thinking about custom filter support for a bit but haven't had time to implement it just yet. I'll keep this open for now. 
@happyDemon thanks for the suggestion. Will look into it.

**Comment by xaksis** [comment]
closing this. Thanks again, @mossadal
