### ISSUE TITLE
Customizable Per-Page dropdown

### ISSUE THREAD

**Issue by TheJaredWilcurt** [xaksis/vue-good-table#177]
I'll be creating a PR for this. It will allow you to pass in an array of objects

```js
<vue-good-table
  :customPerPage="customPerPage"
  :columns="columns"
  :rows="rows"/>
  // ...
  data: function () {
    return {
      customPerPage: [
        {
          amount: 10,
          default: true
        },
        {
          amount: 25
        },
        {
          amount: 50
        }
        {
          amount: -1,
          label: 'All',
        }
      ]
    };
  }
```

Each object can accept:

 * a boolean for `default` to set it as the default value
 * a string for the `label` if they want to customize the label for that object
 * a number for `amount` (required)

If no label is passed in the the label will default to `amount.toString()`. If -1 is used for amount, then all items will be shown.

* * *

I've created a few simple PR's to get the  repo updated and add in some basic linting in preparation for this branch/PR.

**Comment by xaksis** [comment]
This PR has been merged along with another that adds more customization ability to the pager.
