### ISSUE TITLE
Reset to Page 1 on per-page dropdown change

### ISSUE THREAD

**Issue by TheJaredWilcurt** [xaksis/vue-good-table#178]
**Scenario:**

* I have 100 items.
* I am displaying 10 items per page.
* I am on the last page (90-100 of 100)
* I change the per-page dropdown from 10 to 20
* I am now displaying the first 20 items on the page and the pagination shows 180-200 of 100
* I click the "Prev" button 5 times and now I see the last 20 items of the list and the pagination is 80-100.

**Proposed solution:**

I'd like to be able to pass in a value to `resetOnPerPageChange="true"`. This would put you back on page 1-X of 100 on any change to the items-per-page dropdown.

I may create a PR for this.

**Comment by xaksis** [comment]
hey @TheJaredWilcurt this is now fixed in v1.20.0
