### ISSUE TITLE
How to do proper styling

### ISSUE THREAD

**Issue by michelvocks** [xaksis/vue-good-table#179]
Hello,

I've some trouble to correctly customize the style of the table.
I made a fiddle: https://jsfiddle.net/Lhowhqnk/10/

Everything is working smoothly there. I can just override the given CSS-Classes. 
If I do the same within my project, it simply does not work and I have no clue why this happens. 

Some more details about my project. My project is based on vue-admin (https://github.com/vue-bulma/vue-admin) which uses Bulma, Vue 2.0 and Webpack. Is there any difference compared to fiddle? What do I miss here?

Thank you in advance

**Comment by xaksis** [comment]
Does your style tag have a `scoped` attribute? If so, those styles will not effect anything outside the scope of that component.

**Comment by michelvocks** [comment]
Oh wow. Thanks a lot. You made my day 👍
