### ISSUE TITLE
Example usage of onClick

### ISSUE THREAD

**Issue by kirk2022** [xaksis/vue-good-table#18]
I am currently attempting to use 'onClick' as per the instructions, however I get the following error: 

'Uncaught TypeError: this.onClick is not a function'

Please add an example of onClick being used to the documentation.

**Comment by xaksis** [comment]
@kirk2022 can you show your usage?
onClick needs to be a function for example: 
```
<vue-good-table
      :columns="columns"
      :onClick="onClickFn"
      :rows="rows"/>
// where data
data(){
      return {
       // rows, columns ...
        onClickFn: function(){
          console.log('something random');
        },
      };
```

**Comment by xaksis** [comment]
readme updated to better show this. closing.
