### ISSUE TITLE
Add Datepicker to Filter

### ISSUE THREAD

**Issue by frommie** [xaksis/vue-good-table#180]
Hey,

is there an easy way to get a date picker filter for datetime fields? 

I'm having issues to modify the filter inputs, so I added an input as a custom column label but now I cant filter the computed rows. I modified the source-list but the changes are not reflected in the rendered list (so maybe an update function for the table would be fine for a workaround).

Best regards
Christian

Update: I now included daterangepicker and called it on the inputfield using jquery, the rangepicker opens and the input field is filled properly when I select a daterange. But unfortunately the filter function is not called. Is there a way to call the filter function for the field manually?

Update2: Added following jquery to my methods:

```
$('.applyBtn').on("click", function() {
  setTimeout(function(){
    $('input[placeholder="Filter Datum"]')[0].dispatchEvent(new Event('input', { 'bubbles': true }));
  }, 10);
});
```

Its ugly, but it works. Would love to see a official datepicker implementation!

**Comment by xaksis** [comment]
@frommie this is strange, because any change in the source list should be reflected in the generated table as the table is watching for row data changes. I'll look into this.

**Comment by xaksis** [comment]
@frommie v1.20.0 allows you to specify `filterValue` on the columns to change the filter value for a column. You can edit this value on the fly and the table will update to reflect the change. This should work for your usecase.

**Comment by wwwork** [comment]
Is it possible to add date picker to filers place under column label?

**Comment by AndrianD** [comment]
Hello,
Nice plugin thank you. I am using vue 2.5 and as evoked by @wwwork , I would like to know how to implement a datepicker to filter results instead of input text.
Thank you for your answers!
