### ISSUE TITLE
Fixed header

### ISSUE THREAD

**Issue by f-r3d** [xaksis/vue-good-table#181]
Hi',

It can be usefull to have to possibility to set the header fixed, in this way with css (especially flex) it will be possibile to set easily the height of the table body for scrolling and leave the header (and the footer) always visible.

Best regards
Federico

**Comment by xaksis** [comment]
@f-r3d this is now implemented in v2.12.1. documentation: 
https://xaksis.github.io/vue-good-table/guide/configuration/#fixed-header

closing.

**Comment by smellyshovel** [comment]
@xaksis the `fixed-sidebar` option doesn't work in 2.17.6+ at all. Had to downgrade to 2.12.1. Just letting you know. And yep, sorry for necroposting.

**Comment by yogithesymbian** [comment]
its broken responsive when the web have sidebar mode collapse the header width is not 100% just only on **header**
