### ISSUE TITLE
Alternate paging

### ISSUE THREAD

**Issue by f-r3d** [xaksis/vue-good-table#182]
Hi',
with a large number of pages it can be difficult to reach a specific page using "next", it can be usefull to use an input tag instead of, for example, 1 - 10 of 1000.
In this way changing the input value it can be triggered the new page value.

`<span class="page_number"><input type="number" value="x"></span> <span class="page_of"> / 1000</span>`

Best regards,
Federico

**Comment by xaksis** [comment]
@f-r3d good point! I'll look into this.

**Comment by xaksis** [comment]
@f-r3d v2.11.0 allows for page mode with the ability to jump to any valid page.
https://xaksis.github.io/vue-good-table/guide/configuration/pagination-options.html#mode

closing.
