### ISSUE TITLE
Prefill filter column

### ISSUE THREAD

**Issue by hhertogh** [xaksis/vue-good-table#184]
Hello,

is it possible to prefill the filter column with some data so that the search function is automatically launched when loaded?

This can be useful when you search for some data, click on an item, go to a page, then come back, you would like to see the search filter already filled.

Thanks.

**Comment by xaksis** [comment]
@hhertogh you bring up a good usecase. Currently vue-good-table doesn't support this for column filters (for global filter you can use `externalSearchQuery`), but I'll look into adding this in.

**Comment by xaksis** [comment]
@hhertogh this is now added in v1.20.0. you can use `filterValue` property for columns to pre-populate the filters or change them on the fly.
