### ISSUE TITLE
Thousands/Millions Comma Separator for Decimal Data Type

### ISSUE THREAD

**Issue by digital-phantom** [xaksis/vue-good-table#187]
Hi! Loving your package so far.

I would like to ask if it's possible to add a thousands/millions comma separator (like 1,000,000) when displaying data with type "Decimal" ? It would be useful for displaying financial data.

I'm not sure if it's already possible after reading through documentation. Please advise.

Thank you!

**Comment by xaksis** [comment]
hey thank you, @digital-phantom. v1.20.0 supports `formatFn` for columns, where you can specify your own formatting.
