### ISSUE TITLE
display all rows when not on the first page

### ISSUE THREAD

**Issue by kjakobson** [xaksis/vue-good-table#19]
Thanks for previous fix of the pagination. I've found another one related to pagination. Steps to recreate:

1. On table populated with data with let's say 10 rows per page, go to 2nd page.
2. Choose to display **All**
3. Instead of all data, only last row is displayed until you click on **Previous**.

**Comment by xaksis** [comment]
Thanks again for pointing it out! all fixed: v1.6.2
