### ISSUE TITLE
Slow network wrong data being shown on tabs

### ISSUE THREAD

**Issue by sarath49** [xaksis/vue-good-table#192]
I am showing rows of data via tabs using view good table.
While in fast network the table rendering is good, however when network is slow and there is large amount of data to be fetched it does not show the correct data.

For example
I have two tabs shown via vue good table
 a) received 
   Shows entries that were received by current logged in user.
b) forwarded
   Which were forwarded by current logged in user.

Received section may get empty when each table is forwarded using check box and will be listed under forwarded tab.

Forwarded contain thousands of entries that were forwarded.

Now when I open my Chrome Dev tools and set network to 3G slow and switch fast between these two tabs, the data in forwarded will start showing under received tab.

I found a similar issue in vuejs forum 

https://forum.vuejs.org/t/slow-when-hiding-component-with-large-content/27277/9

Thanks

**Comment by xaksis** [comment]
@sarath49 when you have some time, could you try the beta build and see if this problem exists for that build as well?

documentation: https://github.com/xaksis/vue-good-table/tree/new-build
upgrade guide: https://github.com/xaksis/vue-good-table/wiki/Guide-to-upgrade-from-1.x-to-v2.0

**Comment by xaksis** [comment]
closing.
