### ISSUE TITLE
Column filters substring search

### ISSUE THREAD

**Issue by StefanOosten** [xaksis/vue-good-table#193]
Hello,

Is there a way for column filters to search for substring too instead of an exact match?

Searching for "Doe" in a name column won't result fields containing "John Doe"

**Comment by xaksis** [comment]
Hi @StefanOosten, you can add your own filter function for columns:
https://jsfiddle.net/aks9800/obfky53g/

By default, vue-good-table does a filter for `begins-with`

**Comment by StefanOosten** [comment]
Thank you!
