### ISSUE TITLE
Filtering True/False?

### ISSUE THREAD

**Issue by T-Bod** [xaksis/vue-good-table#194]
Great functionality, appreciate your work on this!

I'm displaying status data where status is a true/false value, sorting works as expected however filtering doesn't seem to be working as I receive the following JS error when trying to enter 'true' or 'false':

Error in callback for watcher "columnFilters": "TypeError: _this2.collect(...).toLowerCase is not a function"

Any suggestions?

**Comment by xaksis** [comment]
@T-Bod for custom behavior like filtering true/false etc you should use your own filter for the column. 
Here's a jsfiddle that shows you how you can use your own filter function for a column.
https://jsfiddle.net/aks9800/obfky53g/
