### ISSUE TITLE
input event not fired on select element in IE11

### ISSUE THREAD

**Issue by Idan747** [xaksis/vue-good-table#195]
Hi,

There is a bug on IE11 when changing the filter value in the select filter.
way to fix:
need to replace 'v-on:input' to 'v-on:change'

                  <select v-if="column.filterDropdown && typeof(column.filterOptions[0]) !== 'object'"
                    class=""
                    :value="columnFilters[column.field]"
                    v-on:input="updateFilters(column, $event.target.value)">
                      <option value="" key="-1">{{ getPlaceholder(column) }}</option>
                      <option
                        v-for="(option, i) in column.filterOptions"
                        :key="i"
                        :value="option">
                        {{ option }}
                      </option>
                  </select>

should be 

                  <select v-if="column.filterDropdown && typeof(column.filterOptions[0]) !== 'object'"
                    class=""
                    :value="columnFilters[column.field]"
                    v-on:change="updateFilters(column, $event.target.value)">
                      <option value="" key="-1">{{ getPlaceholder(column) }}</option>
                      <option
                        v-for="(option, i) in column.filterOptions"
                        :key="i"
                        :value="option">
                        {{ option }}
                      </option>
                  </select>

@xaksis I created a pull request for you here:
https://github.com/xaksis/vue-good-table/pull/196

**Comment by xaksis** [comment]
closing! thank you for the PR
