### ISSUE TITLE
Help: Need to i18n of Column Labels

### ISSUE THREAD

**Issue by kashifullahwebdeveloper** [xaksis/vue-good-table#197]
Hi @xaksis,

   I am currently stuck into an issue of translating Table Column Labels (Heading). Could you help me how can I achieve this?

Let's put this into coding :)

```
{
          label: 'Name',  // I want to translate this into other languages 
          field: 'name',
          filterable: true
},
```

Thank you

**Comment by kashifullahwebdeveloper** [comment]
Hi @xaksis,

  I solved my issue using the following code, but I don't know if that is the right way, please let me know.

```
<template slot="table-column" slot-scope="props">
       <span v-if="props.column.label =='Name'">
              {{ $t('lang.components.name') }}
       </span>
</template>
```

Thank you for amazing plugin. :+1:

**Comment by pnhuyduy** [comment]
Hi, I know it's a bit late for response but I found a solution.
change your `columns` from data to computed so when you change your locale it's will update the text.
```javascript
computed: {
    columns() {
      return [
        { label: this.$i18n.t('foo') },
        { label: this.$i18n.t('bar') }
      ]
}
```

Hope this helps!
