### ISSUE TITLE
Functionality: could you make table cells editable?

### ISSUE THREAD

**Issue by focussing** [xaksis/vue-good-table#20]
For example per column property "setEditable".
After editing finished (td blur?) fire event.

**Comment by xaksis** [comment]
thank you for your suggestion, however for additional functionality with table cells etc, you can just create the td template yourself, like so: 
```
<vue-good-table
  title="Dynamic Table"
  :columns="columns"
  :rows="rows"
  :lineNumbers="true"
  :defaultSortBy="{field: 'age', type: 'asec'}"
  :globalSearch="true"
  :paginate="true"
  styleClass="table condensed table-bordered table-striped">
  <template slot="table-row" scope="props">
    <td>{{ props.row.name }}</td>
    <td class="fancy">{{ props.row.age }}</td>
    <td>{{ props.row.btn }}</td>
  </template>
</vue-good-table>
```

**Comment by xaksis** [comment]
closing. Please re-open if this doesn't satisfy your needs.

**Comment by focussing** [comment]
I have created an editable component which I use in the td template like:

```
<vue-good-table :columns="columns" :rows="rows" :paginate="true">
 <template slot="table-row" scope="props">
   <td><editable :item="props.row.strname" @updated="onUpdate(i,'stringnaam',$event)"></editable></td>
   <td> <i class="fa fa-trash-o fa-lg fa-fw" @click="onDelete(i,$event)"></i> </td>
</template>
</vue-good-table>
```

For the updated event I need the row index; how do I do that?

**Comment by xaksis** [comment]
hey @focussing! You can get row index from `props.index`. make sure you're on v1.7.1 or later.

**Comment by focussing** [comment]
Hi @xaksis! 
Thank you.
Didn't know that there was a new release... I was still at 1.6.2.
How can I see there is a new release?

Another issue; after the page is loaded the rows order is not exactly as read from my database...
It should be ordered by index. But the first row has id 104, and the rest goes from id 12 upto 201

**Comment by xaksis** [comment]
@focussing hmm... good question about where to see new release... perhaps i'll add a changelog.

I'll use the open issue to discuss the indexing problem. thanks for pointing it out.

**Comment by focussing** [comment]
Maybe you could make use of "Releases" like I see with other repositories?

**Comment by cristijora** [comment]
@xaksis I see that you have version tags. You could use https://github.com/zeit/release
with which you can generate a changelog very fast

**Comment by xaksis** [comment]
@cristijora awesome! Thanks, I'll use it for the changelog!

**Comment by yashnarkhedkar** [comment]
Issue Title: **"Editable Component Value Propagation Issue"** `"vue-good-table": "2.21.0"`

Description:
When using editable components, such as input fields, and adding an event listener to track changes, an issue arises. When the value of one input is updated, it propagates to all other inputs because it modifies rows.field.value. This behavior is unexpected and can lead to unintended changes in other inputs.
