### ISSUE TITLE
Unable to get rid of unnecessary horizontal scrollbar

### ISSUE THREAD

**Issue by darrylpblack** [xaksis/vue-good-table#200]
I have used styleClass to customize the table but am unable to get rid of the horizontal scrollbar at the bottom even though it is not needed.  Seems to appear in all the samples too.  I've tried to explicitly disable it with overflow-x: hidden without any luck.  Any ideas?  Thanks for your help.  Here's the code, modified from your example.

<template>
  <div class="container">
    <vue-good-table title="Demo Table" :columns="columns" :rows="rows" :paginate="true" :lineNumbers="true" styleClass="table condensed table-bordered table-hover sampleCustomization" />
  </div>
</template>
<script>
export default {
  name: 'Search',
  data() {
    return {
      columns: [{
          label: 'Author',
          field: 'name',
          filterable: true
        },
        {
          label: 'Age',
          field: 'age',
          type: 'number',
          html: false
        },
        {
          label: 'Created On',
          field: 'createdAt',
          type: 'date',
          inputFormat: 'YYYYMMDD',
          outputFormat: 'MMM Do YY'
        },
        {
          label: 'Percent',
          field: 'score',
          type: 'percentage',
          html: false
        }
      ],
      rows: [
        { id: 1, name: 'John', age: 20, createdAt: '20111031', score: 0.03343 },
        { id: 2, name: 'Jane', age: 24, createdAt: '20111031', score: 0.03343 },
        { id: 3, name: 'Susan', age: 16, createdAt: '20111030', score: 0.03343 },
        { id: 4, name: 'Chris', age: 55, createdAt: '20111011', score: 0.03343 },
        { id: 5, name: 'Dan', age: 40, createdAt: '20111021', score: 0.03343 },
        { id: 6, name: 'John', age: 20, createdAt: '20111031', score: 0.03343 },
        { id: 7, name: 'Jane', age: 24, createdAt: '20111031', score: 0.03343 },
        { id: 8, name: 'Susan', age: 16, createdAt: '20131031', score: 0.03343 },
        { id: 9, name: 'Chris', age: 55, createdAt: '20121031', score: 0.03343 },
        { id: 10, name: 'Dan', age: 40, createdAt: '20111031', score: 0.03343 },
        { id: 11, name: 'John', age: 20, createdAt: '20111031', score: 0.03343 },
        { id: 12, name: 'Jane', age: 24, createdAt: '20110731', score: 0.03343 },
        { id: 13, name: 'Susan', age: 16, createdAt: '20170228', score: 0.03343 },
        { id: 14, name: 'Chris', age: 55, createdAt: '20170228', score: 0.03343 },
        { id: 15, name: 'Dan', age: 40, createdAt: '20111031', score: 0.03343 },
        { id: 19, name: 'Chris', age: 55, createdAt: '2011-10-31', score: 0.03343 }
      ]
    }
  }
}

</script>
<style scoped>
.sampleCustomization {
  overflow-x: hidden; 
}

</style>

**Comment by darrylpblack** [comment]
Lost some code in the cut and paste save so here it is again with less rows:

<template>
  <div class="container">
    <vue-good-table title="Demo Table" :columns="columns" :rows="rows" :paginate="true" :lineNumbers="true" styleClass="table condensed table-bordered table-hover sampleCustomization" />
  </div>
</template>
<script>
export default {
  name: 'Search',
  data() {
    return {
      columns: [{
          label: 'Author',
          field: 'name',
          filterable: true
        },
        {
          label: 'Age',
          field: 'age',
          type: 'number',
          html: false
        },
        {
          label: 'Created On',
          field: 'createdAt',
          type: 'date',
          inputFormat: 'YYYYMMDD',
          outputFormat: 'MMM Do YY'
        },
        {
          label: 'Percent',
          field: 'score',
          type: 'percentage',
          html: false
        }
      ],
      rows: [
        { id: 1, name: 'John', age: 20, createdAt: '20111031', score: 0.03343 },
        { id: 2, name: 'Jane', age: 24, createdAt: '20111031', score: 0.03343 },
        { id: 3, name: 'Susan', age: 16, createdAt: '20111030', score: 0.03343 }
      ]
    }
  }
}

</script>
<style scoped>
.sampleCustomization {
  overflow-x: hidden; 
}

</style>

**Comment by darrylpblack** [comment]
<template>
  <div class="container">
    <vue-good-table title="Demo Table" :columns="columns" :rows="rows" :paginate="true" :lineNumbers="true" styleClass="table condensed table-bordered table-hover sampleCustomization" />
  </div>
</template>

**Comment by xaksis** [comment]
@darrylpblack what browser are you on? can you create a jsfiddle where I can reproduce this?

**Comment by darrylpblack** [comment]
Hi Xaksis,

Thanks for getting back to me.  I can create a sample for you but even your
samples have the unnecessary horizontal scrollbar in them.  Here's a quick
snapshot with the unnecessary scrollbar show in your vue-good-demos (
https://xaksis.github.io/vue-good-demos/#/simple-table) with a green
rectangle around it.

Let me know if you still need a sample.

Thanks,

-Darryl

**Comment by xaksis** [comment]
@darrylpblack This should now be fixed in v1.20.3

**Comment by darrylpblack** [comment]
Xaksis,

Just upgraded; your fix works perfectly.  Awesome.  Thanks so much.

Your vue-good-table is an extremely valuable and well-built Vue
component--great work!

Regards and thanks again,

-Darryl

**Comment by xaksis** [comment]
Thank you so much @darrylpblack! Also, when you get some time, try out version 2.0 (it is currently in Beta). I have added a bunch of overall component improvements there.

**Comment by darrylpblack** [comment]
Hi,

Did spend a few minutes on Version 2.0.  The upgrade guide is great but it
would be helpful to have a complementary sample that shows off the new
stuff.  I got my simple sample working again but it is unclear to me how I
get bordering, stripping and condensed table attributes turned on again?
Got the nocturnal working but too dark for my use.

I will look again in a few months.

Thanks!

-Darryl

**Comment by xaksis** [comment]
hey @darrylpblack the new documentation is actually on the new-build branch. You can see it here: 
https://github.com/xaksis/vue-good-table/tree/new-build

I'll create some recipes (still work in progress for now). Thank you for checking it out.
