### ISSUE TITLE
draggable rows

### ISSUE THREAD

**Issue by Fabio1988** [xaksis/vue-good-table#201]
i want to make the rows draggable, but it's not working with draggable or transition-group...

https://jsfiddle.net/h81th3ys/

Is it possible to make the rows draggable within a vue-good-table?

greetings Fabio

**Comment by xaksis** [comment]
Hey, @Fabio1988 this is currently not supported in vue-good-table. It is not on the roadmap in the near future either, but I'll gladly review a PR. 

closing.
