### ISSUE TITLE
AJAX datatable

### ISSUE THREAD

**Issue by Mont4** [xaksis/vue-good-table#204]
Please support [Yajra Datatable](https://github.com/yajra/laravel-datatables) for ajax base api.

it 's not solution ([#128](https://github.com/xaksis/vue-good-table/issues/128)) counld not search on database.

**Comment by xaksis** [comment]
@Mont4 vue-good-table will not be made in-charge of calling API endpoints. The recommended way of doing that would be to have a remote mode where vue-good-table will emit every necessary event (like paging/filtering/sorting) and then you use these events to update your rows accordingly. 

A draft version of this is available in the new major version, which is currently in Beta - https://github.com/xaksis/vue-good-table/wiki/Guide-to-upgrade-from-1.x-to-v2.0#new-events-added-to-support-remote-mode
