### ISSUE TITLE
Error in Render: "TypeError":  cannot read property 'length' of 'null'

### ISSUE THREAD

**Issue by deanilvincent** [xaksis/vue-good-table#205]
Version: 1.19.2

![screen shot 2018-03-14 at 5 01 15 pm](https://user-images.githubusercontent.com/10904957/37392561-6e4b3600-27a9-11e8-982e-430cafdcd411.png)

**Comment by xaksis** [comment]
@deanilvincent this was fixed in v1.20 please update your package. 
I'd also suggest when you have some time, to upgrade to v2.0.0-beta. It has a lot of stability and overall component improvements. it does contain breaking changes though so make sure you read the upgrade guide: 

https://github.com/xaksis/vue-good-table/wiki/Guide-to-upgrade-from-1.x-to-v2.0

**Comment by deanilvincent** [comment]
Thank you @xaksis  We trust your vue-good-table for enterprise level application. :) I'm done installing the 2.0.0-beta.0. I'll drop comments if I would find any bug or enhancement that needs to be address.

**Comment by xaksis** [comment]
That is a great compliment, @deanilvincent! Looking forward to your feedback.

**Comment by jjhesk** [comment]
got the same issue on beta

**Comment by adgrace** [comment]
@jjhesk Did you get a solution?
I am experiencing the same problem: Cannot read property 'length' of undefined.

**Comment by SETTER2000** [comment]
Не работает ваш код.
[Vue warn]: Error in render: "TypeError: Cannot read property 'length' of undefined"

found in

---> <VueGoodTable>
       <TablePoaleell> at src/components/TablePoaleell.vue
         <App> at src/App.vue
           <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
Vue._render @ vue.runtime.esm.js?2b0e:3544
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
run @ vue.runtime.esm.js?2b0e:4548
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4304
(anonymous) @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4396
update @ vue.runtime.esm.js?2b0e:4538
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4625
(anonymous) @ TablePoaleell.vue?0502:40
Promise.then (async)
getRows @ TablePoaleell.vue?0502:38
mounted @ TablePoaleell.vue?0502:56
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4213
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6340
patch @ vue.runtime.esm.js?2b0e:6559
Vue._update @ vue.runtime.esm.js?2b0e:3939
updateComponent @ vue.runtime.esm.js?2b0e:4060
get @ vue.runtime.esm.js?2b0e:4473
Watcher @ vue.runtime.esm.js?2b0e:4462
mountComponent @ vue.runtime.esm.js?2b0e:4067
Vue.$mount @ vue.runtime.esm.js?2b0e:8409
(anonymous) @ main.js?56d7:9
./src/main.js @ app.js:4470
__webpack_require__ @ app.js:724
fn @ app.js:101
1 @ app.js:4484
__webpack_require__ @ app.js:724
(anonymous) @ app.js:791
(anonymous) @ app.js:794
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'length' of undefined
    at VueComponent.typedColumns (vue-good-table.es.js?fe82:1732)
    at Watcher.get (vue.runtime.esm.js?2b0e:4473)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4578)
    at Proxy.computedGetter (vue.runtime.esm.js?2b0e:4830)
    at Proxy.__vue_render__$6 (vue-good-table.es.js?fe82:2322)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3542)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4060)
    at Watcher.get (vue.runtime.esm.js?2b0e:4473)
    at Watcher.run (vue.runtime.esm.js?2b0e:4548)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4304)

**Comment by yogithesymbian** [comment]
```
TypeError: Cannot read properties of null (reading 'length')
    at VueComponent.paginated (vue-good-table.esm.js?f617:14006:1)
```

the error is these lines code
```
 paginated: function paginated() {
      var _this2 = this;

      if (!this.processedRows.length) return []; // here null
```

my version : **"vue-good-table": "2.21.0",**
any solution ?

**edit** i solve by modified the package **_/node_modules/vue-good-table/dist/vue-good-table.js_**
before
```
if (!this.processedRows.length) return []; // modified all of reading length of variable.
``` 

after
```
if (this.processedRows && !this.processedRows.length) return [];
```
reference : https://stackoverflow.com/a/56587738/8122500

still looking for how to init define of the processedRows.
