### ISSUE TITLE
Date localization

### ISSUE THREAD

**Issue by zeusfly-spb** [xaksis/vue-good-table#208]
How can I localize the date formatting?

**Comment by xaksis** [comment]
Hey @zeusfly-spb, can you explain with examples as to what you mean by localizing the format?

**Comment by zeusfly-spb** [comment]
Hello, xaksis! Thanks for the response, I have already solved the problem in php. What can you say about dynamically changing the width of columns in a table, such as colResizeable?

**Comment by xaksis** [comment]
@zeusfly-spb if you mean setting it programmatically, you can do it via "width" property of column. If you mean via user dragging to change width, that is currently not supported. 

either way, i'm going to close this ticket since you seem to have solved it.
