### ISSUE TITLE
rowStyleClass / perPage

### ISSUE THREAD

**Issue by aspirin37** [xaksis/vue-good-table#210]
Hello. I've got several problems after the latest update:
1) "rowStyleClass" stopped working for me. Neither string, nor function. 
2) when "perPage" is set it's dropdown doesn't work. It means I can not set a default value for my table anymore.

**Comment by xaksis** [comment]
@aspirin37 thank you for reporting this, can you confirm that you're using the beta build?

**Comment by xaksis** [comment]
I just tested both properties, and they seem to be working fine. 
here's a fiddle: 
https://jsfiddle.net/aks9800/6jboy8hv/

**Comment by aspirin37** [comment]
Well, I just updated my npm modules with "npm i" and then all tables in my project stopped working correctly. There's "vue-good-table": "^1.12.0" in my package.json. Probably the problem is on my side

**Comment by xaksis** [comment]
ahh! that's a really old version, you should upgrade to the latest. The latest version (non-beta) is 1.20.3. I'm going to close this issue.
