### ISSUE TITLE
BUG: The starting index string of the next page is incorrect

### ISSUE THREAD

**Issue by derFaizio** [xaksis/vue-good-table#214]
If the first page contains 10 (elements 1-10), the next of the next page should start from 11. Right now it lists 10-20. It should be 11-20.

**Comment by xaksis** [comment]
@derFaizio just to confirm, you're talking about the pagination numbers only right? the rows themselves seem to be correct for each page. 

also, can you tell me what version you're on?

**Comment by derFaizio** [comment]
Exactly. Only the pagination numbers. The rows themselves are perfectly fine. I am on version 1.20.3.

**Comment by xaksis** [comment]
@derFaizio  this should now be fixed in v1.21.0.
