### ISSUE TITLE
Add ability to 'All' option from page size dropdown

### ISSUE THREAD

**Issue by skray** [xaksis/vue-good-table#215]
The addition of `customRowsPerPageDropdown` has been great, but I am confused as to why the `All` option (with a value of -1 for the page) is still hardcoded in when providing the custom perPage dropdown. 

In my case, I never want the user to be able to select `All`, as my table is so large (15k rows) that it grinds the browser to a halt while attempting to render so many rows.

Would it be reasonable to add an option to explicitly remove the `All` choice from the pagination dropdown?

**Comment by xaksis** [comment]
absolutely reasonable! It's in there because most use-cases would still need a way to show all rows. But l agree that there should be a way to hide that option. Do you mind telling me if you using the new beta version? or released version?

**Comment by skray** [comment]
Thanks for the quick response! I am not using the beta version yet, just the latest released version.

**Comment by xaksis** [comment]
in version 1.21.0 you can hide the 'all' option, use `paginateDropdownAllowAll`
