### ISSUE TITLE
[BUG] New 'on-search' Event only firing on 'enter' even though the search is on 'key-up'

### ISSUE THREAD

**Issue by ggedde** [xaksis/vue-good-table#216]
### Issue Type
Bug

### Version
2.0.0-beta.5

### Expected Behavior
Should be firing based on 'searchTrigger'.

### Current Behavior
New "on-search'  Event is only firing on 'enter'  even though the search is on 'key-up'.

**Comment by xaksis** [comment]
seems to be working fine here: 
https://jsfiddle.net/aks9800/57a2a4ce/

can you create a jsfiddle to demonstrate this?

**Comment by xaksis** [comment]
ah okay, I see what you mean, the event itself is only triggered on enter. got it.

**Comment by xaksis** [comment]
fixed in version 2.0.0-beta.6

**Comment by ggedde** [comment]
@xaksis Awesome, Thanks
