### ISSUE TITLE
[Enhancement]  Add "filteredRows" in the event from the new 'on-search' Event

### ISSUE THREAD

**Issue by ggedde** [xaksis/vue-good-table#217]
### Issue Type
- [ ] Enhancement

### Version
2.0.0-beta.5

### Expected Behavior
I would like to also get the 'filteredRows' back in the event from the new 'on-seach' Event.
At least is there a way for me to get that data?  

I would like to get all the data from the filteredRows, but if that is not that easy or may cause a performance issue for every on 'key-up' event then at least get the number of filteredRows.  That way I can display the number somewhere else in my template.

### Current Behavior
Only the searchTerm is being returned in the event.

**Comment by xaksis** [comment]
this is now fixed in version 2.0.0-beta.6

**Comment by ggedde** [comment]
@xaksis Awesome, Thanks for the quick update.
So far really loving the simplicity of your this  module.
Thanks
