### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TheJaredWilcurt** [xaksis/vue-good-table#222]
`paginateDropdownAllowAll` is not documented

also

* https://github.com/xaksis/vue-good-table/wiki/Guide-to-upgrade-from-1.x-to-v2.0

says `npm install --save vue-good-table@beta`

The `@beta` can probably be removed now

**Comment by xaksis** [comment]
hey @TheJaredWilcurt 
`paginateDropdownAllowAll` is now part of paginationOptions as `dropdownAllowAll`
https://github.com/xaksis/vue-good-table#pagination-options

removed beta from guide! 👍
