### ISSUE TITLE
Column Data Resizable

### ISSUE THREAD

**Issue by Jochii12** [xaksis/vue-good-table#226]
Hi sir Good day,

Can  ask sir if you can add column resizable , 

Thank you Sir

**Comment by xaksis** [comment]
Hi @LeoKi, if you use the template provided when you create the issue, it'll help avoid me having to ask you a bunch of questions regarding your request. 

What do you mean by column resizable? do you mean for users to be able to resize the columns by dragging an edge? or you being able to resize the column in your code? 

for the latter, you can use column property `width: '200px'`. 

the former is not supported with vue-good-table.

**Comment by LeoKi** [comment]
Hello sir

I mean about resizable is, the user can drag and drop the size of column,

Anyway sir thank you ill use width for sizing.

Thank you sir

**Comment by sudhir600** [comment]
@LeoKi 
"for the latter, you can use column property width: '200px'." where to set column with in `<vue-good-table />`

I m facing the same issue, I want to set different column with for each column. how is it possible?

**Comment by sudhir600** [comment]
It work like this.
```
columns: [
	{
	label: 'Document Number	',
	field: 'documentNumber',
	width: '120px'
	},
	...
```

**Comment by sudhir600** [comment]
@LeoKi  can we add custom style or css class on each column.
ror E.g. 

```
columns: [
	     {
		label: 'Document Number	',
		field: 'documentNumber',
		width: '120px'
		cssClass: 'classname' // or
		style: 'your style goes here'
	     } ,
	...
	
```

**Comment by LeoKi** [comment]
ahehe.. thank you sir...
there some user like to use a resizable column like excel cols . it can be resize. but i stop looking the solution. ill stick it with the current version of this. 

thank you

**Comment by Hego2017** [comment]
Jochii12 Did you find a solution? I have the same problem. I want that td of my table will be resizable

**Comment by Jochii12** [comment]
@Hego2017 unfortunately sir i didn't find a solution for re sizable column. but there is a pure js table column re sizable .

**Comment by Hego2017** [comment]
Jochii12 , ok, I suppose that we can do it with Javascript. Thanks!
