### ISSUE TITLE
Return to first page when executing global search

### ISSUE THREAD

**Issue by skray** [xaksis/vue-good-table#227]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?

2.0.1

### Expected Behavior

When executing a global search, I would expect the pagination to start back at the first page.

### Actual Behavior

The pagination stays on the current page, or the last available one if the list is shortened.

### Steps to Reproduce the Problem

1. Go to the fiddle below
1. Go to the last page of results
1. Search 'n' (filters to 3 results)
1. The table stays on the second page instead of going back to the first

### jsfiddle

https://jsfiddle.net/57a2a4ce/54/

## Question/Enhancement

I could not find a way to force the table to go back to the first page programmatically. Is there a way to do this, or would it be considered as an enhancement?

**Comment by xaksis** [comment]
fixed in v2.0.2 your jsfiddle is working now. Thank you for taking the time to create it. I also added a way to programmatically switch pages - https://github.com/xaksis/vue-good-table#paginationoptionssetcurrentpage-number

closing.

**Comment by skray** [comment]
Great, thank you!
