### ISSUE TITLE
Fetch data from API

### ISSUE THREAD

**Issue by sylvaincaillot** [xaksis/vue-good-table#229]
### Issue Type
- [x] Enhancement Request

### Specs
Using the 2.0.2 version, I would like to use Good-table which is very neat to do API calls to fetch  data. My API is already taking care of the pagination, sorting and filtering and return formatted json but I don't know how to send the relevant parameters to it from Good-table and then how to process what has been returned.

is it possible? That would be perfect.

Cheers
S.

**Comment by xaksis** [comment]
@sylvaincaillot I'm currently working on remote mode for the table... which won't do any sorting/paging etc locally and instead will just emit events with the necessary parameters so you can update the table with remote data. I will try and come up with an example soon.

**Comment by sylvaincaillot** [comment]
That would be perfect, just emit the events, or provide the sorting, query, paging parameters and the API will take care of returning the relevant data.
Thank you

**Comment by xaksis** [comment]
@sylvaincaillot I was finally able to test and release a backend driven vue-good-table instance and can confirm it works well. I created a wiki to go over the workflow: 
https://github.com/xaksis/vue-good-table/wiki/Remote-Mode-Workflow

Let me know if you have any issues with this. Closing.
