### ISSUE TITLE
Add a prop to make the "No data for table" message customizable

### ISSUE THREAD

**Issue by arthurkirsz** [xaksis/vue-good-table#230]
### Issue Type

- [x] Enhancement Request

### Specs
Using 2.0.3
I was expecting all texts to be customizable. Unfortunately, the message when no data is available ("No data for table") is hardwritten.

Would love if you guys could make this overridable through a prop :)

**Comment by arthurkirsz** [comment]
Closing this one now :) I just got to the end of the doc : `<div slot="emptystate">` is my answer. Maybe improve a bit the documentation, I had a hard time to find it.

**Comment by xaksis** [comment]
@arthurkirsz thank you for the feedback, I'll see if I can make that more discoverable.
