### ISSUE TITLE
`remote` mode does not currently work for ungrouped rows

### ISSUE THREAD

**Issue by skray** [xaksis/vue-good-table#234]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?

Latest (v2.0.3)

What browser?

Firefox

### Expected Behavior
What did you expect to happen?

I was trying out the new undocumented `remote` mode. Using the `remote` mode property, I expected to be able to provide the `rows` property as a regular array.

### Actual Behavior
What actually happened?

No rows showed up, I had to format the `rows` parameter as an array of grouped rows.

### Steps to Reproduce the Problem

1. Set the mode property to `remote`
1. Provide an array in the `rows` property

### jsfiddle

https://jsfiddle.net/57a2a4ce/135/

### Additional info

I believe that flattening the rows should be happening after the `mode` check in the `paginated` computed property: https://github.com/xaksis/vue-good-table/blob/new-build/src/components/Table.vue#L477..L484

**Comment by xaksis** [comment]
whoops! this is clearly a bug... thank you for pointing it out. I'll check in the fix shortly

**Comment by xaksis** [comment]
this is now fixed in v2.1.0. @skray remote mode has not been through a litmus test yet, I plan on using it myself over the next few days, so there might be more changes coming soon.

closing this for now.
