### ISSUE TITLE
row keys

### ISSUE THREAD

**Issue by 0b3202b1-9ea6-4018-9159-718338b9f295** [xaksis/vue-good-table#235]
I notice when you loop over rows you use the index as the key.  Vue documentation makes it very clear that that is bad practice.  Actually it offers no value at all.  I suggest the following: suggest to users that they include a `key` value for each row and use that key when it is available.  Also---and this is the real reason why I'm making this post---publish an array of keys to the parent object reflecting the sort order.  It is definitely useful for the parent to be able to access the current sort order.

PS: I am a developer, and I was thinking of writing code for this myself and raising a PR, but it looks like our project isn't going in the same direction anymore.  Even so, this would be a very good improvement, and resident experts here could probably do it better than I.

**Comment by neverender24** [comment]
I seconded this one, as standard Vuejs looping should use the key instead of the index. As index will remain even when sorting but keys are persistent like v-for="item,key in temp"

**Comment by xaksis** [comment]
row keys was changed to an internal property index (which doesn't change while you're interacting with the table) https://github.com/xaksis/vue-good-table/blob/master/src/components/Table.vue#L116 a while back. 

The header row and columns still uses index to loop through, but header rows or column orders are not effected by table interactions. I will be introducing order for columns and we'll upgrade the keys at that point. 

@0b3202b1-9ea6-4018-9159-718338b9f295 by putting a ref on the component you can access the processed rows at any time. This object reflects the current row state of your table including sort/filter etc.

closing.
