### ISSUE TITLE
Template change in footer

### ISSUE THREAD

**Issue by HorstBrack** [xaksis/vue-good-table#236]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Specs
What version are you using?
2.0.5

What browser?
Chromium

### Expected Behavior
What did you expect to happen?

I have rows with checkboxes, and I would like to have a "delete all selected" button at the bottom under the checkboxes.
Right above the "Rows per page" line.
There seems to be no way to pass templates to the footer, the way you can do with the header, right?
If not can this be made possible, or can I do that myself even?

**Comment by xaksis** [comment]
@HorstBrack you are correct in that there's no footer template. for table actions, I suggest you use the table-actions slot which will show up on the top-right of the table.

Relevant documentation:  
https://github.com/xaksis/vue-good-table#table-actions-slot

Also for checkboxes, `v2.1.0` has in-built support for checkboxes. refer to a working example here: https://jsfiddle.net/aks9800/dzka5qz0/ 

closing this.
