### ISSUE TITLE
How to pass the rows index in template to the handlers function?

### ISSUE THREAD

**Issue by arivera12** [xaksis/vue-good-table#24]
```
<template slot="table-row" scope="props">
   <td>{{ props.row.CustomerID }}</td>
   <td><button class="btn btn-danger" v-on:click="del(props.row.ID, $event, $index???)"><i class="fa fa-remove"></i></button>
    </td>
</template>
```

**Comment by xaksis** [comment]
in v1.7.1 you can access index via props.index

**Comment by arivera12** [comment]
Thanks dude it just worked as expected!!!!

**Comment by arivera12** [comment]
Did I miss this from the docs? I always read everything before asking questions over here. If isn't there please add it for future reference for other contributors/users.

**Comment by xaksis** [comment]
@arivera12 actually I added it in v1.7.1 after seeing your question. So thank you for pointing it out. I will add it to the docs soon.
