### ISSUE TITLE
sort-options interferes with input on page 2 and onward

### ISSUE THREAD

**Issue by khe817** [xaksis/vue-good-table#241]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.1.1

What browser?
Chrome 65 , Firefox 59, IE 11, Edge

### Expected Behavior
When configure pagination and sort together for a table with inputs in each row, should be able to enter input regardless of which page user is in.

### Actual Behavior
When add sort to vue-good-table with inputs in each row and pagination already configured, sort interferes with the ability to update inputs when on page 2, and onward.

### Steps to Reproduce the Problem

1. Go to the jsfiddle below.
1. Navigate to page 2 or beyond in the table.
1. Try to update any of the row's column `age`. This is where you could see that user cannot enter any more than 1 letter into the input box without being bounced back to page 1.

### jsfiddle
[jsfiddle reproduction](https://jsfiddle.net/57a2a4ce/169/)

**Comment by xaksis** [comment]
hey @khe817, v2.2.0 fixes this. your jsfiddle is now working. 

closing.
