### ISSUE TITLE
Feature Request - self.$emit('onRowHover', row)

### ISSUE THREAD

**Issue by kgrosvenor** [xaksis/vue-good-table#242]
I hope the title explains it, really like the plugin its fantastic, it seems long winded for me to do custom column template though, what does everyone else think about this?

`<component @onRowHover="selectRowFn"></component>`

**Comment by kgrosvenor** [comment]
And for it to emit current object in the callback

On 11 Apr 2018 23:19, "xaksis" <notifications@github.com> wrote:

@kgrosvenor <https://github.com/kgrosvenor> are you just looking for an
event handler for row hover?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xaksis/vue-good-table/issues/242#issuecomment-380613870>,
or mute the thread

**Comment by col-panic** [comment]
Row hover event would be interesting, would give the chance to provide a tooltip or something else!

**Comment by xaksis** [comment]
@kgrosvenor @col-panic sounds like a plan, expect this in an upcoming release shortly.

**Comment by xaksis** [comment]
This is now available as a table event `@on-row-mouseenter` and `@on-row-mouseleave`. table events section also added to the documentation: 
https://github.com/xaksis/vue-good-table#table-events

closing.

**Comment by kgrosvenor** [comment]
Amazing thanks for taking that on board, makes it all the better 👍 💯
