### ISSUE TITLE
Passing components as column values

### ISSUE THREAD

**Issue by andrewsheffield** [xaksis/vue-good-table#243]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Specs
2.2.0

What browser?
NA

### Expected Behavior
Pass a string in the fashion of
```
columns: [
  {
     field: 'id',
     component: 'my-id-component'
  }
]
```

implements with <component :is='what-ever-string-passed'></component>

This would allow me to build components in the column value for each row.  I could add button groups or hover events or whatever i need.

**Comment by xaksis** [comment]
hey @andrewsheffield you can pass your custom component in the slot for the cell. 
refer to this example: 
https://jsfiddle.net/aks9800/tkuao8f5/

relevant documentation: https://github.com/xaksis/vue-good-table#custom-row-template

closing.

**Comment by andrewsheffield** [comment]
Thank you for the quick response!

This solution doesn't help my use case.  I wrapped your component in my own in order to be able to style and code once on the apps data table design and formatting.  However, I have 1 view that needs a very specific style component in the column for each row.

I implemented your solution as a work around for the moment but takes away the abstraction from the component.

PS. Thank you for building this. This is awesome and one of the better, if not the best, Vue datatables available.

**Comment by xaksis** [comment]
hey @andrewsheffield, thank you for the compliment and I am glad vue-good-table is useful to you. I am actually still unclear as to what your use-case is. Is it possible for you to create a jsfiddle to demonstrate what you're trying to do?

**Comment by andrewsheffield** [comment]
I couldn't reproduce my use case in jsfiddle.

So I made an example in this repo: https://github.com/andrewsheffield/datatableexample

In short, I am wrapping your component to be able to style, add custom logic or provide additional formatting in one place that will apply to the whole app.

I would like to be able to pass components into a column of each row from my wrapper.  This means that adding the use of custom components would have to be abstracted from your template formatting method and would have to be passed as props somehow.
