### ISSUE TITLE
Search don't work when you have Grouped Rows

### ISSUE THREAD

**Issue by christoxl** [xaksis/vue-good-table#244]
Bug

vue-goog-table 2.2.0

Search should work similar to when you don't have groups

Check your own jsfiddle example, just search for 'guppy', the last element of the last group

https://jsfiddle.net/aks9800/wtwwkcgm/

**Comment by xaksis** [comment]
ooh... this looks all kinds of wrong... will have to look into it. thank you for pointing it out.

**Comment by xaksis** [comment]
@christoxl this is now fixed with v2.3.0 the jsfiddle is working as well. 

closing.

**Comment by christoxl** [comment]
I've just tested it on my own project, It's working now

Thanks for the quick response!
