### ISSUE TITLE
fromDate - toDate filter

### ISSUE THREAD

**Issue by StefanOosten** [xaksis/vue-good-table#246]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Expected Behavior
Two filter rows (or datepickers) in a single column to allow users to enter two date's (from and to), the table will then search between those two date's.

**Comment by xaksis** [comment]
@StefanOosten you can use external libraries to modify the input widget to make this happen. Here's an example: 
https://jsfiddle.net/aks9800/ekawt34s/

closing.
closing.
