### ISSUE TITLE
Table-row-after and Table-column-after missing in 2.x?

### ISSUE THREAD

**Issue by shahzadcacf** [xaksis/vue-good-table#248]
### Issue Type (delete the irrelevant ones) 

- [x] Question
I have used Table-row-after in the 1.x and now i have upgraded to 2.x and its now working. Cant find the documentation either
### Specs
What version are you using?
vue-good-table 1.x
What browser?
Chrome

**Comment by xaksis** [comment]
hey, @shahzadcacf custom rows have been simplified a lot in 2.0. You no longer need to specify each td for custom template, just the ones that need to be custom, relevant documentation: 
https://github.com/xaksis/vue-good-table/wiki/Guide-to-upgrade-from-1.x-to-v2.0#custom-tdrow-now-works-differently

To see a working example of how you'd create before and after columns, you can look at this jsfiddle: 
https://jsfiddle.net/aks9800/hsf0sqf8/

closing.
