### ISSUE TITLE
Add row parameter into sortFn

### ISSUE THREAD

**Issue by lamka02sk** [xaksis/vue-good-table#249]
### Issue Type
- [x] Enhancement Request

### Specs
2.3

Would be nice to have row parameter available inside sortFn or at least originalIndex of the row.
```javascript
sortFn(x, y, col, row) {
    return (x < y ? -1 : (x > y ? 1 : 0));
}
```

**Comment by xaksis** [comment]
@lamka02sk what do you mean by row? x and y here come from two different rows.

**Comment by lamka02sk** [comment]
@xaksis I meant index of the `x` row. It could be very useful in some situations, like mine where I have built wrapper over the table. Without index, I am honestly totally lost right now. More specifically, this would be enough and very helpful:
```javascript
// Where xIndex = row.originalIndex
sortFn(x, y, col, xIndex) {
    return (x < y ? -1 : (x > y ? 1 : 0));
}
```

**Comment by xaksis** [comment]
Thank you for your PR. This is now part of v2.4.1

closing.
