### ISSUE TITLE
Sorting doesn't work when global search is used

### ISSUE THREAD

**Issue by webit-moses** [xaksis/vue-good-table#25]
When global search is used and the search term is not empty, sorting by clicking on the table header doesn't seem to work.

**Comment by webit-moses** [comment]
I think this is because in the function processedRows, the global search filtering is done after the sorting. If the filter is done before the sort, then it works

**Comment by xaksis** [comment]
This is now fixed - v1.7.1. Adding enter trigger introduced this bug. Thank you for pointing it out.
