### ISSUE TITLE
`html: true` & `formatFn`

### ISSUE THREAD

**Issue by jonathan-wondereur** [xaksis/vue-good-table#255]
### Issue Type

- [x] Bug
- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?
`2.3.0`

What browser?
`Chrome`

### Expected Behavior
To be able to set `html: true` and specify html in the `formatFn` function.

### Actual Behavior
Data printed directly (not using the `formatFn` function).

### Steps to Reproduce the Problem
1. Try to use `formatFn` for a row with html using `html: true`

### jsfiddle
[example](https://jsfiddle.net/jonathan_wondereur/pLoaoaha/3/)

### Fix
- Update this [line](https://github.com/xaksis/vue-good-table/blob/cff2c59df830825a19709156fec7fc7e99c84234/src/components/Table.vue#L129) to use `collectFormatted` instead of `collect` as [above](https://github.com/xaksis/vue-good-table/blob/cff2c59df830825a19709156fec7fc7e99c84234/src/components/Table.vue#L127)

**Comment by xaksis** [comment]
Hey @jonathan-wondereur, what you're trying to do, should be accomplished using custom cells. Refer to this example: https://jsfiddle.net/aks9800/wtwzg6Lz/

`html: true` is to be used if your row data already contains html. 
`formatFn` is to format the data in your row, not to render html.

closing. Let me know if this doesn't solve your issue and I'll re-open the ticket.

**Comment by jonathan-wondereur** [comment]
@xaksis this works beautifully, thanks for the fast reply with the great example!

**Comment by benrolfe** [comment]
@xaksis, although this works as you've stated - I'd love to be able to format the text with HTML. It keeps all the column settings together.

**Comment by xaksis** [comment]
@benrolfe could you tell me more about what column settings are being lost by using the method above? or an example of what you want the formatted value to look like?

**Comment by benrolfe** [comment]
I'd like to be able to use this JS, but it doesn't work. Your proposed solution requires me to move the <strong> away from the code block into the HTML.

```
{
    label: 'Name',
    field: 'Name',
    html: true,
    formatFn: function(value) {
        return `<strong>${value}</strong>`
    },
},
```
