### ISSUE TITLE
Styles

### ISSUE THREAD

**Issue by sergeevpasha** [xaksis/vue-good-table#257]
### Issue Type (delete the irrelevant ones) 

- [x] Question

Just wondering is there any native way to change style - vgt-wrap? Without touching Table.vue ofcourse

**Comment by xaksis** [comment]
hey @sergeevpasha can you tell me what exactly is your use-case for styling the table wrap? you can provide/override any style within the table by supplying it via [style-class](https://github.com/xaksis/vue-good-table#styletheme). Alternatively, you can also leave off the styles provided with the table and use your own styles for everything. Also, the styles within the component are not scoped, So you can override them with your own styles as well. 

closing. Let me know if this doesn't solve your problem and I'll re-open.

**Comment by sergeevpasha** [comment]
i have 3 tables in one project and all are different. I can't use style scoped cause I actually prefer using scss in a different file. So atm i have to make a div and put table inside this div to be able to write styles different for all. Because i always need to change not only table data, but also search, pagination etc. So just asking, if there was an easier way

**Comment by xaksis** [comment]
Let me see if I understand this right. You have a few tables and in order to style them all differently you're doing the following: 
```html
<div class="my-table-a">
  <vue-good-table></vue-good-table>
</div>
<div class="my-table-b">
  <vue-good-table></vue-good-table>
</div>
<div class="my-table-c">
  <vue-good-table></vue-good-table>
</div>
```
and in your scss files then you're doing something like: 
```scss
.my-table-a{
  & .vgt-wrap{
    // my custom style for a
  }
}
.my-table-b{
  & .vgt-wrap{
    // my custom style for b
  }
}
.my-table-c{
  & .vgt-wrap{
    // my custom style for c
  }
}
```
so, is the issue just that you have an extra div tag to wrap your table? because even if you were able to add additional classes to vgt-wrap itself, you'd still have to do the styling the same way. Don't know if it would reduce the effort required significantly in any way?

**Comment by sergeevpasha** [comment]
maybe, atm I did first ask i didnt do that =)

**Comment by xaksis** [comment]
heh! okay... try it out and let me know if that works. If not, we'll think of something. 👍
