### ISSUE TITLE
<vue-good-table> - Did you register the component correctly?

### ISSUE THREAD

**Issue by niceque** [xaksis/vue-good-table#259]
How to use it without npm?

`<script src=".../vue-good-table.min.js"></script>`

...

`Vue.use(vueGoodTable);`

...

`<vue-good-table :columns="somecolumns" :rows="somerows"></vue-good-table>`

Thnx

**Comment by lefterisnik** [comment]
Hi @niceque, have you found a way how to do it?

**Comment by nburkley** [comment]
You can reference it by `window['vue-good-table'].VueGoodTable`

For example:
```JavaScript
new Vue({
  el: '#my-vue-app',
  components: {
    VueGoodTable: window['vue-good-table'].VueGoodTable
  },
  ....
```
