### ISSUE TITLE
Sorting on number sorts like text

### ISSUE THREAD

**Issue by focussing** [xaksis/vue-good-table#26]
Column that has type='number' sorts like 

103
114
12
121
etc...

**Comment by T-Bod** [comment]
I'm seeing this as well.

**Comment by xaksis** [comment]
out of curiosity, @focussing @T-Bod is your initial data (in rows) of type string? or number? I am unable to replicate this if the type is number.

**Comment by xaksis** [comment]
however, I will make the change to treat the column values as number if the type is number. Thank you for pointing this out.

**Comment by xaksis** [comment]
fixed in v1.9.0

**Comment by focussing** [comment]
thanks 👍

**Comment by T-Bod** [comment]
Sorry for the delayed response, yes, my data are numbers formatted as text.
