### ISSUE TITLE
Table headers hide borders when sorted

### ISSUE THREAD

**Issue by NathanStrutz** [xaksis/vue-good-table#260]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
vue-good-table latest version, running on Firefox.

### Expected Behavior
Sorting by header should leave display alone aside from adding up and down arrows.

### Actual Behavior
Sorting by header hides the border around my <th> table header elements.

## Fix:
Apply `background-clip: padding-box;` to the `th.sorting-desc, th.sorting-asc` items. I had to make mine `!important` in order to fix styles imposed by vgt.

**Comment by xaksis** [comment]
@NathanStrutz can you help me reproduce this? I'm testing this on firefox with multiple columns with long headers and still doesn't cause the border around header elements to disappear?

**Comment by xaksis** [comment]
I've added the requested style for the classes in v2.4.4... although I wasn't able to reproduce it, the new styles don't seem to be affecting existing functionality/visuals so it's all good.

closing.
