### ISSUE TITLE
Allow search in nested rows object

### ISSUE THREAD

**Issue by paulocr** [xaksis/vue-good-table#261]
I will try to get a PR in but wanted to get this out there and hopefully get your thoughts.

I have an object within my rows so for example I can access `props.row.system_id` and `props.row.customer.name` from the table however the global search function is unable to find the values in the nested object.

I assume there needs to be some kind of iteration if props.row has children but I'd like to get your input on feasibility before I try to mess around with the code, my javascript skills are not that good.

Thanks

**Comment by xaksis** [comment]
hey @paulocr! the easiest way you can do this is, have a hidden column for that data:  
```javascript
{
  label: 'hidden column'
  hidden: true,
  field: 'customer.name'
}
```
then it'll be part of search even though it is hidden. 

closing. let me know if you have problem with this approach and I'll re-open this.
