### ISSUE TITLE
Trigger: 'enter' does not disable search on 'key-up'

### ISSUE THREAD

**Issue by Niallfitzy1** [xaksis/vue-good-table#262]
### Issue Type

- [x] Bug

### Specs
What version are you using?
vue-good-table@2.4.3 
vue@2.5.16
What browser?
Firefox 5.0.2, Edge 41.16299.402.0, Chrome 67.0.3396.18
### Expected Behavior
With `:search-options="{ enabled: true, trigger: 'enter'}"` enabled search should only occur when 'enter' key is pressed.

### Actual Behavior
The table searches on 'key-up'.

### Steps to Reproduce the Problem
1. Create a VGT instance with `:search-options="{ enabled: true, trigger: 'enter'}"` 
2. Start typing a search query
3. Table will be searched before pressing enter key.

### jsfiddle
https://jsfiddle.net/Niallfitzy1/hvzdo39r/

**Comment by xaksis** [comment]
thank you for bringing this up. It is now fixed in v2.4.4. your jsfiddle should now be working.

closing.
