### ISSUE TITLE
combination of custom rows and html row data

### ISSUE THREAD

**Issue by ankitwashere** [xaksis/vue-good-table#263]
### Issue Type 

- [x] Question

### Specs
v2.4.3

Firefox, chrome

### Expected Behavior
HTML output when using {{prop.formattedRow[prop.column.field]}} on custom row template. 

### Actual Behavior
Instead it just displays the whole html as plain text. the column definition defines HTML as true. if i do not use custom definition this works okay but when using the custom row template for another field this just fails to render as HTML.

### Steps to Reproduce the Problem
See jsFiddle 

### jsfiddle
https://jsfiddle.net/nL0ozqpo/

Can you please tell me how to fix this. i want a combination of custom rows and html row data.

**Comment by xaksis** [comment]
hey @ankitwashere, just use v-html: 
```markup
<vue-good-table
    :columns="columns"
    :rows="rows"
    :pagination-options="{ enabled: true, perPage: 4}"
    :search-options="{ enabled: true}"> 
     <template slot="table-row" slot-scope="props">
    <span v-if="props.column.field == 'age'">
      age: {{props.row.age}}
    </span>
    <span  v-else-if="props.column.field == 'name'" v-html="props.formattedRow[props.column.field]">
    </span>
    <span v-else>
      {{props.formattedRow[props.column.field]}}
    </span>
  </template>
  </vue-good-table>
```

closing.

**Comment by ankitwashere** [comment]
ahh thanks did not know we could do that
tweaked it a little bit to do exactly what i want it to do

    <vue-good-table
        :columns="columns"
        :rows="rows"
        :pagination-options="{ enabled: true, perPage: 4}"
        :search-options="{ enabled: true}"> 
        <template slot="table-row" slot-scope="props">
        <span v-if="props.column.field == 'age'">
         age: {{props.row.age}}
       </span>
       <span  v-else-if="props.column.html" v-html="props.formattedRow[props.column.field]">
      </span>
      <span v-else>
       {{props.formattedRow[props.column.field]}}
      </span>
     </template>
      </vue-good-table>
