### ISSUE TITLE
deleting rows

### ISSUE THREAD

**Issue by sergeevpasha** [xaksis/vue-good-table#264]
hi again, found one more strange thing. When i delete rows via ajax everything works great and rows disappears... But when i try to delete all, or the last ones - they keep showing until a page restart.

**Comment by xaksis** [comment]
hey @sergeevpasha tough to debug without seeing what you're doing. the issue template (and the answer provided there) would have helped me debug this further... but there isn't much to go by in your description. How are you using the table? are the rows actually deleted? Have you verified that the rows object is empty?

**Comment by xaksis** [comment]
closing. This is the same issue as #267 will be fixed shortly.
