### ISSUE TITLE
Event for toggle checkbox

### ISSUE THREAD

**Issue by jprivillaso** [xaksis/vue-good-table#265]
### Issue Type (delete the irrelevant ones) 
- [x] Enhancement Request

### Specs
2.4.4

What browser?
Chrome

It's not a bug, but a behavior that would be nice to have. I need to have an event to know when the user clicked on the checkbox that is created when I choose to have select-options.
Currently, I can only have an event @on-select-all but I need to have an event that will be triggered when I click on any of the checkboxes.

My scenario is the following: 
I determine whether a register is enabled or not with the checkboxes. So, the checkbox will be true for a register that is `enabled` and false otherwise.

Another thing that I don't know how to do is how to set a specific list of checkboxes to true programatically.

Thanks.

**Comment by xaksis** [comment]
hey @jprivillaso for individual checkboxes you can use @on-row-click. if selection mode is enabled, `params.selected` will tell you whether the row that was clicked on was selected or unselected. refer to this example: https://jsfiddle.net/aks9800/keLjcssn/

for pre-selected rows, just set a property in your row item -  `vgtSelected: true` 

This should solve all your concerns. closing.
