### ISSUE TITLE
Setting rows to empty array.

### ISSUE THREAD

**Issue by JavaGT** [xaksis/vue-good-table#267]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

What browser?
Google Chrome

### Expected Behavior
What did you expect to happen?
For default "No data" label to appear.

### Actual Behavior
What actually happened?
Table content remained the same

this.rows = [] // No change in table. although accessing through dev tools seems so show data changed in vue component, just not the rendered output.

// NOTE
this.rows  can still be updated, just not to an empty array aka
this.rows = [{}] works

**Comment by xaksis** [comment]
@JavaGT Thank you for pointing this out. I was able to reproduce this on my end. will check in a fix shortly

**Comment by JavaGT** [comment]
Excellent thanks

**Comment by xaksis** [comment]
this should be fixed in v2.4.5. 

closing.

**Comment by sergeevpasha** [comment]
@xaksis thx from me too =) atm this is the best tables for vue =)
