### ISSUE TITLE
Class on vgt-global-search

### ISSUE THREAD

**Issue by yudhiezk** [xaksis/vue-good-table#269]
Bug
How come the class vgt-global-search alwasy show event though I have set the searchEnabled to 'false'? Is there a way to remove the element totally if I set it to false?

**Comment by xaksis** [comment]
@yudhiezk you seem to be using an older version of the doc. version 2 requires `search-options: {enabled: false}` please refer to the docs here: 
https://github.com/xaksis/vue-good-table#search-options

closing.

**Comment by yudhiezk** [comment]
I'm referring to the docs and its written "searchOption" not "search-options". And I tried "serach-option" and It doesn't work also. The class "vgt-global-search" is still taking space.

**Comment by Eijun** [comment]
+1
topbar for global search is still displayed even though set search-options to "{enable: false}".

![스크린샷 2019-06-21 오후 5 22 48](https://user-images.githubusercontent.com/17643160/59908982-a0a1ea00-9449-11e9-853b-d9def7fe075c.png)
