### ISSUE TITLE
Next label vertical position out of line with rest

### ISSUE THREAD

**Issue by focussing** [xaksis/vue-good-table#27]
From within Google Developer tools I removed

.label:not(:last-child) {
    /* margin-bottom: 0.5em; */
}

**Comment by xaksis** [comment]
thanks for pointing it out... will push the change with next release.

**Comment by xaksis** [comment]
hey @focussing, upon doing more research, that class is not coming from vue-good-table. Are you using bulma by any chance? because that's one place where that style rule could be coming from. 

I will change the class name so it doesn't clash with external class names.

**Comment by xaksis** [comment]
fixed v1.9.0

**Comment by focussing** [comment]
👍  thank you

**Comment by focussing** [comment]
yep I am using bulma, but other CSS libraries as well, preventing class names from clashing is the right way, or redefine the class name with other contents
