### ISSUE TITLE
External query doesn't work

### ISSUE THREAD

**Issue by tonimc** [xaksis/vue-good-table#270]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?

2.4.5

What browser?

Chrome

### Expected Behavior
What did you expect to happen?

Good Table should allow using a data as a source of search/

### Actual Behavior
What actually happened?

It doesn't rendered the table and throws an error in console.
![image](https://user-images.githubusercontent.com/750002/39717816-ab1caeaa-5234-11e8-9a52-959c2f751c1b.png)

### Steps to Reproduce the Problem
Please detail your steps here

1. Add `externalQuery: searchTerm` on `search-options`
2. Add `searchTerm` as data property.
3. Refresh and table is not rendered

### jsfiddle
https://jsfiddle.net/tonimc/pnrd6w73/1/

**Comment by xaksis** [comment]
v2.4.6 fixes this. your jsfiddle is now working.

**Comment by xaksis** [comment]
ok now it should be working fine. :) v2.4.7
