### ISSUE TITLE
footer style

### ISSUE THREAD

**Issue by vivekt001** [xaksis/vue-good-table#271]
- [x] Question
        
I am trying to adjust the padding of the footer but i am  unable to do it. Can anyone help me?

What browser?
Chrome
### jsfiddle
(https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
@vivekt001 what have you tried so far?

**Comment by xaksis** [comment]
I just had to modify the vgt-wrap__footer to change the padding: 
```css
.vgt-wrap__footer{
   padding: 50px;
 }
```

closing. Let me know if this doesn't work for you and I'll re-open.
