### ISSUE TITLE
Backspace triggering search when it should only be triggered on 'enter'

### ISSUE THREAD

**Issue by yudhiezk** [xaksis/vue-good-table#272]
Question

Is it possible to create custom function when I use @on-sort-change and prevent the default function?

Oh and one more thing. 
On search options, I use enter as trigger, but backspace also running the search function. How to prevent backspace from calling the search function, and only trigger by enter?

**Comment by xaksis** [comment]
hey @yudhiezk, you can customize sort for any column by supplying `sortFn` for that column, see here: https://github.com/xaksis/vue-good-table#sortfn-function

the backspace thing seems to be a bug. I'll look into it.

**Comment by xaksis** [comment]
hey @yudhiezk the backspace trigger should now be fixed in v2.4.8. 

closing.
