### ISSUE TITLE
Adding a way to manipulate selected filters from outside

### ISSUE THREAD

**Issue by stepanorda** [xaksis/vue-good-table#275]
### Issue Type (delete the irrelevant ones) 
- [x] Enhancement Request

### Specs
It would be cool to have a way to manipulate selected filters outside of component. For example adding a prop 'columnFlters' and event @on-filter-change to keep track of changes made inside of component.

Right now I solved this for me bu just accessing VgtFilterRow directly but that's not a reliable solution.

**Comment by xaksis** [comment]
hey @stepanorda! 
doesn't on-column-filter do what you're looking for?
https://github.com/xaksis/vue-good-table#on-column-filter

everytime filter changes, it emits an object indicating the current state of all filters.

**Comment by xaksis** [comment]
Ah... are you looking for a way to create filter inputs outside the table and use that to filter the table?

**Comment by stepanorda** [comment]
Yes I want to control them from outside of the component. I have charts and want to sync selection of the data on charts and in filters. I already did that, but in vary dirty hack way...
```
            select(event) {
                this.$refs.appointmentsTable.$children[1].updateFiltersImmediately({field: 'group'}, event);
            },
```

**Comment by xaksis** [comment]
@matdar @stepanorda this functionality has actually been added to the plugin, I forgot to update here. You can use `filterOptions.filterValue` of a column to populate the filter and have the table respond accordingly. 
refer to:
https://xaksis.github.io/vue-good-table/guide/configuration/column-filter-options.html#filtervalue
here's a working example: 
https://jsfiddle.net/aks9800/1bkzcd3n

closing.
