### ISSUE TITLE
Accessing different row object from non-header row?

### ISSUE THREAD

**Issue by T-Bod** [xaksis/vue-good-table#276]
- [x] Question

Is there a standard way for a non-header row to access other rows (in this case, all rows above it in the table post-sort)?  I'm trying to create  a running balance field which will ideally dynamically iterate over all prior rows and return the sum of an amount field but haven't been able to figure out how to have the field respect the sort order in its summing.

**Comment by xaksis** [comment]
hey @T-Bod i'd sugest you use the @on-row-click to get the row that was clicked on

To get all the rows in the current page, put a `ref` on the table and then access `paginated` which contains all rows in the current page in the correct order. you can then figure out what rows appear before the clicked row and do what you want with them. 

this is too specific of a usecase for the library so a generic implementation for this doesn't make sense to me. 

closing.
