### ISSUE TITLE
Fields containing dot('.') will get value lost

### ISSUE THREAD

**Issue by MoYummy** [xaksis/vue-good-table#277]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?

2.4.8

What browser?

Chrome

### Expected Behavior
What did you expect to happen?

I intend to display data `[{playerlimit:{count:0}}]` by flatting it with '.' as separator.
I use a workaround (4 underscores temp separator) to achieve this.
~~~
c: parent + '____' + current
~~~
~~~
            const col = {
              label: c.replace(/_{4}/g, '.'),
              field: c,
              thClass: 'table-header',
              tdClass: 'table-cell',
            }
~~~
![image](https://user-images.githubusercontent.com/8344384/39917294-a8dffc06-553f-11e8-842b-cbf12ade31d7.png)

### Actual Behavior
What actually happened?

Fields containing dot('.') will get value lost
![image](https://user-images.githubusercontent.com/8344384/39917423-065a2a00-5540-11e8-8cd6-ab560468a3c3.png)

### Steps to Reproduce the Problem
Please detail your steps here

See above

**Comment by xaksis** [comment]
@MoYummy for nested fields you need to make sure your `field` is "playlimit.count". you should not be replacing it with `___` and then be using it for `field`. 

take a look at this example for reference: https://jsfiddle.net/aks9800/8otsu2vo/

closing.

**Comment by MoYummy** [comment]
I tried it but found that there would be performance issue.
For same array (length 20) of objects(depth 4), actions like switching pages or searching key words will take `10s` through nested field path while it takes `200ms` for pre-flattened.

**Comment by MoYummy** [comment]
It looks like the recommended way will has worse performance than flattened one.
![image](https://user-images.githubusercontent.com/8344384/39985824-6153516c-5792-11e8-8553-a4c83f4b5398.png)

Please kindly check https://moyummy.github.io/vue-static/src/#/vue-good-table-demo

Repro:
1. Click 'LOAD'
2. Search something like '6' in search box / 2. Click columns to sort
3. Check console log

In comparison, switch 'isFlat' and do the same thing.

BTW, I found another one but I am not sure if it is a bug. If so, I will open another issue.
Repro:
1. Click 'LOAD'
2. Click columns to sort
3. Switch 'isFlat'
4. Check console log
![image](https://user-images.githubusercontent.com/8344384/39986327-eeae8850-5793-11e8-8b9b-285126f8bbe7.png)
