### ISSUE TITLE
More visual customization, classes, custom pager and filter components

### ISSUE THREAD

**Issue by stepanorda** [xaksis/vue-good-table#278]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request
- [x] Question

### Specs
Right now there is not much instruments to customize the look of table. For example many of the classes are hard coded. Is this by design and you don't want to overcomplicate it and it should used as is or maybe there is plans to change that? I want to use it on project with bootstrap3 I can set the main table classes but for example can't set inputs class to form-controll. Also pager isn't changeable and it has a different html markup then bootstrap. 

One way I see how this could be handled is by creating "classes" prop that would contain something like: {input:'vgt-input', select:'vgt-select'} and so on and the default values will be the same as they are now. And also make prop for sub components like pagination and filters so you can use your own components for them. 

Other way is to make a theme "bootstrap" and add conditions in code so you can just switch to it. 

If it's by design I will just fork and make my own version for internal use, if you want to make it more flexible I can spent a little more time and make a PR with the things I mentioned here.

**Comment by xaksis** [comment]
@stepanorda feel free to create a sass theme for your particular use case and submit as a PR. you can follow the "nocturnal" sass file for reference. 
https://github.com/xaksis/vue-good-table/tree/master/src/styles/nocturnal

Creating props for customizing style for every single element is a bit overkill, specially when you can override any of those styles by providing your own style rules for the said classes. The styles of elements/components within the table are not scoped so you can override them as you wish. 

For even greater flexibility in customization, leave off the default stylings completely that come with vgt and provide your own styles for html elements like you would for your own components. 

closing.

**Comment by stepanorda** [comment]
well if you already have all the classes like in bootstrap case, creating a sass theme with the same functionality is not the most handy and logical solution :) But ok, I understand your position I guess you don't want to overcomplicate this.

**Comment by xaksis** [comment]
not sure what you mean by sass theme with the same functionality? sass themes are simply variants of existing variables and classes to create a new theme. That's exactly what you'd do if you wanted to create a new theme for bootstrap right?
