### ISSUE TITLE
Select on checkbox only

### ISSUE THREAD

**Issue by sergeevpasha** [xaksis/vue-good-table#279]
So i have selectable rows that are links... Is there a way to allow user select rows only by pressing a checkbox? Cause I use entire row as a link

**Comment by sergeevpasha** [comment]
so is it possible to do smth with that?

**Comment by xaksis** [comment]
@sergeevpasha reasonable ask! will work on it shortly

**Comment by xaksis** [comment]
v2.6.0 now allows you to specify `selectOptions.selectOnCheckboxOnly: true`
