### ISSUE TITLE
Functionality request: Colomn headers template?

### ISSUE THREAD

**Issue by focussing** [xaksis/vue-good-table#28]
Like row templates, add possibility of defining column headers in html like adding font awesome icons

**Comment by xaksis** [comment]
This is actually tricky since unlike rows, columns have the added ability to sort via click. If like row, I allow templates for columns, the component itself will no longer be able to register to click events and perform sorts. 

I can however, look into allowing for html instead of strings as label.

**Comment by focussing** [comment]
Using the thClass property html strings can be used as label (I did that with a font-awesome icon).
like `<i class="fa fa-trash-o"></i>`

Preventing a column from being sorted for example by `sortable:false` would open the gate for other click event handlers. Of course when other columns are being sorted the non-sortable class would be sorted as well because of the rows structure of the table.

**Comment by mgattelli** [comment]
@xaksis 
It would be great to allow insert html instead of string as label in order (for example) to translate the headers.

**Comment by cristijora** [comment]
@xaksis Maybe put the slot inside v-for?
```html
<th v-for="column in columns" @click="doWhatever">
     		 <slot name="columns" :column="column">
     				 {{column}}
     	 	</slot>
 </th>
```
Like this you can keep the icons and the click events like they are but rather customize the text/html for the header.
The usage would be 
```html
<template slot="columns" scope="props">
       <span v-if="props.column =='Name'">
          <i class="fa fa-address-book"></i> {{props.column}}
       </span>
       <span v-else>
          {{props.column}}
       </span>
   </template>
```

Sample fiddle https://jsfiddle.net/bt5dhqtf/1212/

**Comment by xaksis** [comment]
good idea @cristijora I'll look into this.

**Comment by xaksis** [comment]
This is now available in v1.14.x Here's an example: 
https://xaksis.github.io/vue-good-demos/#/dynamic-table
closing this.

**Comment by gergo2007** [comment]
Hello, can you please add the example for this somewhere? Page is throwing a 404

**Comment by xaksis** [comment]
hey @gergo2007 This is an old issue that references deprecated docs. Current documentation covers all of this.
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-headers

**Comment by gergo2007** [comment]
@xaksis thanks for the reply, im still using the old (1.21) version. Does the new doc cover the old version as well?

Thanks!
