### ISSUE TITLE
Expose DOM Click Event Object In Row/Cell Click Handler

### ISSUE THREAD

**Issue by mlholt03** [xaksis/vue-good-table#282]
### Issue Type (delete the irrelevant ones) 
- [x] Enhancement Request

### Specs
It would be nice if the DOM click event object was expose-able to the click handler.  My use case is that I would like the ability to know if the user was holding Alt, Ctrl, etc., when they clicked on a row.

**Comment by xaksis** [comment]
`on-row-click` and `on-cell-click` both now contain the click event in their params - v2.6.0
