### ISSUE TITLE
Feature Request: Row Headers

### ISSUE THREAD

**Issue by RaghunathHyd** [xaksis/vue-good-table#284]
It will be great if in future versions, if you could also include row headers as well. Will be useful for display of information in a different manner. 

Thanks

**Comment by xaksis** [comment]
@RaghunathHyd sorry I'm not quite clear on the requirement here... can you explain a bit more about what you mean by
>include row headers as well

**Comment by RaghunathHyd** [comment]
Apologies for not being more clear. 

Right now we have headers for each column in the top row.

What I was requesting is to have a header for each row in the first column. Useful for small table to display information where using a normal table might be overkill.

Please see the pic.

![row headers](https://user-images.githubusercontent.com/17150206/40395631-ac4e2d1c-5e46-11e8-97a9-83f27270a3e6.png)

**Comment by xaksis** [comment]
@RaghunathHyd sorry for the delay. Unfortunately currently there's no way of doing this in VGT and this isn't on the roadmap for the near future either. Pivoting tables would take non-trivial effort which isn't a high priority for VGT right now. I will gladly review a PR though if you want to take a shot at it. 

closing.
