### ISSUE TITLE
Feature to toggle checkbox state programatically

### ISSUE THREAD

**Issue by JevPrentice** [xaksis/vue-good-table#287]
### Issue Type (delete the irrelevant ones) 
- [x] Enhancement Request

### Specs
MacBook Pro (Retina, 15-inch, Mid 2015)

### What browser?
Chrome - Version 66.0.3359.181 (Official Build) (64-bit)

### New Desired Behavior
Please introduce a trigger to allow a developer to update the state of the checkboxes on the UI, for example having the table load with various values with all the items already selected, or updating the state of a checked item from elsewhere in the webapp

From a users point of view it should be the equivalent to the table loading and the user clicking the select all button

**Comment by xaksis** [comment]
Hey @JevPrentice just add 'vgtSelected: true' to row objects that you want to appear selected. 

closing.

**Comment by JevPrentice** [comment]
Thanks @xaksis this is working well!

**Comment by jayadevkv** [comment]
vgtSelected: true not working for rows. I can see that it is a property of selected rows object. Could you pls show an example

**Comment by xaksis** [comment]
Hey @jayadevkv! You simply have to modify your components row object and not the table's

`this.rows[0].vgtSelected = true`

**Comment by jayadevkv** [comment]
Still it is not working. I am doing everything in created hook. Only after getting response to data that I am setting 
   `this.rows[0].vgtSelected = true` 
I tried to move it to mounted , but giving error
Thank you for helping me

**Comment by JevPrentice** [comment]
Hi @jayadevkv, if it helps - consider my implementation 

methods: {
	...
	onSelectAll: function (params) {
        let vm = this
        vm.modalDashboardAppIds = []
        params.selectedRows.forEach(function (key) {
          if (params.selected) {
            key.vgtSelected = true
          }
        })
      }
    ...
}

**Comment by xaksis** [comment]
Hey @jayadevkv ... you have to think about vue's reactivity caveat. You can't just assign the value to a nested json. you'd have to use Vue's set
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
try: 
`this.$set(this.rows[0], 'vgtSelected', true);`

**Comment by jayadevkv** [comment]
Now i have modified my sql to return vgtSelected property by default. I am wondering why it still not working

**Comment by jayadevkv** [comment]
Found the issue it is working only if we enable global search 

`:search-options="{ enabled: true }"`

I think now it is a bug. I prefer individual search and filters
