### ISSUE TITLE
Pagination for ALL is not working properly

### ISSUE THREAD

**Issue by hemanthReddy06** [xaksis/vue-good-table#288]
- [x] Bug  -  If we change the no of records to ALL in rows per page, it should disable the next button.

What browser?
In all browsers

### Expected Behavior
If we change the no of records to ALL in rows per page, it should disable the next button.
### Actual Behavior
After changing no of rows to ALL in rows per page next button is enabled.

### Steps to Reproduce the Problem
Please detail your steps here

1. make the next button disable when we select ALL in rows per page.

### jsfiddle
https://jsfiddle.net/m70xgeL5/

**Comment by xaksis** [comment]
@hemanthReddy06 good catch! will release a fix shortly.

**Comment by xaksis** [comment]
fixed in v2.6.0

**Comment by hemanthReddy06** [comment]
Thanks
