### ISSUE TITLE
Invalid regular expression: /\/: \ at end of pattern

### ISSUE THREAD

**Issue by joannesalfa** [xaksis/vue-good-table#293]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.6.2.

### Expected Behavior
What did you expect to happen?

It should not display the error.

### Actual Behavior
What actually happened?

It broke the page after accidentally typed one letter  "&#92;"

### Steps to Reproduce the Problem
Please detail your steps here

1. Use the simple example with vue component file (Only when use Vue-Cli (Webpack) or Nuxt)
2. Find "Search Table Input"
3. Type  a letter "&#92;"

**Comment by joannesalfa** [comment]
Also it applies to "[" and "]"

**Comment by xaksis** [comment]
@joannesalfa this should now be fixed in v2.6.3 thanks to @OperKH
