### ISSUE TITLE
Searching

### ISSUE THREAD

**Issue by fabiokounang** [xaksis/vue-good-table#295]
Hey guys, im having a little trouble here, so i have 100 data, and the limit of my data is 10 per page. And when i enter keyword to search, it's just searching through that 10 data on the page, but what i want is to search for all the 100 data. anyone can help ? thank you ! ^ ^

**Comment by xaksis** [comment]
hey @fabiokounang can you show me how you're using it?

**Comment by fabiokounang** [comment]
hey, sorry for the late reply, i already figured it out^ ^, i wasnt get to database when i search it, but now i do, so it is solved ^ ^.oh by the way,  the new problem is, the vue warning about props, how can i solve it ? the warning is "avoid mutating direct props" blablabla

**Comment by xaksis** [comment]
Sounds like you're mutating props in your component which vue frowns upon. If you look it up online, you'll see some alternative patterns that are more in line with Vue's best practices. 

Since this isn't related to vue-good-table, I will close this.
