### ISSUE TITLE
Please Add " totalRows " prop to Readme!

### ISSUE THREAD

**Issue by drna3r** [xaksis/vue-good-table#297]
Table.vue
```
  props: {
    mode: { default: 'local' }, // could be remote
    totalRows: { }, // required if mode = 'remote'
```

**Not knowing this has hurt me...!**

**Comment by xaksis** [comment]
@drna3r apologies!! This is still somewhat in testing so I haven't fully documented it. However, now I think it's mature enough (I just rolled out an implementation to prod for one of my projects) so I'll definitely make it more visible in the readme shortly. 

There's a wiki that details a sample remote workflow: 
https://github.com/xaksis/vue-good-table/wiki/Remote-Mode-Workflow

**Comment by xaksis** [comment]
new documentation is up which includes `totalRecords` as one of the table properties:
https://xaksis.github.io/vue-good-table/guide/configuration/#totalrecords

closing this.

**Comment by jiabingtian** [comment]
@xaksis the newest code doesn't 'totalRecords' property
