### ISSUE TITLE
Please Add loadingText

### ISSUE THREAD

**Issue by drna3r** [xaksis/vue-good-table#299]
Please Add loadingText (for changing loading text) like : 
    // text options
    nextText: 'Next',
    prevText: 'Prev',
    rowsPerPageText: 'Rows per page',
    ofText: 'of',
    allText: 'All',

( loading... ) in remote mode.
thank u..

**Comment by xaksis** [comment]
just use loadingContent slot within the table tag.
```html
<vue-good-table ...>
  <template slot="loadingContent">
    <!-- your content here -->
  </template>
</vue-good-table>
```

closing.

**Comment by drna3r** [comment]
Thank u

**Comment by drna3r** [comment]
@xaksis Thank you for introducing loadingContent slot!
But I couldn't find " **loadingContent slot** " in Readme or Wiki .. 
Is there another doc ?!

_thanks for supporting_ ...

**Comment by benrolfe** [comment]
Could this be added to the documentation please?
