### ISSUE TITLE
HTML fields are forced to the end of the table

### ISSUE THREAD

**Issue by jlugao** [xaksis/vue-good-table#3]
I am trying to use the first column as an image column, basically I am declaring the field as:
`'<img class= "img-thumbnail img-search" src="' +  config.imageServerURI + data.profilePic + '"/>'`
and the column configuration as:
`      {
          label: 'Profile Image',
          field: 'image',
          html: true,
          width: '100px',
        },`

The problem is the title is displaying in the right place (the first position) and the data itself is displaying on the last column. Am I doing something wrong? I managed to work around the problem by setting every column as html: true.

A suggestion, if I may, would be to create an image column that receives a css class.

**Comment by xaksis** [comment]
Thank you for pointing this out. There's a bug in the code. I'm going to check in a fix right now. 

To answer your question, v1.3.0 now supports dynamic tds so you can actually create the table cells yourself. Example: 
```html
<vue-good-table
  title="Dynamic Table"
  :columns="columns"
  :rows="rows"
  :lineNumbers="true"
  :defaultSortBy="{field: 'age', type: 'asec'}"
  :globalSearch="true"
  :paginate="true"
  styleClass="table condensed table-bordered table-striped">
  <template slot="table-row" scope="props">
    <td>{{ props.row.name }}</td>
    <td class="fancy-image"><img src='{{ props.row.image }}' /></td>
    <td>{{ props.row.percent }}</td>
  </template>
</vue-good-table>
```

**Comment by xaksis** [comment]
All done! version 1.3.1 now has your fix as well.
