### ISSUE TITLE
How to create a action bar inside the row?

### ISSUE THREAD

**Issue by fagworio** [xaksis/vue-good-table#301]
- [x] Question

Amazing tab.

How to create a action bar inside the row ?
Like Delete, Edit, Disable

Every row will have the actions.

Thanks.

**Comment by drna3r** [comment]
I created an simple action bar with "[Custom Row Template](https://github.com/xaksis/vue-good-table#custom-row-template)" : 

like this : 
```
<vue-good-table
  :columns="columns"
  :rows="rows">
  <template slot="table-row" slot-scope="props">
    <span v-if="props.column.field == 'Delete'">  /// Or Edit , Disable etc...

          // Your Button !
           <button type="button" class="btn btn-primary">
                 Delete
             </button>

    </span>
    <span v-else>
      {{props.formattedRow[props.column.field]}}
    </span>
  </template>
</vue-good-table>
```

**Comment by fagworio** [comment]
Lol, Thanks.

**Comment by drna3r** [comment]
👍

**Comment by xaksis** [comment]
thanks @drna3r . closing this.

**Comment by coccoinomane** [comment]
Let's say the button is a component itself which emits an event when clicked. How to intercept the event from the parent component?
Sorry for reopening the thread, but I am stuck 😅

**Comment by p0psicles** [comment]
Just put a `@click="methodToRun"` on the component.

**Comment by coccoinomane** [comment]
Thanks! It turns out that I had an unrelated bug which messed up things, now that I've fixed it your solution works fine 🤦🏻‍♂️
