### ISSUE TITLE
Create reset method for table (paginate to page 1 and clear column filters)

### ISSUE THREAD

**Issue by akselect** [xaksis/vue-good-table#302]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

Allow programmatically resetting of the table to remove all column filters + paginate back to 1. This is specially useful for remote mode.

**Comment by drna3r** [comment]
Thanks you for discuss this issue!
I Use [Remote Mode ](https://github.com/xaksis/vue-good-table#remote-mode) With [Axios ](https://github.com/axios/axios) and I have to repeat my code in [Mounted ](https://vuejs.org/v2/api/#mounted) When Get I Empty String [on column filter](https://github.com/xaksis/vue-good-table#on-column-filter) ....

But I'm not sure that this is the best solution...!

**Comment by xaksis** [comment]
@drna3r @akselect all done now you can use `reset` method of the table. 

<vue-good-table ref="my-table" ...>
</vue-good-table>

// in your handler
this.$refs['my-table'].reset();

closing.
