### ISSUE TITLE
Clear the selected rows

### ISSUE THREAD

**Issue by brokeyourbike** [xaksis/vue-good-table#303]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using? 

- [x] 2.6.6

### Expected Behavior
Is there any way to clear the selected rows programmatically?
User select rows, press button for action, and in the end it would be nice to clear selection.

**Comment by xaksis** [comment]
hey @brokeyourbike, just put a `ref` on the table and then call `unselectAllInternal()`

```vue
<vue-good-table ref="my-table" ...>
</vue-good-table>

// in your handler
this.$refs['my-table']. unselectAllInternal();
```

closing.
