### ISSUE TITLE
is vue table can handle data ~1 lakhs

### ISSUE THREAD

**Issue by rockyshukla** [xaksis/vue-good-table#305]
hello guys, your vue-good-table is so good and I want to know how I can handle data up to  ~1 lakhs or more is it possible and one more thing is  vue table work for server side like datatable

**Comment by xaksis** [comment]
@rockyshukla thanks for the kind words. 
To make vue-good-table work with a very high payload, you can follow the remote workflow (where server needs to take care of sorting/filtering/pagination etc) - https://github.com/xaksis/vue-good-table/wiki/Remote-Mode-Workflow 


closing.

**Comment by rockyshukla** [comment]
@xaksis  thanks for your response it tried your suggestion but the global search is not working in a mode remote
