### ISSUE TITLE
search option is not working

### ISSUE THREAD

**Issue by rockyshukla** [xaksis/vue-good-table#307]
hello folks thanks for such great table i have issue with search let me show my code first

                 <vue-good-table
                                   mode="remote"
                                  
                                  @on-page-change="onPageChange"
                                  @on-sort-change="onSortChange"
                                  @on-column-filter="onColumnFilter"
                                  @on-per-page-change="onPerPageChange"

                                  :totalRows="totalRecords"
                                  pagination-options="{
                                    enabled: true,
                                    searchFn: myFunc
                                  }"
                                  :searchOptions="{enabled: true}"
                                  :rows="rows"
                                  :columns="columns"    
                                 />
                       methods:{
                                     myFunc(row, col, cellValue, searchTerm){
                                        console.log(searchTerm)
                                      },
                         }
this method not working at all i.e if i remove mode="remote" still no trigger and another issue with "@on-search" 

                         <vue-good-table
                                   mode="remote"
                                  
                                  @on-page-change="onPageChange"
                                  @on-sort-change="onSortChange"
                                  @on-column-filter="onColumnFilter"
                                  @on-per-page-change="onPerPageChange"

                                  :totalRows="totalRecords"
                                  pagination-options="{
                                    enabled: true,
                                    searchFn: myFunc
                                  }"
                                  :searchOptions="{enabled: true}"
                                  :rows="rows"
                                  :columns="columns" 
                                 @on-search="onSearch"   
                                 />
                       methods:{
                                     onSearch(params) {
                                 console.log(params) 
                             }
                         }
this method is work if i remove mode="remote" in short both method not get trigger

**Comment by xaksis** [comment]
@rockyshukla this should now be fixed. @on-search should now emit an event in remote mode. 

closing.
