### ISSUE TITLE
Dropdown filter not working in Edge

### ISSUE THREAD

**Issue by StefanOosten** [xaksis/vue-good-table#308]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

What browser?
Edge

The dropdown filters don't seem to work in Edge. (normal filters do)

### jsfiddle
This fiddle works fine in Chrome, but try it in Edge.

https://jsfiddle.net/57a2a4ce/353/

**Comment by xaksis** [comment]
@StefanOosten thank you for pointing it out. I only have a mac so sometimes it's tough to identify these bugs. I'll see if I can find a way to debug this.

**Comment by StefanOosten** [comment]
Any updates on this? It would be nice if it was fixed since Edge is quite a major browser nowadays :)

**Comment by xaksis** [comment]
@StefanOosten sorry for the delay. Finally got my hands on a windows machine so was able to debug. Looks like v-on:input doesn't work on edge with <select>. This is now fixed in v2.13.1

closing.
