### ISSUE TITLE
how to show images/image thumbnails inside cells?

### ISSUE THREAD

**Issue by aloay** [xaksis/vue-good-table#309]
### Issue Type
- [x] Question

**Comment by xaksis** [comment]
hey @aloay, you can do it two ways: 
1.  preferred way - use custom row template: https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template
2. Use the html property of column: https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#html

closing.
