### ISSUE TITLE
Initial table rows order differs from database rows order

### ISSUE THREAD

**Issue by focussing** [xaksis/vue-good-table#31]
After the table is loaded the rows order is not exactly as read from my database...
That data is sorted by index. 
The data is shown like this:

- 104
- 2
- 4
- 7
- 12
- ... etc
- 94
- 95
- 103
- 3
- 105
- 108
- ... etc
- 129
- 220

There is no defaultSortBy, pagination=false and no sorting click was done.

**Comment by xaksis** [comment]
I will take a look at this. In the mean time you can do defaultSortBy="id" to get the right order. sort should work even though the id column is hidden in your case.

**Comment by xaksis** [comment]
fixed in v1.9.3
