### ISSUE TITLE
Unable to register component locally

### ISSUE THREAD

**Issue by robertjk** [xaksis/vue-good-table#312]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.8.0

What browser?
Firefox 61.0b5

### Expected Behavior
What did you expect to happen?

I'd expect to be able to import `VueGoodTable` component and register it locally using `components` prop on my component which uses `VueGoodTable` in it's template.  Especially tha the [docs](https://xaksis.github.io/vue-good-table/guide/#installation) actually list this as an option ("Import into your component").

### Actual Behavior
What actually happened?

When I do it (example code below), I'm given the following error

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <VueGoodTable>
       <SearchResultsDisplay> at src/components/SearchResultsDisplay.vue
         <SearchPage> at src/components/SearchPage.vue
           <App> at src/App.vue
             <Root> vue.esm.js:591
warn
vue.esm.js:591
mountComponent
vue.esm.js:2758
Vue.prototype.$mount
vue.esm.js:8540
Vue.prototype.$mount
vue.esm.js:10939
init
vue.esm.js:4137
createComponent
vue.esm.js:5608
createElm
vue.esm.js:5555
patch
vue.esm.js:6130
lifecycleMixin/Vue.prototype._update
vue.esm.js:2670
updateComponent
vue.esm.js:2788
get
vue.esm.js:3142
run
vue.esm.js:3219
flushSchedulerQueue
vue.esm.js:2981
nextTick/<
vue.esm.js:1837
flushCallbacks
vue.esm.js:1758
```

```
<script>
import VueGoodTable from 'vue-good-table';

export default {
  components: {
    VueGoodTable,
  },
  (...)
};
</script>

<template>
(...)
   <vue-good-table (...) />
(...)
</template>
```

If I register `VueGoodTable` globally using `Vue.use(VueGoodTable)` (code below), the table renders fine without the error.

```
<script>
import Vue from 'vue';
import VueGoodTable from 'vue-good-table';

Vue.use(VueGoodTable);

export default {
  (...)
};
</script>

<template>
  (...)
  <vue-good-table (...) />
  (...)
</template>
```

**Comment by xaksis** [comment]
same issue as #280 component export has a bug. Will be fixed shortly.

keeping #280 open for now.

**Comment by xaksis** [comment]
@robertjk component export should now be fixed with v2.8.1. thank you for reporting with detailed usage.
```js
import { VueGoodTable from }  from  'vue-good-table';

export default {
  components: {
    VueGoodTable,
  },
  (...)
};
```
Install instruction for your ref:
https://xaksis.github.io/vue-good-table/guide/#installation

**Comment by robertjk** [comment]
Thanks :).

**Comment by rafaelgov95** [comment]
@xaksis the same error happens when I use shims-vue.d.ts need help to use in TS
