### ISSUE TITLE
Do not use rem units for styling

### ISSUE THREAD

**Issue by robertjk** [xaksis/vue-good-table#313]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Specs
What version are you using?
2.8.0

What browser?
Firefox 61

### Expected Behavior
What did you expect to happen?

I expected to use your table component and have the styles applied correctly.

### Actual Behavior
What actually happened?

The table looks very bad. That is because you use `rem` units to set padding on elements and I'm having this in my base stylesheet:

```
html {
  // Setting to 1px to make rem calculcations easier. Now to set font-size
  // to 20px, you set it to 20rem instead of 1.42857142857rem.
  font-size: 1px;
}

body {
  font-size: 16rem;
}
```

### My recommendation

I think as your code is a library to be used by others, you should make the least assumptions as possible about the code of the people which will use it. When you use `rem`, you assume that the base font size on the root of the document is equal to `16px`. Some people prefer to set base `font-size` to `1px` or `10px` to ease the calculation of other `font-size`s and some might set it to even different values. All of these will break your styles and make your library unusable (like it does for me).

2 solutions you have is using `px` or `em` values. If you use `em` values, then the values would always be proportional to the text size. If you use `px` then they will have fixed values, which in fact is almost the same what's happening now with `rem`-s - no matter what `font-size` is set on the table element, the `padding`-s are staying the same.

**Comment by xaksis** [comment]
@robertjk good point. I'll take a look.

**Comment by robertjk** [comment]
The other thing you might think about is, enapsulating styles inside the component (and making them scoped). Then people using the component, wouldn't have to import the stylesheet separately - it would be imported along with the component. Unless you want the stylesheet to be optional, but still you can probably achieve both by having some component prop controlling if the styles would be declared or not.

**Comment by xaksis** [comment]
hey @robertjk the styles were part of the component to begin with but were moved out because community requested it. People have spoken and want the option to leave the styles out completely. Whether the styles are imported or not cannot be controlled via props if the styles are part of the component, I think you meant have it conditionally apply via props which is exactly how it was before - however if you're not using the in-built styles then having it bundle with your app is just increasing your app payload and devs were not very keen on that.

**Comment by robertjk** [comment]
Thanks for the explanation.

I didn't mean conditionally apply styles. I thought it was possible to somehow wire importing the stylesheet with the prop value, but I did some research and it seems impossible indeed. It's a bit surprising to me people want to use component without styles, but if they want it, I understand your position :).

**Comment by xaksis** [comment]
styles updated to use em units in v2.8.2

**Comment by rlightner** [comment]
@robertjk I use the component with a completely different style sheet to mimic Tabler, so I'm happy they aren't scoped.

**Comment by robertjk** [comment]
@rlightner I understand the need, but for me one big idea of components is about sealing all the things inside the component, so that they don't pollute the global scope. Is it possible to have a separate stylesheet for the component and don't pollute the global scope?

**Comment by rlightner** [comment]
@robertjk What exactly is being polluted? He has things 'namespaced' under vgt-. Sealing all the things means they become unchangeable, then we really would be locked in to a control that has no ability to be styled do to the extra tags Vue.js adds to every single rendered component. Outside of using rem (which is pretty common) are you actually experiencing a style creep?

**Comment by robertjk** [comment]
By polluting I mean creating some rules in global CSS scope. Maybe the author of this comonent prefixes all his CSS classes names, so that they target nothing more than his component, but not all of the authors do. Some of them create classes like `.input`, `.select` and `.container`. And some of them use selectors only with HTML elements without class at all, like `input[type="search"] { ... }` or `button { ... }`, which leak and re-style your whole page.

Thats why modules are present in all programming languages and were brought to JavaScript too. And that's why things like CSS Modules and scoped styles in Vue loader are emerging. Importing stylesheet separately in global scope is like a step backward to me.

Even when you have styles sealed inside a component (scoped), you can still override them using `>>>`/`/deep/` selectors. You can even create a wrapping component (with it's own scoped styles), when you want them to be applied multiple times.

**Comment by rlightner** [comment]
@robertjk  I get all that, but that's not what this author is doing. If you want the table to only be in one component, you can just import the css in that component. It's namespaced enough that it won't affect any of your normal styles. I know this issue is closed, but I'd say this request is a step backwards and would potentially affect other people using it who rely on the table following their root font size. I know they can go in and adjust their surrounding element, but for what? So long story short, @xaksis I'm not in favor of this change, but its your code. 

Thanks for working on this project.

**Comment by robertjk** [comment]
Oh I'm not requesting to change it. I see people need such feature, so I think it's better to stay like that. I'm more about saying we should re-think the idea we write our styles with Web Components emerging and find some modular way to do that.
