### ISSUE TITLE
Sortable headers should suggest to the user visually that they can be clicked

### ISSUE THREAD

**Issue by robertjk** [xaksis/vue-good-table#314]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Specs
What version are you using?
2.8.0

What browser?
Firefox 61

### Actual Behavior

The headers are sortable, but that's not in any way communicated visually to the user. There is no icon, no underline, not even cursor changes to pointer, when the user hovers the header with mouse. Only when the user clicks the header, he can discover that they are sortable. Some users may not do that and assume that the table doesn't offer sorting capabilities.

In my opinion that's not good user experience.

### Expected Behavior

The first thing that should be done in my opinion is setting cursor to pointer on header hover. The other thing I'd do is underline the text of the headers, which suggests interaction even without hovering. Alternatively to underline an icon can be put next to each header.

**Comment by xaksis** [comment]
@robertjk cursor to pointer is a great catch... i meant to do that but amongst all the other things it got put on the back burner. will add that in. 

For any other additional styling, you can use custom column headers: 
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-headers

**Comment by xaksis** [comment]
fixed in v2.8.2 

closing.
