### ISSUE TITLE
Format rows from API call

### ISSUE THREAD

**Issue by rangata** [xaksis/vue-good-table#316]
Dear Friends,

I am a new in JavaScript like languages. Maybe is not the right place to ask here, but I hope you can help me.

I want to show table with grouped rows by category.

Here is my data structure
`[{"id":1,"name":"ProductName","model":"the model","created_at":"2018-06-21 06:05:41","updated_at":"2018-06-21 06:05:41","product_type":"basic","category":"CARS"]`

How can I adopt it to fit in table?

Best regards!

**Comment by xaksis** [comment]
@rangata hey there! you can take a look at the following that guides you through making a grouped table.
https://xaksis.github.io/vue-good-table/guide/advanced/grouped-table.html

in your case the format of the rows would need to be something like: 
```
rows: [{
  mode: 'span', // span means this header will span all columns
  label: 'CARS, // this is for the header row, so use the value you have in `category`
  children: [
    { "id":1,"name":"ProductName","model":"the model","created_at":"2018-06-21 06:05:41","updated_at":"2018-06-21 06:05:41","product_type":"basic",},
    { /* row 2 */ },
  ]
}]
```
going to close this. if you run into issues, comment again and we'll see if we can help.
