### ISSUE TITLE
html rendering in Grouped Table

### ISSUE THREAD

**Issue by vigorem** [xaksis/vue-good-table#319]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.8.1

What browser?
Chrome

Whit `groupOption` enabled, I'm looking for a way to display directly html to the groupRows inserted. 

I tried the following : 

    rows: [
            {
              mode: 'span',
              label: '<div class="h2">Mammal</div>',
              children: [
                { name: 'Elephant', diet: 'herbivore', count: 5 },
                { name: 'Cat', diet: 'carnivore', count: 28 },
                { name: 'Dog', diet: 'omnivore', count: 12 },
                { name: 'Dolphin', diet: 'carnivore', count: 9 },
              ],
            },
          ]

with no success.

Many thanks for any suggestions
https://jsfiddle.net/Lzm0xyg6/

**Comment by xaksis** [comment]
@vigorem with v2.8.2 you can specify `html: true` and you'll get what you want. 
example: 
```js
rows: [
        {
          mode: 'span',
          label: '<div class="h2">Mammal</div>',
          html: true, // if this is true, label will be treated as html
          children: [
            { name: 'Elephant', diet: 'herbivore', count: 5 },
            { name: 'Cat', diet: 'carnivore', count: 28 },
            { name: 'Dog', diet: 'omnivore', count: 12 },
            { name: 'Dolphin', diet: 'carnivore', count: 9 },
          ],
        },
      ]
```

closing.
