### ISSUE TITLE
Define CSS class of Grouped Rows

### ISSUE THREAD

**Issue by vigorem** [xaksis/vue-good-table#320]
### Issue Type (delete the irrelevant ones) 
- [x] Enhancement Request

### Specs
What version are you using?
`2.8.2`
What browser?
`Chrome`

Using `groupOption`, it would be great to be able to define the CSS class of the groupRows inserted for higher display customization.

**Comment by xaksis** [comment]
@vigorem you can now use slots to customize header rows
https://xaksis.github.io/vue-good-table/guide/advanced/grouped-table.html#customizing-header-row

closing.
