### ISSUE TITLE
Maintaining header visibility on scroll?

### ISSUE THREAD

**Issue by T-Bod** [xaksis/vue-good-table#321]
- [x] Question

Is there a recommended way to "freeze panes" or maintain visibility of the headers when scrolling through a long table?  There are a bunch of possible JS/CSS solutions online, just wondering if there's a supported way I should be using.

**Comment by xaksis** [comment]
hey @T-Bod this is currently not supported in vue-good-table. If you submit a PR i'll be more than happy to review it.

**Comment by xaksis** [comment]
@T-Bod this is now implemented in v2.12.1. You can see the documentation here: 
https://xaksis.github.io/vue-good-table/guide/configuration/#fixed-header

closing.
