### ISSUE TITLE
Adding custom buttons in Grouped Rows Headers

### ISSUE THREAD

**Issue by vigorem** [xaksis/vue-good-table#324]
### Issue Type 
- [x] Question
- [x] Enhancement Request

### Specs
What version are you using?
2.8.1

What browser?
Chrome

Following the **excellent** enhancement provided in [#319 ](https://github.com/xaksis/vue-good-table/issues/319) which allows injecting `html`  in row headers, I was looking for a way to add buttons (like show / hide details).

I've tried the following : 

    rows: [{
        mode: 'span',
        html: true,
        label: '<div class="h2">Mammal <button @click="alert(Mamal)">some button</button></div>',
        children: [{
                name: 'Elephant',
                diet: 'herbivore',
                count: 5
            },
            {
                name: 'Cat',
                diet: 'carnivore',
                count: 28
            },
            {
                name: 'Dog',
                diet: 'omnivore',
                count: 12
            },
            {
                name: 'Dolphin',
                diet: 'carnivore',
                count: 9
            },
        ],
    }]

But obviously this kind of inject won't be taken into account by Vue.

I could do a simple `onclick` in my button tag but I'm looking a way to make it cleaner. As far as my understanding goes, there is no template scope for grouped rows but I could be very wrong.

### jsfiddle
https://jsfiddle.net/a68bhLoc/

Many thanks in advance,

Sébastien

**Comment by xaksis** [comment]
hey @vigorem v2.10.0 allows customizing header rows using slots: 
https://xaksis.github.io/vue-good-table/guide/advanced/grouped-table.html#customizing-header-row

closing.
