### ISSUE TITLE
Pagination resets after remote sort

### ISSUE THREAD

**Issue by jamessnook** [xaksis/vue-good-table#325]
### Issue Type:

- [x] Bug??  (or else  user error...)
- [x] Question

### Specs
2.8.2

What browser?
Chrome

### Expected Behavior

Pagination remains unchanged after remote sort of current page.

### Actual Behavior

Select column sort while pagination is showing records 11-15.  After sort,  pagination shows that it is at records 1-10 and previous button is disabled though the visible data is now records 11-15 as sorted on the server using laravel pagination.

### Steps to Reproduce the Problem

1. Use remote and, pagination options enabled ( sort options enabled or not listed both worked the same)
2. Implement code as in example for remote.  (note the doc shows pagination-options with no ":" in front of it and the pagination did not appear until I added the ":"
3.  Use pagination to navigate to second or last page (I only had two pages.)   
4. Sort on a column.  
5. Note that pagination inputs have reset as if you are now on the first page.

**Comment by jamessnook** [comment]
It looks like it is a feature.  From line 822 of Table.vue:

     // every time we change sort we need to reset to page 1
      this.changePage(1);

I can program around this by resetting page to one in my code whenever there is a sort.  However it would still be nice to have a way to programmaticly  tell the paginator what page you are on.

**Comment by xaksis** [comment]
@jamessnook this is a rather debated UX feature. Consider this - If the user is on page 4 and sorts on a column, there's no way to predict what the content of page 4 would be. In fact, the user will end up somewhere in the middle of the sorted range. This is why the decision was made to go to the beginning of the table on sort. 

I'm going to close this unless there's a strong preference/reason as to why the default behavior of sort should be different.

**Comment by Sell24** [comment]
I understand the debate on this feature, but would it be possible to have this as a option? The reason being is that I am using the grouped option and then within that group, I am sorting the values by the appropriate column. Since I am using server-side sorting, I know what page I am on and what I need to sort. It all works except for the fact that the paginator gets reset to the first page. 

Nice job on the code by the way.
