### ISSUE TITLE
How to set custom column with?

### ISSUE THREAD

**Issue by sudhir600** [xaksis/vue-good-table#328]
I don't see any custom way to set column width in this table. If i use css like this

```
.tbl tr th:nth-of-type(1),
.tbl tr td:nth-of-type(1){
	width: 15%!important;	
}

.tbl tr th:nth-of-type(2),
.tbl tr td:nth-of-type(2){
	width: 15%!important;	
}

.tbl tr th:nth-of-type(3),
.tbl tr td:nth-of-type(3){
	width: 15%!important;	
}

```

above code change the table column but behind that whole table took same width as previous. 
See in this screenshot.

![image](https://user-images.githubusercontent.com/4952560/42270864-7bc4f5d4-7f9f-11e8-9c3b-a7c7c0c96293.png)

**Comment by belvederef** [comment]
The documentation talks about it here https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#width.
```
columns: [
  { 
    label: 'name',
    field: 'user_name',
    width: '50px',
  },
  // ...
]
```

**Comment by xaksis** [comment]
@belvederef thank you for referencing the doc.
@sudhir600 it seems like an issue with your custom styles and not vgt. If you can reproduce this in a jsfiddle I'll take a look. 

closing for now.
