### ISSUE TITLE
how to create a Dropdown options list in columns

### ISSUE THREAD

**Issue by fagworio** [xaksis/vue-good-table#329]
Nice work, very good component.
So, I have a doubt about how to create a Dropdown options list in columns,
I try the docs and unfortunately I was not able to reproduce the tutorial.

So, have someone a sample to share about how to create dropdown options on collumns?
Image sample 
https://github.com/xaksis/vue-good-table/raw/master/README/images/vgt-table.advanced.png

**Comment by xaksis** [comment]
hey @fagworio thank you. Here's a simple example of dropdown filter: 

https://jsfiddle.net/aks9800/a6k1uoxn/

closing.

**Comment by fagworio** [comment]
Thanks, Lol.

This help me a lot.

**Comment by antoniomsspider** [comment]
is this still working?
