### ISSUE TITLE
Radio-button Table?

### ISSUE THREAD

**Issue by sorayadragon** [xaksis/vue-good-table#330]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
2.8.2

What browser?
Chrome

### Question
Is it possible to only allow the user to select a single row in the checkbox table (i.e. a radio-button table)?

**Comment by xaksis** [comment]
it certainly should be possible @sorayadragon but you'll have to do some customizations. Here's a possible plan: 

1. create a custom [before column of radio buttons](https://xaksis.github.io/vue-good-table/guide/advanced/#adding-custom-columns)
1. make sure all radio buttons are part of the same group. 
1. keep track of which row is selected via [on-row-click handler](https://xaksis.github.io/vue-good-table/guide/configuration/table-events.html#on-row-click)

closing.

**Comment by luisdoniad** [comment]
Too late for you @sorayadragon but it works. Maybe others want this at 2022:

Using @on-row-click event you have the row selected (or unselected), then, if you add vgtSelected = true / false to your row element passed by prop to vue-good-table...
On row clicked, set to false vgtSelected property on all your row elements except the row selected, that you may set to true.

```js
@on-row-click="selectOne"
```

```js       
 selectOne(payload) {
    //for select just one item
    if (!payload || !payload.row || !payload.row.vgtSelected) {
        return;
    }
    for (let i = 0; i < this.data.length; i++) {
        const element = this.data[i];
        if (element.id !== payload.row.id) {
            element.vgtSelected = false;
            continue;
        }
        element.vgtSelected = payload.selected;
    }
}
```

Another point is to add a new flag for disable th select-all checkbox. I am using a fork of this project and I could do it.
