### ISSUE TITLE
Control selected rows from the component

### ISSUE THREAD

**Issue by KINKCreative** [xaksis/vue-good-table#331]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Question

How can I control the selected rows from the component itself? E.g. I'd like to check certain rows or all rows at time of instantiation of the table / or with a method?

**Comment by xaksis** [comment]
hey @KINKCreative please refer to this closed issue: 
https://github.com/xaksis/vue-good-table/issues/287

you can use vgtSelected property to achieve what you're looking for.

closing.
