### ISSUE TITLE
Keep selected rows when searching rows

### ISSUE THREAD

**Issue by jurgenbosch** [xaksis/vue-good-table#332]
### Issue Type
- [x] Enhancement Request

Enhancement idea; 
When using the checkbox option and combining it with the search option the following happens; 
When checking two rows and than search the two selected rows got forgotten. 

This behavior is due to line 897 in component Table.vue that reads;
this.unselectAllInternal(true); 

If you unselect this rule it will not flush the options anymore. 
Ideally this would be an option of the select options in function initializeSelect.

**Comment by xaksis** [comment]
@jurgenbosch this isn't as straightforward as just removing the reset. The selected row info is based on displayed rows (processed rows). If you remove the reset, as you search, the displayed rows change, the selected info changes to say 'there's nothing selected' even though there are rows selected, they just aren't visible. 

It'll take some effort to figure out how to do this without breaking the functionality. I'll keep this open but no ETA on this just yet.

**Comment by xaksis** [comment]
same as #286 going to keep that one and close this.

**Comment by JulienJarvis** [comment]
any chance to have this feature ?
