### ISSUE TITLE
Remote pagination and  sorting

### ISSUE THREAD

**Issue by sylvaincaillot** [xaksis/vue-good-table#333]
### Issue Type (delete the irrelevant ones) 
- [x] bug
- [x] Enhancement Request

### Expected Behavior
Using the remote mode, I would expect when you sort a column, to be automatically redirected to the first page with the correct sorting.

### Actual Behavior
It is marked first page but in reality it keeps the current page number which prevents the sorting to be correct.

I had to change the code as follow to make it work:
```
onSortChange(params) {       
        this.updateParams({
          sort: {
            type: params.sortType,
            field: this.columns[params.columnIndex].field,
          },
          page: 1,
        });
        this.loadItems();
      },
```

**Comment by xaksis** [comment]
Hey @sylvaincaillot, Not sure what you mean by 
>  in reality it keeps the current page number
in remote mode, the table cannot change the actual row data for you, you'll have to handle it in the `on-sort-change` handler which you seem to be doing. This is also true for `on-filter-change`, on-`global-search` etc. With each such event, you need to reset the page to 1 in the handler. 

closing.
