### ISSUE TITLE
Format filter value

### ISSUE THREAD

**Issue by sylvaincaillot** [xaksis/vue-good-table#334]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request
- [x] Question

### Expected Behavior
In remote mode, I would like to format the filter values first. For example, I have a date column in VGT but I would like to see all the records from 2018. So I type 2018 in the relevant column filter but would like to send '01-01-2018' instead to my API. Can it be done?

Is it also possible to display a datepicker for a date column filter?

Anyway thank you very much for what you've done so far for the remote mode.

S.

**Comment by xaksis** [comment]
@sylvaincaillot in remote mode, you're fully in-charge of what your API receives. set a handler on 'on-filter-change' and put your logic in that handler. For example in your case, In the filter-change handler you'll test to see If date column has a filter, and if it's "2018", change it to "01-01-2018" before you send the request to the backend. 

Currently using custom widgets for filter is not possible, but I will be more than happy to review a PR for this.

closing.

**Comment by sylvaincaillot** [comment]
Thnak you very much @xaksis,

I am now using the `@on-column-filter="onColumnFilter"` to reformat my date as necessary but it makes me think of some improvements which might be useful to vue-good-tables.

Since you have now this remote mode, it would be great to filter a column based on a different field in the API:

For example, I want to display a datetime field in my table but i want to get the filtering to be made against my API on a different field.

It would give something like:

```
{
            label: 'Dispatch on',
            field: 'dispatchDate',
            type: 'date',
            dateInputFormat: 'DD-MMM-YYYY',
            dateOutputFormat: 'DD MMM YYYY',
            filterOptions: {
                enabled: true, // enable filter for this column
                placeholder: 'Enter a year',                
                trigger: 'enter',
                filterField:'dispatchYear', <-- New field used for the filtering
            },            
          },
```

In many case the `field `and `filterField` would be the same (if no filterField, use the field by default for example) butit would give a great flexibility for users targeting more specialized APIs like me ;)

What do you think?

S.
