### ISSUE TITLE
Collapsable filter header

### ISSUE THREAD

**Issue by sylvaincaillot** [xaksis/vue-good-table#335]
### Issue Type

- [x] Question

Hello,

Is there any css class attached with the filter header row? I would like have it collapsed by default and then give the user to expand it when needed.

Any suggestion?

Thank you

Sylvain

**Comment by xaksis** [comment]
hey @sylvaincaillot you can now customize header rows using slots: 
https://xaksis.github.io/vue-good-table/guide/advanced/grouped-table.html#customizing-header-row

closing.

**Comment by tripflex** [comment]
@sylvaincaillot I was looking to do this as well, and @xaksis provided a method for doing this by setting the filter enabled false, see #355 for details and fiddle
