### ISSUE TITLE
How to add Button function??

### ISSUE THREAD

**Issue by standfv** [xaksis/vue-good-table#337]
### Issue Type (delete the irrelevant ones) 

- [ ] Bug
- [ ] Enhancement Request
- [x] Question: How to add Button function?

### Specs
What version are you using?

What browser?

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happened?

### Steps to Reproduce the Problem
Please detail your steps here

1.
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
@standfv I have no idea what this issue is about?? I'm going to close this. Please add more details about what you're asking and I'll re-open if it is relevant.
