### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by enghelewa** [xaksis/vue-good-table#339]
### Issue Type
Enhancement Request

### Specs
VGT v2.11.0

### Expected Behavior
Could you please update the docs so that people could find the right info there.

In the section of "[Custom pagination](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template)" you need to add more information about how to use the provided `props.pageChanged()` and `props.perPageChanged()` because it will not work until you hit the source of VGT to fined out the write format of data you should provide for these two methods.

for `pageChanged()` the write format is `{ currentPage: this.currentPage }`
for `perPageChanged()` the write format is `{ currentPerPage: this.currentPerPage}`

**Comment by xaksis** [comment]
@enghelewa thanks for pointing this out. @VictorCazanave wanna take this one? If not, I'll see if I can do it when I get a few free cycles.

**Comment by VictorCazanave** [comment]
@xaksis Yes, I'll try to do it this week.

**Comment by xaksis** [comment]
@enghelewa @VictorCazanave I had some time so I updated the documentation: 
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-pagination

closing.
