### ISSUE TITLE
Dynamic row class

### ISSUE THREAD

**Issue by rudden** [xaksis/vue-good-table#343]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Specs
Latest (2.11.0)

What browser?
Chrome

### Expected Behavior
First of all - great component! Really solves some time consuming issues for me. One thing I haven't been able to solve yet is to set a dynamic row class based on a condition.

I have a table with rows that display games with including their results and based on the result I'd like to apply a class to the individual row. So for example if a certain team has one the game the row should be colored green, and if they have lost the row class should apply a red color. I already have the logic to determine which class to apply to the row - I just haven't been able to figure out how to apply a custom class to the tr elements. The scopes available for cells doesn't really solve my issue.

Is this completely new functionality or have I just missed something in the docs?

Thanks in advance! :)
/Simon

**Comment by xaksis** [comment]
Hi @rudden thank you for appreciating the component... I am glad it was able to save you time! 

To answer your question - currently there's no way to conditionally style a row. There is a non-elegant way of doing it. I created a quick example to demo it here: 
https://jsfiddle.net/aks9800/rLqbk8eh/

Having said that, there needs to be a better way to do this. I'll definitely look into it.

**Comment by rudden** [comment]
Hi @xaksis 

Well, the non-elegant way works perfect until you've figured out a more elegant way to do it :)

Thank you very much for your help!

**Comment by rudden** [comment]
Overdelivering! Nice one. Thanks again!

**Comment by cannap** [comment]
Hi, question

 i tried to style it i have  the following scenario

1. Via Websocket i get changes to a Item
2. i will watch then i need to add a class to this tr to let i "PULSING"  later i will remove 
3.  but i have no idea how to do since i dont know how to style the TR conditional not td

**Comment by p0psicles** [comment]
That's tricky. I would check if you could update a rows attribute (reserved for that ws state) and then change the :key on the vue-good-table to have re-render.

So, you use the `rowStyleClassFn` function to conditionally add the tr class.

**Comment by cannap** [comment]
yea damn i need a other way it would be nice to have a whole tr to override :D so i could move it in a different file 
and then watch it set the updated id to show the blinking class  and remove it and repleat...
