### ISSUE TITLE
Table column width not being picked, and how to make rows not wordwrap

### ISSUE THREAD

**Issue by gthuo** [xaksis/vue-good-table#344]
### Question
My table does not seem to respect the column width i set in the headers. It just automatically allocates the width to use. Also, due tho this dynamic width adjustment, some row contents end up to be so much word-wrapped, which makes the rows very thick. Any solutions, or ideas of what I could be doing wrong?
![image](https://user-images.githubusercontent.com/13334580/43313066-afcfdf06-9197-11e8-896a-3682c4b28ff1.png)

![image](https://user-images.githubusercontent.com/13334580/43313027-9763ac36-9197-11e8-931b-05e79a64c7bc.png)

The column dimensions clearly show that the width for name should be almost 4 times that of the number, but the other screenshot shows they have basically the same column width.
### Specs
2.12.1

**Comment by fnrcum** [comment]
I am also experiencing this, if you fixed it, could you tell me how you did that? for me the width attribute is not taken into account
