### ISSUE TITLE
Feature Request: Allow formatting of pagination page ranges for i18n...

### ISSUE THREAD

**Issue by darkermatter** [xaksis/vue-good-table#35]
Hello!

While all the other text in the table can be internationalised, there is one item that can't:

> 1-10 of 100

Could we have an option to at least change the word "of"?

Thanks! :-)

**Comment by xaksis** [comment]
sure! I'll add that in to the next patch.

**Comment by xaksis** [comment]
added in v1.9.1

**Comment by darkermatter** [comment]
@xaksis That's great news. I'll update to it later this week. Thanks so much for the quick patch!
