### ISSUE TITLE
Adding Custom Row Template to specifc row?

### ISSUE THREAD

**Issue by danchristian** [xaksis/vue-good-table#351]
Is it possible to apply a Custom Row Template to a specific row? My end goal is inline-editing, so when a user clicks on an individual row, that row then turns into editable inputs, they would be able to edit the inputs and when clicking outside the row, the data would be saved and the row returns to read only.

I've been able to make a start by doing a simple `v-if`, but it then applies that Template to all rows:
```
<template slot="table-row" slot-scope="props" v-if="isActive">
  <span v-if="props.column.field == 'type'"><input v-model="props.row.type"></span>
</template>
```

I can bring back the row object on click, but unsure if I can use anything from that to then customise the Custome Row Template?

```
onRowClick(params) {
  this.isActive = true;
  console.log(params.row);
}
```

Thank You

**Comment by xaksis** [comment]
@danchristian here's a quick example I created to show how you can change the row template based on a click: 
https://jsfiddle.net/aks9800/1764cbs8/

obviously you'll have to take care of what happens when a click happens outside, or on another row. But this should get you started. 

closing.

**Comment by danchristian** [comment]
@xaksis That's really helpful thanks. And just to be clear, if I wanted some of them editable and not others and some of the editable items are different types of input, then I have to do a check for each one, within the `v-if`? So..

```
<span v-if="props.row.active">
  <span v-if="props.column.field == 'subcategory'">{{ props.row.subcategory }}</span>
  <span v-if="props.column.field == 'text'"><input type="text" v-model="props.row.text"></span>
  <span v-if="props.column.field == 'time'"><input type="number" v-model="props.row.time"></span>
</span>
```

**Comment by danchristian** [comment]
Also, just for anyone looking at this in the future, I converted the loop from your example into ES6 syntax 🙂

```
onRowClick(params) {
  for (let row of this.rows) {
     if (params.row.id === row.id) {
       this.$set(row, 'active', true);
     }
   }
}
```
