### ISSUE TITLE
Fixed column & header

### ISSUE THREAD

**Issue by kn7007** [xaksis/vue-good-table#353]
Hello,
First, thank you for this beautiful package.
Do you planned to implement fixed columns?
Btw, fixed header may be still not complete. Header column width too long for column width.

![capture](https://user-images.githubusercontent.com/35058512/43724299-ca7ef074-99c3-11e8-8882-8446351cd0e4.JPG)

**Comment by manofthefort** [comment]
I also experience this problem when using fixed header.  There needs to be an offset for the scroll bar.

**Comment by manofthefort** [comment]
I have devised a workaround with some CSS.

    /* Vue Good Table OVERRIDES */
    /* ################################################################# */
    table.vgt-table.vgt-fixed-header {
        position: relative !important;
    }
    
    table.vgt-table.vgt-fixed-header th:last-child {
        /* Offset for the scrollbar, you may have to adjust this */
        width: calc(100% + 17px) !important;
    }
    
    table.vgt-table:not(.vgt-fixed-header) > thead {
        /* Collapse the first row which is the un-fixed table heder */
        visibility: collapse;
    }

**Comment by xaksis** [comment]
@kn7007 @manofthefort keep in mind that this only happens on windows. The fix will actually be an issue on macs since the default scrollbars there don't take up additional space - so use with caution.

**Comment by xaksis** [comment]
@kn7007 glad the fix worked for you. The fixed column is not on the roadmap just yet, but I'll happily review a PR for it. 

closing.
