### ISSUE TITLE
Manage Loading state.

### ISSUE THREAD

**Issue by danmash** [xaksis/vue-good-table#356]
Would be nice to have access to customize and manage a state of this `Loading...` Is it possible? 
![2018-08-07 12-29-53](https://user-images.githubusercontent.com/3535056/43767381-a5e4a3a6-9a3d-11e8-915e-91dd786038fb.png)

**Comment by xaksis** [comment]
hi @danmash the documentation is a bit lacking here, I'll work on adding the necessary bits there but here's the gist: 

If you want to show loading notification manually, you can do so using table's: `isLoading=true` property.

if you want to customize what loading looks like you can make use of this slot: 
```html
<vue-good-table ...>
  <template slot="loadingContent">
    <!-- your content here -->
  </template>
</vue-good-table>
```
closing.

**Comment by danmash** [comment]
Thanks!

**Comment by ChaStPierre** [comment]
@xaksis Do you have a working example of this? I know its very simple to do but I haven't had any success getting this to run.
