### ISSUE TITLE
Server side filtering for columns

### ISSUE THREAD

**Issue by entwicklerRepo** [xaksis/vue-good-table#357]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
latest

1. Sorry I'm pretty new in vuejs, but Is there a way to do server side filtering for columns?

**Comment by xaksis** [comment]
hey @entwicklerRepo welcome to vue and vue-good-table! for server-side workflow, you can refer to the following workflow: 
https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html

specifically for server-side column filtering, as the document states, you'll make use of the `@on-column-filter="onColumnFilter"` event. Hopefully, this should get you started. 

closing.

**Comment by entwicklerRepo** [comment]
@xaksis thanks a lot! it took a while to fully understand, but it runs like a charm now 👍
