### ISSUE TITLE
Unable to customize the message "No data for table"

### ISSUE THREAD

**Issue by pedroresende** [xaksis/vue-good-table#358]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Specs
Version: 2.8.2
Browser: Any

### Expected Behavior

I would be nice to be able to customize the "No data for table" message, passing by props.

### Actual Behavior

It's not possible to customize, since it is harcodded

### Steps to Reproduce the Problem
Please detail your steps here

1.Add a table, without any content

**Comment by xaksis** [comment]
Hi @pedroresende, a slot has already been provided to customize the empty state. I think It's straightforward enough to use without having to use a prop for it. 
 
https://xaksis.github.io/vue-good-table/guide/configuration/#empty-state-slot

closing.
