### ISSUE TITLE
How do I do this? [transpiler]

### ISSUE THREAD

**Issue by 0libre** [xaksis/vue-good-table#36]
> The plugin is meant to be used with existing Vue 2.x projects. It uses ES6 features so as long as your build process includes a transpiler, you're good to go.
It would be great with an proper example, I'm running this: https://github.com/wolfeidau/cognito-vue-bootstrap and would like to add **vue-good-table** but, being new in the world of webpack, vue etc - I have no idea what or how I should do this.
I've tried multiple guides but they also make vast assumptions.

So please, could someone help me out? :)

**Comment by xaksis** [comment]
hey @0libre, cognito-vue-bootstrap is just another vue project... so I don't think you need to do anything special. It is the same process you'd follow for any vue plugin: 

- first install the plugin: cd into your root directory and do: `npm i --save vue-good-table`
- then to use the plugin,  locate the file called main.js in your project's  `src` directory,
- in that file (main.js), add the following as per readme: 
```javascript
import VueGoodTable from 'vue-good-table';

Vue.use(VueGoodTable);
```
- you should now be able to use the plugin in any of your components by following the readme instructions.

**Comment by 0libre** [comment]
@xaksis Hi, thank you for replying 👍 
Problem is that if I follow your guide (and all others I can find) 
**I get this error:**
VM8658:1 Uncaught SyntaxError: Unexpected token import

**On this row:**
import GoodTable from './components/Table.vue';

I read something about the plugin might need some "transpile" but I have zero idea how to do this, nor have I had this problem with another plugin. So I've been bashing my head in for the entire day, trying to get this to run.

**Comment by xaksis** [comment]
I am unclear as to what you mean by template?... how have you included other plugins? how are you importing the current plugin? If you give a complete description of what you're doing, I might be able to understand your issue better...
