### ISSUE TITLE
Table not getting cleared when service response empty, showing previous results.

### ISSUE THREAD

**Issue by ubstack** [xaksis/vue-good-table#360]
### Issue Type

- [x] Bug

### Specs
Vue 2.5

What browser?
Chrome

### Expected Behavior
Expecting grid to show NO DATA text

### Actual Behavior
It is showing previous records, even the response is empty

### Steps:
Input: 
data() {
    return {
      items: []
     }
}

Update: 
axios.get(url, {params: this.searchObj})
      .then(response => {
           this.items = response.data.items
       });

### Note: When I change it to different search options for the response will not be empty, the table is getting updated with the data, but for the empty responses it's not updating.

**Comment by xaksis** [comment]
Hey @ubstack there's no reason why it shouldn't update when there's no data. Just make sure you set it to empty array `[ ]` when there's no response.data.items. 

closing. Let me know if the above doesn't work and we'll work it out.

**Comment by ubstack** [comment]
Still trying different ways to get ride of this, i tried setting to [], table data still remains it's not getting cleared. Please let me know if you need additional inputs to get it resolved, Thanks.
