### ISSUE TITLE
How to handle double click?

### ISSUE THREAD

**Issue by danmash** [xaksis/vue-good-table#361]
- [ ] Enhancement Request

Hi, I need to handle double click instead of simple click. 
Double click will open a new tab. Single click while copy some info from the row.

**Comment by xaksis** [comment]
`on-row-dblclick` event added for table row in v2.13.0. Keep [browser compatibilty](https://developer.mozilla.org/en-US/docs/Web/Events/dblclick) in mind.

**Comment by danmash** [comment]
I'm using chrome and this feature  doesn't work

**Comment by danmash** [comment]
it works thank you
