### ISSUE TITLE
Sort by id doesn't work

### ISSUE THREAD

**Issue by Sharvadze** [xaksis/vue-good-table#362]
If you have numeric value in the table, the sorting doesn't work

`Error in getter for watcher "selectedRows": "TypeError: d.toLowerCase is not a function"`

**Comment by xaksis** [comment]
hey @Sharvadze, if you don't specify column type, it's going to assume it's a string. Refer to: 
https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#type

closing

**Comment by bthyfos** [comment]
i have specified the column type and all but i still get this error..

**Comment by bthyfos** [comment]
i ended up removing all the type of the columns and now i get this error 

Error in render: "TypeError: d.toLowerCase is not a function"

**Comment by p0psicles** [comment]
You'll have to check per column what the type is, and set type I'd it's not a string.

**Comment by osmaircoelho** [comment]
The same error is appearing for me, in my case the data comes with a number and then I transform the number to a string because it goes through a javascript function that transforms the id into a string, at the end, the column displays a string 

I update my good-vue-table to 2.21.11 still not working...

**Comment by osmaircoelho** [comment]
I think you need to change the field as it is in the array because in mine I changed it and it worked, and I changed it to display only string instead of showing numbers
```

{
         label: "Status",
         field: "statusContract.name",
         sortable: true,
         type: "string",
}
```

**Comment by yayanbachtiar** [comment]
> I think you need to change the field as it is in the array because in mine I changed it and it worked, and I changed it to display only string instead of showing numbers
> 
> ```
> 
> {
>          label: "Status",
>          field: "statusContract.name",
>          sortable: true,
>          type: "string",
> }
> ```

it's work for me
thanks
