### ISSUE TITLE
formatFn with html true

### ISSUE THREAD

**Issue by danmash** [xaksis/vue-good-table#363]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

`formatFn` function doesn't work together with `html=true` (I see raw value instead of function result)
```
      this.query.columns.forEach(function (value, i, array) {
        if (value.field == 'id') {
          array[i].formatFn = function (value) {
            return '<a href="/orders/' + value + '" target="_blank">' + value + '</a>'
          };
          array[i].html = true;
        } 
      }
```
If `html=false` I see a function result html code.

**Comment by xaksis** [comment]
hey @danmash, any reason you can't use the row template here? it'll be a lot cleaner than using a format function to render HTML. FormatFn is meant to provide a quick way to format your text, not to render HTML elements. 

Take a look here: 
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template

**Comment by danmash** [comment]
you are right. finally, I choose the row template option.
Thank you
