### ISSUE TITLE
While the mode is `remote` the `initialSortBy` sort param is permanent.

### ISSUE THREAD

**Issue by danmash** [xaksis/vue-good-table#364]
While the mode is `remote` the `initialSortBy` sort param is permanent. 
Can't be changed.

**Comment by xaksis** [comment]
Hey @danmash, not sure what you mean by permanent? initialSortBy is meant to be the sort for when the table is initially mounted. Once it is mounted, you need to either re-mount the table or call the internal function reset `this.$refs['myTable'].reset()`

closing.

**Comment by danmash** [comment]
@xaksis I mean when I set `initialSortBy` I see this sort, but after this I can't change sorting at all. This small triangle every time in the single place (initial sort by column)

**Comment by bogatyrjov1** [comment]
danmash means that when mode="remote" and :sort-options="{ initialSortBy }" are both specified, sorting won't work
