### ISSUE TITLE
externalQuery questions

### ISSUE THREAD

**Issue by danmash** [xaksis/vue-good-table#366]
- [ ] Why I can't use `externalQuery` with default interface? I want to bind some field to default input. Is it possible? 

- [ ] My problem can be solved also with a different trigger type. A type which would trigger a search with some delay after `key up`. To allow user type something in the input field and then make search after without pushing the `Enter` key.

**Comment by xaksis** [comment]
@danmash - don't understand what you mean by not being able to use externalQuery with default interface. 

for column filters, you can use filterValue key to set filter values from outside the table. Just keep in mine that you can't simply assign values to this property... you'll need to use `$set` for nested object change detection.

closing.
