### ISSUE TITLE
Column search+ global search

### ISSUE THREAD

**Issue by Dracks977** [xaksis/vue-good-table#367]
- [x] Question

is it possible to have a global and column search at the same time ?

**Comment by danchristian** [comment]
> Column filters cannot be used if global search is enabled

https://xaksis.github.io/vue-good-table/guide/configuration/column-filter-options.html#enabled

Although this functionality would be great.

**Comment by Dracks977** [comment]
it's possible, just activate one and put one variable in the other

```
 :select-options="{ 
    enabled: true,
    selectOnCheckboxOnly: true
  }" ref='vueGoodTable'
  :search-options="{
    enabled: boolColumnSearch,
    externalQuery: searchGlobal
  }"
```
and 

```
 return {
                boolGlobalSearch: true,
                boolColumnSearch: false,
```

**Comment by Dracks977** [comment]
it's a usebug, but it works xD

**Comment by danchristian** [comment]
I can't get this to work. I want a table without checkboxes and global and column search.

https://jsfiddle.net/tob624xf/
