### ISSUE TITLE
Grouping header table cells are not hidden when the column is hidden

### ISSUE THREAD

**Issue by xgx252c** [xaksis/vue-good-table#369]
### Issue Type
- [x] Bug

### Issue
When a column has hidden set to true then the column cells are hidden, but it does not hide the grouping cells for the same column. See jsfiddle below.

### Specs
Version: v2.13.0

### Possible solution
I looked into [VgtHeaderRow.vue](https://github.com/xaksis/vue-good-table/blob/master/src/components/VgtHeaderRow.vue) line 24+ and adding !column.hidden there seems to be solving the problem:
```  <th
    v-if="headerRow.mode !== 'span' && !column.hidden"
    v-for="(column, i) in columns"
    :key="i"
```

### jsfiddle
https://jsfiddle.net/4g6fwhpn/

**Comment by xaksis** [comment]
@xgx252c this is fixed in v2.13.1

closing.
