### ISSUE TITLE
Feature Request: Responsive tables

### ISSUE THREAD

**Issue by RIanDeLaCruz** [xaksis/vue-good-table#37]
Hi

What this aims to do is to add a scrollbar for when there is overflow on the x-axis.

**Comment by xaksis** [comment]
Hi @RIanDeLaCruz, thanks... i'll review it shortly.

**Comment by RIanDeLaCruz** [comment]
@xaksis I've put in a pull request for this

**Comment by xaksis** [comment]
@RIanDeLaCruz thank you for your help! closing.

**Comment by RIanDeLaCruz** [comment]
Thank you!
