### ISSUE TITLE
Pagination Info Not Updating Upon Reseting Current Page to 1

### ISSUE THREAD

**Issue by josephting** [xaksis/vue-good-table#370]
### Issue Type

- [x] Bug

### Specs
vue-good-table@2.13.0
Chrome Stable Latest (v68.0.3440.106)

### Expected Behavior
Current page in pagination info should go back to page 1 when currentPage is reset back to 1 due to filtering or perPageChange.

### Actual Behavior
Current page did not get updated in Pagination Info component but the table is displaying page 1 records.

### Steps to Reproduce the Problem
1. Go to page 4 (Click next 3 times or enter 4 in input and press enter)
2. Change rows per page from 2 to 5

### jsfiddle
https://jsfiddle.net/eywraw8t/295127/

**Comment by xaksis** [comment]
@josephting this is now fixed in v2.13.1 

closing.
