### ISSUE TITLE
Disable Whole Table Option

### ISSUE THREAD

**Issue by deanilvincent** [xaksis/vue-good-table#375]
Hi @xaksis 

I'm just wondering, is there any option that we can disable the whole table?

For instance, I have a request from my API. I want to disable the whole table while my request is communicating with my REST Service/Server.

So far, I've tried the `:disabled="true"` inside the table option but I'm not sure if it is possible.

Thank you!

**Comment by xaksis** [comment]
hey @deanilvincent this should be easily doable via simple css. Just put: 
`pointer-events: none;`
on the table wrapper and none of the elements within the table will be reactive.

**Comment by deanilvincent** [comment]
Thank you @xaksis :)
