### ISSUE TITLE
Trigger column-filter on filterValue change

### ISSUE THREAD

**Issue by 1stkeks** [xaksis/vue-good-table#376]
### Issue Type 
- [x] Question

### Specs
What version are you using?
2.12.2

What browser?
Google Chrome

### Expected Behavior
If I set the "filterValue" the columnfilter should filter

### Actual Behavior
- With JQuery clicking on the filter-input opens a daterangepicker
- On selecting a daterange I set the "filterOptions.filterValue" of the column
- To actually filter the data I have to click on Input field again, and press any key (default trigger (keyup))

Is there any way to call the filter method on filterValue-change?

https://jsfiddle.net/57a2a4ce/522/

p.s. if you have a good way to implement the date-range-picker I'd be glad to hear it. Selecting by the placeholder is not a good way to do this, but I couldn't come up with a better way right now..

**Comment by xaksis** [comment]
Hey @1stkeks, remember that for vue to detect changes in nested objects, you need to keep the caveats in mind - https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats
To fix your issue: 
`self.$set(found.filterOptions, 'filterValue', $(this).val());`
