### ISSUE TITLE
Can't seem to filter Boolean values

### ISSUE THREAD

**Issue by danchristian** [xaksis/vue-good-table#378]
- [x] Bug

What version are you using?
2.0.0.alpha

What browser?
Chrome

### Expected Behavior
I can filter boolean values

### Actual Behavior
I can't filter boolean values

### jsfiddle
https://jsfiddle.net/ywdujp43/

**Comment by xaksis** [comment]
hey @danchristian thank you for pointing this out. This is now fixed in version 2.13.2

closing.

**Comment by HudsonMCynner** [comment]
Hello, I found a solution to this problem, I added another IF condition in the Compare function inside the default.js file that is inside the folder.

I added this code :   **if (typeof d === 'boolean' ) return d;**

compare(x, y) {


    function cook(d) {

      if (typeof d === 'undefined' || d === null) return '';
      if (typeof d === 'boolean' ) return d;
      return d.toLowerCase();
    }
    x = cook(x);
    y = cook(y);
    if (x < y) return -1;
    if (x > y) return 1;
    return 0;
  },
};
