### ISSUE TITLE
Can column filter dropdown be autogenerated?

### ISSUE THREAD

**Issue by oflittlemother** [xaksis/vue-good-table#380]
- [x] Question
Can column filter dropdown be autogenerated?
- ex. based on a 'Date' column, auto populate the dropdown items based on the data dates

**Comment by oflittlemother** [comment]
or perhaps can a Datepicker (ex. vue-datepicker-local) component be attached to the input field?

**Comment by xaksis** [comment]
hey @oflittlemother here's an example of how you can use third party library for date input created by another user: 
https://jsfiddle.net/aks9800/ekawt34s/

closing.

**Comment by oflittlemother** [comment]
Thank you, perfect example!
