### ISSUE TITLE
Page change event triggered when perPage is changed

### ISSUE THREAD

**Issue by josephting** [xaksis/vue-good-table#382]
### Issue Type

- [x] Bug

### Specs
* v2.13.2
* Latest Chrome Stable

### Expected Behavior
Changing perPage should **ONLY** trigger `on-per-page-change` event

### Actual Behavior
Changing perPage triggered both `on-per-page-change` & `on-page-change` event

### Steps to Reproduce the Problem
Please detail your steps here

1. Next & Prev page is working properly with only `onPerPageChange` event getting triggered
2. Changing perPage to any other perPage will trigger both `onPerPageChange` and `onPageChange` at the same time

### jsfiddle
https://jsfiddle.net/Lp8xw7ec/

v2.13.0 behavior - https://jsfiddle.net/saemvn4p/

**Comment by josephting** [comment]
It seems like this is intentional behavior from #371 ?
Please confirm. It feels like we're losing feature here to only change page back to 1 only when the current page exceeds the max page number after having the perPage changed.

**Comment by josephting** [comment]
@VictorCazanave Got it. Thank you for your confirmation. Agreed. Going with simpler method is usually better in this case.

@xaksis I've put together a JSFiddle to highlight the issue I'm facing with using `on-per-page-change` and `on-page-change` event.

https://jsfiddle.net/8dbemzjp/

Since `on-page-change` event is always called regardless of page or perPage being changed, I figured I should only do a table data reload from server only on `on-page-change`.
However, `on-page-change` is returning the old `currentPerPage` I think because the `$emit('per-page-changed')` is called after the page is changed back to 1.

If there is no particular reason behind having the page changed to 1 before emitting `per-page-changed`, I would like to have `this.changePage(1)` to only be called after `per-page-changed` has been emitted.

**Comment by xaksis** [comment]
@josephting took your recommendation. 2.13.3 has your fix.
