### ISSUE TITLE
How to filter column for null values?

### ISSUE THREAD

**Issue by danchristian** [xaksis/vue-good-table#384]
### Issue Type
- [x] Question

### Specs
What version are you using?
@2.13.2

What browser?
Chrome

### Expected Behavior
If I have a column with String values, how can I apply a filter that only shows the `null` (empty) rows?

`this.columns[9].filterOptions.filterValue = null`

### Actual Behavior
I can only seem to be able to reset it to show all rows.

### jsfiddle
https://jsfiddle.net/wbx0z8ra/

**Comment by xaksis** [comment]
hey @danchristian what's your usecase for this? the filterValue should not have values that cannot be entered by an endUser in a column filter. Otherwise you'll have inconsistent behavior between filter via code vs. filter via user interacting with the column filters...

**Comment by danchristian** [comment]
@xaksis I have a column of ‘comments’. I want the column to be searchable but also have a button that when clicked will filter the table by a Boolean value on another column && all entries with no comments.

**Comment by xaksis** [comment]
hmm One thing I can think of is prepopulate the comments that are empty with something like `N/A` then in formatFn you can check to see if the value is N/A and show '' instead. Here's an example: 
https://jsfiddle.net/aks9800/csrq0h4v/

this is your example. click on 'show empty' to show empty rows.

**Comment by danchristian** [comment]
If I `console.log(this.rows.length)` on my project I get `Cannot read property 'length' of undefined"` but when I do that on your link I get `8`. If I `console.log(this)` on your link I can see the `get rows` but I only have `get columns` in my project console. Any idea what could be going on?

**Comment by xaksis** [comment]
@danchristian depends on where you're console logging it. As the error indicates, in your case you seem to be logging rows before rows exist? hard to tell without looking at the code. Either way this sounds like a different issue than the original ticket. 

I'll close this ticket since the original issue can be dealt with using the example I provided above.
