### ISSUE TITLE
How to set filterValue based on condition?

### ISSUE THREAD

**Issue by danchristian** [xaksis/vue-good-table#385]
### Issue Type
- [x] Question

### Specs
What version are you using?
@2.13.2

What browser?
Chrome

### Expected Behavior
If I have a column of Boolean values, how can I set `filterValue: "false"` to show all false rows, unless there are no `false` values in which case, show all true rows (or all rows if not Boolean)

Either built into the `filterValue` functionality or customisable like `filterValue: "false" ? "false" : "true"`

**Comment by xaksis** [comment]
@danchristian use the filterFn property to do this - [FilterFn](https://xaksis.github.io/vue-good-table/guide/configuration/column-filter-options.html#filterfn)
```
filterOptions: {
  enabled: true,
  filterFn: this.myCustomFilter, // add your custom logic in this function.
  filterValue: 'false'
}
```
A lot of these answers can be found by going through the documentation or posting on StackOverflow.

closing.

**Comment by danchristian** [comment]
Thanks. I had read the docs but didn't realise `filterFn` and `filterValue` could be used together. Sorry, there was a `Question` option on the Issue so seemed appropriate to ask here.
