### ISSUE TITLE
Server side LoadItems()

### ISSUE THREAD

**Issue by jreq** [xaksis/vue-good-table#387]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.0

What browser?
Google Chrome

`loadItems() {
                getFromServer(this.serverParams).then(response => {
                    this.totalRecords = response.totalRecords;
                    this.rows = response.rows;
                });`

What should I do for use loadItems() ? Replace getFromServer by an axios method ? If yes, what should I put in PHP method ?

**Comment by xaksis** [comment]
@jreq I'm sorry, this is beyond the scope of the plugin. You might have better luck by asking that question on stackoverflow. You can get an idea about the service signature here: https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html#prep-work
