### ISSUE TITLE
defaultSortBy to sort by more than 1 column

### ISSUE THREAD

**Issue by dariagrudzien** [xaksis/vue-good-table#389]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
1.21
Chrome Version 69.0.3497.72 (Official Build) beta (64-bit)

### Expected Behavior
Looking for a way to have `defaultSortBy` sort the table by two columns, first by Date then by From. Tried with an array of objects. How could this be done?

### Actual Behavior
No change, table is sorted by the first column only.

### Steps to Reproduce the Problem
Pass an array in `defaultSortBy`, like this: `:defaultSortBy="[{field: 'Date', type: 'asc'}, {field: 'From', type: 'asc'}]"`

### jsfiddle
https://jsfiddle.net/Lra2yk0t/6/

**Comment by xaksis** [comment]
@dariagrudzien sorty it took so long, but this is now implemented in v2.16: 
https://xaksis.github.io/vue-good-table/guide/configuration/sort-options.html#initialsortby

in addition user can also shift-select multiple columns for multi-column sort

closing.
