### ISSUE TITLE
Computed property "paginated" was assigned to but it has no setter

### ISSUE THREAD

**Issue by Webprogramo** [xaksis/vue-good-table#39]
Hello,

The following error is displayed when the component is run.
<img width="787" alt="screen shot 2017-08-07 at 6 32 32 pm" src="https://user-images.githubusercontent.com/6793822/29050002-e109a27e-7b9e-11e7-84e3-ab2adb35e373.png">

**Comment by xaksis** [comment]
hey @Webprogramo, could you show me how you're using the plugin? I'm having trouble reproducing it.

**Comment by Webprogramo** [comment]
Everything works correctly, only in console it shows the previous error.


`<vue-good-table
                        title=""
                        :columns="columns"
                        :rows="rows"
                        rowsPerPageText=""
                        :paginate="true"
                        prevText="Anterior"
                        nextText="Siguiente"
                        styleClass="table table-bordered condensed">
                        <template slot="table-row" scope="props">
                            <td>
                                <el-button
                                    @click="showinfo(props.row.id)"
                                    class="icontbn icon-show-blue"
                                    ref="test">
                                </el-button>
                                <router-link active-class="link-activo" :to="'/clientes/nuevo-cliente/'+props.row.id">
                                    <el-button
                                        class="icontbn icon-edit">
                                    </el-button>
                                </router-link>
                            </td>
                            <td>
                                {{ props.row.name }}
                            </td>
                            <td>{{ props.row.nit }}</td>
                            <td>{{ props.row.address }}</td>
                            <td>{{ props.row.email }}</td>
                            <td>{{ props.row.phone }}</td>
                        </template>
                    </vue-good-table>`

Thanks

**Comment by xaksis** [comment]
@Webprogramo is this still an issue for you? do you mind creating a jsfiddle to illustrate this?
https://jsfiddle.net/aks9800/mn27rd7b/

**Comment by xaksis** [comment]
closing this, please re-open and create a jsfiddle if you can. thanks.
