### ISSUE TITLE
Saving sort & filter

### ISSUE THREAD

**Issue by oflittlemother** [xaksis/vue-good-table#390]
### Issue Type (delete the irrelevant ones) 
- [x] Question
How can the sorted and/or filtered state of the table be saved?
For example, I'm displaying database data and would like to save my custom sorting and filtering as a custom view of that first data pull.

**Comment by xaksis** [comment]
um... just save the initial state variables in your db or something? Then before you pull the data, fetch the default settings and initialize the table. This isn't really a plugin question. You'll just need to save the default state either in your DB or local storage etc. 

closing.
