### ISSUE TITLE
💯 Releases!

### ISSUE THREAD

**Issue by TheJaredWilcurt** [xaksis/vue-good-table#391]
![100 releases](https://user-images.githubusercontent.com/4629794/45056073-d7944400-b05f-11e8-9224-3129eb806851.png)

@xaksis @tonimc @VisualBean @VictorCazanave @megaket4up @VitorLuizC @RIanDeLaCruz @cristijora 

We did it! (and by "we" I mean mostly @xaksis)

![dog confetti](https://user-images.githubusercontent.com/4629794/45056984-699d4c00-b062-11e8-89ac-adf7d6ff8f23.gif)
![cat confetti](https://user-images.githubusercontent.com/4629794/45056990-6b670f80-b062-11e8-82f8-f6f3086f5b90.gif)

**Comment by xaksis** [comment]
haha! Wow... thank you for keeping an eye on it @TheJaredWilcurt! Well done all of us!

**Comment by VisualBean** [comment]
:)
