### ISSUE TITLE
All remote serverParams?

### ISSUE THREAD

**Issue by oflittlemother** [xaksis/vue-good-table#393]
- [x] Question
What are all the possible remote serverParams?
For example, what parameter needs to be updated when [ @on-search="onSearch" ] is triggered?
How about when [ @on-column-filter="onColumnFilter" ] is triggered?

The documentation is vague regarding remote mode.

**Comment by xaksis** [comment]
hey @oflittlemother can you tell me what about the documentation is vague?
https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html#prep-work shows you exactly what you need to send to server each time any of the triggers is hit, regardless of what trigger...
each time you'll be sending: 
```
serverParams: {
  // a map of column filters example: {name: 'john', age: '20'}
  columnFilters: {
  },
  sort: {
    field: '', // example: 'name'
    type: '' // 'asc' or 'desc'
  },

  page: 1, // what page I want to show
  perPage: 10 // how many items I'm showing per page
}
```
back to the server and server should bring back new set of `rows` and `totalRows`... which you need to update once you get the response back.

going to close this. Let me know how the documentation can be improved... or better yet submit a PR :)

**Comment by oflittlemother** [comment]
Will Global Search work with Column Filters in remote? If so, what are the serverParams for Global Search? My current project loads data correctly from the server but nothing works. No Global Search, no Column Filters, no Sorting, no Paging.

    onSearch(params){
      this.updateParams({search: params.searchTerm});
      this.loadRecords(this.the_start_date, this.the_end_date, this.the_group_by);
    },
    onSortChange(params){
      this.updateParams({
        sort: {
          type: params.sortType,
          field: this.columns[params.columnIndex].field
        },
        page: 1
      });
      this.loadRecords(this.the_start_date, this.the_end_date, this.the_group_by);
    },
    onColumnFilter(params){
      this.updateParams(params);
      this.loadRecords(this.the_start_date, this.the_end_date, this.the_group_by);
    },
