### ISSUE TITLE
'totalRecords' incorrect when grouping rows

### ISSUE THREAD

**Issue by oflittlemother** [xaksis/vue-good-table#394]
- [x] Bug
Why does 'totalRecords' show only 1 when I group rows?
Shouldn't the behavior always show a total of all items pulled from the database, independent of groups?
The current behavior showing only 1 creates a problem with paging, sorting, column filtering, global search.

**Comment by oflittlemother** [comment]
Nothing works, it just outputs a list of the children items, but I'm unable to interact with it.
Here is my debug output:

Rows:
[ { "transaction_id": null, "transaction_type": null, "storage_account_id": null, "storage_account_name": "Total:", "transaction_value": null, "transaction_date": null, "transaction_days_active": 0, "children": [ { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 20, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 787.28, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2578, "transaction_type": "Deposit", "storage_account_id": "100-001-0242", "storage_account_name": "Beck Trust Account", "transaction_value": 1197.34, "transaction_date": "2018-06-21", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2562, "transaction_type": "Deposit", "storage_account_id": "100-001-0238", "storage_account_name": "Business Account", "transaction_value": 1197.34, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2561, "transaction_type": "Deposit", "storage_account_id": "100-001-0236", "storage_account_name": "Smith Personal", "transaction_value": 14.22, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2575, "transaction_type": "Deposit", "storage_account_id": "100-001-0249", "storage_account_name": "person Personal", "transaction_value": 2000, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2561, "transaction_type": "Deposit", "storage_account_id": "100-001-0236", "storage_account_name": "Smith Personal", "transaction_value": 14.22, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2594, "transaction_type": "Deposit", "storage_account_id": "100-001-0246", "storage_account_name": "Estate Account", "transaction_value": 1197.34, "transaction_date": "2018-06-22", "transaction_days_active": 1 }, { "transaction_id": 2602, "transaction_type": "Deposit", "storage_account_id": "100-001-0255", "storage_account_name": "Beck Joint", "transaction_value": 787.28, "transaction_date": "2018-06-25", "transaction_days_active": 3 }, { "transaction_id": 2575, "transaction_type": "Deposit", "storage_account_id": "100-001-0249", "storage_account_name": "person Personal", "transaction_value": 1197.34, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 1197.34, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2561, "transaction_type": "Deposit", "storage_account_id": "100-001-0236", "storage_account_name": "Smith Personal", "transaction_value": 1197.34, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 977.08, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 977.08, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2581, "transaction_type": "Deposit", "storage_account_id": "100-001-0253", "storage_account_name": "Beck Business", "transaction_value": 14.22, "transaction_date": "2018-06-21", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2577, "transaction_type": "Deposit", "storage_account_id": "100-001-0242", "storage_account_name": "Beck Trust Account", "transaction_value": 1197.34, "transaction_date": "2018-06-21", "transaction_days_active": 0 }, { "transaction_id": 2602, "transaction_type": "Deposit", "storage_account_id": "100-001-0255", "storage_account_name": "Beck Joint", "transaction_value": 14.22, "transaction_date": "2018-06-25", "transaction_days_active": 3 }, { "transaction_id": 2563, "transaction_type": "Deposit", "storage_account_id": "100-001-0237", "storage_account_name": "Apple Joint", "transaction_value": 14.22, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2563, "transaction_type": "Deposit", "storage_account_id": "100-001-0237", "storage_account_name": "Apple Joint", "transaction_value": 787.28, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2599, "transaction_type": "Deposit", "storage_account_id": "100-001-0246", "storage_account_name": "Estate Account", "transaction_value": 1197.34, "transaction_date": "2018-06-22", "transaction_days_active": 1 }, { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 977.08, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 787.28, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 2005, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2562, "transaction_type": "Deposit", "storage_account_id": "100-001-0238", "storage_account_name": "Business Account", "transaction_value": 1197.34, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2575, "transaction_type": "Deposit", "storage_account_id": "100-001-0249", "storage_account_name": "person Personal", "transaction_value": 1197.34, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 977.08, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2571, "transaction_type": "Deposit", "storage_account_id": "100-001-0245", "storage_account_name": "User Personal", "transaction_value": 1197.34, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2575, "transaction_type": "Deposit", "storage_account_id": "100-001-0249", "storage_account_name": "person Personal", "transaction_value": 1197.34, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 1903, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2594, "transaction_type": "Deposit", "storage_account_id": "100-001-0246", "storage_account_name": "Estate Account", "transaction_value": 977.08, "transaction_date": "2018-06-22", "transaction_days_active": 1 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 1197.34, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 787.28, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 1197.34, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2575, "transaction_type": "Deposit", "storage_account_id": "100-001-0249", "storage_account_name": "person Personal", "transaction_value": 1197.34, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2567, "transaction_type": "Deposit", "storage_account_id": "100-001-0239", "storage_account_name": "Apple Personal", "transaction_value": 787.28, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2580, "transaction_type": "Deposit", "storage_account_id": "100-001-0242", "storage_account_name": "Beck Trust Account", "transaction_value": 1197.34, "transaction_date": "2018-06-21", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2575, "transaction_type": "Deposit", "storage_account_id": "100-001-0249", "storage_account_name": "person Personal", "transaction_value": 1197.34, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 14.22, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2563, "transaction_type": "Deposit", "storage_account_id": "100-001-0237", "storage_account_name": "Apple Joint", "transaction_value": 787.28, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 977.08, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2601, "transaction_type": "Deposit", "storage_account_id": "100-001-0254", "storage_account_name": "VNB Estate Account", "transaction_value": 1197.34, "transaction_date": "2018-06-25", "transaction_days_active": 3 }, { "transaction_id": 2594, "transaction_type": "Deposit", "storage_account_id": "100-001-0246", "storage_account_name": "Estate Account", "transaction_value": 1197.34, "transaction_date": "2018-06-22", "transaction_days_active": 1 }, { "transaction_id": 2603, "transaction_type": "Deposit", "storage_account_id": "100-001-0253", "storage_account_name": "Beck Business", "transaction_value": 1197.34, "transaction_date": "2018-06-25", "transaction_days_active": 3 }, { "transaction_id": 2562, "transaction_type": "Deposit", "storage_account_id": "100-001-0238", "storage_account_name": "Business Account", "transaction_value": 1197.34, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 977.08, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 977.08, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 14.22, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2568, "transaction_type": "Deposit", "storage_account_id": "100-001-0240", "storage_account_name": "Trust Account", "transaction_value": 1197.34, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2563, "transaction_type": "Deposit", "storage_account_id": "100-001-0237", "storage_account_name": "Apple Joint", "transaction_value": 14.22, "transaction_date": "2018-06-19", "transaction_days_active": 0 }, { "transaction_id": 2573, "transaction_type": "Deposit", "storage_account_id": "100-001-0250", "storage_account_name": "BeRich Personal", "transaction_value": 787.28, "transaction_date": "2018-06-20", "transaction_days_active": 0 }, { "transaction_id": 2562, "transaction_type": "Deposit", "storage_account_id": "100-001-0238", "storage_account_name": "Business Account", "transaction_value": 1300, "transaction_date": "2018-06-19", "transaction_days_active": 0 } ] } ]

Total Records: 1

Start Date: 2018-04-01

End Date: 2018-06-30

Group By: transaction_type

**Comment by xaksis** [comment]
@oflittlemother there are 15k downloads of this library a month. So while there might be bugs, I highly doubt that a statement like "nothing works" is productive. I understand you're frustrated but you'd need to create a more descriptive ticket of how you're using the table - remote mode or client side only? what version? relevant code that you're using (not a dump of your row data)

I'm closing this ticket.

**Comment by oflittlemother** [comment]
I'm using
- remote mode
- latest version 2.13.3

updateParams(newProps){
      this.serverParams = Object.assign({}, this.serverParams, newProps);
    },
    onSearch(params){
      this.updateParams(params);
      this.loadRecords(this.the_start_date, this.the_end_date, this.the_group_by);
    },
    onPageChange(params){
      this.updateParams({page: params.currentPage});
      this.loadRecords(this.the_start_date, this.the_end_date, this.the_group_by);
    },
    onPerPageChange(params){
      this.updateParams({perPage: params.currentPerPage});
      this.loadRecords(this.the_start_date, this.the_end_date, this.the_group_by);
    },
    onSortChange(params){
      this.updateParams({
        sort: {
          type: params.sortType,
          field: this.columns[params.columnIndex].field,
        },
      });
      this.loadRecords(this.the_start_date, this.the_end_date, this.the_group_by);
    },
    onColumnFilter(params){
      this.updateParams(params);
      this.loadRecords(this.the_start_date, this.the_end_date, this.the_group_by);
    },
    loadRecords(start_date, end_date, group_by){
      this.rpc('report.list_completed_transactions', [start_date, end_date, group_by]).then(result => {
        this.totalRecords = result.totalRecords;
        this.rows = result.rows;
      });

**Comment by oflittlemother** [comment]
<vue-good-table
        mode="remote"
        @on-search="onSearch"
        @on-page-change="onPageChange"
        @on-per-page-change="onPerPageChange"
        @on-sort-change="onSortChange"
        @on-column-filter="onColumnFilter"
        :totalRows="totalRecords"
        :pagination-options="paginationOptions"
        :group-options="groupOptions"
        :search-options="searchOptions"
        :columns="columns"
        :rows="rows"
        styleClass="vgt-table striped bordered condensed">

**Comment by oflittlemother** [comment]
columns: [
        {
          label: 'Transaction ID',
          field: 'transaction_id',
          type: 'number',
          sortable: true,
          filterOptions: {
            enabled: true,
            placeholder: 'Transaction ID…',
          },
        },
        {
          label: 'Transaction Type',
          field: 'transaction_type',
          filterOptions: {
            enabled: true,
            placeholder: 'Transaction Type…',
            filterDropdownItems: ['Deposit', 'Withdrawal'],
          },
        },
        {
          label: 'Account ID',
          field: 'storage_account_id',
          filterOptions: {
            enabled: true,
            placeholder: 'Account ID…',
          },
        },
        {
          label: 'Account Name',
          field: 'storage_account_name',
          filterOptions: {
            enabled: true,
            placeholder: 'Account Name…',
          },
        },
        {
          label: 'Transaction Value',
          field: 'transaction_value',
          type: 'decimal',
          filterOptions: {
            enabled: true,
            placeholder: 'Transaction Value…',
          },
          headerField: this.transactions_total,
        },
        {
          label: 'Transaction Date',
          field: 'transaction_date',
          type: 'date',
          dateInputFormat: 'YYYY-MM-DD',
          dateOutputFormat: 'YYYY-MM-DD',
          filterOptions: {
            enabled: true,
            placeholder: 'YYYY-MM-DD',
          },
        },
        {
          label: 'Days Active',
          field: 'transaction_days_active',
          type: 'number',
          filterOptions: {
            enabled: true,
            placeholder: 'Days Active…',
          },
          headerField: this.days_average,
        },
      ],
      rows: [],
      totalRecords: 0,
      paginationOptions: {
        enabled: true,
        mode: 'pages',
        perPageDropdown: [5, 10, 25, 50, 75, 100],
        nextLabel: '',
        prevLabel: '',
        rowsPerPageLabel: 'Records per Page',
        pageLabel: 'Page',
      },
      groupOptions: {
        enabled: true,
        headerPosition: 'bottom',
      },
      searchOptions: {
        enabled: true,
        placeholder: 'Search Completed Transactions',
      },
      serverParams: {
        columnFilters: {
        },
        sort: {
          field: '',
          type: '',
        },
        page: 1,
        perPage: 10,
      }
