### ISSUE TITLE
[Enhancement] th/tdClass should be able to take in a function

### ISSUE THREAD

**Issue by kn7007** [xaksis/vue-good-table#398]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.13.3

What browser?
Chrome
### Expected Behavior
I'm searching everywhere but not found solution. I want to format td class base on value itself, how can i do with vue good table.
Eg: if value is string, td have .blue class, if value is number, td have .red classs. Hope its clear enough.

**Comment by xaksis** [comment]
Hey @kn7007 , you can find an example right in the wiki: 
https://jsfiddle.net/aks9800/t6vt8q84/

closing.

**Comment by kn7007** [comment]
Thank you @xaksis, i thinking about it before but for me, it seem to be tricky because it not effected on td tag and we must style for span properly. Its more useful if you can add function style to tdClass like rowStyleClass.

**Comment by xaksis** [comment]
Hey @kn7007 good suggestion. I'll look into this.

**Comment by kn7007** [comment]
No problem, i'm waiting for the next version. Hope here from you soon

**Comment by xaksis** [comment]
@kn7007 done: 
https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#tdclass
