### ISSUE TITLE
how to add button each row

### ISSUE THREAD

**Issue by nacimgoura** [xaksis/vue-good-table#399]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.13.3

What browser?
All browser.

Thank you for your librarie. I would like to be able to add buttons to each line instead of selecting a line and clicking on the button. Like this image: 

![maxresdefault](https://user-images.githubusercontent.com/9990521/45222888-00157b80-b2b6-11e8-90b9-b25caf474207.jpg)

It's similar to this https://github.com/xaksis/vue-good-table/issues/323 but I don't want my buttons to be included in the variable row.

Thanks for your help !

**Comment by xaksis** [comment]
hey @nacimgoura you need to use a custom row template: 
documentation - https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template
in your case: 
```html
<template slot="table-row" slot-scope="props">
    <span v-if="props.column.field == 'action'">
      <button class="myButton" @click="doSomething(props.row)"></button>
    </span>
    <span v-else>
      {{props.formattedRow[props.column.field]}}
    </span>
  </template>
```

closing.

**Comment by nacimgoura** [comment]
Thanks :wink: I didn't understand correctly.
