### ISSUE TITLE
Anyway you could add a "date" field to column types to sort on?

### ISSUE THREAD

**Issue by bbennett36** [xaksis/vue-good-table#4]
I could probably hack something together or edit the current component but I'm sure you could do this more efficiently than me. Just let me know, thanks!

**Comment by bbennett36** [comment]
Guessing that's a no? Lol

**Comment by xaksis** [comment]
Don't sell yourself short friend! You would have done a fine job i'm sure. I used moment to parse/format dates. you can find the changes in version 1.4.0.

**Comment by xaksis** [comment]
Example usage: 
you can add a column like so: 
```
{
          label: 'Created On',
          field: 'createdAt',
          type: 'date',
          inputFormat: 'YYYYMMDD',
          outputFormat: 'MMM Do YY',
          filterable: false,
        },
```
and your date should look like '20160423' //depending on the format you specify in inputFormat.

**Comment by bbennett36** [comment]
Awesome! Thanks, I appreciate it!

**Comment by xaksis** [comment]
No problem! let me know if you have a problem using it.

**Comment by bbennett36** [comment]
Sounds good, ill do some testing tomorrow and report back with the results.

**Comment by bbennett36** [comment]
I got that working but it looked like there was an error in your sort method.

I had to change

```
  if (this.columns[this.sortColumn].field === 'date') {
                x = moment(x + '', this.columns[this.sortColumn].inputFormat);
                console.log(x)
              }
```

to 

```
  if (this.columns[this.sortColumn].type === 'date') {
                x = moment(x + '', this.columns[this.sortColumn].inputFormat);
                console.log(x)
              }
```  
  
Looks like you have it looking at the field name instead of the field type. My field name was "due_date" so it wasn't working at first and I had to go through and change that.

Other than that, it works great. Thanks again!

**Comment by xaksis** [comment]
whoops! good catch... 1 fix coming right up.

**Comment by xaksis** [comment]
v1.4.1

**Comment by xaksis** [comment]
@bbennett36 I just switched out the date parsing/formatting library. Please let me know if all your use cases still work fine? Thank you!

**Comment by bbennett36** [comment]
Are you able to use the 'defaultsortby' setting on a date field? Mine doesn''t seem to be working. The regular date sorting is still working perfect though.
