### ISSUE TITLE
Input in the template slot?

### ISSUE THREAD

**Issue by Troland** [xaksis/vue-good-table#40]
I have encounted a problem as below:

```
<vue-good-table
   :columns="fields"
    :rows="enrollmentPlans"
    styleClass="vuetable recruit__tb">
     <template slot="table-row" scope="props">
       <td width="15%"><input class="course__input" type="text" v-model="props.row.hour"></td>
     </template>
</vue-good-table>
```

The problem is that the v-model in the input elememen seems not work, while i change the input value, the data is unchanged.I'm confused, any help is apperiated.

**Comment by xaksis** [comment]
hey @Troland instead of using props values for your v-model, use: 
```javascirpt
v-model="enrollmentPlans[props.index].hour"
```
try it out and close the issue if it works.

**Comment by xaksis** [comment]
hey @Troland just released a fix in v1.9.3. You can now set model like so: 

```javascript
v-model="enrollmentPlans[props.row.originalIndex].hour"
```
closing. please re-open if you have more questions

**Comment by Troland** [comment]
Sorry, so late for response.While it throws error

```
Error in render function: "TypeError: Cannot read property 'price' of undefined
```
etc.

I'm using the latest`vue-good-table` version **1.14.1** and Vue version is **2.4.4**。

**Comment by xaksis** [comment]
@Troland can you show me your usage in jsfiddle. I have created a base one for you here: 

https://jsfiddle.net/aks9800/5pvh4r9p/2/

Thanks

**Comment by Troland** [comment]
@xaksis Thanks, i have updated the demo [https://jsfiddle.net/5pvh4r9p/3/](https://jsfiddle.net/5pvh4r9p/3/).You open the webDev tools and see the data is changed.That's the problem, still unresolved.

**Comment by Troland** [comment]
@xaksis I think i found the problem, i read the source code ,and found that i shoud take care of the property `paginated` to get the modified data.Thanks anyway, good work.

**Comment by xaksis** [comment]
@Troland can you explain that a bit? how is paginated related here? I looked into it a little bit didn't get a change to dig deep enough. Would appreciate seeing your working code.

**Comment by xaksis** [comment]
@Troland I was finally able to isolate and fix the issue. v1.14.3 has the fix that'll make this work for you. Here's a jsfiddle that should work. 
https://jsfiddle.net/aks9800/5pvh4r9p/4/
