### ISSUE TITLE
externalQuery and remote mode error with on-search parameters

### ISSUE THREAD

**Issue by sgjackman** [xaksis/vue-good-table#400]
### Issue Type
- [x] Bug

### Specs
Version 2.14.0
Chrome

### Expected Behavior
I want to use remote mode with an external query field and a custom @on-search event to load my data from the server.

### Actual Behaviour
Everything works, but it seems that this combination causes the @on-search event to fire early, so that the last character entered in the search field does not come through in the parameters. 

### Steps to Reproduce the Problem
I'm logging the parameters sent to @on-search method to the console, and the searchTerm is always one character short. You can see this in the jsfiddle below. Obviously this is a problem, because the server query is not what the user typed.

### jsfiddle
https://jsfiddle.net/57a2a4ce/582/

**Comment by xaksis** [comment]
Hey @sgjackman, thanks for pointing this out. it is now fixed in v2.14.1. your jsfiddle is working too now.
