### ISSUE TITLE
Single select on checkbox table

### ISSUE THREAD

**Issue by ivarzap** [xaksis/vue-good-table#402]
Is it possible to single select?
In case not, is there a workaround? It should:
1) Hide the SelectAll check box
2) Intercept the @on-selected-rows-change event and update the SelectedRows list.

### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?
2.14.0
What browser?
Chrome 69.0.3497.92

**Comment by sorayadragon** [comment]
See Issue #330

**Comment by xaksis** [comment]
@sorayadragon thanks for the reference ticket. @ivarzap you should be able to create a single select table following that plan. 

closing.

**Comment by luisdoniad** [comment]
See https://github.com/xaksis/vue-good-table/issues/330#issuecomment-1228403657
