### ISSUE TITLE
Total Records Counter

### ISSUE THREAD

**Issue by oflittlemother** [xaksis/vue-good-table#404]
- [x] Question
Is it possible to show a 'total records counter' in the pagination footer (or anywhere, ex. 'table actions')?
This counter should update with global search/column filters.

I think a visual reference to total records (regardless of grouping) is helpful, paired with pagination.

**Comment by xaksis** [comment]
tha pagination shows total records right between previous and next buttons... take a look here.
https://jsfiddle.net/aks9800/3wze61oj/
1-5 of 11 where 11 is the total number of rows. 

closing.

**Comment by axelitus** [comment]
But how about if I'm using `mode: 'pages'` and still want to display the total number of records?

I see there's a prop aptly named `totalRowCount`, but how can I access it in the `table-actions` slot to display it there?
