### ISSUE TITLE
html = true disappears when using slots

### ISSUE THREAD

**Issue by oflittlemother** [xaksis/vue-good-table#406]
- [x] Bug
I can't seem to output column rows with html when using slots.

### Specs
What version are you using?
2.14.1

What browser?
Chrome & Firefox

### Expected Behavior
What did you expect to happen?
The html to be interpreted.

### Actual Behavior
What actually happened?
Just appears as text.

### Steps to Reproduce the Problem
Use the table row slot.

```
<template slot="table-row" slot-scope="props">
  <span v-if="props.column.field == 'html_true_field'">
      {{ props.formattedRow.html_true_field }}
  </span>
  <span v-else>
      {{ props.formattedRow[props.column.field] }}
  </span>
</template>
```

**Comment by xaksis** [comment]
thanks @mbalandis. @oflittlemother you can't use declarative rendering `{{}}` for rendering html. This is more about vue than the plugin itself. Please refer to the link posted by @mbalandis.

closing.

**Comment by oflittlemother** [comment]
So true, I was so involved with Python backend yesterday that I completely forgot about this hahaha
Thank you @mbalandis & @xaksis for pointing this out so quickly :metal:
