### ISSUE TITLE
Unable to hide a column on specific screen sizes

### ISSUE THREAD

**Issue by TheFrankman** [xaksis/vue-good-table#409]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
Good Vue Table latest
Chrome (latest)

### Expected Behavior
Using bootstrap classes I'd like to be able to hide a column on mobile.

### Actual Behavior
TD still visible on search / filter row.

Perhaps the documentation isn't clear on this.

### Steps to Reproduce the Problem

With bootstrap 4 add these classes to thClass and tdClass column parameters : 

```
label : "File Size",
field : "file_size",
sortable : true,
thClass: "d-sm-none d-md-block",
tdClass: "d-sm-none d-md-block",
filterOptions: {
     enabled: true,
     placeholder: 'Enter file size ...',
     trigger: 'enter',
},
```

![image](https://user-images.githubusercontent.com/1402017/45880146-e8062780-bd9e-11e8-95df-d2611dfadc0d.png)

### jsfiddle
N/A

**Comment by xaksis** [comment]
same as #381 

closing (will be taken care of in 381)

**Comment by TheFrankman** [comment]
@xaksis - Not resolved by https://github.com/xaksis/vue-good-table/issues/381
Any chance of re-opening this ?

**Comment by TheFrankman** [comment]
@xaksis this was never resolved as far as I can tell.
Cam we please look back into this.
