### ISSUE TITLE
Date is in unixtime, possible to use inputFormat?

### ISSUE THREAD

**Issue by ssuess** [xaksis/vue-good-table#41]
Hi, my date column is output in unixtime (ie `1486231256 `) and I have tried both 'U' (php designation) and 'X' (moment.js designation), but both result in "invalid date" message. Is there a way to format these in my table?

**Comment by ssuess** [comment]
I found a fix myself by importing moment into Table.vue and changing line 214:

```
          // convert to date
          // return format(parse(v, column.inputFormat), column.outputFormat);
          return moment(v, column.inputFormat).format(column.outputFormat);
        }
```

**Comment by ssuess** [comment]
hm, i spoke too soon. The date formatting works, but the sorting is broken...

**Comment by xaksis** [comment]
hmm looks like date-fns doesn't like string for "x" and "X" formats... and i'm forcing conversion to string. I'll release a patch version with a fix shortly.

**Comment by ssuess** [comment]
Thanks!

**Comment by xaksis** [comment]
fixed in v1.10.0.

**Comment by ssuess** [comment]
Are you sure this is fixed? I have tried 'U', 'x', and 'X' all of which return a date in 1970:

```
{ label: 'Date',
          field: 'date',
          width: '15%',
          sort: true,
          type: 'date',
          inputFormat: 'X',
          outputFormat: 'MMM D, YYYY '
        }
```

**Comment by xaksis** [comment]
@ssuess make sure your date is not string...

**Comment by ssuess** [comment]
my json return from axios call to the API that I am using for the table source shows non quoted (ie like 1482166496 not "1482166496"), is there something else I need to do?

**Comment by xaksis** [comment]
https://date-fns.org/v1.28.5/docs/format
you'd need to multiply your datetime value with a 1000 to get it in the correct format for 'x' to work.

**Comment by ssuess** [comment]
I did as you suggested and it works, thanks.

**Comment by ssuess** [comment]
Except that sorting does not work on these formatted dates, is that to be expected?

**Comment by xaksis** [comment]
good catch, looks like there's a bug there... gonna create another issue to fix that.
