### ISSUE TITLE
Can column filter dropdown be autogenerated? - Revisited

### ISSUE THREAD

**Issue by ChaStPierre** [xaksis/vue-good-table#410]
- [x] Question

I see that you have already answered this question #[380](https://github.com/xaksis/vue-good-table/issues/380) however I'm also looking to autogenerate/prepopulate the dropdown based on the existing unique values of the columns. 

I've tried various ways to do this via the filterDropdownItems however it doesn't seem to support a function call to return the required array. 

Is there a workaround? I would also submit to extend the current filterDropdownItems functionality to support function call.

Thanks

**Comment by ChaStPierre** [comment]
Update
I finally got this going by directly accessing the proper $ref table column fields. Hope there a better workaround or simpler solutions. Rendering is slowed down when work with 100 records

 [https://codepen.io/cspx99/pen/pONXoO](https://codepen.io/cspx99/pen/pONXoO)
Thanks

**Comment by xaksis** [comment]
hey @ChaStPierre you don't need to use refs here... just set `column.filterOptions.filterDropdownItems` with whatever you want. Here's an example: 
https://jsfiddle.net/aks9800/u7n9x4vb/

closing.

**Comment by tripflex** [comment]
While I understand it would be easy to do this with custom code ... @xaksis but why not add this to library?

**Comment by bhargavjoshi** [comment]
I think this should be allowed by the library.

**Comment by andersstaleker** [comment]
I second that, this would be a really nice addition!

**Comment by mcandylab** [comment]
@ChaStPierre jquery? Seriously?
