### ISSUE TITLE
Support programmatic navigation

### ISSUE THREAD

**Issue by joshua-s** [xaksis/vue-good-table#414]
### Issue Type (delete the irrelevant ones) 
- [x] Enhancement Request

### Specs
What version are you using?
2.14.1

What browser?
Firefox

### Expected Behavior
I'd like to be able to navigate programmatically. I tried setting `paginationOptions.setCurrentPage` to no avail.

### Actual Behavior
This option only works when the table is first rendered.

**Comment by joshua-s** [comment]
```
<vue-good-table
<vue-good-table
  ...
  :pagination-options="ruleTable.pagination"
  ...
>

export default {
  name: 'MarkersView',
  props: ['rulesetID'],
  components: { VueGoodTable },
  
  data: function () {
    return {
      ruleTable: {
        pagination: {
          enabled: true,
          setCurrentPage: 1
        }
      }
    }
  },

  methods: {
    setCurrentPage: function (page)  {
      this.ruleTable.pagination.setCurrentPage = page
    }
  }
}
```

**Comment by xaksis** [comment]
heh... that's what i suspected... remember that vue cannot see your nested data change if you assign like that... 
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

use `$set` 

closing.

**Comment by joshua-s** [comment]
Hey, thanks for the advice. I tried:
`this.$set(this.ruleTable.pagination, 'setCurrentPage', 1)`

It didn't do anything.

**Comment by xaksis** [comment]
@joshua-s hmm... not sure what you're doing wrong. Here's a quick working example I created: 
https://jsfiddle.net/aks9800/m5rz4adh/

also, just because a property is defined in data doesn't automatically make it reactive. only primitive values are reactive by default. nested properties in arrays and objects are not. Read the link I provided above.
