### ISSUE TITLE
Manage loading state

### ISSUE THREAD

**Issue by ChaStPierre** [xaksis/vue-good-table#417]
- [x] Bug
- [x] Question

@xaksis in #356 you show how to manage loading.

I know its very simple to implement but I haven't had any success with it. Not sure if I'm doing something wrong or if its a bug.

Do you have a working example of this? 
thks

**Comment by xaksis** [comment]
@ChaStPierre what did you try? Can you post your code?

**Comment by ChaStPierre** [comment]
I've basically cut and pasted your code.  I would submit an example but sure how to simulate this in a sandbox.

```
<vue-good-table  
    ref="sr-table" 
    :columns="fields" 
    :isLoading="true" 
    :rows="filteredItems" 
    :pagination-options="{ 
         enabled: true, 
         perPage: 8 , 
         perPageDropdown: [8, 20, 40, 80, 100, 200, 400]
     }" 
    :sort-options="{ enabled: true }" 
     styleClass="vgt-table condensed striped">
  
    <template slot="loadingContent">
       <div> animated loading....</div>
    </template>
  </vue-good-table>

```

**Comment by xaksis** [comment]
ah... @ChaStPierre loading is only supported for when you're using the table in **remote mode**. `mode="remote"`

In other words, when filtering/paging etc shoots a request to the backend to get new page of data. You can read more about it here: 
https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html#why-remote-mode

closing.

**Comment by blurdylan** [comment]
In my case, I really need handle the **remote** mode on my own–Not using the built in mode.
It'll be nice for me to have a `loading` prop for which I could handle the logic in my SFC.

**Comment by bthyfos** [comment]
Hey guys is there a way to automatically reload after any event of the vue-good table..JUST LIKE  

`table.ajax().reload` in datatables
