### ISSUE TITLE
Update Documentation for Custom row

### ISSUE THREAD

**Issue by Dragonxero** [xaksis/vue-good-table#419]
### Custom Row Template
Update or clarify documentation with examples or more details for:
- customs columns containing HTML elements such as buttons
- custom columns for calculable data.

**Comment by xaksis** [comment]
@Dragonxero can you explain what exactly do you need clarified?
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template
The documentation has example code along with live output of the example code here. 

What do you mean by calculable data?

**Comment by Dragonxero** [comment]
For example a detail check-out tablet with quantity and price, for showing subtotal oficina each ítem type.

**Comment by xaksis** [comment]
@Dragonxero I don't know if I understand your usecase completely but looks like you're talking about grouped rows: https://xaksis.github.io/vue-good-table/guide/advanced/grouped-table.html#_5-what-if-you-wanted-to-add-a-total-count-in-summary-rows

also there's a recipe in the wiki showing exactly how to use this: 
https://jsfiddle.net/aks9800/0t820euy/

closing.
