### ISSUE TITLE
InitialSortBy and fieldFn?

### ISSUE THREAD

**Issue by StefanOosten** [xaksis/vue-good-table#421]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?
2.13
What browser?
Chrome

Is it possible to use the initialsortby on a field that uses a function to calculate a number and therefore has no field name?

Something like this doesnt seem to work:
   initialSortBy: {field: 'fieldFn', type: 'desc'}

**Comment by xaksis** [comment]
@StefanOosten yes, this should be fine given that functions are just strings when used as key. I recommend that you update to v2.16.0 though just so you can leverage the new sorting workflow.

closing.

**Comment by Herz3h** [comment]
I'm trying to achieve same thing in latest version, what should I specifiy in `field: ` when using `initialSortBy: { field: ? }` @xaksis

**Comment by mperumalswamy** [comment]
@Herz3h 
Not sure what field name should be there, but maybe a suggestion to have formatFn to do the dateTime replacements and keep the field name fixed.
