### ISSUE TITLE
Table Actions footer?

### ISSUE THREAD

**Issue by oflittlemother** [xaksis/vue-good-table#423]
- [x] Enhancement Request
- [x] Question
Can the table actions be set as a fixed footer, instead of a header?

### Specs
What version are you using?
Latest

What browser?
Chrome & Firefox

**Comment by oflittlemother** [comment]
These are currently tied to the Global Search area, so hacking the CSS would need JS to move it to the bottom.

**Comment by xaksis** [comment]
@oflittlemother any reason you can't just create a div below the table? Why does it need to be part of the library?

**Comment by oflittlemother** [comment]
I was asking something similar to #236, currently the table actions are on top, and the grouping summary row scrolls when using a max height. I was looking for a fixed footer option/template, if existed.

**Comment by oflittlemother** [comment]
Perhaps a toggle option for just the table actions, so you can position them top or bottom, or both (like pagination).

**Comment by xaksis** [comment]
hey @oflittlemother I have added a footer action slot in v2.14.7 that you can use: 
https://xaksis.github.io/vue-good-table/guide/configuration/#table-actions-footer-slot
