### ISSUE TITLE
Sorting should sort UTF-8 encoded values "naturally"

### ISSUE THREAD

**Issue by axelitus** [xaksis/vue-good-table#426]
### Issue Type (delete the irrelevant ones) 

- [ ] Bug
- [x] Enhancement Request
- [ ] Question

### Specs
What version are you using?
2.14.6

What browser?
Chrome 69.0.3497.100

### Expected Behavior
What did you expect to happen?
The values are sorted "naturally" even when UTF-8 encoded values are present:
- Abraham
- Ángel
- Bárbara
- Beto

### Actual Behavior
What actually happened?
The values are sorted ASCII encoded first, then UTF-8 encoded:
- Abraham
- Beto
- Bárbara
- Ángel

### Steps to Reproduce the Problem
Please detail your steps here

1. Create a vue-good-table.
1. Set some row values with UTF-8 encoded characters.
1. Sort by column containing UTF-8 encoded characters.

### jsfiddle
[vue-good-table UTF-8 sort issue](https://jsfiddle.net/axelitus/5xnrvyw6/)

**Comment by xaksis** [comment]
@axelitus thank you for pointing this out: The default sort in v2.14.7 now takes diacritic into account.
