### ISSUE TITLE
npm build not compile vue good css.

### ISSUE THREAD

**Issue by dsudaez** [xaksis/vue-good-table#428]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?

"vue-good-table": "^2.13.0",

What browser?

Chrome Versión 65.0.3325.181

### Expected Behavior

I am using VUE CLI for my application. So I need to deploy my app to aws. 

I use vue good table for some views. And  I need it shows ok.

### Actual Behavior

When I run npm run build and deploy the application, all styles are ok. Except for the  vue good table css base. I CAN WATCH this styles in the development mode, but not in the production mode.

*** How do I import this styles? I add it in my main js, just like this: 
      
       import 'vue-good-table/dist/vue-good-table.css'

Some one has to lead with the same problem?
Im not sure if the problem belongs to this plugins, but Im so confused becuse every other dependence style is building ok.

Please. I just need an opinion, o suggestions. I am from Argentina, sorry for my english!

**Comment by xaksis** [comment]
@dsudaez this should now be fixed in v2.14.7 thanks to @XertroV's PR
