### ISSUE TITLE
plugin to export

### ISSUE THREAD

**Issue by d-knafo** [xaksis/vue-good-table#429]
### Issue Type 
- Enhancement Request

### Specs
What version are you using?
2.14.6

an plugin for export (in Pdf, Excel, Csv, Print) is planned?

thanks for you work ! 
Great !

**Comment by xaksis** [comment]
Hi @d-knafo. This is currently not in the roadmap. You can read more about this topic in the following issue: 
https://github.com/xaksis/vue-good-table/issues/142

closing.
