### ISSUE TITLE
How do i make a selectable option?

### ISSUE THREAD

**Issue by ChadTaljaardt** [xaksis/vue-good-table#43]
I want to have the first field to have a checkbox for each row, and then when the user selects a checkbox it will add it to the data model, how would i do this?

**Comment by xaksis** [comment]
There are a few ways you can do it... the most straight forward way is to use your own template for the rows. 
- define your first column as empty {label: '', field: ''} (this will make space for checkbox)
- within the template, add first td as your checkbox 
```html
<td><input type="checkbox" @click="checkboxClicked(props.row)"/></td>
```
- then in your method `checkboxClicked` do whatever you want with the clicked row. 

closing... please re-open if you have more questions/concerns.

**Comment by focussing** [comment]
Hello! 

How can I get the row number, in stead of the row content?


Best regards, Met vriendelijke groet,
Raymond Verbruggen

FOCUSSING B.V.
Mispel 8
7621 WB Borne
Netherlands
+31 6 250 500 69 
mail@focussing.nl 
www.focussing.nl

**Comment by xaksis** [comment]
@focussing the readme contains this info, but here it is again: 

> In addition to prop.row that contains the row object, prop.index contains the index for the table display row. And prop.row.originalIndex contains the original row index. You can access the original row object by using row[prop.row.originalIndex].

**Comment by focussing** [comment]
Sorry to bother you; with “originalIndex” you mean the row index before any sorting and filtering?

Best regards, Met vriendelijke groet,
Raymond Verbruggen

FOCUSSING B.V.
Mispel 8
7621 WB Borne
Netherlands
+31 6 250 500 69 
mail@focussing.nl 
www.focussing.nl

**Comment by xaksis** [comment]
@focussing no problem. yes... originalIndex is the array index for the object without sorting/filtering/paging.. so if you do myRowArray[prop.row.originalIndex], this will give you the entire object for that row.

**Comment by focussing** [comment]
thanks!
working now on my 3rd project with your table :)


Best regards, Met vriendelijke groet,
Raymond Verbruggen

FOCUSSING B.V.
Mispel 8
7621 WB Borne
Netherlands
+31 6 250 500 69 
mail@focussing.nl 
www.focussing.nl

**Comment by ssuess** [comment]
Hi, I was able to add a row in the correct formatting, modifying your Table.vue with this:

 ```
       <tbody>
          <tr v-for="(row, index) in paginated" :class="onClick ? 'clickable' : ''" @click="click(row, index)">
            <th v-if="lineNumbers" class="line-numbers">{{ getCurrentIndex(index) }}</th>
            <slot name="table-row" :row="row" :index="index">
              <td v-for="(column, i) in columns" :class="getDataStyle(i, 'td')" v-if="!column.hidden">
                <span v-if="!column.html">{{ collectFormatted(row, column) }}</span>
                <span v-if="column.html" v-html="collect(row, column.field)"></span>
              </td><td><a class="primary" @click='editRow(props.row)'>edit</a></td>
            </slot>
          </tr>

        </tbody>
```
And then adding a method:

```
      editRow() {
        alert("edit:" + props.row);
      },
```

but when I click on my edit link, I get errors:

`[Vue warn]: Property or method "props" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.`
AND
`TypeError: undefined is not an object (evaluating '_vm.props.row')`

Any ideas why? Thanks!

**Comment by ssuess** [comment]
Nevermind, I just figured out I needed to include my template code in my own vue, not the base Table.vue file.
