### ISSUE TITLE
Clear style of other rows

### ISSUE THREAD

**Issue by sylvaincaillot** [xaksis/vue-good-table#432]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.14.6

What browser?
Chrome

### Question
Following my previous question #427 , I have updated my code as follow

```
<vue-good-table
          @on-row-dblclick="onRowDoubleClick"
          :rowStyleClass="rowStyleClassFn"
...     
      </vue-good-table>

    rowStyleClassFn(row) {
      return row.active ? 'VGT-row-red' : 'VGT-row';;
    },

    onRowDoubleClick(params) {
          this.$set(params.row, 'active', !params.row.active);       
    },

<style scoped>
  tr.VGT-row:hover {
    background-color: yellow;
  }
tr.VGT-row-red:hover {
    background-color: red;
  }
</style>
```

Not sure if it is the best solution but it works. 
However, when I click on a different row for example, I would like to set the active value to False except for the double-clicked one.
Is there a way to access all the rows and loop into them to set active to False for the non clicked ones or is there a much easier way of doing what I want to achieve?

Thank you
S.

**Comment by xaksis** [comment]
here's a working example: 
https://jsfiddle.net/aks9800/kv60L5rd/

closing.
