### ISSUE TITLE
Built-in Search Performance

### ISSUE THREAD

**Issue by j--w** [xaksis/vue-good-table#433]
### Issue Type
- [x] Bug

### Specs
What version are you using?
2.5.17
What browser?
Chrome 69.0.3497.100
### Expected Behavior
Global search should be performant with a moderately sized dataset(1000 rows, 6 columns)

### Actual Behavior
Search performance is notably laggy and this gets worse with larger search terms and bigger datasets.

Some quick troubleshooting by a colleague indicated that this seems to be slowing down at the diacriticless third party dependency of the search function

### Steps to Reproduce the Problem
1. Create a basic instance of vue-good-table with 1000 rows and 5 - 10 columns and try searching for a 10 character string within

I understand that this can be resolved with a custom search function but thought it might be worth raising this to see if there is any ideas for a solution for the global default search.

### jsfiddle
I created the example in codepen(created it before looking at issue template)
https://codepen.io/jiiim/pen/KGWLZe

An example of basic custom search that performs much better
https://codepen.io/jiiim/pen/vVxqwa

**Comment by xaksis** [comment]
looks like it is indeed caused by diacriticless comparison. What I can do is allow the ability to skip diactric comparison via a prop. you can now use the following in v2.15.0: 
https://xaksis.github.io/vue-good-table/guide/configuration/search-options.html#skipdiacritics
