### ISSUE TITLE
Trigger a default column sort based on saved user settings

### ISSUE THREAD

**Issue by ChaStPierre** [xaksis/vue-good-table#435]
- [x] Question

I'm currently saving users preferred column filters and sort view to local storage and now need to trigger the column sort on page load. How can I do this? I've tried to set the table @sort-options using the no success. 
self.$refs["sr-table"].sortOptions.initialSortBy.field
self.$refs["sr-table"].sortOptions.initialSortBy.type

I have however been able to get the sort going using the following but the column caret icons does not appears. 
self.$refs["sr-table"].sortType = "asc"
self.$refs["sr-table"].sortColumn = 1

Thanks

**Comment by xaksis** [comment]
@ChaStPierre don't forget the vue nested object caveat. You can't simply assign nested objects... you have to do it the vue way. also you don't have to do this via $ref. You can this.$set your sortOptions data in the component. 

closing.
