### ISSUE TITLE
Error missing loadash.clone dependency

### ISSUE THREAD

**Issue by axelitus** [xaksis/vue-good-table#437]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [ ] Enhancement Request
- [ ] Question

### Specs
What version are you using?
2.15.0

What browser?
Chrome (although the error is prior to web publish)

### Expected Behavior
What did you expect to happen?
No error is outputed when compiling assets (I'm using Laravel) with `npm run dev` or `npm run prod`

### Actual Behavior
What actually happened?
An error is outputed stating that loadash.clone dependency is not found:

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                    10:46:17

This dependency was not found:

* lodash.clone in ./node_modules/vue-good-table/dist/vue-good-table.es.js

To install it, you can run: npm install --save lodash.clone
```

### Steps to Reproduce the Problem
Please detail your steps here

1. Include vue-good-tables in app.js file with:
    ```
    import VueGoodTablePlugin from 'vue-good-table';

    Vue.use(VueGoodTablePlugin);
    ```
1. Compile assets with `npm run dev`

**Comment by lloydjatkinson** [comment]
Same issue here. The issue was introduced in 483a9a9.

**Comment by axelitus** [comment]
It seems that [vue-good-table.es.js](https://github.com/xaksis/vue-good-table/blob/91adb9dc4e9e016b9c81074d7d6b85b98fca65b8/dist/vue-good-table.es.js#L15) is still trying to import loadash.clone even when in version 2.15.0 was removed as a dependency.

Removing that line does the trick and the assets compile just fine.
![image](https://user-images.githubusercontent.com/732441/46880516-72760000-ce0e-11e8-9432-39fcf9cda4d2.png)

But the component does not work in the Web Browser and the Console shows this error:

```
Uncaught ReferenceError: clone is not defined
    at Object.diacritics.a (app.js:31946)
    at __webpack_require__ (app.js:20)
    at Object.<anonymous> (app.js:1647)
    at __webpack_require__ (app.js:20)
    at Object.defineProperty.value (app.js:1635)
    at __webpack_require__ (app.js:20)
    at Object.defineProperty.value (app.js:63)
    at app.js:66
```

**Comment by axelitus** [comment]
For the time being, as a workaround, I'm adding `"lodash.clone": "^4.5.0"` to my `packages.json` file to include the missing dependency, but this needs to be fixed.

**Comment by xaksis** [comment]
looking into this.

**Comment by xaksis** [comment]
weird... dist still shows version 2.14.7 I'll republish with a patch to see if it updates.

**Comment by owensource** [comment]
I'm getting this error as well, in addition to the errors in my issue, after updating the package (2.15.0).

**Comment by xaksis** [comment]
give npm a few minutes. 2.15.1 should be available with the fix: 
https://github.com/xaksis/vue-good-table/blob/master/dist/vue-good-table.es.js

closing.

**Comment by axelitus** [comment]
Removed the `lodash.clone` dependency, removed the `lodash.clone` folder from the `node_modules`, updated the npm modules and try to compile again and... it worked correctly!

Thanks for the awesome response time on this!
