### ISSUE TITLE
Filtered data

### ISSUE THREAD

**Issue by igorpocta** [xaksis/vue-good-table#438]
### Issue Type

- [x] Question

### Specs
What version are you using?
Latest

What browser? 
Chrome

### Qustion
Hello, is there any option to get filtered data from the parent component when I am using 
`<vue-good-table :columns="columns" :rows="rows" />`
Eg. I have total 500 records. When I use filter, I give back 180 records. I need to access to this set.

**Comment by xaksis** [comment]
@igorpocta you can get filtered rows by putting a ref on your table in the following way: 

```
<vue-good-table ref="myTable" ...>
</vue-good-table

this.$refs.myTable.filteredRows[0].children; // this would contain all rows that currently match filters. 
```

if you are using pagination and only want rows matching filters on the current page, use `paginated[0]` instead of `filteredRows[0]`

closing.

**Comment by hjelperne** [comment]
Hi, Is there any way to determine if there are any filters applied or not - at all?
this.$refs.myTable.filters.length > 0 (just pseudo example) or something similar?

**Comment by tassadar81** [comment]
@xaksis maybe in 2018 the method you described worked but now:

this.$refs.myTable.filteredRows[0].children;

return the unfiltered list and not the filtered ones; just tried with 2.21

**Comment by thomas-fortin** [comment]
Same issue than @tassadar81 for me.

I have the version 2.21.1, and the `this.$refs.myTable.filteredRows` does not exist anymore (returns `undefined`).

@xaksis is there a new way to easily access the filtered rows please ?

**Comment by chirag4396** [comment]
this.$refs.myTable.filteredRows[0].children; is returning rows which is before the filter and once again when I'm filtering any column it is returning the earlier filter values. so is there any other way to get the filtered rows after the filtration is done?

**Comment by PhamDinhKhoi** [comment]
> @xaksi this.$refs.myTable.filteredRows[0].children; is returning rows which is before the filter and once again when I'm filtering any column it is returning the earlier filter values. so is there any other way to get the filtered rows after the filtration is done?

Me too. Have you found a solution for this yet?
