### ISSUE TITLE
VGT save properties object (persisted state)

### ISSUE THREAD

**Issue by oflittlemother** [xaksis/vue-good-table#440]
### Issue Type
- [x] Enhancement Request

Could we have or does it exist already an output object of properties that change when using VGT?

For example:
- initial/normal click sort
- column filtering
- global search
- pagination
- etc

An accessible object of these that anyone could use to create a saved version of that VGT instance.

"A common requirement for web apps is to save the user customization and settings when interacting with your app, and then restore them once he/she logs back at some point in the future."

**Comment by xaksis** [comment]
hey @oflittlemother, I am not convinced that this needs to be part of the library. I do this for a bunch of my tables and it's relatively trivial to have an object store all the necessary data. Almost exactly as described in the [remote workflow](https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html) (look at the data object used there)

Making this part of the library would mean introducing a second interface for the same properties and then the added maintenance of keeping this interface in sync with all existing as well as new features when this can easily be done client side. 

closing.
