### ISSUE TITLE
Add new table style options

### ISSUE THREAD

**Issue by roberto910907** [xaksis/vue-good-table#441]
### Issue Type

- [x] Enhancement Request

### Specs
What version are you using?
2.15.3

### Expected Behavior
What did you expect to happen?

I think this table should have as many style options as vue boostrap table has. https://bootstrap-vue.js.org/docs/components/table/#table-style-options

I can research about how is this implemented in bootstrap-vue and open a PR to add some new style options.

@xaksis What do you think?

**Comment by xaksis** [comment]
hey @roberto910907! The whole idea behind separating the styles and offering it independently was to allow people to use whatever styles they want to use for the component. If people want to use bootstrap styles they can freely use it and ignore the styles that come with the table. They can also choose to use table styles as core and override everything with their own (bootstrap) styles. 

So, I don't think it's worth including all possible style options with the library itself. Closing.
