### ISSUE TITLE
Initial value of paginator perPageDropdown 

### ISSUE THREAD

**Issue by projct1** [xaksis/vue-good-table#443]
### Issue Type
- [x] Bug

### Specs
2.15.3

### What browser?
All

### Expected Behavior
Initial value of paginator perPageDropdown is 50

### Actual Behavior
Nothing to displayed http://skrinshoter.ru/s/201018/6A85Yi1o

### Steps to Reproduce the Problem
```html
<vue-good-table :pagination-options="paginator" />
```
```javascript
        data() {
            return {
                paginator: {
                    enabled: true,
                    perPageDropdown: [50, 100, 200, 300, 500, 1000]
                };
            }
        },
```
Just set `perPageDropdown` more then 10

**Comment by xaksis** [comment]
@projct1 thank you for reporting this. This is now fixed in v2.16

**Comment by projct1** [comment]
Still not working, even in v2.16 😕

**Comment by iAn-Pinto** [comment]
> Still not working, even in v2.16 😕

Not working for me too in v2.16
