### ISSUE TITLE
'on-column-filter' event emitted for every column that has an initial 'filterValue'

### ISSUE THREAD

**Issue by skray** [xaksis/vue-good-table#445]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?

Latest 2.15.3

What browser?

FF, Chrome

### Expected Behavior
What did you expect to happen?

I expected the 'on-column-filter' even to be emitted once when the table loads, with all of the values from any initial column filterValues.

### Actual Behavior
What actually happened?

'on-column-filter' is called once for each column that has an initial filterValue. 

We are using the 'on-column-filter' event to trigger an API call to fetch data, so having the event triggered for every filterValue passed in to the column definition means our API is called once for each filterValue. I'm not sure how to discern when the 'on-column-filter' events are coming from the initial table creation filterValues, and when they are coming from user provided input, so I can't find a clear way to not call the API on certain triggers of 'on-column-filter'.

### Steps to Reproduce the Problem
Please detail your steps here

1. Create a table with multiple columns, and have filterValues in at least two column definitions
1. Log the number of emitted 'on-column-filter' events

### jsfiddle

https://jsfiddle.net/e5pncx0u/

![2018-10-26 at 9 15 am](https://user-images.githubusercontent.com/3921751/47568673-b7fef680-d8ff-11e8-9f3a-d033a28fece8.png)

**Comment by xaksis** [comment]
@skray thank you for detailed report on this bug. v2.16 should fix this for you.

**Comment by jcasale** [comment]
I am on 2.16.0 and this behaviour exists for me still. I also pass in a default filter on a column and both `on-column-filter` and `on-per-page-change` are called when the component mounts.

**Comment by SevymolSebastian** [comment]
I am using 2.16.0. But still this behaviour exists.
