### ISSUE TITLE
How to replace filter input with datepicker ?

### ISSUE THREAD

**Issue by keen-on-design** [xaksis/vue-good-table#446]
### Issue Type
- [x] Question

### Specs
2.15.3

Is it possible to replace filter text input with a custom one (custom datepicker for example)? Can it be done using slots alike table-rows (it's actually very helpful).

**Comment by xaksis** [comment]
hey @keen-on-design it's not a straightforward implementation as there are many events associated with column filters that we need to take care of through the slots. However, people have customized the column filters using external libraries, for example: 
https://jsfiddle.net/aks9800/ekawt34s/

closing.
