### ISSUE TITLE
How can I customize the grid checkbox?

### ISSUE THREAD

**Issue by avlima** [xaksis/vue-good-table#447]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.12.2

What browser?
safari

1. I would like to know if it is possible to customize the style of the checkbox, leave it with a different color and size of the pattern. Is this possible?

**Comment by xaksis** [comment]
hey @avlima, You'd customize the style like any other checkbox. You can use `.vgt-checkbox-col input` selector for your style rules. 

closing.

**Comment by TargiX** [comment]
Maybe you don't know, but checkbox can't be customized directly, you need to add label, so this is really big problem as we can only use default ones.
