### ISSUE TITLE
How to get id in array selected checkbox

### ISSUE THREAD

**Issue by NandaRusfikri** [xaksis/vue-good-table#448]
**### How to Custom get id in array selected checkbox**

- [x] Question

### Specs
Latest 

What browser?
FF, Chrome
### Expected Behavior
Custom  get id in array after checkbox in selected
### Actual Behavior
this only show array selectedRow

### Steps to Reproduce the Problem
Please detail your steps here

<img width="353" alt="adaaaaaaaaaa" src="https://user-images.githubusercontent.com/23564348/47625525-57b6c180-db58-11e8-87be-8e02594de7ae.png">

**Comment by xaksis** [comment]
@NandaRusfikri I'm not sure what the question is here? You have access to all rows that are selected [via event](https://xaksis.github.io/vue-good-table/guide/configuration/table-events.html#on-selected-rows-change) `@on-selected-row-change` and via property `selectedRows`. How you extract `id` or any other property out of it, is up to you.

Closing. Let me know if I misunderstood your question and I'll re-open it.
