### ISSUE TITLE
lineNumbers should be line-numbers

### ISSUE THREAD

**Issue by enghelewa** [xaksis/vue-good-table#449]
`lineNumbers` should be `line-numbers`

- [x] Bug
- [ ] Enhancement Request
- [ ] Question

### Specs
What version are you using?
2.11.0

What browser?
google chrome 70

### Expected Behavior
line numbers options should work for any environment.

### Actual Behavior
When running npm production script line numbers disappear

**Comment by xaksis** [comment]
hey @enghelewa the property is actually camelcased. HTML attributes are case-insensitive, so when using non-string templates, camelCased prop names need to use their kebab-case (hyphen-delimited) equivalents. Read about it here: https://012.vuejs.org/api/options.html#props

closing.

**Comment by xaksis** [comment]
documentation updated.
