### ISSUE TITLE
Custom columns not rendering

### ISSUE THREAD

**Issue by unikitty37** [xaksis/vue-good-table#450]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.15.3

What browser?
Vivaldi 2.1.1337.36

### Expected Behavior
When I copy the example at https://xaksis.github.io/vue-good-table/guide/advanced/#adding-custom-columns, I should get "before" and "after" columns in the table.

### Actual Behavior
The columns do not render. There is no error message in the browser console.

### Steps to Reproduce the Problem
1. Create a template in the `table-row` slot.
1. Check for `props.column.field` being `before` or `after`.
1. Add content for those cases.

### jsfiddle
https://jsfiddle.net/y1w52n73/

**Comment by xaksis** [comment]
hey @unikitty37, you need to add the respective columns to the column def. Add the following to the column definition. 
```
      {
          label: 'Before',
          field: 'before'
        },
        {
          label: 'After',
          field: 'after'
        },
```

closing.
