### ISSUE TITLE
Targeting Dynamically Generated Column Filter Input to Render Popover/Dropdown

### ISSUE THREAD

**Issue by ow-en** [xaksis/vue-good-table#453]
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using?
2.14.1
What browser?
Chrome

@xaksis, I'm not sure if this is possible or practical, but I'll ask anyway. Right now, I've got a great table set up where I have Flatpickr's rendering from column filters. 

I'm able to render Flatpickr in column filters by selecting the filters based on their placeholders, see below:

```javascript
            addDatepickers() {
                let inputs = [
                    'input[placeholder="Filter X"]',
                    'input[placeholder="Filter Y"]',
                    'input[placeholder="Filter Z"]'
                ];
                inputs.forEach(function (input) {
                    flatPickr(input, {
                        dateFormat: "m-d-Y",
                        mode: "range",
                        allowInput: true
                    });
                });
            },
```

This is all working perfectly after some tweaking, which I detailed in #451. Now that I have the datepickers working, I'm trying to tackle a similar, but separate issue: I need to toggle a popover or dropdown from the column filter.

This popover or dropdown would contain two inputs, and a slider. The script for the popover/dropdown isn't the issue- the issue is targeting the column filter and passing in the popover/dropdown programatically.

I'm able to do this conveniently with Flatpickr, because it supports being called as a function. With a popover/dropdown, however, this isn't possible (that I know of). I need to create the popover/dropdown, and have it be rendered just below the column filter input on click.

Is this something that you would be able to help me with? Any ideas that might helpful? I'm kind of at a loss. I was considering targeting the existing filterOptions -> filterDropdownItems, and attempting to alter the html on it, but that seems tedious, if even possible.

As a last resort, I suppose I could trigger a modal on click from the column filter input, but that seems like a lot of overhead for a simple popover/dropdown.

Let me know what you think.

Thanks,

**Comment by owensource** [comment]
@xaksis  Any ideas on this? I've more or less given up on the possibility. The main issue is being able to target the dynamically generated column filters using html markup. Targeting them in a function is a problem I've already solved via the Flatpickr example above, but being able to pass in html markup is proving to be more difficult.

Targeting the column filters in a template slot came to mind, but I'm not sure of the specific prop syntax that would be required to target them in that manner.

**Comment by xaksis** [comment]
@owensource hey sorry for the delay in response, Owen. Unfortunately past few weeks have been really busy for me and I haven't had a chance to look through it. Filter slot seems to be a pretty requested feature so I plan to tackle that once I get a few free cycles. I'll keep you posted but I think it'll take me another week or so before I jump back into it.

**Comment by xaksis** [comment]
@ow-en could you please send me an email - shay@crayonbits.com
