### ISSUE TITLE
Selecting rows programatically

### ISSUE THREAD

**Issue by rubenriskpossible** [xaksis/vue-good-table#457]
### Selecting rows programatically

How can I selecting rows programatically?

### Specs
v2.15.3
Google Chrome

Hi there. 
I was wondering how to select rows programatically, I mean, is there any option like "select by id" or "by value"?

I have tried to do something like:

**Code Start**
this.$refs['my-table'].selectedRows = [ myObjects[0] ];
**Code End**

Where myObjects is a collection of data-rows binded to the table, but when I try that I receive this error message.

Computed property "selectedRows" was assigned to but it has no setter.
found in
---> <VueGoodTable>
       <VApp>
         <Root>

Thanks in advance.
Regards

**Comment by xaksis** [comment]
thanks @owensource 

@rubenriskpossible if you want to select rows programmatically, you can use the rows' internal property `vgtSelected`, just remember vue's reactivity caveat so you'd have to do something like: 

```
this.$set(this.rows[0], 'vgtSelected', true);
```
that will select the first row. 

closing. Let me know if you have an issue with this, I'll re-open.

**Comment by MohitDeshwal** [comment]
> thanks @owensource
> 
> @rubenriskpossible if you want to select rows programmatically, you can use the rows' internal property `vgtSelected`, just remember vue's reactivity caveat so you'd have to do something like:
> 
> ```
> this.$set(this.rows[0], 'vgtSelected', true);
> ```
> that will select the first row.
> 
> closing. Let me know if you have an issue with this, I'll re-open.

Doing this doesn't work. Nor it fires event nor updates selected rows.

**Comment by MohitDeshwal** [comment]
For Clarification purpose here is whats desired:

Flow -> User makes a selection -> we save selection data to database ;
   ThenIf  -> (User needs to change selection) we present table re initialised with same data/selected rows.

**Comment by MohitDeshwal** [comment]
Could anyone please respond? Is it possible?

**Comment by zacharytyhacz** [comment]
Yes I want to know to know how to do this as well also.

**Comment by xaksis** [comment]
@MohitDeshwal, @zacharytyhacz  
Not sure how you are trying this. But here's an example to show that this **does** work.
https://jsfiddle.net/aks9800/keLjcssn/

**Comment by seekingtheoptimal** [comment]
Not sure why, but if then I unselect with the checkbox manually, it gets stuck, and works again for the second click on the toggle only (even in your example). If I set it to false, and then true again in the same click handler, then it works as expected. Weird : )

**Comment by montemadjo** [comment]
Just for convenience, in vue2 you should write
`this.$set(this.rows[0], 'vgtSelected', true);`

but in vue3 it would be
`this.rows[0].vgtSelected = true;`
