### ISSUE TITLE
Server-side PHP Example

### ISSUE THREAD

**Issue by AndrianD** [xaksis/vue-good-table#458]
### Issue Type (delete the irrelevant ones) 
- [x] Question
Hello,
Super plugin, congratulations.
However I have a question, would you have an example of sending parameters to php server? Let me explain:
From the documentation here : https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html
I'm using Symfony 4 in back and VueJs in front

1. Currently we have the code on the client side, but I do not see any call to an url (something like: `axios.post` for example) to send the data to the server.

2. Also how must the server be configured (to receive the data and **process** correctly).
Thank you for your reply

### Specs
What version are you using?
VueJS 2.5.4

### What browser?
Google Chrome

**Comment by abishekrsrikaanth** [comment]
@AndrianD, I am new to this plugin as well. The plugin only offer you will the data that is ready to be sent to the server side. This is explained under the section [What we send to the server](https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html#prep-work).

How you send to the server is left to the developer and is not dependent on a specific plugin. 
The 3rd example on this section (https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html#provide-handlers-for-user-events) has the method `getItems` which invokes a method `getFromServer`. This is your own implementation of what you send to the server. 

This could definitely be abstracted within the plugin so the developer is only responsible of accepting the parameters on the server and provide the response back to the client transformed in the required format. I am hoping we can expect this in future releases. But I hope this answers your question.

**Comment by xaksis** [comment]
@abishekrsrikaanth thank you for your detailed answer! @AndrianD, I believe the above answers your question.

closing.
