### ISSUE TITLE
First and Last link for pagination

### ISSUE THREAD

**Issue by sweetsmile212** [xaksis/vue-good-table#461]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Specs
What version are you using?
2.X
What browser?
Chrome
### Expected Behavior
What did you expect to happen?
Need a first page and last page link for pagination. 
### Actual Behavior
What actually happened?
We currently have only next and previous links
### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
hey @sweetsmile212 support for this does not come out of the box with the plugin. However you can replace the provided pagination with your own using the custom pagination feature: 
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-pagination

closing.
