### ISSUE TITLE
Force horizontal scrolling 

### ISSUE THREAD

**Issue by fnrcum** [xaksis/vue-good-table#462]
### Issue Type 

- [x] Question

### Specs
Version 2.16.0?

What browser?
Chrome/Firefox/Edge

### Question
Is there a way to force horizontal scrolling to happen? For example I have a rather large table (14 columns) and I would like this table to scroll horizontally as a few of the columns have a lot of data in them. Problem is, I set the width attribute for them but it still forces the data to fit in the screen making those columns have a large height.

### Expected Behavior
Providing the number of columns at which horizontal scrolling should appear. For example after 5 columns (and depending on the container width) horizontal scrolling should occur in order to maintain the field width supplied

### Actual Behavior
Right now even if you supply a field width it will still try to shrink the other fields to make the field fit in the table width

### Steps to Reproduce the Problem
The steps are easy, Create a table with 10 columns and give each of those columns a width of 400px and give them enough data to see the words wrapping. You will see the fields are resized to somewhat of an equal amount

**Comment by xaksis** [comment]
hey @fnrcum this is not an issue with the plugin but the way html tables work. In general, the td widths are ignored if they exceed the table width. In the absense of table width, table width is derived from user agent (browser): 
https://www.w3.org/TR/html401/struct/tables.html#adef-width-TABLE

so the column width property will only be respected if the total width of td specified, is less than the width of the table. you can however hack this by putting an inline-block element inside the td with the specified width. 

closing.

**Comment by yogithesymbian** [comment]
can we add properties to get inline-block to make it easy on use?

**Comment by RushiJeavio** [comment]
@fnrcum @yogithesymbian Any luck?

**Comment by yogithesymbian** [comment]
> uld occur in order to maintain the field width supplied

no . i still on using boostrap table , good table is look likes antd table its awesome but i dont know how to make it inline-block  on vue good table because my client need to fast on deployment, so i dont deep custom to provide or offering other solution.
