### ISSUE TITLE
Search does not work with escaped characters

### ISSUE THREAD

**Issue by karakayasemi** [xaksis/vue-good-table#466]
Since only search term is escaped in this method https://github.com/xaksis/vue-good-table/blob/master/src/components/types/default.js#L9, search does not work with escaped characters. As a quick solution, we may escape rowVal too.

### Issue Type
- [x] Bug

### Specs
2.16.0

What browser?
Chrome, Firefox

### Expected Behavior
"192.168" search term should match with all entries in provided fiddle.

### Actual Behavior
Nothing matched

### jsfiddle
(https://jsfiddle.net/4L27s8cy/

**Comment by karakayasemi** [comment]
@xaksis why input needs to be escaped from special characters when searching? Can we simply remove the escaping part?

**Comment by xaksis** [comment]
@karakayasemi the diactric library crashes if the characters like '[' aren't escaped. I'll explore the latter option for fixing this.

**Comment by karakayasemi** [comment]
Alright, what about escaping `rowval` too?

**Comment by karakayasemi** [comment]
@xaksis Have you had time for the problem?

**Comment by xaksis** [comment]
@karakayasemi really sorry for the delay on this... this should now be fixed with v2.16.3
