### ISSUE TITLE
When deleting last row from table it doesn't refresh but works on reloading page

### ISSUE THREAD

**Issue by onlineexamsystem** [xaksis/vue-good-table#469]
<vue-good-table
                      :columns="columns"
                      :rows="rows"
                      :pagination-options="pagination_options"
                      :lineNumbers="true" >

                      <template slot="table-column" slot-scope="props">
                        <span class="vue-table-header">
                           {{props.column.label}}
                        </span>
                      </template>

                      <template slot="table-row" slot-scope="props">
                          <span v-if="props.column.field == 'actions'">
                             <button type="button" class="btn btn-sm btn-primary" aria-label="Left Align" @click="itemAction('expand-item',props.row)" ><i class="glyphicon glyphicon-plus-sign " aria-hidden="true"></i></button>
                             <button type="button" class="btn btn-sm btn-danger" aria-label="Left Align" @click="itemAction('delete-item',props.row)" ><i class="glyphicon glyphicon-trash " aria-hidden="true"></i></button>
                          </span>

                          <span v-else class="vue-table-rows">
                            {{props.formattedRow[props.column.field]}}
                          </span>
                      </template>

                      <div slot="table-actions">
                                <button type="button" class="btn btn-primary " @click="showFormModal = true" ><i class="glyphicon glyphicon-send"></i></button>
                                <button type="button" class="btn btn-primary " @click="RefreshData()" ><i class="glyphicon glyphicon-refresh"></i></button>
                      </div>

                  </vue-good-table>
<script>
import { VueGoodTable } from 'vue-good-table'
import Loading from 'vue-loading-overlay'
 import notificate  from '../functions/notifications'
 import {apiService} from '../functions/apiServices'

 export default {
data:function (){
    return{
      url :"http://localhost:8080/http://localhost:4443",
      pagination_options:{
        enabled:true,
        perPage:8,
        mode: 'pages'
      },
      columns: [
        {
          label:'id',
          field:'id',
          hidden:'true'
        },
        {
          label:'Author',
          field:'author',
        },
        {
          label:'Message Title',
          field:'title',
        },
        {
          label:'Actions',
          field:'actions'
        },
      ],
      rows:[],
      loading:false,
      showModal:false,
      showFormModal:false,
      title:'',
      author:'',
      desc:'',
      item:[],
    }
  },
  methods:{
    async RefreshData(){
      var apiUrl =  this.url+"/messages"
      this.loading = true
      var status =await apiService.Get(apiUrl)
      this.loading = false
      if(status.error){
          return this.notificate('App says',status.error,'error')
      }
      if (status.data == null){
        return this.notificate('App says','No data in table right now','warning')
      }
      this.rows = status.data

    },

    async deleteMessage(id){
      var data={
        id:id
      }
      var apiUrl = this.url+"/message"
      this.loading=true
      var status = await apiService.Delete(apiUrl,JSON.stringify(data));
      this.loading=false
      if(status.error){
            return this.notificate('App says',status.error,'error')
        }
        this.notificate('App says','Message Deleted','success')
    },

    async addMessage(){
      if(this.title ==""||this.author ==""||this.desc==""){
        return this.notificate('app says',"All Fields Are required",'error')
      }
        var data={
        'author':this.author,
        'title' : this.title,
        'body': this.desc
      }

      var apiUrl = this.url+"/message"
      this.showFormModal=false
      this.loading=true
      var status = await apiService.Post(apiUrl,JSON.stringify(data));
      this.loading=false
      if(status.error){
            return this.notificate('App says',status.error,'error')
        }
        await this.RefreshData()
        this.notificate('App says','Message Added','success')
    },

    async getDetail(id){
        var apiUrl = this.url+"/message/"+id
        this.loading = true
        var status =await apiService.Get(apiUrl)
        this.loading = false
        if(status.error){
            return this.notificate('App says',status.error,'error')
        }
        this.items = status.data
        this.showModal=true
    },
    async itemAction(action,data){
      if(action =="expand-item"){
          await this.getDetail(data.id)
      }else if (action =="delete-item") {
          await this.deleteMessage(data.id)
          await this.RefreshData()
      }
    }
  },
watch:{
      showFormModal:function(){
        if(this.showFormModal == false){
          this.title=''
          this.author=''
          this.desc =''
        }
      }
  },
  created(){
     this.RefreshData()
  },
components:{
    VueGoodTable,
    Loading,

  },
mixins:[notificate]
 }
</script>

Demo Available Here http://185.247.116.110:4443/

```

**Comment by xaksis** [comment]
@onlineexamsystem there's no way I'll be able to decipher what's going on by looking at your minimized code :/. Please re-format this ticket so people can read and understand it. Thanks. 

closing. Will re-open once the code format is updated.
