### ISSUE TITLE
Adjust position of column & data ?

### ISSUE THREAD

**Issue by bombkiml** [xaksis/vue-good-table#472]
### i can adjust position of column & data ?

- align left
- align center
- align right
etc.

Please let me know

**Comment by gemilaguinaldo** [comment]
would love this feature!

**Comment by xaksis** [comment]
@bombkiml @gemilaguinaldo usually the type of data determins the alignment automatically: 
numbers and dates are right alighed, text is left aligned. but... you can add any style class you want using `thClass` or `tdClass` properties of column: 
https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#tdclass

closing.

**Comment by bombkiml** [comment]
@xaksis  thank you so much, i like vue-good-table (^^)

**Comment by takagaki-bb** [comment]
@xaksis But what I expect is that only the specified class will be applied.
Actually, the existing class is left as it is as shown below, so the centering of `text-center` is not applied.
`vgt-left-align text-center`

**Comment by naufalfarras** [comment]
same situation with @takagaki-bb , i am using tailwind and i think the specificity caused this to happen, maybe we can make the class will be replaced whenever we define `thClass` or `tdClass`

**Comment by yakovcohen4** [comment]
I'm trying to align center of the table (head, body both), but I can't...
That is to contain the `vgt-left-center`.
@xaksis

**Comment by yogithesymbian** [comment]
its only to center of the top position how about the `middle` position ? i have height of td and the center only on top position.

**edit**: vertical center and horizontal center
