### ISSUE TITLE
How to access header's index in a grouped table

### ISSUE THREAD

**Issue by r00nscapenab** [xaksis/vue-good-table#478]
How do you access these header's indexes?
![image](https://user-images.githubusercontent.com/24377641/50327718-28567c80-052b-11e9-865a-f63a159cfbb6.png)

**Comment by ow-en** [comment]
To access a header row's index in a grouped table, it would simply be:

`rows[indexOfRow].label`

as shown in the snip below:

![image](https://user-images.githubusercontent.com/36556380/51882331-68332f80-2333-11e9-910f-6ed789059444.png)

While an official prop does not exist to date (to my knowledge), you should be able to access the header both statically and dynamically using the notation listed above. 

Closing for now.
