### ISSUE TITLE
per page dropdown incorrect when setting perPageDropdown array

### ISSUE THREAD

**Issue by corbosman** [xaksis/vue-good-table#479]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using? 2.16.0

What browser? Chrome

### Expected Behavior
What did you expect to happen?  

When I change the page size, the dropdown should reflect the new page size

### Actual Behavior
What actually happened?

The dropdown remains on the default page size. Important to note is that if I dont provide a perPageDropdown array, everything works fine.

### Steps to Reproduce the Problem
Please detail your steps here

1. Set your own perPageDropdown, this is what I have:

```
<vue-good-table
                        :isLoading="loading"
                        :columns="columns"
                        mode="remote"
                        @on-page-change="onPageChange"
                        @on-column-filter="onColumnFilter"
                        @on-per-page-change="onPerPageChange"
                        @on-search="onSearch"
                        :rows="rows"
                        :searchOptions="{
                            enabled: true,
                            placeholder: 'Zoeken',
                        }"
                        :sort-options="{ enabled: false }"
                        styleClass="table table-striped table-bordered"
                        ref="auditTable"
                        :totalRows="totalRecords"
                        :paginationOptions="{
                            enabled: true,
                            mode: 'records',
                            perPage: 20,
                            position: 'top',
                            perPageDropdown: [20, 50, 100, 200 ],
                            dropdownAllowAll: false,
                            nextLabel: 'volgende',
                            prevLabel: 'vorige',
                            rowsPerPageLabel: 'per pagina',
                            ofLabel: 'van',
                            pageLabel: 'page', // for 'pages' mode
                            allLabel: 'All',
                        }">
```

2. Change the dropdown from 20 to 50. Dropdown stays on 20, even though 50 records are now fetched. 

3. Cant change back to 20 because VGT thinks it's already selected.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by projct1** [comment]
Agree. Still not working. Here some issue, but closed =\ https://github.com/xaksis/vue-good-table/issues/443

**Comment by iAn-Pinto** [comment]
Issue not fixed in v2.16. Kindly help resolve.
> ### Issue Type (delete the irrelevant ones)
> * [x]  Bug
> 
> ### Specs
> What version are you using? 2.16.0
> 
> What browser? Chrome
> 
> ### Expected Behavior
> What did you expect to happen?
> 
> When I change the page size, the dropdown should reflect the new page size
> 
> ### Actual Behavior
> What actually happened?
> 
> The dropdown remains on the default page size. Important to note is that if I dont provide a perPageDropdown array, everything works fine.
> 
> ### Steps to Reproduce the Problem
> Please detail your steps here
> 
> 1. Set your own perPageDropdown, this is what I have:
> 
> ```
> <vue-good-table
>                         :isLoading="loading"
>                         :columns="columns"
>                         mode="remote"
>                         @on-page-change="onPageChange"
>                         @on-column-filter="onColumnFilter"
>                         @on-per-page-change="onPerPageChange"
>                         @on-search="onSearch"
>                         :rows="rows"
>                         :searchOptions="{
>                             enabled: true,
>                             placeholder: 'Zoeken',
>                         }"
>                         :sort-options="{ enabled: false }"
>                         styleClass="table table-striped table-bordered"
>                         ref="auditTable"
>                         :totalRows="totalRecords"
>                         :paginationOptions="{
>                             enabled: true,
>                             mode: 'records',
>                             perPage: 20,
>                             position: 'top',
>                             perPageDropdown: [20, 50, 100, 200 ],
>                             dropdownAllowAll: false,
>                             nextLabel: 'volgende',
>                             prevLabel: 'vorige',
>                             rowsPerPageLabel: 'per pagina',
>                             ofLabel: 'van',
>                             pageLabel: 'page', // for 'pages' mode
>                             allLabel: 'All',
>                         }">
> ```
> 1. Change the dropdown from 20 to 50. Dropdown stays on 20, even though 50 records are now fetched.
> 2. Cant change back to 20 because VGT thinks it's already selected.
> 
> ### jsfiddle
> If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
> you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by skegel13** [comment]
I am also seeing this issue. It is only happening when the perPageDropdown custom. When not set, everything works fine.

**Comment by xaksis** [comment]
sorry for the delay on this. v2.16.3 should have this fixed.

**Comment by DerekNMartin** [comment]
I'm still experiencing this issue on 2.18
