### ISSUE TITLE
For Reference: Table/Filter/Search Reset Button

### ISSUE THREAD

**Issue by ow-en** [xaksis/vue-good-table#486]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement

### Specs
What version are you using?
Latest 

### Expected Behavior
What did you expect to happen?
This issue posting is for reference only, but it might be worth merging - let me know if you'd like a pr. This came up in reference to a table global reset button. In #452 this is referenced, and the recommended course of actions is to add a ref to the table, and then use `this.$refs['someTable'].reset();`

### Actual Behavior
What actually happened?

On the surface, the above reset logic appears to work. However, there are some limitations. If you have already applied filters, a global search, or sort, and are using the table in remote mode, the serverParams object is not wiped out and reset by this reset button. I'm not sure how this works for client-side tables, but I think I may have had the same issue there, as well.

The UI itself appears to reset, but when loadItems() queries the server, existing filters, sorts, and searches are reapplied. This results in a 'reset' table, but with all of those parameters still in place.

I found a solution this issue, via a multi-step procedure:

In my existing resetTable() function, I added a couple of steps. First, I added a key to the table itself:

```js
                                <vue-good-table :isLoading="rows > 0 ? true : false"
                                                ref="someTable"
                                                mode="remote"
                                                :key="tableKey" // key added
                                                :columns="columns"
                                                :rows="rows"
                                                :pagination-options="paginationOptions"
                                                :totalRows="totalRecords"
                                                @on-selected-rows-change="selectionChanged"
                                                @on-page-change="onPageChange"
                                                @on-sort-change="onSortChange"
                                                @on-column-filter="onColumnFilter"
                                                @on-per-page-change="onPerPageChange"
                                                :selectOptions="{
                                                    enabled: true,
                                                    selectOnCheckboxOnly: true,
                                                    selectionText: 'rows selected',
                                                    clearSelectionText: 'clear',
                                                }"
                                                styleClass="vgt-table condensed striped"
                                                :search-options="{ searchFn: filterFunction }"
                                                @on-row-click="onRowClick"
                                                :rowStyleClass="rowStyleClassFn">
```

Then, within the reset function, I altered the table's key: `this.tableKey += 1`.

Within Vue, altering a component's key results in a full re-rendering of that component. This wipes the table's state and results in a full refresh. Despite this, I noticed that data's serverParams object still wasn't being successfully reset.

To wipe the state of serverParams, I added the following to the reset function:

`Object.assign(this.$data, this.$options.data());`

This is a function from Vue 1.x that completely wipes data's state. It may be overkill, but it was the only way I was able to successfully reset filters, sort, and search.

Finally, I added the existing recommended reset functionality `this.$refs['someTable'].reset();` for good measure, and then triggered loadItems();

When put together, my reset method reads as follows:

```js
            resetTable() {
                Object.assign(this.$data, this.$options.data());
                this.tableKey += 1;
                this.loadItems();
                this.$refs['someTable'].reset();
            },
```

Some of this may be overkill, but the above was the only way I was able to fully reset the component, the serverParam's object's state, and rerender/loadItems correctly. I've tested this fairly extensively, and it doesn't appear to have any side effects or unintended consequences that I've observed thus far.

For anyone else having issues fully resetting their table (particularly server-side remote mode tables) to zero, give this a shot.

@xaksis any input on this? Anything stick out to you on this as potentially causing issues down the line? 

Thanks,

**Comment by ow-en** [comment]
Update: the above reset function still works for my server-side tables in production, without observing any side-effects thus far. For my client-side tables, however, this appears to break a few things. As mentioned, the above may be overkill. If anyone is referencing this, I would recommend against using this reset if you are using a client-side table. Will update when I figure out a better solution.

**Comment by Erwan-source** [comment]
Thanks a lot, worked great!!
