### ISSUE TITLE
Remote Mode: on-sort-change triggers twice

### ISSUE THREAD

**Issue by projct1** [xaksis/vue-good-table#488]
### Issue Type
Bug

### Version
2.16

### Expected Behavior
One call

### Actual Behavior
`@on-sort-change="onSortChange"` runs twice
http://skrinshoter.ru/s/100119/60bJEIE6

**Comment by projct1** [comment]
Its obviously a bug...

**Comment by xaksis** [comment]
I was able to reproduce this. looking into it.

**Comment by xaksis** [comment]
Nvm, that was just my mistake. @ow-en the two vue events you see are just 1. child component telling parent component that something has happened. then parent component telling your component that something has happened. It's the same event propagating up. 

The remote table is behaving as it should. I created an example here to make sure the triggers are only firing once.
https://jsfiddle.net/aks9800/c83ektoj/
@projct1 My guess is something in your implementation is firing the request twice. 

closing.
