### ISSUE TITLE
Grouped table documentation example code does not fit with the result

### ISSUE THREAD

**Issue by louisdcoulombe** [xaksis/vue-good-table#490]
### Issue Type (delete the irrelevant ones) 
- [x] Enhancement Request

### Steps to Reproduce the Problem
Please detail your steps here

1. Go to https://xaksis.github.io/vue-good-table/guide/advanced/grouped-table.html
2. Compare the example code with the result. The data is not the same

![image](https://user-images.githubusercontent.com/3957903/51349260-d3971a80-1a72-11e9-92ec-6b2b185e2848.png)

**Comment by ow-en** [comment]
Thanks for pointing this out, @louisdcoulombe . The screenshots point to data referenced in the grouped-table recipe: https://github.com/xaksis/vue-good-table/wiki/Vue-good-table-Recipes-(vue-good-table-2.x)

The code samples, however, reference the sample data from the basic-table recipe. I'll fix this in the coming days. Closing.
