### ISSUE TITLE
Question: Is there a way to calculate from values in the row?

### ISSUE THREAD

**Issue by Tuginho** [xaksis/vue-good-table#494]
### Issue Type (delete the irrelevant ones) 

- [x] Question

--------------------------
In BootstrapVue Table we have the option to calculate values from the row in an other field.

>         {
          // A virtual column with custom formatter
          key: 'birthYear',
          label: 'Calculated Birth Year',
          formatter: (value, key, item) => {
            return (new Date()).getFullYear() - item.age
          }
        }

Do we have a same option here in vue-good-table?

**Comment by ow-en** [comment]
Hi, @Tuginho,

In the (docs)[https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#formatfn] you'll find that vue-good-table has a `formatFn` which does exactly (from what I can tell) what the above example appears to do.

Additionally, if you have a (grouped table)[https://xaksis.github.io/vue-good-table/guide/advanced/grouped-table.html#customizing-header-row], you can set up a summary row with a custom format function, as well.

Please let me know if I missed anything, but that should cover it. Also, please take a peek at the documentation before posting an issue. Thanks for using vgt!

Closing.
