### ISSUE TITLE
Issue sorting columns

### ISSUE THREAD

**Issue by atravotum** [xaksis/vue-good-table#495]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using: 2.16 (although I've also tried on 2.0 and 2.12)

What browser: Chrome (latest)

### Expected Behavior
What did you expect to happen: I expected the sort to happen

### Actual Behavior
What actually happened: When trying to sort certain tables by a numeric field it breaks the sort

### Steps to Reproduce the Problem
Just sort on a numeric field, and you will get an error about the following code 

function cook(d) {
      if (typeof d === 'undefined' || d === null) return '';
      return d.toLowerCase();
}

It seems that d is sometimes not a string so this fails. I have tried adding a type definition of number to my number columns and it makes no difference. If I update this code in the plugin though to do d = String(d), it works even on numeric fields since 1 converted into "1" will still come before "2" etc.

### jsfiddle
I work on proprietary software I don't think I could post the full solution here.

**Comment by ow-en** [comment]
Closing.

**Comment by atravotum** [comment]
Interesting, let me explore the different data types because that may actually be the case. Thank you for the quick return, love the plugin btw, saved us a ton of dev time.

**Comment by ow-en** [comment]
No problem - if you have any additional problems or questions about this issue, I can reopen - just let me know. Also, thanks for the kind words, @xaksis is creator, and I agree, it's an amazing plugin.

Best of luck,
