### ISSUE TITLE
ar

### ISSUE THREAD

**Issue by rahul1500** [xaksis/vue-good-table#497]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?

What browser?

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happened?

### Steps to Reproduce the Problem
Please detail your steps here

1.
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by ow-en** [comment]
@rahul1500 

I'm assuming this was posted accidentally? If you do have an issue, please edit and I can reopen.

Closing.
