### ISSUE TITLE
Checkboxes does not get updated on click or change in UI

### ISSUE THREAD

**Issue by rahul1500** [xaksis/vue-good-table#498]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.16.0
What browser?
Chrome Version 72.0.3626.96 

### Expected Behavior
What did you expect to happen?
Checkboxes in table should check and uncheck in UI

### Actual Behavior
What actually happened?
it is updating variabless and data but not showing in UI
<img width="400" alt="screenshot 2019-02-13 at 11 49 52 am" src="https://user-images.githubusercontent.com/30120415/52691003-86c93580-2f85-11e9-9116-06a5b4f63be1.png">

**Comment by ow-en** [comment]
Same as #496 (directly below this issue).

Closing.
