### ISSUE TITLE
dateInputFormat in milliseconds

### ISSUE THREAD

**Issue by karasalaravikumar** [xaksis/vue-good-table#503]
{
          label: 'Done On',
          field: 'completedDate',
          type: 'date',
          **dateInputFormat: 'ms',**
          dateOutputFormat: 'DD-MM-YYYY'
        }

- [x] Bug : it is always returning todays date
- [x] Is this the correct way of passing the milliseconds to input format ? because i am getting milliseconds as date from backend ?

### Specs
What version are you using?
2.16.0
What browser?
chrome
### Expected Behavior
What did you expect to happen?
milliseconds should be accepted as input format and return the expected date
### Actual Behavior
What actually happened?
it is giving me today's or current date
### Steps to Reproduce the Problem
Please detail your steps here

1. {
          label: 'Done On',
          field: 'completedDate',
          type: 'date',
          **dateInputFormat: 'ms',**
          dateOutputFormat: 'DD-MM-YYYY'
        }
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by ow-en** [comment]
@karasalaravikumar , in the future, please reference the [docs](https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#dateinputformat) before posting an issue.

As referenced in the documentation, a list of available DateInputFormat options is available [here](https://date-fns.org/v2.0.0-alpha.7/docs/parse). 

The correct DateInputFormat (per date-fns) for milliseconds would be `SSS`.

Closing.
