### ISSUE TITLE
Injecting unimported css

### ISSUE THREAD

**Issue by kreejzak** [xaksis/vue-good-table#505]
### Issue Type
- [x] Bug

### Specs
What version are you using?
^2.16.2

Hi, I am not importing the default css into my app.js file but the css is still injected into the head of html. 
So when I try to provide my own styles, it's overwritten by that injected css.

![screenshot 2019-02-24 at 02 08 43](https://user-images.githubusercontent.com/3613973/53293729-71e86f80-37d9-11e9-979f-e0db6df52a0e.png)
![screenshot 2019-02-24 at 02 10 07](https://user-images.githubusercontent.com/3613973/53293728-71e86f80-37d9-11e9-98e9-540635631ecf.png)

Thanks 
Paul

**Comment by xaksis** [comment]
@kreejzak thanks for pointing this out, will look into it. Looks like the rollup plugin got updated and the config file didn't work as expected.

**Comment by xaksis** [comment]
v2.16.3 released which the css extracted out.
