### ISSUE TITLE
Remote mode: Unable to sort in descending order

### ISSUE THREAD

**Issue by jazzlikethat** [xaksis/vue-good-table#506]
### Issue Type

- [x] Question

### Specs
What version are you using?
v2.16.0

What browser?
Google Chrome

### Expected Behavior
What did you expect to happen?
In case of remote mode, on clicking the column header, the table should fire an event with sort type as "asc". And, on clicking the column header the second time, the table should fire an event with sort type as "dsc" instead of "asc".

### Actual Behavior
What actually happened?
No matter how many times the column header is clicked, the table always fires an event with sort type as "asc".

**Comment by xaksis** [comment]
hey @jazzlikethat not sure how you're implementing this but plugin is working fine (asc/desc): 
example: https://jsfiddle.net/aks9800/c83ektoj/

closing. will re-open if you produce a fiddle showcasing the bug.
