### ISSUE TITLE
Can't change sorting direction on initialSortBy column

### ISSUE THREAD

**Issue by RobinBrons** [xaksis/vue-good-table#507]
### Issue Type

- [x] Bug

### Specs
What version are you using?
2.16.2

What browser?
Safari Version 12.0.2 (14606.3.4)

### Expected Behavior
What did you expect to happen?
To be able to sort the `initialSortBy` column

### Actual Behavior
What actually happened?
Nothing 😅 You have to sort another column before you can change the direction of the `initialSortBy` column

### Steps to Reproduce the Problem

1. just add `initialSortBy` (see [fiddle](https://jsfiddle.net/7gqn1bvh/))

### jsfiddle
https://jsfiddle.net/7gqn1bvh/

**Comment by xaksis** [comment]
ugh! that is indeed a bug! thanks for catching it @RobinBrons! will look into it.

**Comment by RobinBrons** [comment]
Eh I'm sorry... this isn't a bug. In my JSFiddle I have:

```js
:sort-options="{
  enabled: true,
  initialSortBy: {
    field: 'createdAt',
    sort: 'asc'
  }
}
```

this should obviously be:
```js
:sort-options="{
  enabled: true,
  initialSortBy: {
    field: 'createdAt',
    type: 'asc'
  }
}
```

As you can see in [this JSFiddle](https://jsfiddle.net/x15woLkp/), it works.

I'm sorry for the trouble. You were very quick to answer though, thanks for that!

**Comment by xaksis** [comment]
hah! the little things we miss :) You caught it before I spent time on it so 👍 !
