### ISSUE TITLE
Be able to sort on object property

### ISSUE THREAD

**Issue by RobinBrons** [xaksis/vue-good-table#508]
### Issue Type
- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?
2.16.2

What browser?
Safari Version 12.0.2 (14606.3.4)

### Expected Behavior
What did you expect to happen?
Be able to sort on an object property. Right know I have a column with a user object:
```js
{
  label: 'Username',
  field: 'user',
  filterable: true,
  clickable: true, // Custom value
},
```

An example of what `user` returns is:

```json
{
  "_id":"5c34fc232007756d25f3729e",
  "role":"admin",
  "active":true,
  "username":"Robin",
  "email":"example@example.com"
}
```

I of course want to be able to sort based on the `name` of a user. Maybe it would be nice if you could set a `sortValue`, like so:

```js
{
  label: 'Username',
  field: 'user',
  filterable: true,
  clickable: true, // Custom value
  sortable: true,
  sortValue: 'user.username'
},
```

Or is this something that can be achieved by using `sortFn`?

PS: Sorry for spam

**Comment by xaksis** [comment]
@RobinBrons yeah, for something like this you're better off providing your sort function. In fact, that's the very reason sortFn property exists, to cater to custom sorts where you want to sort by a different field etc. That's how I'd do it.

closing.
