### ISSUE TITLE
server side render

### ISSUE THREAD

**Issue by shaunc** [xaksis/vue-good-table#511]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [x] Enhancement Request

### Specs
What version are you using?
@2.16.2

What browser?
Chrome, but problem is Nuxt.

### Expected Behavior
What did you expect to happen?

Not being able to render on the server is ok.... I was prepared to wrap the table in [vue-no-ssr](https://github.com/egoist/vue-no-ssr). 

### Actual Behavior

However, the included code contains in module scope:
```js
var HEAD = document.head || document.getElementsByTagName('head')[0];
```
so I can't even `import` the component. Can this initialization be moved inside a function, so that
I can at least reference vue-good-table in my component?

**Comment by shaunc** [comment]
NB this is from `znck/vue-runtime-helpers` which is included from `rollup-plugin-vue` ... which is a dev dependency?? Its easy to fix the line above -- "HEAD" is used in exactly one place inside `addStyle()` and there one can easily precede the use of "HEAD" with `if (HEAD === UNDEFINED) { ...}` and initialize it if necessary.

However, before going off and submitting PRs to `znck/vue-runtime-helpers` and `rollup-plugin-vue` and then asking for a version bump, I wonder why this is getting bundled up anyway?

**Comment by xaksis** [comment]
2.16.3 should fix this... there was a mismatch of rollup to config and the bundled file weren't correct. Give it a try and we can open this up if the issue isn't resolved.

**Comment by shaunc** [comment]
Very good -- thanks!
