### ISSUE TITLE
Pagination doesn't work in remote mode

### ISSUE THREAD

**Issue by unixconky** [xaksis/vue-good-table#512]
Version: v2.16.2

In remote mode `total` props == `currentPerPage` instead of `totalRecords` so there is only one page visible, for example 1 - 30 of 30 and "Next" button is disabled. I do everything according to "remote mode" documentation. How can I fix it?

![zrzut ekranu z 2019-03-04 08-17-39](https://user-images.githubusercontent.com/25853438/53717167-8f5fae00-3e57-11e9-8a0d-8c15fe648cf5.png)

![zrzut ekranu z 2019-03-04 08-22-05](https://user-images.githubusercontent.com/25853438/53717170-925a9e80-3e57-11e9-940f-e0225f972df1.png)

**Comment by unixconky** [comment]
`totalRows` is undefined, I can't find the reason.
![zrzut ekranu z 2019-03-04 10-49-35](https://user-images.githubusercontent.com/25853438/53724992-634e2800-3e6b-11e9-8750-9c0ae27759f5.png)

**Comment by unixconky** [comment]
Ok, changed :totalRows="totalRecords" to :total-rows="totalRecords" and it's working fine.

**Comment by sam-g-roberts** [comment]
Docs need updating to reflect this, i spent a long time trying to figure this out

**Comment by xaksis** [comment]
Hey @sam-g-roberts  this isn't a library-specific issue, more of your specific Vue implementation. The props would work fine as they are in string templates but for HTML templates you need to use kebab case:
https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case
