### ISSUE TITLE
styles 

### ISSUE THREAD

**Issue by stevyrino** [xaksis/vue-good-table#515]
### Issue Type (delete the irrelevant ones) 

- [x] Question ---- Canned styles not being applied.

### Specs
"vue-good-table": "^2.16.3",
"vue": "latest",
 "vue-template-compiler": "latest",

What browser?
firefox 65.0.1
### Expected Behavior
Table to be styled

### Actual Behavior
Table is not styled.

### Steps to Reproduce the Problem
Just using vue-good-table in default mode.

![screenshot_2019-03-05_21-24-31](https://user-images.githubusercontent.com/16284559/53858798-51b27080-3f90-11e9-8a48-4fd4414b38f0.png)

**Comment by xaksis** [comment]
hey @stevyrino! could you show me how you're importing it? did you import the styles? 
https://xaksis.github.io/vue-good-table/guide/

**Comment by stevyrino** [comment]
Yes .... I wasn't importing the styles correctly ... cheers.
