### ISSUE TITLE
Is "Checkbox Table with Pagination" working in remote mode?

### ISSUE THREAD

**Issue by unixconky** [xaksis/vue-good-table#516]
I'm trying to use this: https://jsfiddle.net/aks9800/dzka5qz0/ but in remote mode and when I click "Next page" all selected rows are cleared.

**Comment by xaksis** [comment]
hey @unixconky in remote mode, table has no concept of the page before and the page after, you'd have to maintain the selection/state yourself and set them programmatically every time a new page loads. you can use the internal row property `vgtSelected` to mark a row selected.

closing.
