### ISSUE TITLE
Table footer icw grouped table

### ISSUE THREAD

**Issue by p0psicles** [xaksis/vue-good-table#518]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?
2.16.3

What browser?
chrome (latest stable)

### Expected Behavior
Is it possible to have per table group a footer added?
Preferably with a function, so I can display some calculated values based on the grouped table displayed?

### Actual Behavior
What actually happened?

**Comment by xaksis** [comment]
sure is! 
jsfiddble example: https://jsfiddle.net/aks9800/0t820euy/
documentation: https://xaksis.github.io/vue-good-table/guide/advanced/grouped-table.html#_5-what-if-you-wanted-to-add-a-total-count-in-summary-rows

closing. Let me know if this isn't what you want.

**Comment by p0psicles** [comment]
Yes more or less. I'm already using the header-row to group a show's seasons.
I'm using this slot for that:
```<template slot="table-header-row" slot-scope="props" :class="'my-class'"></..>```
But i'd like to also have a footer, that shows some summary info. Like the amount of episodes that season has. Is there a second slot available for this?

**Comment by xaksis** [comment]
So, you can either use the header or the summary row. Currently the table doesn't support having both. You can have a summary row with the sum count like the jsfiddle example though.

**Comment by p0psicles** [comment]
okay, so what I like to achieve is this:
![image](https://user-images.githubusercontent.com/1331394/54237145-96508580-4515-11e9-849d-d388798d116b.png)

In red, should show some summary about the episodes (red), But I also need the headers (seasons in yellow).

Is it possible to introduce a new slot for this? Like table-footer-row? If possible, I can dig into your code, and PR it?

**Comment by xaksis** [comment]
yeah, I understand this isn't currently possible with the table. Please go ahead and submit a PR, I'd be happy to review.

**Comment by p0psicles** [comment]
I've submitted a PR. It's not much code to review?

**Comment by p0psicles** [comment]
@xaksis I don't mind investing some of my time into your project. But it would be nice if you gave some feedback on the pr's?

**Comment by xaksis** [comment]
@p0psicles, I'm sorry but I'm having an exceptionally busy week. I'll review it when I get some free cycles. I appreciate your patience.

**Comment by p0psicles** [comment]
Long week. But I understand. Life can take prio. In the mean time I've added a number of features in my fork.
Let me know when you get back on track. To see if and how certain features can make its way in.
