### ISSUE TITLE
How to add additional button next to "clear" link (checkbox table)

### ISSUE THREAD

**Issue by unixconky** [xaksis/vue-good-table#519]
How to add an additional button next to the "clear" link (checkbox table)? I know that there is "action" slot but I need this on the left side.

![Zrzut ekranu z 2019-03-12 08-24-22](https://user-images.githubusercontent.com/25853438/54181946-6fa43780-44a0-11e9-9935-77b08875bbb7.png)

**Comment by xaksis** [comment]
hey @unixconky, you can use the selection-row-actions slot: 
https://xaksis.github.io/vue-good-table/guide/advanced/checkbox-table.html#selected-row-action-slot

closing.

**Comment by connorshea** [comment]
Would you be open to making a slot that can be used to customize the entire `vgt-selection-info-row` element? I'd like to put the "2 rows selected" text and "clear" button in a `span` or `p` so I can more easily style it :)

**Comment by seekingtheoptimal** [comment]
how to bind click event in selected-row-action-slot? it does not have any props
