### ISSUE TITLE
Zero (0) values not displayed

### ISSUE THREAD

**Issue by richardpenman** [xaksis/vue-good-table#52]
I noticed a value of 0 (zero) and leaving a value out will both result in a blank cell. For example with these rows:

    rows: [
        {id:1, name:"John",score: 0},
        {id:7, name:"Jane"},
      ],

I want to distinguish these two cases - is it possible to force displaying the 0 (zero)?

**Comment by richardpenman** [comment]
I noticed setting `html: 'true'` in the columns definition will display the zero values - is that the proper way to achieve this?

**Comment by xaksis** [comment]
@richardpenman 0 should definitely be displayed... you have indeed discovered a bug. I'll update this later today.

**Comment by xaksis** [comment]
fixed in 1.10.1. 0 should now be displayed
