### ISSUE TITLE
Different FormatFn on same field

### ISSUE THREAD

**Issue by vinke1996** [xaksis/vue-good-table#520]
### Issue Type (delete the irrelevant ones) 
- [x] Bug

### Specs
What 
version are you using?
2.16.2

What browser?
chrome (latest stable)

I have 3 columns for my table. these 3 columns has the same field (which is an array) but all 3 columns has a different FormatFn.
If I show one of these columns at a time everything worked fine. But if I put the 3 columns after each other all the columns shows the value from the last FormatFn.

Below you can see the 3 different columns I created
<img width="250" alt="Screenshot 2019-03-12 at 10 53 54" src="https://user-images.githubusercontent.com/1562165/54191094-7e491980-44b5-11e9-88c9-9cc08593f009.png">

The next images shows the output in the table. In this case each FormatFn function returns only the string 'Distance', 'Amount' or 'Tip'

<img width="247" alt="Screenshot 2019-03-12 at 10 55 27" src="https://user-images.githubusercontent.com/1562165/54191176-ab95c780-44b5-11e9-9b68-87b2043c55b7.png">
As you can see all three columns show TIP as value.

If I removed the Amount & Tip columns from my code and only leave the Distance one. I get the value I wanted.
<img width="94" alt="Screenshot 2019-03-12 at 10 55 51" src="https://user-images.githubusercontent.com/1562165/54191261-daac3900-44b5-11e9-827a-81f310f7c708.png">

**Comment by xaksis** [comment]
Hey @vinke1996, can you show me the full code here? I suspect your `formatFn: getDistance` should actually be `formatFn: this.getDistance`.

**Comment by xaksis** [comment]
going to close this. Let me know if you still have this issue  after you've corrected the functions
