### ISSUE TITLE
Is there a way to make selected rows as one row per selection only

### ISSUE THREAD

**Issue by 181** [xaksis/vue-good-table#525]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?

What browser?

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happened?

### Steps to Reproduce the Problem
Please detail your steps here

1.
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
hey @181, using the format provided helps me get more details for your request. In this case for example... I don't know if you mean select 1 checkbox at a time? or fire an event when you click on the row. the latter is certainly possible: 
https://xaksis.github.io/vue-good-table/guide/configuration/table-events.html#on-row-click

closing.
