### ISSUE TITLE
set RowsData programatically

### ISSUE THREAD

**Issue by zfrk** [xaksis/vue-good-table#528]
### Issue Type (delete the irrelevant ones) 

- [x] Question

I have two different table on my page and I want set Rows data programmatically to the second table upto first one selections. How can I do it ?

Thanks,

Zafer

**Comment by xaksis** [comment]
@zfrk These kinds of questions are better suited for stackoverflow. But i'll get you started. You can use the @on-click event from the first table to populate rows for the second table. 

closing.
