### ISSUE TITLE
Scrollbars appear in the drop-down box for adding operations to the table

### ISSUE THREAD

**Issue by friend-ship** [xaksis/vue-good-table#529]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?

What browser?

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happened?

### Steps to Reproduce the Problem
Please detail your steps here

1.
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
@friend-ship There simply isn't enough information in this ticket for me to investigate. I'm going to close this. Please create another ticket preferably with a fiddle so I can look into it.
