### ISSUE TITLE
How can I add click link on every cell of a specific column ?

### ISSUE THREAD

**Issue by Aylay** [xaksis/vue-good-table#532]
### Issue Type
- [x] Question

### Specs
What version are you using? 2.16.3

### Question
Hello

I would like to add a click to a edition page in the first cell ?
I don't know how to do it.

Thank ;)

**Comment by xaksis** [comment]
hey @Aylay you can use the `@on-cell-click` event: 
https://xaksis.github.io/vue-good-table/guide/configuration/table-events.html#on-cell-click
can use the`params.column` property to figure out which column is emitting the click.

closing.
