### ISSUE TITLE
Caret is not set using initialSortBy with remote table

### ISSUE THREAD

**Issue by axelitus** [xaksis/vue-good-table#533]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.16.3

What browser?
Chrome version 73.0.3683.86

### Expected Behavior
What did you expect to happen?
When using an initialSortBy value (either single or multiple) I would expect that the caret will be placed showing the sorted column.

### Actual Behavior
What actually happened?
No caret is being shown on the headers.

### Steps to Reproduce the Problem
Please detail your steps here

1. Setup a table with remote behavior
1. Set an initialSortBy value
1. Load the page

I'm not really sure how the initial setup is made with remote tables, I think its a bit tricky if you want to optimize the initial calls to the remote (and not trigger calls for every initial configuration) but also if no events are being triggered (when setting the initial options) how are we supposed to prepare the call to the remote server?

**Comment by xaksis** [comment]
hey @axelitus, I have a feeling you're using this incorrectly as it is working fine in the example here: 
https://jsfiddle.net/aks9800/c83ektoj/

For initial setup, depending on what those initial values are (whether they are being set directly on the table or something that you're just holding in your payload) it might trigger the initial call more than once. You can and should add logic to debounce the calls from the table just like any widget that has the potential of firing events too quickly. As for initialSortBy value, it seems to be working fine.

closing.

**Comment by eric-naguras** [comment]
The caret is shown indeed when you use initialSortBy in the sort options in the table definition 
`<vue-good-table></vue-good-table`>

It does NOT work if you put the initial sort in the data script section in 
`serverParams:{}`
The table is sorted correctly but the column does not show the caret.
