### ISSUE TITLE
Pagination - Rows per page resets on row selection

### ISSUE THREAD

**Issue by pwalker27** [xaksis/vue-good-table#534]
### Issue Type

- [x] Bug

### Specs
2.16.3
Chrome/IE 11

### Expected Behavior
I have a checkbox table with pagination enabled. I expect that if I change my rows per page, then make a table selection, the rows per page will remain the same.

### Actual Behavior
If I change the rows per page from the default, then as soon as I select a row on the table the rows per page reverts back to the default (actual row count doesn't change) 

### Steps to Reproduce the Problem
1. Change Rows per page to 4
2. Select an item from the table
3. Rows per page will now show 1 again and still display 4 items.

If I remove the printout of the testArray, everything works fine.

### jsfiddle
https://jsfiddle.net/pagxq2vt/2/

**Comment by soobax** [comment]
I have the same issue. I have a select dropdown in Table Action Slot. Every time I change the select option, the 'Rows per page' resets to default.

**Comment by xaksis** [comment]
ooh! clearly a bug. Will take a look. Thanks for bringing this up @soobax @pwalker27
