### ISSUE TITLE
on more one Custom Row Template make other cells null (solved)

### ISSUE THREAD

**Issue by marmulack** [xaksis/vue-good-table#537]
### Issue Type (delete the irrelevant ones) 
  Solved
- [] Bug

### Specs
What version are you using?
^2.16.3
What browser?
mozilla
### Expected Behavior
What did you expect to happen?
change 2 column custumize
### Actual Behavior
What actually happened?
2 columns was changed but other columns make null
### Steps to Reproduce the Problem
Please detail your steps here

that is my source as a vue component. i loaded row data from database and worked true, but when i try to make actions as Custom Row Template from your doc other columns changed to empty.

```
> <vue-good-table title="personal Manegment" :columns="columns" :rows="rows"
>                 :lineNumbers="true"
>                 >
>             <template slot="table-row" slot-scope="props">
>                 <span v-if="props.column.field == 'state'">
>                     <span v-if="props.row.state == 1">
>                         <h5><span class="badge badge-success">active</span></h5>
>                     </span>
>                     <span v-else>
>                         <h5><span class="badge badge-danger">deavtive</span></h5>
>                     </span>
>                 </span>
>                 <span v-if="props.column.field == 'actions'">
>                     <span v-if="props.row.actions == null"> #err
>                         <button class="btn btn-warning" @click.prevent="$modals.myModal.$show()">edit</button>
>                         <button class="btn btn-danger" @click.prevent="$modals.myModal.$show()">delete</button>
>                     </span>
>                 </span>
>             </template>
>             <div slot="table-actions">
>                 <button class="btn btn-info" @click.prevent="$modals.myModal.$show()">new</button>
>             </div>
>         </vue-good-table>
```
so when remove `#err` line tag that's worked true and i need to have actions column.

solved ==> just need to change `v-if` to `v-else-if`

**Comment by xaksis** [comment]
yeah as you probably figured out, you seem to be missing the part about rendering the rest of the columns: 
```
<span v-else>
      {{props.formattedRow[props.column.field]}}
    </span>
```
closing.
