### ISSUE TITLE
console Error on load and worked vue-good-table true

### ISSUE THREAD

**Issue by marmulack** [xaksis/vue-good-table#538]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
^2.16.3
What browser?
firefox quantom 66.0
### Steps to Reproduce the Problem

on my source vue-good-table worked true but on browser console i have below error:
![vgt](https://user-images.githubusercontent.com/15891911/56081598-43276680-5e24-11e9-8ce7-bc1ef2e7ad7a.jpg)
and this is my source:

> <template>
    <div class="app-container">
        <vue-good-table
                title="Personal Manager"
                :columns="columns"
                :rows="rows"
                :lineNumbers="true"
                :rtl="true">
   </div>
</template>

> <script>

    import { VueGoodTable } from 'vue-good-table';
    import 'vue-good-table/dist/vue-good-table.css';
    import { getPersonal } from '@/api/table';
    export default {
      components: {
        VueGoodTable,
      },
      data(){ ... },
> </script>

All source worked correctly But this Error say <vue-good-table> tag is invalid. and i think the problem is for Babel auto router in my project are using.

**Comment by xaksis** [comment]
This error usually happens if rows is not an array, in case of remote table, perhaps you are trying to render the table before the rows object exists. putting a `v-if="rows && rows.length"` on the table should fix this. 

closing.
