### ISSUE TITLE
Header of HTML-enabled column should render using v-html

### ISSUE THREAD

**Issue by ton212** [xaksis/vue-good-table#540]
### Issue Type (delete the irrelevant ones) 
- [x] Enhancement Request

### Specs
What version are you using?
2.16.3

What browser?
Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)

### Expected Behavior
What did you expect to happen?
Header cell of HTML-enabled column should be render using `v-html`.

### Actual Behavior
What actually happened?
The header cell is render as normal text without HTML parsing and styling.

### Steps to Reproduce the Problem
Please detail your steps here

1. Set column `html` property to `true`
2. Pass HTML string in `label` property

### jsfiddle
https://jsfiddle.net/rn9s7ye6/
Please see the "name" column, the `<sup>3</sup>` was not rendered correctly.

**Comment by xaksis** [comment]
Hey @ton212 for customized headers please use the respective slots: 
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-headers

closing.
