### ISSUE TITLE
Custom loading classes

### ISSUE THREAD

**Issue by PrimozRome** [xaksis/vue-good-table#543]
- [x] Enhancement Request

### Expected Behavior

Currently in the remote mode the class `is-loading` is applied to the wrapper element `<div class="vgt-inner-wrap is-loading">` and this element is appended to the HTML template:

```
<span class="vgt-loading__content">
    Loading...
</span>
```

I would like to see ability to customise which loading CSS classes are added to the wrapper. I have my own CSS loading classes that grey out and add spinner to the containers and would love to use those. Also need the ability to disable the appended "loading" span element.

<img width="1405" alt="Screenshot 2019-04-26 at 11 30 12" src="https://user-images.githubusercontent.com/1180467/56798238-afd43500-6816-11e9-9d6d-03d3206a1113.png">

**Comment by PrimozRome** [comment]
I have been able to achieve this with

`<template slot="loadingContent">&nbsp;</template>`

and overriding `is-loading` CSS class

**Comment by xaksis** [comment]
@PrimozRome glad you were able to solve this. closing.
