### ISSUE TITLE
vue good tables don't work on IE10,at version 2.16.3

### ISSUE THREAD

**Issue by mimanghuilang** [xaksis/vue-good-table#544]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.16.3

What browser?
ie

### Expected Behavior
work normal on ie10

### Actual Behavior
don't work on ie10

### Steps to Reproduce the Problem
Please detail your steps here

1.i follow the Instructions of https://xaksis.github.io/vue-good-table/guide/#installation，it‘s didn't work on ie10，i'm use vue-cli3

**Comment by mimanghuilang** [comment]
just like issue #153

**Comment by xaksis** [comment]
hey @mimanghuilang, I've tested it in both actual IE 10 and IE 10 emulator. It is working in both. I'm going to close this til I see some errors, more details or more people complaining about the same.
