### ISSUE TITLE
Searching/Sorting on long strings is render blocking (Slow Performance)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [xaksis/vue-good-table#545]
* **Issue Type:** Bug
* **Version:** 2.16.4
* **Browser:** Chrome
* **Issue:** When sorting on long strings the UI thread locks up.

**Steps to reproduce:**

1. Go to: https://jsfiddle.net/phtdf4cn/2
1. Click on the "Increase Count" button
   * Count should go up to `1` instantly
1. Sort on Name or Description, then click on the "Increase Count" button
   * There is a long delay before the count goes up

This goes even slower when you have a bunch of custom `<template>`'s to handle different scenarios.

Chrome's performance tab shows the slowness comes during the comparison of every item in the table.

![Chrome dev tools performance graph showing "compare"](https://user-images.githubusercontent.com/4629794/57051944-13fd5b80-6c52-11e9-94b7-bc9478216cd3.png)

**Comment by TheJaredWilcurt** [comment]
* Talk on performance in Vue: https://www.youtube.com/watch?v=5B66qer8cZo
* Slides from talk: https://slides.com/akryum/vueconfus-2019#1
* Repo from talk: https://github.com/Akryum/vue-9-perf-secrets

**Comment by senfomat** [comment]
@TheJaredWilcurt since a performance enhancing patch for this particular "diacriticless" behavior you've seen was included in the latest version: can you check if the problem is still present?

**Comment by TheJaredWilcurt** [comment]
I can no longer reproduce this in the latest VGT. 👍
