### ISSUE TITLE
Default Search Behaviour don't search

### ISSUE THREAD

**Issue by ozata** [xaksis/vue-good-table#546]
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using?
2.16.4
What browser?
Chrome
### Expected Behavior
What did you expect to happen?
When I just write, enabled: true, for search-options, I want it to search the table, but It does not search it, I have to use custom search function.
### Actual Behavior
What actually happened?
It just shows an empty list. For example there are 1115, 2222 and 1124, when I use searchFn option and give custom function and write 1 in search bar, automatically I get 1115 and 1124(or 2222 disappears for that matter), but when I delete searchFn option and insert 1 into search bar, I get an empty list.

### Steps to Reproduce the Problem
Please detail your steps here

1. Create a table and add search-options
2. Don't use a custom function and try to search something in list
3. See that it will bring an empty list

**Comment by xaksis** [comment]
This is probably because your column type is `number`. If your data is a number, partial string match would not make sense there, it does a full match only. If you want partial match, you're correct in writing your own filter function, converting values to strings and doing a comparison. 

closing.
