### ISSUE TITLE
Remote table doesn't refresh on filter, and pagination, 

### ISSUE THREAD

**Issue by obaidsamadian** [xaksis/vue-good-table#547]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [ ] Enhancement Request
- [ ] Question

### Specs
What version are you using?
16.4
What browser?
chrome
### Expected Behavior
What did you expect to happen?
new data show up after setting filter ro going to antoher page
### Actual Behavior
What actually happened?
everything was fine on 16.3, after I upgraded to 16.4 remote table broke

**Comment by xaksis** [comment]
Not nearly enough information here for me to look into it. The demo seems to be working fine: 
https://jsfiddle.net/aks9800/c83ektoj/

closing. Will reopen if you can provide some context - is there an error message? are the events not being fired?
