### ISSUE TITLE
Width property doesn't work

### ISSUE THREAD

**Issue by obaidsamadian** [xaksis/vue-good-table#548]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [x] Enhancement Request
- [ ] Question

### Specs
What version are you using?
16.3
What browser?
Chrome

### Problem
When the table gets overflow-x ( the table is bigger than the viewport ), the width property doesn't work anymore! 

### Solution
Change of "width" property to "min-width". that will solve the problem.

https://stackoverflow.com/questions/9305763/set-column-width-of-table-in-div-with-horizontal-scrollbar

**Comment by xaksis** [comment]
@obaidsamadian cool! TIL. Thank you for this ticket. will add this to the next version
