### ISSUE TITLE
use of template breaks filters

### ISSUE THREAD

**Issue by ssuess** [xaksis/vue-good-table#55]
I just started using templates, and I have found that they seem to break filters I had on the rows. For example, This is my template row:

`<td>{{ props.row.date }}</td>`

And it will display the unixtime value from my dataset just fine. But in my col defs I have this:

```
{ label: 'Date',
          field: function (row) {
            var X = row.date * 1000
            return X
          },
          width: '15%',
          sort: true,
          type: 'date',
          inputFormat: 'x',
          outputFormat: 'MMM D, YYYY '
        }
```

which is being completely ignored now that I am using a template. Is there a way to have my formatting still get applied when using a template?

**Comment by ssuess** [comment]
Hi, any advice on this? Am I doing something wrong? Thanks.

**Comment by xaksis** [comment]
sorry for the delay... got really busy. You aren't doing anything wrong. The dynamic table was made with the assumption that all manipulation of data format will occur outside of the table component. However, with your usecase i do see a benefit of providing both the original data as well as the formatted row data.

So I have now added `props.formattedRow` to v1.11.0. For your usecase, update the library then you can use `props.formattedRow.date` to get the formatted date.

closing this, please re-open if you have questions or concerns.
