### ISSUE TITLE
Remove checkbox using custom row template?

### ISSUE THREAD

**Issue by patrickbolle** [xaksis/vue-good-table#551]
I'm using the custom row templates and it is working great! But I'm looking to remove checkboxes on certain rows.

For example, I want to remove all checkboxes after row 500.

Is this possible?

Thanks for the great library!

**Comment by xaksis** [comment]
Hey @patrickbolle, for a customized use-case like that it might be better to use the custom template to create your own column with checkboxes. You can then more precisely control which rows have checkboxes and which don't.

closing.  Let me know if you encounter an issue doing this, and we can re-open and discuss more.

**Comment by gauravgavhane05** [comment]
@xaksis 
@patrickbolle 
How to disable specific row for checkbox selection ?
