### ISSUE TITLE
Method to get currently displayed rows on the table

### ISSUE THREAD

**Issue by ace-subido** [xaksis/vue-good-table#553]
### Issue Type (delete the irrelevant ones)
- [ ]  Bug
- [ ]  Enhancement Request
- [x]  Question

Is there a way to get a list of all the currently displayed rows on a table? For example, someone had a table with this data:

Name | Address | Number
-|-|-
John Doe | California | 1234567 |
Jane Doe | New York | 1234567 |
Freddie Mercury | Kansas | 1234567 |

And I filtered it as such that only `John Doe` and `Jane Doe` was only visible via `Search`. Is there a way that I can get that `John Doe, Jane Doe` rowset?

**Why?**

I'd like to be able to process these rows for something else. For example: make a `table-actions` button that gets the filtered rowset and throws their ID's to an API to export the rows into a CSV file.

**Comment by xaksis** [comment]
hey @ace-subido, you can put a ref on the table and access the proprty 'paginated' to get a list of currently displayed rows.
```
// in a non-grouped regular table you can do 
this.$refs['my-table'].paginated[0].children
```
