### ISSUE TITLE
Ability to add content to topleft of table

### ISSUE THREAD

**Issue by vincentntang** [xaksis/vue-good-table#554]
I'm looking to stylize the search bar to the topright corner of the table, and add a variable title to the topleft of the table. Below image is an example

![image](https://user-images.githubusercontent.com/10290348/59458161-eb878600-8de7-11e9-94f6-a846b9b4b4a8.png)

Is there a vue-slot built in to handle this? 

All I can find is this documentation

```
<div slot="table-actions">
     Projects Listing
 </div>
```

and then swapping the order with css-styles

```
  .vgt-global-search__actions {
    order: 1;
  }
  .vgt-global-search__input {
    order: 2;
  }
```

to get this result:

![image](https://user-images.githubusercontent.com/10290348/59458741-145c4b00-8de9-11e9-84d0-9b97ec578552.png)

------------

Are there better ways of handling positioning elements for these items?

**Comment by xaksis** [comment]
hey @vincentntang the best way to do this is to use an external field for search. You can then create your own search bar and input field above the table however you want:
https://xaksis.github.io/vue-good-table/guide/configuration/search-options.html#externalquery

closing.
