### ISSUE TITLE
Determine if any filters are currently being applied

### ISSUE THREAD

**Issue by hjelperne** [xaksis/vue-good-table#556]
### Issue Type (delete the irrelevant ones) 
- [x] Question

Hi, Is there any way to determine if there are any filters applied or not - at all?
this.$refs.myTable.filters.length > 0 (just pseudo example) or something similar?

### Specs
What version are you using?

2.16.3

What browser?

Chrome

**Comment by xaksis** [comment]
hey @hjelperne sorry for the delay. You can look at: 
`this.$refs.myTable.columnFilters.`
this will have an object where the property is the column field and value is the filter value: 
```
{
  "age": "20",
  "name": "John"
}
```

closing.
