### ISSUE TITLE
Search first letter issue

### ISSUE THREAD

**Issue by Karl-NGP** [xaksis/vue-good-table#557]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.16.5

What browser?
Any

### Actual Behavior
What actually happened?
If you load up a basic table with 4 different rows having names such as "Jane", "John", "Dan", "Susan", the search filter is not working as it should.

Typing in the first letter J (or j), filters out "Dan" and "Susan"
Typing in the first letter S (or s), does not filter out anything. This should show "Susan" only
Typing in the first letter H (or s), filters out "Jane", "Dan", but keeps "Susan" which should not be there as well?

**Comment by xaksis** [comment]
Hey @Karl-NGP, general search filters the entire table, it does not restrict search on any particular column. This means that when you type in s, it looks through the whole table for things that contain "s".  In this case, it finds all rows that have dates with Oct 31**s**t. 
when you type in 'h', it finds all rows that have dates with 'th'

If you want to filter on names only. Use [column filters](https://xaksis.github.io/vue-good-table/guide/configuration/column-filter-options.html). 

Closing.
