### ISSUE TITLE
Row max-height

### ISSUE THREAD

**Issue by Franz0410** [xaksis/vue-good-table#558]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?
v2.16.5
What browser?
-Google Chrome
### Expected Behavior
What did you expect to happen?

i want to set the max height of a row, i tried to pass a class in row-style-class but it doesn't effect

**Comment by xaksis** [comment]
hey @Franz0410, can you post your code of exactly what you tried and what you were trying to achieve? It'll help me investigate this better.

**Comment by Franz0410** [comment]
i resolve the issue

**Comment by kartikkwatra** [comment]
@Franz0410 could you please share how you did it? I'm trying to do the same.

**Comment by luisdoniad** [comment]
@Franz0410 bravo! great help
