### ISSUE TITLE
Programmatic page navigation

### ISSUE THREAD

**Issue by Spacarar** [xaksis/vue-good-table#560]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.16.5

What browser?
Chrome

### Expected Behavior
What did you expect to happen?
According to https://github.com/xaksis/vue-good-table/issues/414 using `this.$set` on `paginationOptions.setCurrentPage` should allow for programmatic page navigation; however, even the example you provided here https://jsfiddle.net/aks9800/m5rz4adh/
also no longer works.

### Actual Behavior
What actually happened?
The page does not change even if using best reactivity practices described in the issue above.

### Steps to Reproduce the Problem
Please detail your steps here

1. Create a table with multiple pages and paginationOptions
2. set the current page to something that is not the current page
3. watch nothing change

### jsfiddle
this was provided in your previous answer and can be used as a current example of the issue
https://jsfiddle.net/aks9800/m5rz4adh/

**Comment by Spacarar** [comment]
after slight further investigation. the example does work if you add the line

`delete this.paginationOptions.setCurrentPage`
before setting the new value


Turns out the page does change, however the pagination object doesn't reflect this.

It is this issue https://github.com/xaksis/vue-good-table/issues/245.

**Comment by xaksis** [comment]
Ah, yeah the `position: both` implementation was never finished and that's why it's not in the official documentation. I'd refrain away from using that. 
Can you tell me how you're setting current page currently that you have to delete the field first?

**Comment by Spacarar** [comment]
I thought it was a reactivity issue and had attempted to delete the value and then use `setCurrentPage` to try and see if vue would react to the change. I later edited my comment to say it was the `position:both` issue. There is no reason to use a delete before setting a new page. Didn't realize this was still open. closing the issue.
