### ISSUE TITLE
Custom Columns documentation should be clarified.

### ISSUE THREAD

**Issue by sheldoncoupeheure** [xaksis/vue-good-table#561]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

Hello. 
To create a custom column using vue-good-table, using slots/props and adding the wanted additionnal columns in the `columns` array are both necessary.

However, the documentation only explicitly talks about the slots/props magic ([here](https://xaksis.github.io/vue-good-table/guide/advanced/#adding-custom-columns)). There is no mention of adding the custom columns in the `column` array.

The documentation should provide additional code samples and clear explanation as xaksis did in issue #450 (see screencap below)

![image](https://user-images.githubusercontent.com/13921610/59910462-3b7ed200-9412-11e9-99f1-de6748f16ac5.png)

**Comment by humblecoder** [comment]
Apologies, but this still makes no sense to me.  What if I need to add a custom column with `<button>`?  Please provide a clear, concise example of this type of customization.   Thanks.
