### ISSUE TITLE
Custom th/tdClass not taking effect

### ISSUE THREAD

**Issue by ricardomiguelvieira** [xaksis/vue-good-table#564]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?

2.16.5

### Expected Behavior
I expected the properties I've set for the custom th/td class to take effect.

### Actual Behavior
Nothing happened. No changes took place.

----------------------------------------------------------------------
`<style lang="scss" scoped>
  @import '~variables';

.custom-th-class {
    text-align: center !important;
  }

</style>`

`columns: [
        {
          label: 'Name',
          field: 'display_name',
          thClass: 'custom-th-class'
        }
]`

What am I performing wrongfully so that the changes don't take place?

**Comment by xaksis** [comment]
Hi @ricardomiguelvieira,
looks like that should be working. Here's a working example - you can compare your code against it: 
https://jsfiddle.net/aks9800/dc1L3pza/

oh it could be that you've scoped your style so it doesn't apply to any nested component. Try removing scoped or using `/deep/` for it to affect the child components 

closing.
