### ISSUE TITLE
How to ignore rowOnClick for certain parts of row?

### ISSUE THREAD

**Issue by vincentntang** [xaksis/vue-good-table#566]
If I have an @onRowClick event handler, is there a way I can disable it for certain custom slotted icons so it doesn't trigger?

For instance, when a user clicks on a row, it goes to that item's page. If they click the "X" delete button, it should just delete it only

![image](https://user-images.githubusercontent.com/10290348/60045935-1b5e4580-9694-11e9-8a2c-b10eb644bc68.png)

**Comment by xaksis** [comment]
hey @vincentntang,
this is a vue/js question rather than a vgt question. You can prevent an event from propagating up to the parent by stopping it. use `@click.stop="yourButtonFn"` and it won't propagate to the row.

here's a working example: https://jsfiddle.net/aks9800/wtwzg6Lz/
closing.
