### ISSUE TITLE
How can I filter a column with a drop-down of filter operators?

### ISSUE THREAD

**Issue by matdar** [xaksis/vue-good-table#568]
- [x] Question

Hello
I would like to display a drop-down of filter operators, e.g.:

>
>=
<
<=
etc. 

next to the value to apply to the operator.

For example filter for a number > 100 by selecting '>' in the drop-down and entering 100 into the column filter.

Is that possible to do now via some customisation?
Thanks
Matt

**Comment by xaksis** [comment]
This isn't possible right now. However I have seen implementations where users type "> 20" which is then parsed by a custom filter: 
https://xaksis.github.io/vue-good-table/guide/configuration/column-filter-options.html#filterfn
