### ISSUE TITLE
Missing dependency in 2.17.2

### ISSUE THREAD

**Issue by SouthRibbleTech** [xaksis/vue-good-table#571]
I was happy to see the fix this morning that was put in place overnight 2.17.2 (Thank you) but when I tried to use it this morning, i get the following error

```
This dependency was not found:

* vue-runtime-helpers/dist/normalize-component.js in ./node_modules/vue-good-table/dist/vue-good-table.esm.js

To install it, you can run: npm install --save vue-runtime-helpers/dist/normalize-component.js
```
vue-good-table: 2.17.2
Windows 7
vue: 2.6.10
Node: 10.15.3

**Comment by rashed50702** [comment]
I am facing same problem

**Comment by ccclin** [comment]
Same [issue](https://github.com/xaksis/vue-good-table/issues/569#issuecomment-509521329)

**Comment by SouthRibbleTech** [comment]
For the time being, just so that I can continue to work, I have downgraded to 2.16.5

```
"vue-good-table": "2.16.5"
```

But for this to work, I had to delete my node_modules folder and do a fresh `npm install`

Once fixed I will upgrade to the latest version.

**Comment by xaksis** [comment]
keeping #569 open
