### ISSUE TITLE
Add ability to specify custom theme

### ISSUE THREAD

**Issue by stefandevo** [xaksis/vue-good-table#572]
### Issue Type

- [x] Bug

### Specs

Based upon the black-rhino and nocturnal default themes, I could create a scss file for my own theme. By setting the `theme` prop on the control I can use these themes. However, some parts are not themeable at the moment.

https://github.com/xaksis/vue-good-table/blob/master/src/components/Table.vue#L6

This shows that the `vgt-wrap` is hard-coded for checking upon the two default themes where the `vgt-table` class selector can be extended with your own theme (using the .theme property).

Can this be changed? Otherwise I have to complete override all elements.

**Comment by xaksis** [comment]
hey @stefandevo, good point, I'll look into allowing usage of custom themes. When I first rolled this out, I was thinking people would maybe add PRs for new themes so everyone else can use them too. But it does make sense to have an ability to use your own internal theme also.

**Comment by xaksis** [comment]
hey @stefandevo , so I played around with this myself and realized that custom themes can already be specified.
`vgt-wrap` the hardcoded themes there don't have any style rules attached to them (i'll remove them shortly)

To use custom themes, all you have to do is create a parent class, add the overrides under the parent class and then supply that parent class as a theme. 
Look at black-rhino theme for example: https://github.com/xaksis/vue-good-table/tree/master/src/styles/black-rhino
```scss
.vgt-table.my-theme{
 // all your overrides here
}
```

then in table: 
```html
<vue-good-table
  theme="my-theme"
  //..
</vue-good-table>
```

I'm going to close this as I just created a custom theme myself and it works well without any additional changes.

**Comment by xaksis** [comment]
aw crap, just realized that pagination actually depends on vgt-wrap class. 
*sigh* will fix this. sorray!
re-opening

**Comment by xaksis** [comment]
hardcoded theme reference removed in v2.18. closing.

**Comment by GouravShandilya** [comment]
how i add my own css in vue-good-table
