### ISSUE TITLE
on-page-change and on-column-filter called twice initially

### ISSUE THREAD

**Issue by SevymolSebastian** [xaksis/vue-good-table#575]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.17.3
What browser?
Chrome

### Expected Behavior
on-page-change and on-column-filter events should be called once initially.

### Actual Behavior
on-page-change and on-column-filter events should be called twice initially. Duplicate requests are send when page is created

**Comment by xaksis** [comment]
@SevymolSebastian could you create an example to show this issue?
Seems to be working fine here: 
https://jsfiddle.net/aks9800/a2841urL/
Will re-open if you can provide a reproducible snippet.
