### ISSUE TITLE
How to set column filter in Vue method?

### ISSUE THREAD

**Issue by unixconky** [xaksis/vue-good-table#577]
How to set column filter in Vue method? I need to set filter to "approved". 

My method:

`<button v-on:click="onClickShowApproved">Show only approved</button>`

```
onClickShowApproved: function() {
   ....
}

```

Here is my column code:
```
{
  label: 'Status',
  field: 'status',
  type: 'text',
  filterOptions: {
    enabled: true,
    placeholder: 'All',
    //filterValue: '',
    filterDropdownItems: [
      { value: 'approved', text: 'Approved' },
      { value: 'rejected', text: 'Rejected' },
    ],
    filterFn: this.columnFilterFn, 
    trigger: 'enter',
  },
},
```

**Comment by unixconky** [comment]
https://stackoverflow.com/a/56349748/3115655  it works but only in vue-good-table 2.15, not working in 2.16. Any ideas?

**Comment by xaksis** [comment]
@unixconky the answer in stackoverflow is somewhat correct. it is definitely a nested object reactivity caveat. However `vue.set` doesn't work for pre-existing properties. You'd need to use Object.assign.

**Comment by oze4** [comment]
#578 #579

Good luck with this! I've switched to a better, more responsive solution.

**Comment by xaksis** [comment]
@oze4 has identified a bug that is causing this. Will be testing that later today. Thank you, @oze4

**Comment by xaksis** [comment]
@unixconky @oze4 looks like this is a change in the vue 2.6 behavior as well: 
https://vuejs.org/v2/api/#vm-watch
> Note: when mutating (rather than replacing) an Object or an Array, the old value will be the same as new value because they reference the same Object/Array. Vue doesn’t keep a copy of the pre-mutate value.

I'll release a fix to address this but keep in mind that you still have to use `vue.set` or `object.assign` to mutate nested objects and not simply assign new values: 
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by xaksis** [comment]
v 2.17.4 should fix this. Remember to use: 
```
this.$set(this.columns[0].filterOptions, 'filterValue', 'filterTerm');
```
closing.

**Comment by xaksis** [comment]
created a working example - so sharing for reference:
https://jsfiddle.net/aks9800/cyegzwL7/

**Comment by oze4** [comment]
> v 2.17.4 should fix this. Remember to use:
> 
> ```
> this.$set(this.columns[0].filterOptions, 'filterValue', 'filterTerm');
> ```
> 
> closing.

Keep in mind, you only have to use `$set` or `Object.assign` **_if the `filterValue` property was not set to empty before trying to programmatically change it._**

In the following example I originally set the `filterValue` to `""` - this way I can just set the value without having to worry about `$set` or `Object.assign` or `JSON.stringify(...)`

[Set to 'empty' value](https://github.com/oze4/vue-good-table/blob/455601526abbd1159a9f275f36d39b34dd5ae2fe/dev/App.vue#L77)

[Don't have to worry about `$set`, etc...](https://github.com/oze4/vue-good-table/blob/455601526abbd1159a9f275f36d39b34dd5ae2fe/dev/App.vue#L242)

As a "best practices" or "rule of thumb" you should always use `$set`/`Object.assign` so you don't have to remember to set `filterValue` to an empty value beforehand..

Cheers mate.
