### ISSUE TITLE
Programmatically Change Filter Value

### ISSUE THREAD

**Issue by oze4** [xaksis/vue-good-table#578]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.17.3

What browser?
Firefox/Chrome

### Expected Behavior
What did you expect to happen?
Filter value to be updated - this worked in v2.15.3... In fact, v2.15.3 was the last version this worked in - I also tested this in v2.16.0, to no avail.

### Actual Behavior
What actually happened?
Sadly, nothing.

### Steps to Reproduce the Problem
Go to the CodePen below and click the button that says `Click To Change Name Filter`

### jsfiddle
1. #### [Example of this *not* working (v2.17.3)](https://codepen.io/oze4/pen/MNbKeV)
2. #### [Example of this working (v2.15.3)](https://codepen.io/oze4/pen/zQjEmK?editors=1010)

**Comment by xaksis** [comment]
a few issues with your code: 
1. you're assigning a value directly to a nested object. this is not a reactive change for vue.
2. in 2.17.3 version you're using the spread operator to copy the array. this does a shallow copy and is not useful when it comes to reactivity. 
I modified your code to do a deep copy and it works fine. 
```
changeFilter(field, newFilter) {
      let newCols = JSON.parse(JSON.stringify(this.columns));
      let found = newCols.find(c => {
        return c.field == field;
      });
      console.log(found);
      if (found) {
        if (found.hasOwnProperty("filterOptions")) {
          //if (found.filterOptions.hasOwnProperty("filterValue")) {
            console.log(found);
            console.log(newFilter);
            found.filterOptions.filterValue = newFilter;
            this.columns = newCols;
            console.log(this.columns);
          //} else {
            //alert(`Column '${field}' does not have filterValue property!`);
          //}
        } else {
          alert(`Column '${field}' does not have filtering configured!`);
        }
      } else {
        alert(`Field '${field}' does not exist!`);
      }
    }
```
Closing.

**Comment by oze4** [comment]
>     1. you're assigning a value directly to a nested object. this is not a reactive change for vue.
> 
>     2. in 2.17.3 version you're using the spread operator to copy the array. this does a shallow copy and is not useful when it comes to reactivity.
>        I modified your code to do a deep copy and it works fine.

1. How/why does this work in 2.15.3 if it isn't reactive for Vue? Doesn't make much sense.

2. Yes, this was for testing - using the exact same code in 2.17.3 does not work like it does in 2.15.3.... Furthermore, if you console log the output (while using spread) it clearly shows the value is modified.

Thank you for the working code, but something had to have changed under the hood from 2.15.3 to 2.17.3.

**Comment by xaksis** [comment]
> Thank you for the working code, but something had to have changed under the hood from 2.15.3 to 2.17.3.
Yea the Vue version changed from 2.5 to 2.6, slot behavior etc changed too.
regarding the console.log... of course, you'll see the change in the log. The change happens on the object, but the change is not **reactive**.

**Comment by oze4** [comment]
That's makes sense with the Vue version changing. So then Vue obviously changed something to ignore shallow copies and only respect changes when a new object is supplied, not just a new property. It's almost like the older version of Vue was smarter - or is there a good reason for not picking up on nested changes?
