### ISSUE TITLE
Reactive Nested Changes (ref #578)

### ISSUE THREAD

**Issue by oze4** [xaksis/vue-good-table#579]
# Reference issue #578 

Clearly Vue reacts to nested changes.... I am highly confused at why this does not work in Good Table..

### Reactive nested changes:
[![Edit on CodePen](https://www.vectorlogo.zone/logos/codepen/codepen-icon.svg)](https://codepen.io/oze4/pen/ymVagv?editors=1010)

### Example showing GoodTable not recognizing changes:
[![Edit on CodePen](https://www.vectorlogo.zone/logos/codepen/codepen-icon.svg)](https://codepen.io/oze4/pen/MNbKeV?editors=1010)

**Comment by xaksis** [comment]
@oze4 please read vuejs documentation. This isn't related to VGT. 

https://vuejs.org/v2/guide/reactivity.html

Closing.

**Comment by oze4** [comment]
@xaksis

Yes, I can see Vue is reacting to the changes I made but VGT isn't. This is 100% related to VGT. Vue is reacting. VGT is not. Pretty clear to see that.

**Comment by oze4** [comment]
@xaksis

You should not have to supply a completely new columns object for VGT to react to the changes. Vue reacts to them, why does VGT not? It's fine if you don't want to fix this flaw but it's pretty apparent that it is indeed a flaw.
