### ISSUE TITLE
Required Functionality Request: Allow user to delete the row.

### ISSUE THREAD

**Issue by 2rohith2** [xaksis/vue-good-table#58]
The user should be able to delete the row and on confirmation, delete the row in the table and support for a custom method call (send the row details this method) where a developer can write there own code to delete data on server side.

**Comment by VisualBean** [comment]
you could just add another column with an actions menu - where you could delete the row based on what ever props.row.property

Like
```
  <template slot="table-row" scope="props">
            <td>{{props.row.id}}</td>
            <td>{{props.row.name}}</td>
             <td> 
<button @click="delete(props.row.id)">del</button>
              </td> 
          </template>
```

and then delete the item in the array with above id

**Comment by xaksis** [comment]
thank you @VisualBean , 
@2rohith2 in addition, when you create dynamic template you also have access to the original row index via `props.originalIndex` (if you don't  have a unique id per row). this index can be used to delete the given row as well. 

Closing. Please reopen if you have more questions/concerns

**Comment by 2rohith2** [comment]
@xaksis @VisualBean I have used a dynamic template, my custom function is called when I click on the delete and I will send an `ajax` call to delete from the server.

But still, I don't understand how do I delete the row from the table which is already rendered on the page?

**Comment by xaksis** [comment]
@2rohith2 you have to re-fetch your data and update rows once the row is deleted.

**Comment by cristijora** [comment]
@xaksis isn't it possible to simply 
```js
delete(id){
 // delete from server
 const indexToDelete = this.rows.findIndex(row=>row.id === id)
 if(indexToDelete !== -1 ){
   this.rows.splice(indexToDelete, 1)
 }
}
```

Delete from local rows instead of refetching data?

**Comment by xaksis** [comment]
@cristijora yes that's definitely a way to do it, but the problem I see with that approach is that it would create a out of sync condition between UI and backend, in case there was an error deleting the row. 

In order to keep things in sync, this would need to be done in the handler of the delete call (handling the error case). Depending on the usecase (and payload size) it might be easier to just return the new set of rows and let the table react to it. 

I do think these are more implementation details though and less about the component itself.

**Comment by 2rohith2** [comment]
>>> @2rohith2 you have to re-fetch your data and update rows once the row is deleted.

@xaksis Do you mean I have to get the `Users` data after deleting the row from the table and assign new data to row?

**Comment by cristijora** [comment]
He meqnt that you need to refetch the rows again and reassign the to the table. So you have to options. The one I mentioned above where you have to delete the item only in the success function/callback of your ajax delete call or simply refetch table data after your ajax delete call

**Comment by 2rohith2** [comment]
@xaksis Please close his issue, I have used `re-fetch` the user details, the table is working fine.

Thanks to @xaksis @cristijora
