### ISSUE TITLE
Disable checkbox info bar

### ISSUE THREAD

**Issue by connorshea** [xaksis/vue-good-table#583]
### Issue Type

- [x] Enhancement Request

### Specs
What version are you using? v2.17.4

What browser? Firefox 70 (Nightly)

### Expected Behavior
I should be able to disable the checkbox selected row info bar.

This yellow bar:

<img width="1354" alt="Screen Shot 2019-08-03 at 12 57 03 PM" src="https://user-images.githubusercontent.com/2977353/62415887-630ab200-b5ee-11e9-9de9-63491c4a8dc9.png">

I don't have a need for it and I'd like to handle the modifications done on the selected rows from outside the table.

### Actual Behavior
I'm unable to disable the checkbox selected row info bar.

### Steps to Reproduce the Problem
Please detail your steps here

1. Create a table with the select checkboxes enabled
1. Select a row
1. See that there's an info bar for the selected rows
1. See that there's no way to disable this info bar.

**Comment by connorshea** [comment]
For now I'm just working around it by setting it to `display: none` in my CSS, but that's not ideal.

**Comment by xaksis** [comment]
In v2.18.0, you can now disable the info bar by using `disableSelectInfo: true` in selectOptions.
https://xaksis.github.io/vue-good-table/guide/advanced/checkbox-table.html#configuration

closing.

**Comment by connorshea** [comment]
Thanks!
