### ISSUE TITLE
Adding a custom row at the end of the table (with pagination)

### ISSUE THREAD

**Issue by TotomInc** [xaksis/vue-good-table#585]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
VGT `^2.17.4`

### What browser?
Chromium / Electron

### Expected Behavior
I would like to add a custom row at the end of a table which have pagination options.

If I have my pagiation option set to 5 elements/page, I want to see my custom row after the 5th element (but before the pagination element). Same applies with 10 elements/page, I want to see my custom row after the 10th element, and so on...

**Comment by xaksis** [comment]
hey @TotomInc, this seems to be a very specialized use-case. One way you could achieve this is to not use the provided pagination and use your own pagination component instead- https://xaksis.github.io/vue-good-table/guide/advanced/#custom-pagination. 

Hope this helps,
Closing.

**Comment by TotomInc** [comment]
Thanks for the answer, I doubt I will do this as I need to do my own pagination system and I prefer to let vue-good-table handle this.

I’ll try to find an alternative with my issue.
