### ISSUE TITLE
Required Functionality Request: Support for icons in row.

### ISSUE THREAD

**Issue by 2rohith2** [xaksis/vue-good-table#59]
In my table, I have a **Gender** column, the data from the server is **m** or **f** for male or female respectively.

You should allow the use of icons for some particular data.

Ex: You can ask the user to supply icon HTML and place the icon in the row.
```javascript
columns: [
	{
		label: 'Gender',
		field: 'gender',
		filterable: true,
		icon:{
			'm': '<i class="fa fa-male" aria-hidden="true"></i>',
			'f': '<i class="fa fa-female" aria-hidden="true"></i>'
		}
	}
],
````

**Comment by xaksis** [comment]
Hey @2rohith2, using html is already possible via `html` column property. You don't need anything specific for icons. If you want to dynamically create one icon vs. the other based on data, I suggest you use the dynamic templating (also explained in the readme)
```javascript
<vue-good-table
  title="Dynamic Table"
  :columns="columns"
  :rows="rows">
  <template slot="table-row" scope="props">
    <td>{{ props.row.name }}</td>
    <td class="fancy">{{ props.row.age }}</td>
    <td>
         <i v-if="props.row.gender == 'm'" class="fa fa-male" aria-hidden="true"></i>
         <i v-if="props.row.gender == 'f'" class="fa fa-female" aria-hidden="true"></i>
    </td>
  </template>
</vue-good-table>
```

closing.
