### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window'

### ISSUE THREAD

**Issue by sybrendotinga** [xaksis/vue-good-table#590]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
`2.18.0`

What browser?
`Chrome 75.0.3770.142`

### Expected Behavior
Renders the table with the columns and data, without console errors

### Actual Behavior
I receive a `getComputedStyle` on (probably) the hidden `address1` column

### Steps to Reproduce the Problem
1. I create a `vue-good-table` with a fixed header.
2. I set the order of the columns in my view: 
```
expectedColumns: [
        {
          field: "customerNumber"
        },
        {
          field: "name"
        },
        {
          field: "address1"
        },
        {
          field: "zipCode"
        },
        {
          field: "city"
        },
        {
          field: "country"
        },
        {
          field: "customerStatus"
        }
]
```
3. I receive columns with additional data that I have rights to from the API (you can see that in the XHR request). In this case I do not have rights for `address1`
4. I merge both `expectedColumns` and `apiColumns`, and set columns `hidden: true` that I do not have rights for (in this case `address1`)
5. I receive a `getComputedStyle` on (probably) the hidden `address1` column (see minimal reproducible example)

One solution that I came up with is to remove  `hidden` when I do not have rights for it, because I do not receive it as row data anyway. That way `vue-good-table` will not show it as a column anyway.

### Code Sandbox
CodeSandbox reproduction link: 
- Live view: https://nhupq.csb.app/
- Editor: https://codesandbox.io/s/vue-template-nhupq

**Comment by FascistDonut** [comment]
I receive the same error when hiding columns on a table that has fixed headers.

**Comment by peterwhite** [comment]
+1 Same here - fixed header plus hidden columns, same setup as @sybrendotinga

Removing the hidden columns or removing the fixed header resolves the issue.

**Comment by CHEWX** [comment]
Looks like the fix sorted this out. Can we close the issue — @sybrendotinga @xaksis

**Comment by xaksis** [comment]
yep! thanks @CHEWX
