### ISSUE TITLE
Set selected rows based on server data

### ISSUE THREAD

**Issue by eyalankri** [xaksis/vue-good-table#592]
- [x] Question

### Specs
2.18.0

### Expected Behavior
I save the selected rows-data in the database.  if the page loads again I would like to have these rows already selected based on the data returned from the server.

### Actual Behavior
After filling the ` vue-good-table` and verify that the data exists in dom, I am looping for each row and check if it's selected in the server results,  if it does I do: `$(el).click()`

**Comment by xaksis** [comment]
hey @eyalankri, you can set `vgtSelected` property on rows to programmatically select them. 
```
this.$set(this.rows[2], 'vgtSelected', true);
```
working example: 
https://jsfiddle.net/aks9800/keLjcssn/241/

closing.
