### ISSUE TITLE
perPage now working

### ISSUE THREAD

**Issue by cjcaber09** [xaksis/vue-good-table#594]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?

What browser?
Chrome
### Expected Behavior
What did you expect to happen?
to only show 2 records
### Actual Behavior
What actually happened?
shows all

### Steps to Reproduce the Problem
Please detail your steps here

<vue-good-table
                mode="remote"
                @on-page-change="onPageChange"
                @on-sort-change="onSortChange"
                @on-column-filter="onColumnFilter"
                @on-per-page-change="onPerPageChange"
                :totalRows="totalRecords"
                :isLoading.sync="isLoading"
                :pagination-options="{
                    enabled: true,
                    mode:'pages',
                    perPage:2
                }"
                :rows="rows"
                :columns="columns"/>

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
hey @cjcaber09, in remote mode, your backend controls what is displayed by sending the correct configuration of rows to display. Every time per page is changed, it emits an event. Use this event to send the correct parameters to the backend so they send you the correct # of rows to display.

closing.
