### ISSUE TITLE
How to disable responsive table and add horizontal scrollbar

### ISSUE THREAD

**Issue by paulhuisman** [xaksis/vue-good-table#595]
### Issue Type
[x] Question

### Specs
What version are you using?
2.6.10

What browser?
Latest Chrome

### Description
I love this plugin! We made a table with around 15 columns, so showing it responsive is not really going to work. Can someone tell me how to disable responsive rescaling and add a horizontal scrollbar instead?

**Comment by paulhuisman** [comment]
Fixed with `overflow: scroll !important;`

**Comment by LovelyAndy** [comment]
@paulhuisman Hey Paul, I'm sure you're well passed this by now, but if you can remember, where did you put the `overflow: scroll !important`?
