### ISSUE TITLE
Date parsing error

### ISSUE THREAD

**Issue by Dave3of5** [xaksis/vue-good-table#599]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.18.0
What browser?
Chrome

### Expected Behavior
What did you expect to happen?
Date formatting was working

### Actual Behavior
What actually happened?
Upgraded to the latest version and the date formatting has broken.

### Steps to Reproduce the Problem
Please detail your steps here

ISO dates coming back from the server no longer parse correctly:

This is the date coming back from the server:

2019-08-31T14:36:28.511Z

Input format is yyyy-MM-dd and the date is not formatting correctly.

**Comment by Dave3of5** [comment]
Here is a repro:

https://jsfiddle.net/s0ear5pk/1/

Note that the second column doesn't show correctly at all. Something strange happening with the date parsing with the version of date-fns used here. Trying this online with the alpha and it parses those date without question.

**Comment by xaksis** [comment]
hey @Dave3of5,
if you look at the console you'll see: 
`Not a valid date: "2019-08-31T14:36:28.511Z"`
This is because your input format (supplied in the column object) does not perfectly match with date string that is in your rows.
Correct format: 
```
dateInputFormat: 'yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'',
```
corrected jsfiddle:
https://jsfiddle.net/aks9800/ubkmadwe/

format guide: 
https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#changed

closing.

**Comment by p0psicles** [comment]
Don't want to create a new issue for this. But I can if needed.
I have a similar issue.
Date string: `2020-01-29T03:00:00+01:00`
Tried format: `'yyyy-MM-dd\'T\'mm:ss:SSXXX'`

Have a codesandbox to try out. And it should work with dateFns.
https://codesandbox.io/s/date-fns-bg2gh

@xaksis any idea why vue-good-table is giving back `Invalid Date`?
https://codesandbox.io/s/vue-datatable-82w7i

**Comment by aacassandra** [comment]
thanks @xaksis , awesome!

**Comment by shabanovtg** [comment]
Not correct parse timezone from ISO string and render.

Correct time should be **2019-08-31 17:36:28 +03**

How I can set flags.timestampIsSet = true? This flag set only if format T

![image](https://github.com/xaksis/vue-good-table/assets/6978754/4fe0f6e7-dced-463a-ba60-75132bfd3305)

I'm forced to convert data to milliseconds 

![image](https://github.com/xaksis/vue-good-table/assets/6978754/04fa0171-2e1c-41ec-af8a-750dd044e4bd)


https://jsfiddle.net/x7Lb4e3w/
![image](https://github.com/xaksis/vue-good-table/assets/6978754/7f656911-a2dc-4928-9938-ef9aece52382)


> hey @Dave3of5, if you look at the console you'll see: `Not a valid date: "2019-08-31T14:36:28.511Z"` This is because your input format (supplied in the column object) does not perfectly match with date string that is in your rows. Correct format:
> 
> ```
> dateInputFormat: 'yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'',
> ```
> 
> corrected jsfiddle: https://jsfiddle.net/aks9800/ubkmadwe/
> 
> format guide: https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md#changed
> 
> closing.
