### ISSUE TITLE
Contribution issues

### ISSUE THREAD

**Issue by cristijora** [xaksis/vue-good-table#6]
1. How to test the component locally? Do I have to setup a whole new project and use the library there?
2. The current demos folder structure doesn't allow `npm install`
3. Is there going to be a browser bundle so we can test stuff easily on jsfiddle for example ?

**Comment by xaksis** [comment]
1. for now, yes
2. removed demo folder in favor of [online demos](https://xaksis.github.io/vue-good-demos/#/simple-table)
3. I haven't looked into it yet

**Comment by xaksis** [comment]
soling this... seems like you addressed most of these :) 👍
