### ISSUE TITLE
Display data for nested array

### ISSUE THREAD

**Issue by pageanengineer** [xaksis/vue-good-table#605]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.17.4

What browser?
Chrome

### Expected Behavior
What did you expect to happen?
Would like to display ID from data below

### Actual Behavior
What actually happened?
Blank data spot in table

### Steps to Reproduce the Problem
Please detail your steps here
Put `field: 'alerts[0]._id',` for the field value

Row data I am trying to work with - note that this example only has one item in the alerts array however in the final application it likely will not be just one. I have removed most of the data from the rows to make it cleaner past just the alerts cleanup.

```
rows: [
            {
                "alerts": [
                    {
                        "users": [
                            "5d548ad4bffdaf09d5348b75"
                        ],
                        "status": true,
                        "_id": "5d54a84145661b25ccfefec8",
                        "__v": 0
                    }
                ],
                "status": false,
                "_id": "5d54a888b8f1cc1d60ef8671",
                "createdAt": "2019-08-15T00:34:17.019Z",
                "__v": 0
            }
        ]
```

**Comment by xaksis** [comment]
hey @pageanengineer, use a [custom function](https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#field) in field for something as specialized as this:
```
columns: [
  { 
    label: 'whatever',
    field: this.fealdFn,
  },
  // ...
]
// in methods
fieldFn(rowObj) {
  return rowObj.alerts[0]._id;
}
``` 
Closing

**Comment by pageanengineer** [comment]
@xaksis Thanks, I noticed when I do multiple of the functions in a single table that it always just outputs the last one I ran and doesn't give the data for each field. 

The below code gives just the users data back in both fields.
```
{
	label: 'Incident ID',
	field: this.displayID,
	width: '15%',
	tdClass: 'text-center text-nowrap',
	thClass: 'text-center text-nowrap'
}, {
	label: 'Responded Users',
	field: this.displayUsers,
	width: '15%',
	tdClass: 'text-center text-nowrap',
	thClass: 'text-center text-nowrap'
},


displayID(alert) {
	return alert.alerts[0]._id
},
displayUsers(alert) {
	return alert.alerts[0].users
}
```

**Comment by j-wil** [comment]
@pageanengineer I just ran into the exact same problem you described in your last comment did you ever come up with a solution?

**Comment by j-wil** [comment]
Ahhhh I just found the solution in this issue https://github.com/xaksis/vue-good-table/issues/620#issuecomment-543196980

For anyone else who comes across this the fix in the above example is as follows: 
```{
	label: 'Incident ID',
	field: row => this.displayID(row),
	width: '15%',
	tdClass: 'text-center text-nowrap',
	thClass: 'text-center text-nowrap'
}, {
	label: 'Responded Users',
	field: row => this.displayUsers(row),
	width: '15%',
	tdClass: 'text-center text-nowrap',
	thClass: 'text-center text-nowrap'
},


displayID(alert) {
	return alert.alerts[0]._id
},
displayUsers(alert) {
	return alert.alerts[0].users
}```

**Comment by HatemBay** [comment]
@j-wil for some reason this doesn't work for me, any ideas?
my code:
 columns: [
                {
                    label: "Id",
                    field: "id",
                    hidden: true
                },
                {
                    label: "Name",
                    field: "name",
                    tdClass: "pt-3 text-capitalize"
                },
                {
                    label: "Preview",
                    field: row => this.displayColor(row),
                    tdClass: "pt-3",
                    html: true
                },
                {
                    label: "Created On",
                    field: "created_at",
                    type: "date",
                    dateInputFormat: "yyyy-MM-dd HH:mm:ss",
                    dateOutputFormat: "MMM do yy",
                    tdClass: "pt-3 text-left",
                    thClass: "text-left"
                },
                {
                    label: "Manage",
                    field: "manage",
                    thClass: "text-right"
                }
            ],
            priorities: [],


displayColor() {
            var element = document.createElement("span");
            element.setAttribute("class", "badge badge-pill");
            Object.assign(element.style, {
                backgroundColor: this.priorities[0].bg_color,
                color: this.priorities[0].text_color
            });
            element.innerHTML = "TEST";
            return element.outerHTML;
        }

only this.priorities[0] attributes are shown in every row

**Comment by AntonFix** [comment]
> 

Hello,
Anybody can help me, please?

How to create searching in array of object?

In column "Organizations" table return an array with 3 objects:
``[
   { "id": 2, "name": "De Tinten vzw", "postcode": 9000, "city": "Gent" }, 
  { "id": 3, "name": "KRAS Gent vzw", "postcode": 9000, "city": "Gent" }, 
  { "id": 4, "name": "Test vzw", "postcode": 1000, "city": "Brussel" }
 ]``


![chrome_0QDGaZSJX1](https://user-images.githubusercontent.com/2990135/194323972-79e832a4-1aa4-491e-a2a6-dc0cbaabfac1.png)

If i use return row.get_organisations[0].name then column return only first object (and i can find them).

How can i return list (ex., ul>li) and make it searchable?

Thank you.

```
columns: [
	{
	  label: 'Forename',
	  field: 'forename',
	},
	{
	  label: 'Name',
	  field: 'name',
	},
	{
	  label: 'Organizations',
	  field: this.fieldTestFn,
	},
	{
	  label: 'Created On',
	  field: 'created_at',
	  type: 'date',
	  dateInputFormat: 'yyyy-MM-dd',
	  dateOutputFormat: 'do MMM yy',
	}
],

methods: {
	fieldTestFn(row) {
	  return row.get_organisations
	}
},
