### ISSUE TITLE
Search for elements in object

### ISSUE THREAD

**Issue by sytheveenje** [xaksis/vue-good-table#609]
### Issue Type

- [x] Question

### Specs
What version are you using?
2.18.0

I have a columns setup like this:

```
columns: [
                    {
                        label: '#',
                        field: 'id'
                    },
                    {
                        label: 'Address',
                        field: 'address'
                    },
                    {
                        label: 'Example',
                        field: 'example_field'
                    },
                ],
```

Now address is an object. When I search for `streetname` it doesn't show the rows where the address has `streetname` in it. How can I expand the search to also search for things inside my object?

For reference, my template is like this:

```
<template slot="table-row" slot-scope="props">

                <div v-if="props.column.field === 'id'">
                    <a href="#" class="text-link" @click.prevent="myFunction()"># {{ props.row.id}}</a>
                </div>

                <span v-else-if="props.column.field === 'address'">
                    <address>
                        {{ props.row.address.first_name }} {{ props.row.address.last_name }} <br>
                        {{ props.row.address.streetname }} <br>
                        {{ props.row.address.city }}
                    </address>
                </span>

                <span v-else>
                  {{ props.formattedRow[props.column.field] }}
                </span>

            </template>
```

**Comment by sytheveenje** [comment]
Sorry, I already found a solution [here in issue 261](https://github.com/xaksis/vue-good-table/issues/261). Is there a way to make this easier when the nested object got a lot of items?

**Comment by xaksis** [comment]
Hey @sytheveenje, for a specialized case like this, the best way is to customize your filter function where you can supply your own filter function.
https://xaksis.github.io/vue-good-table/guide/configuration/column-filter-options.html#filterfn

closing.
