### ISSUE TITLE
Adding row to input array does not affect the table

### ISSUE THREAD

**Issue by VisualBean** [xaksis/vue-good-table#61]
There is in issue regarding the table to being reactive to changes in the aray used for :row

**Comment by VisualBean** [comment]
I see that it actually does get added, but it doesn't re-"filter" once the row is added

**Comment by VisualBean** [comment]
Adding defaultSortBy fixed the issue. :) but maybe it should refilter on additions to the rows?

**Comment by xaksis** [comment]
Hey @VisualBean ... I'll keep this open for now and see if I can look into making the default state reactive.

**Comment by 2rohith2** [comment]
@VisualBean I have a small suggestion, you can re-fetch the data after adding the data to the server and reassign the data to row.

This might work.

**Comment by xaksis** [comment]
hey @VisualBean i just tested this... and it actually works without the default sort. I'm going to close this.
