### ISSUE TITLE
How to add edit & delete button in each row & able to capture row id?

### ISSUE THREAD

**Issue by akmalelias** [xaksis/vue-good-table#612]
- [x] Question

### Specs
What version are you using?
2.18.0

What browser?
Chrome Version 77.0.3865.90

Hi, thanks for the vue-good-table. Nice work. Just wondering how can I add edit & delete button for each row like the standard datatable? And also how to capture the row data id?
Thanks in advance.

**Comment by marekfilip** [comment]
Here, I created an simple example on jsfiddle.
https://jsfiddle.net/marekfilip/jm4ywzor/

Basically you create a [custom column](https://xaksis.github.io/vue-good-table/guide/advanced/#adding-custom-columns) and then [customizing template](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template) for it to render a buttons with @click function.

**Comment by akmalelias** [comment]
@marekfilip thank a lots! Now I get the idea.
