### ISSUE TITLE
Template slot for column filters

### ISSUE THREAD

**Issue by paulhuisman** [xaksis/vue-good-table#616]
### Issue Type

- Enhancement Request

### Specs

What version are you using? 2.18.0

What browser? Chrome

### Description

Can a template slot for column filters be introduced? Right now there is a `slot="table-column" ` but this doesn't work for the filters on top of the column.

This way we can add our own html for filters. Datepickers, multiselects, you name it.

**Comment by xaksis** [comment]
consolidating with #675

**Comment by TheJaredWilcurt** [comment]
@paulhuisman 

As of [v2.21.0](https://github.com/xaksis/vue-good-table/releases/tag/v2.21.0) this feature is now available.

* [Docs for using custom filter slot](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)
