### ISSUE TITLE
How 

### ISSUE THREAD

**Issue by joshk132** [xaksis/vue-good-table#621]
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using?
2.17.4

What browser?
All

### Expected Behavior
What did you expect to happen?
Would like to have it output HTML/template

### Actual Behavior
What actually happened?
Can only figure out how to return anything but HTML/template code

### Steps to Reproduce the Problem
Please detail your steps here

1.Current value is `[ "Josh Kirby", "Josh Kirby 2" ]`

Would like to display an ordered list inside the table field

Currently have

```
{
	label: 'Name',
	field: this.formatNames,
	width: '25%',
	tdClass: 'text-center text-nowrap',
	thClass: 'text-center text-nowrap'
}

// Unsure what to do here
formatNames(names) {
			
}
```

In my data property of this.rows...

`[ "Josh Kirby", "Josh Kirby 2" ]`

**Comment by xaksis** [comment]
hey @joshk132 there's quite a lot of documentation on how to begin here: 
https://xaksis.github.io/vue-good-table/
