### ISSUE TITLE
Bug with pagination

### ISSUE THREAD

**Issue by tasselchof** [xaksis/vue-good-table#625]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
Last

### Expected Behavior
What did you expect to happen?

I expect to show page 3 in pagination panel

### Actual Behavior
What actually happened?

I see page number 1

### Steps to Reproduce the Problem
Please detail your steps here

1. I added parsing of the page from query string;
2. I open table and switch to page 3 (I am using pages mode)
3. I reload the application with URL: http://localhost:8080/#/delivery-manager/parcels?sort%5Bfield%5D=&sort%5Btype%5D=&page=3&perPage=25
4. As expected page 3 loaded (data actually coming from page 3), but down in input I have page 1: https://monosnap.com/file/EItgJKOBFV0FQ4wGkdzs8PSO2Swoco
5. The same issue with the "Rows per page" parameter.

**Comment by xaksis** [comment]
Same as #634. will be fixed shortly.
