### ISSUE TITLE
When clicking on a table row with checkbox the table ordering is redone using value of "initialSortBy"

### ISSUE THREAD

**Issue by thiagovella** [xaksis/vue-good-table#626]
- [x] Bug

### Specs
What version are you using?
2.18.0

What browser?
Firefox v69.9.2(64-bits)

### Expected Behavior
By sorting the table by a column different than the initial set, I expected that when a row was selected the sorting would be maintained.

### Actual Behavior
Every time I click on a row the table ordering is redone using the initial value.

### Steps to Reproduce the Problem
1. Customize VGT with checkbox table. Example:
                    :selectOptions="{
                                enabled: true,
                                selectOnCheckboxOnly: true, 
                                selectionInfoClass: 'custom-class',
                                selectionText: 'rows selected',
                                clearSelectionText: 'clear',
                              }"

2. Enable "initialSortBy" option. Example:
                               :sort-options="{
                                enabled: true,
                                initialSortBy: {field: 'name', type: 'asc'}
                                }"
3. Choose another column to sort and select any row.

**Comment by HaydenHodge** [comment]
I am also noticing this, seems like it has been around since version 2.17.5. The change that caused it: Table.vue#495; the 'if' statement being commented out. I wonder why this decision was made?

    sortOptions: {
      handler(newValue, oldValue) {
        // if (!isEqual(newValue, oldValue)) {
        this.initializeSort();
        // }
      },
      deep: true,
    },

**Comment by thiagovella** [comment]
@HaydenHodge , Initially I was using version 2.16.5, and also had the same problem, I'm reporting on this latest version because I decided to upgrading to version (2.18.0) and the problem happened the same way ...

**Comment by TheJaredWilcurt** [comment]
Updated to 2.18.0 today (from 2.17.4). My tests started breaking, and after MUCH console logging, I tracked it down to:

```js
      handler: function handler(newValue, oldValue) {
        console.log('sortOptions: handler');
        console.log('newValue', newValue.enabled, newValue.initialSortBy.field, newValue.initialSortBy.type);
        console.log('oldValue', oldValue.enabled, oldValue.initialSortBy.field, oldValue.initialSortBy.type);
        if (!lodash_isequal(newValue, oldValue)) {
          this.initializeSort();
        }
      },
      deep: true
    },
```

Found the new and old values were identical, so I put the `!lodash_isequal` back in and it fixed 3 of my failing tests.

@xaksis is there any need to reinitialize the sort if the sort options have not changed?
