### ISSUE TITLE
With pagination 'position' set to 'both', changing pages does not update other pagination section

### ISSUE THREAD

**Issue by dylanvanes** [xaksis/vue-good-table#631]
### Issue Type

- [x] Bug

### Specs
What version are you using?

2.18.0

What browser?

All

### Expected Behavior
What did you expect to happen?

Changing pages would update the pagination details at both the top and bottom of the table. i.e. "1 of 20" would become "2 of 20" in both section.

### Actual Behavior
What actually happened?

If you change the page at the top of the table, the pagination details at the bottom of the table do not update. So if you go from page 1 to page 2 at the top of the table, the bottom of the table will still read "1 of 20". The same thing occurs if the change the "Rows per page" value.

### Steps to Reproduce the Problem

1. Use these pagination options:
```
:pagination-options="{
    enabled: true,
    mode: 'pages',
    position: 'both',
    perPage: 3
}"
```
2. Change the page number and the "Rows per page" value at the top of the table.
3. See that the pagination options at the bottom of the table have not updated.

### jsfiddle
https://jsfiddle.net/dylanvanes/bt2h4Lkd/

**Comment by xaksis** [comment]
@dylanvanes yeah, this is not currently available. 'both' is not an officially supported option for position: 
https://xaksis.github.io/vue-good-table/guide/configuration/pagination-options.html#position
Currently, VGT only supports top or bottom.

closing.

**Comment by gathuku** [comment]
Hi @xaksis any plans to add `both` option in pagination position.

**Comment by mgd722** [comment]
@xaksis would you accept a PR for this?
