### ISSUE TITLE
Custom perPage dropdown gets reset when selecting new perPage number from dropdown

### ISSUE THREAD

**Issue by DerekNMartin** [xaksis/vue-good-table#634]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.18

What browser?
Chrome Version 78.0.3904.70 (Official Build) (64-bit)

### Expected Behavior
What did you expect to happen?
In remote mode.
When selecting from a custom set `perPageDropdown` I should be able to change the number of items per page, and it should remain, rather than switching back to the default number.

### Actual Behavior
What actually happened?

When selecting from the dropdown of perPage, the page will load the right amount of records, and display the correct amount of pages, but after loading the records, the perPage dropdown will switch back to the default number which also changes the total number of pages.

### Steps to Reproduce the Problem
Please detail your steps here

1. Have server mode on, and have a custom perPageDropdown array
2. Change the perPage from ex. 10 to 100
3. Table will populate
4. perPage gets set back to 10 automatically

**Comment by kramer99** [comment]
Same thing happening here.

**Comment by julen-folky** [comment]
Me too. Besides, the total number of pages does not change.
