### ISSUE TITLE
FilterDropDown set wrong type

### ISSUE THREAD

**Issue by ivanlunardi** [xaksis/vue-good-table#637]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.18.0
What browser?
Chrome
### Expected Behavior
when i tried to use filter dropdown i'm expecting the type of filter is equal of definition of filed
### Actual Behavior

if the colums type is defined number and with filterDropdownItems = [{value:100,text:"100"},{value:200,text:"200"}]
the @on-column-filter return a string instead a number

### Steps to Reproduce the Problem
Please detail your steps here

1 define a table with a column with filterDropdown like [{value:10,text:"100"},{value:20,text:"200"}]
1. when you select "100" a value in @on-column-filter a received { columnFilter : {field : "10" }}
instead of { columnFilter : {field : 10 }}

Note: the field is in a nestedObject

**Comment by xaksis** [comment]
@ivanlunardi the on-column-filter event emits the option value for <select> element. for your spec, the resulting option tag will be:

```
<option value="10">10</option>
```

As you can see, only strings are allowed for value attributes. Which is what you'd get on the on-change event. We don't do anything special here.

Closing.
