### ISSUE TITLE
formattedRow is empty and Date in the column is not converted.

### ISSUE THREAD

**Issue by 2rohith2** [xaksis/vue-good-table#65]
Data from the server:
````javascript
[{"fullname":"Rohith Kumar","email":"mail@gmail.com","gender":"m","telephone":"8888888888","altertelephone":"5555555555","address":"address","dob":"1990-01-01","signon":"2017-07-31T10:14:01.198Z","active":true,"admin":true}]
````
---

Data from `vue-good-table` `props.row`
```
{ "row": { "fullname": "R k", "email": "as@asfm12.com", "gender": "m", "telephone": "1321321321", "altertelephone": "", "address": "s", "dob": "1985-02-02", "signon": "2017-08-07T08:23:20.809Z", "active": false, "admin": false }, "formattedRow": { "fullname": "", "email": "", "gender": "", "telephone": "", "altertelephone": "", "address": "", "dob": "", "signon": "", "active": "", "admin": "" }, "index": 1 }
```
---
Table Configuration

```javascript
<vue-good-table
		title="User"
		:columns="columns"
		:rows="rows"
		:lineNumbers="true"
		:defaultSortBy="{field: 'fullname', type: 'asc'}"
		:globalSearch="true"
		:paginate="true"
		styleClass="table table-bordered table-striped">
		<template slot="table-row" scope="props">
			<td>{{ props.row.fullname }}</td>
			<td>{{ props.row.email }}</td>
			<td align="center">
				<i v-if="props.row.gender == 'm'" class="fa fa-male fa-2x" aria-hidden="true"></i>
				<i v-if="props.row.gender == 'f'" class="fa fa-female fa-2x" aria-hidden="true"></i>
			</td>
			<td>{{ props.row.telephone }}</td>
			<td>{{ props.row.address }}</td>
			<td>{{ props.row.dob}}</td>
			<td align="center">
				<i v-if="props.row.active == true" class="fa fa-check-square-o fa-2x text-success" aria-hidden="true"></i>
				<i v-if="props.row.active == false" class="fa fa-ban fa-2x text-danger" aria-hidden="true"></i>
			</td>
			<td align="center">
				<i v-if="props.row.admin == true" class="fa fa-check-square-o fa-2x text-success" aria-hidden="true"></i>
				<i v-if="props.row.admin == false" class="fa fa-ban fa-2x text-danger" aria-hidden="true"></i>
			</td>
			<td>{{ props.row.signon}}</td>
			<td><button @click="edit(props.row.id)">Edit</button></td>
			<td><button @click="delete(props.row.id)">Delete</button></td>
		</template>
	</vue-good-table>
```
---
Column:

```javascript
columns: [
	{
		label: 'Name',
		field: 'fullname',
		filterable: true
	},
	{
		label: 'Email ID',
		field: 'email',
		filterable: true
	},
	{
		label: 'Gender',
		field: 'gender',
		filterable: true
	},
	{
		label: 'Telephone',
		field: 'telephone',
		filterable: true
	},
	{
		label: 'Address',
		field: 'address',
		filterable: true
	},
	{
		label: 'DOB',
		field: 'dob',
		type: 'date',
		inputFormat: 'YYYY-MM-DD',
		outputFormat: 'Do MMM YY',
		filterable: true
	},
	{
		label: 'Active',
		field: 'active',
		filterable: true
	},
	{
		label: 'Admin',
		field: 'admin',
		filterable: true
	},
	{
		label: 'Registered',
		field: 'signon',
		type: 'date',
		inputFormat: 'YYYY-MM-DDTHH:mm:ss.sssZ',
		outputFormat: 'Do MMM YY',
		filterable: true
	},
	{
		label: 'Edit',
		filterable: false
	},
	{
		label: 'Delete',
		filterable: false
	}
],
```
---
**Screen Shot**
In this screen shot, I didn't use `props.formattedRow.dob` because the column will be empty.
![image](https://user-images.githubusercontent.com/5773985/30199267-94d43b58-948f-11e7-9086-d3701aedf9f5.png)

Another issue is in the column header **DOB** and **Registered** is aligned to **right**, it should be **left** aligned.

**Comment by xaksis** [comment]
@2rohith2 what version of the plugin are you using?

**Comment by 2rohith2** [comment]
@xaksis I am using `"vue-good-table": "^1.10.1",`
I just installed using `npm install --save vue-good-table`

**Comment by xaksis** [comment]
@2rohith2 please update your plugin to see formattedRows. 
also, since you're using dynamic templates... component has no control over your html so you can right/left align as you want by directly manipulating the html tags - <td>

closing.

**Comment by 2rohith2** [comment]
@xaksis I have updated the package to `"vue-good-table": "^1.12.0",` still issue is not fixed.
I am talking about the `formattedRow`

**Comment by 2rohith2** [comment]
>>> component has no control over your html so you can right/left align as you want by directly manipulating the html tags

How can I do this?

Ex: `<td align="left">{{ props.row.dob}}</td>` If I use this the data in the row is aligned to left not the table header.

**Comment by 2rohith2** [comment]
>>> component has no control over your html so you can right/left align as you want by directly manipulating the html tags

How can I apply alignment to the table header?

**Comment by xaksis** [comment]
@2rohith2 can you post your code regarding formattedRow? once you update make sure you re-run the vue project. 

the reason why headers for DOB and Registered are right aligned is because they are both dates. It's good UX practice to keep dates right aligned for easy comparisons down a column. (same reason why numbers are right aligned). 

If you really want them to be left aligned, you can use the thClass property to give them your own class.

**Comment by 2rohith2** [comment]
@xaksis I have already posted my code in the issue.
Please let me know if you need more information.

**Comment by xaksis** [comment]
I don't see any reference to formattedRow in your code.

**Comment by 2rohith2** [comment]
Code: `<td>{{ props.formattedRow.dob}}</td>`
If I use the above reference, the `dob` column is empty in my table.

Data from `vue-good-table` `props.row`
```
{ "row": { "fullname": "R k", "email": "as@asfm12.com", "gender": "m", "telephone": "1321321321", "altertelephone": "", "address": "s", "dob": "1985-02-02", "signon": "2017-08-07T08:23:20.809Z", "active": false, "admin": false }, "formattedRow": { "fullname": "", "email": "", "gender": "", "telephone": "", "altertelephone": "", "address": "", "dob": "", "signon": "", "active": "", "admin": "" }, "index": 1 }
```

**Comment by xaksis** [comment]
here's what i'm seeing with your data for `props.formattedRow.dob`: 
`2nd Feb 85`

```html
  <vue-good-table
      :columns="columns"
      :paginate="true"
      :rows="rows">
      <template slot="table-row" scope="props">
        <td>{{ props.formattedRow.dob }}</td>
      </template>
    </vue-good-table>
```

so the only thing I can think of as to why this isn't working is that your build has cached an older version of the plugin. Current version of the plugin seems to be working fine for all my tests.

**Comment by 2rohith2** [comment]
@xaksis I have cloned my project again, set it up newly but still, `formattedRow` is not working.
My `DOB` & `Registered` column is empty.

![image](https://user-images.githubusercontent.com/5773985/30263277-e82d82dc-96f1-11e7-8cf2-e51801501f96.png)

**Comment by xaksis** [comment]
@2rohith2 I actually was finally able to replicate the date bug where formattedRow is blank. I added a fix in version 1.14.1. That should fix it for you. Sorry about not being able to do this earlier.

**Comment by 2rohith2** [comment]
@xaksis Thank you!!!

But still, your fix is not working properly.
Please find the below screenshot.

![image](https://user-images.githubusercontent.com/5773985/30950881-3aa5a532-a43d-11e7-8d19-21d6c2d06f79.png)

`DOB` column is `left-aligned` instead of `right align`
`Registered` column has `Invalid Date` when I use ISO Date String.
Ex: 2017-07-31T10:14:01.198Z

Please re-open this issue.

**Comment by xaksis** [comment]
@2rohith2 
for alignment, like i mentioned before, if you're using custom row template, you'll have to align the td content yourself. The whole point of custom rows is to allow you to format the rows yourself. 

secondly, your inputFormat for Registered date is wrong. you should use: `YYYY-MM-DDTHH:mm:ss.SSS` and it'll work fine.
