### ISSUE TITLE
Async column styling

### ISSUE THREAD

**Issue by dcrystalj** [xaksis/vue-good-table#653]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [ ] Enhancement Request
- [ ] Question

### Specs
2.18

Chrome

### Expected Behavior
Apply styling on async columns settings.

### Actual Behavior
Width is not applied

### Steps to Reproduce the Problem

1. Set columns after table is rendered
1. Set prop `width: '500px' of one column
1. There should be table with column 500px but it is not unless you do screen resize.

### jsfiddle
https://jsfiddle.net/dcrystalj/05yrn78a/3/

**Comment by TheJaredWilcurt** [comment]
@dcrystalj This should be fixed in the latest release
