### ISSUE TITLE
@on-per-page-change event getting called twice

### ISSUE THREAD

**Issue by ali19vinit15project** [xaksis/vue-good-table#654]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
^2.18.1

What browser?
Chrome

### Expected Behavior
What did you expect to happen?
Getting called only once when I change the Per page dowpdown

### Actual Behavior
What actually happened?
Method gets called twice

### Steps to Reproduce the Problem
Please detail your steps here

1.Using
![image](https://user-images.githubusercontent.com/54504755/72278632-6bb1ea80-365a-11ea-8867-1d74d9bc312b.png)

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

`<vue-good-table
      mode="remote"
      @on-search="onSearch"
      @on-page-change="onPageChange"
      @on-sort-change="onSortChange"
      @on-column-filter="onColumnFilter"
      @on-per-page-change="onPerPageChange"
      :totalRows="totalRecords"
      :isLoading.sync="isLoading"
      ref="my-table"
      :columns="columns"
      :rows="rows"
      :line-numbers="true"
      :search-options="searchOptions"
      :sort-options="sortOptions"
      :pagination-options="paginationOptions"
      :select-options="selectOptions"
      @on-selected-rows-change="selectionChanged"
      styleClass="vgt-table striped bordered"
      >
      <div slot="table-actions">
        <router-link to="/employee" class="btn btn-primary btn-sm" tag="button">Add</router-link>&nbsp;
      </div>

      <template slot="table-row" slot-scope="props">

        <span v-if="props.column.field == 'edit'">        
          <router-link :to="{ name: 'Profile', params: { empId: props.row.id } }" class="ti-pencil" tag="a"></router-link>&nbsp;          
        </span>  
        <span v-else-if="props.column.field == 'photo'">        
          <img class="w-100 rounded-circle" :src= "props.row.photo">       
        </span> 
        <span v-else>
          {{props.formattedRow[props.column.field]}}
        </span>
      </template>
    </vue-good-table>`

**Comment by xaksis** [comment]
2.21.9 should fix this.
