### ISSUE TITLE
Support passing filter cell as a slot

### ISSUE THREAD

**Issue by zwx00** [xaksis/vue-good-table#655]
### Issue Type

- [x] Enhancement Request

### Specs
Any.

### Expected Behavior
I want to style the filter cell. In particular, I wish it were exposed in the same way other cells are (via scoped slots), so that I can provide my own widget. One particular use case for this is date input which is very hard to do by hand, especially if the table is server side. In this case, I'd rather provide a datepicker widget for our users.
 
### Actual Behavior
Filter field cannot be customized beyond converting it to a select field.

**Comment by xaksis** [comment]
consolidating with #675

**Comment by TheJaredWilcurt** [comment]
@zwx00 

As of [v2.21.0](https://github.com/xaksis/vue-good-table/releases/tag/v2.21.0) this feature is now available.

* [Docs for using custom filter slot](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)
