### ISSUE TITLE
Change cell background color in template

### ISSUE THREAD

**Issue by Hraph** [xaksis/vue-good-table#659]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.18.1
### Question
I would like to change the background-color of a column cell dynamically. Is there a way to do that in the table-row template? The only example available is for changing the font color of the cell span inside the <td>
Thanks

**Comment by rajatjain3571** [comment]
@Hraph Did you found any solution for it. I am stuck on the same. I am trying to set color on the basis of data which i get from my api but haven't found anything to change colors of cells

**Comment by Hraph** [comment]
> @Hraph Did you found any solution for it. I am stuck on the same. I am trying to set color on the basis of data which i get from my api but haven't found anything to change colors of cells

I'm sorry but from what I remember of the project, I ended up abandoning the idea of changing the background color and using font color instead. Too bad @xaksis didn't respond to the issue.
I'll be happy to know how to do it. GL

**Comment by xaksis** [comment]
@Hraph @rajatjain3571 this can be done with some basic CSS. Here's an example: 
https://jsfiddle.net/aks9800/ou1cLpy8/

closing.

**Comment by rajatjain3571** [comment]
@xaksis Thanks a lot. It worked for me
