### ISSUE TITLE
Required Functionality Request: How to make the dynamic table responsive.

### ISSUE THREAD

**Issue by 2rohith2** [xaksis/vue-good-table#66]
@xaksis One of the columns in the table has more data to be displayed.
How I can make the table responsive i.e there should be no `Horizontal` scroll bar, this feature is required because the table can be viewed on different screens.

Ex: `DataTable` has a very good implementation to make the table responsive.
https://datatables.net/extensions/responsive/examples/styling/bootstrap4.html

Let me know your views on this feature.

**Comment by 2rohith2** [comment]
@xaksis Any update on this?

**Comment by xaksis** [comment]
Hey @2rohith2 this is not in the plans anytime soon. You are welcome to take a stab at it though. I'll be happy to review a pull request.
