### ISSUE TITLE
Drop Down Filterables no longer work

### ISSUE THREAD

**Issue by TheScree** [xaksis/vue-good-table#661]
Bug

### Specs
  "dependencies": {
    "@nuxtjs/axios": "^5.5.4",
    "@nuxtjs/google-analytics": "^2.2.3",
    "nuxt": "^2.8.1",
    "nuxt-webfontloader": "^1.1.0",
    "vue-good-table": "^2.16.5"
  },
  "devDependencies": {
    "@nuxtjs/tailwindcss": "^1.0.0",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-prettier": "^3.0.1",
    "nuxt-purgecss": "^0.2.1",
    "prettier": "^1.16.4"
  }

What browser?
Chrome Version 80.0.3987.87 (Official Build) (64-bit)

### Expected Behavior
When I select from a list of drop down items, rows should appear or disappear when selected.

### Actual Behavior
All rows vanished when selecting an item.

### Steps to Reproduce the Problem
Tried two different drop down list configurations;
```
          filterOptions: {
            enabled: true,
            filterDropdownItems: [
              { value: 'major', text: 'Major' },
              { value: 'minor', text: 'Minor' },
              { value: 'exploration', text: 'Exploration' }
            ]
          }
```
as well as the more basic version:
```
          filterOptions: {
            enabled: true,
            filterDropdownItems: ['major', 'minor', 'exploration' ]
          }
```

1.  Neither were able to find plain text equivalents in the rows beneath the filter
2.  Selecting any option caused all rows to be disqualified/not-match and were hidden.

The latest Nuxt version required the following change to account for updates to the platform. The table properly loads and can be used, with the exception of this filter issue with a small change in the Nuxt instructions you provide.

In the nuxt.config.js file you need to change the line to read as:

`plugins: [{ src: '~/plugins/vue-good-table', mode: 'client' }],`

note that "ssr: false" is no longer a valid option for a plugin item.

**Comment by xaksis** [comment]
closing, should be fixed now.
