### ISSUE TITLE
Is the VGT Dead?

### ISSUE THREAD

**Issue by TheJaredWilcurt** [xaksis/vue-good-table#663]
Hey @xaksis

Been using VGT for like 2 years at work. There are a few PR's we were looking forward to being merged so we could use those features:

* https://github.com/xaksis/vue-good-table/pull/587
* https://github.com/xaksis/vue-good-table/pull/641

Wanted to know what the status was for the project. Do you need help maintaining it? Should we just fork it and merge those PR's into our fork and use the fork at work for the time being? Should we maintain the fork in a way that can be merged back into this repo?

**Comment by xaksis** [comment]
@TheJaredWilcurt, I'm going to add you as a contributor if you want to help maintain it. Is that okay?

**Comment by xaksis** [comment]
Done! You're now a collaborator @TheJaredWilcurt. Go forth and make the changes community requires.
