### ISSUE TITLE
Build/Release request

### ISSUE THREAD

**Issue by TheJaredWilcurt** [xaksis/vue-good-table#667]
@xaksis 

2 new features and 1 bug fix have been merged to `master`:

* https://github.com/xaksis/vue-good-table/pull/587 - Add multiselect filter
* https://github.com/xaksis/vue-good-table/pull/641 - Collapsable groups
* https://github.com/xaksis/vue-good-table/pull/666 - Async column styling

Can you do a build/release to npm?

**Comment by xaksis** [comment]
done!
