### ISSUE TITLE
sass cannot compile in version v2.19.0

### ISSUE THREAD

**Issue by serakfalcon** [xaksis/vue-good-table#672]
### Issue Type (delete the irrelevant ones) 
- [x] Bug
### Specs
What version are you using? v2.19.0

What browser? n/a
### Expected Behavior
What did you expect to happen? Sass should be able to compile using the following file: https://github.com/xaksis/vue-good-table/blob/master/src/styles/style.scss

### Actual Behavior
What actually happened? Sass could not compile due to incorrect linkage in line 2.

Existing line:

@import "../../node_modules/vue-select/dist/vue-select";

What it should be:

@import "../../../vue-select/dist/vue-select";

As is, Sass cannot compile.

**Comment by xaksis** [comment]
@serakfalcon thank you for reporting this. @cassmbautista
