### ISSUE TITLE
Slots for custom filters

### ISSUE THREAD

**Issue by davidjr82** [xaksis/vue-good-table#675]
@TheJaredWilcurt I am openning this ticket to discuss the idea expressed in #668 as @xaksis suggested.

The point is that recently, the multiselect filter has been merged in #587. Although this is really nice, it has downsides too:

- Users only can use this multiselect component, and not other one if they would want to.
- Package has more kb, even a user doesn't want to use it.

Imagine a user now wants to have a date filter, and submit a PR with it. Other wants a range date filter. More PRs.

If we can use a slot to provide the filter each user wants, we can keep the package slim, and let the users to use the filter they want, and provide an example in docs for a "default filter" if they want to use a standard filter.

There are other opened issues that could be closed with this implementation, for instance, #664 #661 and more. Something good of this approach is that the maintainance of the filters wouldn't be on our side, but in the user side.

I would like to do it by myself, but I am beginning recently with this library and I feel that I don't have enough knowledge of it to make those changes.

Thanks!

**Comment by TheJaredWilcurt** [comment]
This is a good idea. I don't have time to work on it at the moment however (traveling for work). But this is a better overall approach to what is currently in use. Accepting PRs.

**Comment by xaksis** [comment]
Consolidating, https://github.com/xaksis/vue-good-table/issues/632, https://github.com/xaksis/vue-good-table/issues/655,

**Comment by pres-camacho** [comment]
Since vue-good-table is a real benefit in our project and this feature really happens to be missing for us, i'd like to apply for this task.

**Comment by Josh-of-TT** [comment]
any movement here?

**Comment by robgaston1** [comment]
@Josh-of-TT (and @xaksis) I put a PR up for this. 

I added and exposed a function through the new slot so that users who want to can still have their custom filter values passed into the table. If that works out, I know it would be helpful for the way we use the table.

**Comment by TheJaredWilcurt** [comment]
@davidjr82 @pres-camacho @Josh-of-TT 

As of [v2.21.0](https://github.com/xaksis/vue-good-table/releases/tag/v2.21.0) `Vue-Select` is no longer a dependency of Vue-Good-Table.

We have replaced it with a new feature of a custom filter slot. You can now pass in any component for custom filtering. There is a migration guide for how to add Vue-Select to your project and get the same functionality back.

* [Docs for using custom filter slot](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)
* [Docs for migrating and adding Vue-Select back in to your table](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)

Closing this issue.
