### ISSUE TITLE
If All option is selected in per page dropdown, All option text disappears when filtering columns that change the value of all

### ISSUE THREAD

**Issue by jjmartucci** [xaksis/vue-good-table#676]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using? 2.19.1
What browser? Checked in Chrome, Firefox, and Safari on MacOS

### Expected Behavior
Per page dropdown text should remain visible even when changing results using column filters.

### Actual Behavior
"All" option text disappears when filtering a column that causes the value of "All" to change.

### Steps to Reproduce the Problem
Please detail your steps here

When using the `dropdownAllowAll: true`
1. Select "All" on the per page drop down. i
2. Filter a column so the total number of records associated with "All" changes
3. The "All" text will no longer be visible in the dropdown but will still be selected.

### jsfiddle
https://codesandbox.io/s/xenodochial-spence-gwbir

**Comment by TheJaredWilcurt** [comment]
PR merged, assuming this can be closed. Reopen otherwise.
