### ISSUE TITLE
Is table filtered

### ISSUE THREAD

**Issue by hansen168** [xaksis/vue-good-table#677]
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using?
Latest

What browser?
Chrome

### Expected Behavior
Is there anyway to know if a table has filter? something like isFiltered...

**Comment by TheJaredWilcurt** [comment]
@hansen168

* https://xaksis.github.io/vue-good-table/guide/configuration/table-events.html#on-column-filter

```html
<vue-good-table
  :columns="columns"
  :rows="rows"
  @onColumnFilter="(params) => { isFiltered = !!Object.keys(params).length }"
/>
```
```js
data: function () {
  return {
    isFiltered: false
  };
}
```
`params` will either contain the filters, like so `{ field1: 'filterTerm', field3: 'filterTerm2' }`, or be an empty object `{}`.

So `Object.keys(params)` will either be `['field1', 'field3']` or `[]`.

So `Object.keys(params).length` will either be `2` or `0`.

So `!!Object.keys(params).length` will either be `true` or `false`.
