### ISSUE TITLE
Set initial value of multiselect filters

### ISSUE THREAD

**Issue by Lynne-Daniels** [xaksis/vue-good-table#678]
I'm very happy see the recent addition of multiselect filter dropdown menus, but have a question about how I might set the initial values. 

Single Selects
`this.$set(this.columns[foundIndex].filterOptions, 'filterValue', this.$route.query[key]);`

I am using the pattern in https://github.com/xaksis/vue-good-table/issues/475#issuecomment-518040333 to set initial filters to match a url query, but have not been able to make this work with any multiselects.  Is there a way to access and change the selections in this new feature?

Multi Selects
`???`

**Comment by xaksis** [comment]
@cassmbautista @TheJaredWilcurt Please take a look.

**Comment by TheJaredWilcurt** [comment]
@Lynne-Daniels 

As of [v2.21.0](https://github.com/xaksis/vue-good-table/releases/tag/v2.21.0) `Vue-Select` is no longer a dependency of Vue-Good-Table.

We have replaced it with a new feature of a custom filter slot. You can now pass in any component for custom filtering. There is a migration guide for how to add Vue-Select to your project and get the same functionality back. Using Vue-Select directly will give you greater control of it. So you could, for example, set it's initial filter value!

* [Docs for using custom filter slot](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)
* [Docs for migrating and adding Vue-Select back in to your table](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)

Closing this issue.
