### ISSUE TITLE
is there 'enum' type for columns?

### ISSUE THREAD

**Issue by btalaei** [xaksis/vue-good-table#681]
Question: 

is there '**enum**' type for columns?
i did not find Enum type for columns and try to write my own function for sorting such columns with  **sortFn** but it does not work or me!

**Comment by TheJaredWilcurt** [comment]
I'm not sure what you are actually asking for. there is no `enum` type in JavaScript. So you are forcing me to assume that you are referring to the concept of enumeration, which is extremely vague. If you read the wikipedia article for it, you will find that what you think of as "enumeration" is just an arbitrary set of restrictions chosen by a programming language. These restrictions vary greatly from language to language, basically making the term pointless if in regards to a language that has not defined it's own meaning of what an `enum` is.

* https://en.wikipedia.org/wiki/Enumerated_type

Can you remove the word `enum` from your request, and instead, describe with detail and specificity exactly what feature you are requesting?

**Comment by xaksis** [comment]
closing.
