### ISSUE TITLE
bug table.reset()

### ISSUE THREAD

**Issue by xdecow** [xaksis/vue-good-table#685]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.19.1

What browser?
chrome 80

### Expected Behavior
reset table filters and receive event filter-changed

### Actual Behavior
the filters are reset but the event is not emitted
TypeError: Cannot read property 'forEach' of undefined

### Steps to Reproduce the Problem

1. create a table that has filters other than multiselect
2. create a button that uses table.reset()

### jsfiddle
https://jsfiddle.net/xdecow/5qLyhsfe/10/

## note
In VgtFilterRow, the ref = "vgt-multiselect" is declared within an IF
you need to check if the instance exists before using foreach (line 108)

current:
```
function reset(emitEvent = false) {
      this.columnFilters = {};

      // Clear the selection in the multiselect
      this.$refs['vgt-multiselect'].forEach((ref) => {
        ref.clearSelection();
      });

      if (emitEvent) {
        this.$emit('filter-changed', this.columnFilters);
      }
    },
```
to:

```
function reset() {
      var emitEvent = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : false;
      this.columnFilters = {}; // Clear the selection in the multiselect

      if ('vgt-multiselect' in this.$refs) {
        this.$refs['vgt-multiselect'].forEach(function (ref) {
          ref.clearSelection();
        });
      }

      if (emitEvent) {
        this.$emit('filter-changed', this.columnFilters);
      }
    },
```

**Comment by phena109** [comment]
I can confirm this is the case as I also run into the same issue. My application does not even activated any select functions.

**Comment by xaksis** [comment]
I think this has been fixed. Will close once the new version is rolled out to npm.
