### ISSUE TITLE
How to add data without create each columns by name?

### ISSUE THREAD

**Issue by thdung002** [xaksis/vue-good-table#686]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
v2.19.1
What browser?
Not tested yet

I have a question that I get a data array[{}] from database with some merge, sort computed. Then what I need to add to the component automatically without create by hand each column/ with name, types, etc....
How to just add a data to it and working? If not sorry to bother!

**Comment by xaksis** [comment]
hey @thdung002 without knowing what your array is it's tough to give you a suggestion here. However to answer your question, plugin expects a certain format for column and rows so you'd have to supply it in the correct format for it to work. 

you can read more about it here: https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#label

closing.
