### ISSUE TITLE
Date type column format issue

### ISSUE THREAD

**Issue by mgattelli** [xaksis/vue-good-table#69]
Hi @xaksis 
First of all.... your component is really **good** as the name say :)

I'm having the following issue:
the input format for a column is a Date String with the following format `DD-MM-YYYY HH:mm:ss` but the date-fns parse can't parse my input string and, of course, the output is not the expected.

My column configuration is:
```javascript
{
      ....
},
{
	label: 'Created at',
	field: 'creationDateF',
	type: 'date',
	inputFormat: 'DD-MM-YYYY HH:mm:ss', //e.g. 07-09-2017 19:16:25
	outputFormat: 'DD-MM-YYYY HH:mm:ss'
},
{
     .....
}
```

I'm using the version `"vue-good-table": "^1.10.1"` the one installed using the npm command.

**Comment by xaksis** [comment]
hey @mgattelli do you mind posting some of your data rows, so I can replicate it on my end?

**Comment by xaksis** [comment]
here's what i'm using
```html
<template>
  <div>
    <vue-good-table
      :columns="columns"
      :paginate="true"
      :rows="rows"/>
  </div>
</template>

<script>
  import Vue from 'vue';
  import VueGoodTable from '../src/index';
  Vue.use(VueGoodTable);
  export default {
    name: 'test',
    data(){
      return {
        searchTerm: null,
        columns: [
          {
            label: 'Name',
            field: 'name',
          },
          {
            label: 'Age',
            field: 'age',
            type: 'number',
          },
          {
            label: 'Created at',
            field: 'creationDateF',
            type: 'date',
            inputFormat: 'DD-MM-YYYY HH:mm:ss', //e.g. 07-09-2017 19:16:25
            outputFormat: 'DD-MM-YYYY HH:mm:ss'
          }
        ],
        rows: [
          {name: "John", age: "20", creationDateF: "07-09-2017 19:16:25"},
          {name: "Jane", age: "24", creationDateF: "09-10-2017 19:16:25"},
        ],
      };
    },
  };
</script>
```
here's my output: 

Name | Age | Created at
-- | -- | --
John | 20 | 09-07-2017 19:16:25
Jane | 24 | 10-09-2017 19:16:25

Let me know if you're doing something different.

**Comment by mgattelli** [comment]
Sorry for the delay and really thanks for the quick response @xaksis 

You pointed out the exact problem.

As you can see the input date String is in format **DD-MM-YYYY HH:mm:ss** (e.g. 07-09-2017 19:16:25 where 07 is the day, 09 is the month and so on) so why the output string is formatted as **MM**-DD-YYYY HH:mm:ss (`09-07-2017 19:16:25`)?

My rows are more or less like the ones you posted.

**Comment by xaksis** [comment]
@mgattelli very interesting... looks like this is a date-fns issue. I'll check to see if they have a ticket for this already.

**Comment by mgattelli** [comment]
Hola @xaksis 

I found something interesting.

In order to parse the input date string you are using the method **parse** of the date-fns version `1.28.5` and in the [documentation](https://date-fns.org/v1.28.5/docs/parse) there's no information about the format string as the second argument... **_but_** it seems that the date-fns team works on another **parse** function that they will include in the version `2.0.0` (you can find the documentation [here](https://date-fns.org/v2.0.0-alpha.2/docs/parse)) and it works as we expected ([here](https://github.com/date-fns/date-fns/issues/219) you can find the discussion).

Will you use the `2.0.0-alpha.2` in order to solve the problem?

**Comment by xaksis** [comment]
@mgattelli thank you for the suggestions and debugging. I'll look into that tonight.

**Comment by xaksis** [comment]
@mgattelli v1.12.3 contains the alpha release of date-fns. Should fix this issue. Thanks for your help!

**Comment by cesarlinux** [comment]
Hi, after a research for a vuejs table component that accomplish with most of my wanted features, I decided to use this excellent tool, so I'm a newcomer to vue-good-table and I'm getting date format problems too, my data is as follows "2020-06-27 14:21:09" with format "yyyy-MM-dd hh:mm:ss" and the desired output is "dd-MM-yyyy" so the above date will be "27-06-2020"
Here's my [jsfiddle](https://jsfiddle.net/tz3ud5vr/) 
Some help please?

**Comment by xaksis** [comment]
hey @cesarlinux if you look at the docs, it links to the relevant datefns page: 
https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#dateinputformat
As it mentions there, the datefns format page is: 
https://date-fns.org/v2.0.0-beta.4/docs/parse

Now looking at that, in your jsfiddle you have for example, '2017-10-11', the column definition would be: 
```
{
      label: 'DateTime',
      field: 'datetime',
      type: 'date',
      dateInputFormat: 'yyyy-MM-dd',
      dateOutputFormat: 'dd-MM-yyyy'
    },
```
notice that you had a bug where you were calling it `inputFormat` when the property is `dateInputFormat`. And the casing for format was wrong. 

Hope this helps. Also, for future reference, please don't comment on a closed ticket. It becomes more likely to get ignored if the ticket is already closed.

**Comment by cesarlinux** [comment]
Many thanks by the quick response @xaksis !!!
with your comment I made the corrections in a new 
[jsfiddle](https://jsfiddle.net/ts7fewkh) and it's working like charm!
Also in my code.
Thanks!

**Comment by yogithesymbian** [comment]
how about format 
```
// 2024-03-12T14:15:00.000Z // this data string
// dateInputFormat: 'yyyy-MM-ddTHH:mm:ss',
          dateInputFormat: 'yyyy-MM-ddHH:mm:ss.000Z',
```
i can only format directly on scope

**Comment by yogithesymbian** [comment]
for example 
```
{
          label: 'Time',
          field: 'time',
formatFn: this.dateHumanReadAble
```
methods
```
dateHumanReadAble(value) {
      const format = moment(value).format('D MMMM YYYY - hh:mm A')
      if (format === 'Invalid date') {
        return 'Belum Diisi ❗️'
      }
      return format
    },
```

its work , but when search its only work with `2024-03-12T14:15:00.000Z`
