### ISSUE TITLE
How to use row buttons with  Checkbox Table

### ISSUE THREAD

**Issue by udaraz** [xaksis/vue-good-table#693]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using? 
2.19.1
What browser?
firefox

### Expected Behavior
What did you expect to happen?
I need to use buttons with checkbox table
### Actual Behavior
What actually happened?
It's select the row (checkbox) when I click on the button
### Steps to Reproduce the Problem
Please detail your steps here

1.Use check box table
2.Then try to use buttons inside rows

**Comment by udaraz** [comment]
I have fixed it like this
`<a href="javascript:void(0)" @click.stop="editRecord(props.row)">`

**Comment by xaksis** [comment]
hey @udaraz, you can use row templates to customize the rows and add buttons or whatever you wish to your rows. More info here: https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template

closing.
