### ISSUE TITLE
Is this still maintained? The documentation is outdated.

### ISSUE THREAD

**Issue by skillshrine** [xaksis/vue-good-table#695]
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using?
v2.19.1

### Question
As the subject. I am finding a lot of documentation inconsistencies. One example is the server side rendering section: https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html

The handler methods are not inline with the main Configuration options section (in particular sorting).

Also the Table Options columns section, lists a column type of 'filterable' which doesn't appear to work when specified. Instead Column Filter Options specifies an object which is set on a column.

Overall it's costing a lot of time to figure out precisely what is valid information and what is not.

**Comment by TheJaredWilcurt** [comment]
It's still maintained, documentation is hard, please create PR's when you find inconsistencies or things that are out of date,

**Comment by xaksis** [comment]
Totally agree with @TheJaredWilcurt. @skillshrine vue-good-table is complex and has quite a lot of customization options. Apart from doing our best to maintain it on our own, we depend on folks such as yourself who are benefiting from this library, to help us identify and resolve inconsistencies. Creating PRs is a great way to contribute and help the community.

closing.
