### ISSUE TITLE
Moment.js might produce big bundles

### ISSUE THREAD

**Issue by cristijora** [xaksis/vue-good-table#7]
Moment.js is well known for a very high size 
There are many issues around this https://github.com/moment/moment/issues/2373
I saw that vue-good-table uses moment only to format dates in a couple of places
A good alternative for such operations is https://github.com/date-fns/date-fns

With date-fns you can import only the functions you need (e.g format) and not import the whole library to do this operation. This helps a lot reducing the overall vue-good-table size when used in production.

Update:
Here is some proof:
Simple app (vue-cli wepback with vue only)
![clean](https://cloud.githubusercontent.com/assets/15955045/26752894/bb6f7dc8-4862-11e7-8aca-f5782ee7e5e1.PNG)

As you can see the vendor file has 60kb which contains only `Vue` basically

Same app with a very basic `vue-good-table` added
![vue-good-table](https://cloud.githubusercontent.com/assets/15955045/26752898/e5de9792-4862-11e7-9aa3-e7779e402c43.PNG)

Size went up from 60kb up to 688 kb because of moment.js

**Comment by xaksis** [comment]
Thank you for bringing this up @cristijora. Makes a lot of sense. Looking into it.

**Comment by xaksis** [comment]
v1.5.2 replaced moment with date-fns parse/format functions. Thank you @cristijora for the recommendation!
