### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by TheJaredWilcurt** [xaksis/vue-good-table#705]
@xaksis There have been a few things merged to master. Can we get a build for docs and dist and a version bump and a release?

* https://github.com/xaksis/vue-good-table/compare/v2.19.1...master

**Summary of changes:**

* Table Header Rows can now have custom classes applied. @robgaston1 
* Feature to maintain expanded rows based on passed in row keys. (Fixes all rows collapsing when any data in table changes, such as when used as a shopping cart). @robgaston1 #704 
* Fixes RTL sorting icon position: #690 @msjaber 
* Fixes a console error when vSelect is enabled but not in use on a table.
* General improvements to documentation, including #555 @vincentntang

**Comment by xaksis** [comment]
hey @TheJaredWilcurt yep! Going to take a look and release this weekend. 👍
