### ISSUE TITLE
CSS breaks all my other css v-select

### ISSUE THREAD

**Issue by vikramjhurry** [xaksis/vue-good-table#708]
Hello,
When I installed and imported vue-good-table and css in my project it affected my other v-select components rendering . Is there a solution for this. Am I doing something wrong - how to prevent this? Thanks

- [x] Question

### Specs
What version are you using?
Last version
What browser?
Chrome

### Expected Behavior
What did you expect to happen?
That it does not affect my other css
### Actual Behavior
What actually happened?
Affected all v-select style everywhere

### Steps to Reproduce the Problem
Please detail your steps here

1. 
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
@cassmbautista @TheJaredWilcurt looks like this is related to the multiselect PR, could you guys take a look?

**Comment by TheJaredWilcurt** [comment]
@vikramjhurry 

As of [v2.21.0](https://github.com/xaksis/vue-good-table/releases/tag/v2.21.0) `Vue-Select` is no longer a dependency of Vue-Good-Table, and thus does not ship with it's CSS anymore.

If you were using the `filterMultiselectDropdownItems` feature, there is a migration guide for how to add Vue-Select to your project and get the same functionality back by using a custom filter slot.

* [Docs for using custom filter slot](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)
* [Docs for migrating and adding Vue-Select back in to your table](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)

Closing this issue.
