### ISSUE TITLE
Option to ellipsize overflowing text in a table cell

### ISSUE THREAD

**Issue by barakamwakisha** [xaksis/vue-good-table#711]
### Issue Type
- [x] Enhancement Request

Please consider adding a customization option to dynamically ellipsize overflowing text (text that wraps onto a new line) in a table cell

**Comment by p0psicles** [comment]
Can't you just do this your self using css? You can use templates to add your own html/css to cells

**Comment by nicolastorgato** [comment]
@barakamwakisha Hi, how did you fix this? Because basically I need to apply overflow:hidden if a row text is too long, so that the text doesn't go on a new line. 
Thanks!

**Comment by barakamwakisha** [comment]
Hi @nicolastorgato, this should work

`.text-to-ellipsize {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
}`

You could also read more here [https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/](url)

**Comment by LovelyAndy** [comment]
@barakamwakisha I'm sure you've completely moved on from this, but where did you put that class? On your vue-good-table directly? I've chucked your code onto my in attempts to get it to work the same way, but messing with the `webkit-box` has proven to be quite difficult. 
If you have any tips on how you got your overflow working please let me know!
Cheers!
https://codesandbox.io/s/vue3-table-filter-forked-kqtlv6?file=/src/App.vue

**Comment by barakamwakisha** [comment]
Hi @LovelyAndy! I customized what's rendered in the table rows using the `table-row` slot.

 ```vue
<template>
  <div>
    <vue-good-table
     :columns="columns"
     :rows="rows"
    >
      <template slot="table-row">
         <div>
          <span class="text-to-ellipsize">Lengthy text that would otherwise overflow</span>
         </div>
      </template>
    </vue-good-table>
  </div>
</template>
 ```

You can find out more about customization from the [docs](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template)

**Comment by LovelyAndy** [comment]
@barakamwakisha Thanks a lot!
