### ISSUE TITLE
Search Time

### ISSUE THREAD

**Issue by imposs86** [xaksis/vue-good-table#712]
Question
Specs
What version are you using?
v2.19.1
What browser?
Not tested yet

I have a question that I get big data (approximately 20.000) from database. When i wanna search on the table, i can wait too long. I can use trigger: 'enter',skipDiacritics: true property. Is this another way to solve this problem?

**Comment by xaksis** [comment]
Can you give more details about this issue? 

- are you paging the data?
- is all the data frontloaded or are you making backend requests for searches?

Also, you might have better luck with use-case specific questions like these on stackoverflow.

**Comment by TheJaredWilcurt** [comment]
This is a duplicate of https://github.com/xaksis/vue-good-table/issues/545

**Comment by xaksis** [comment]
no response. closing.
