### ISSUE TITLE
Unknown custom element: <v-select> - did you register the component correctly?

### ISSUE THREAD

**Issue by unixconky** [xaksis/vue-good-table#714]
> Unknown custom element: <v-select> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Should I register v-select component or it should work out of the box?

**Comment by hmqk1995** [comment]
following. met the same problem

**Comment by xaksis** [comment]
@cassmbautista @TheJaredWilcurt. Please take a look.

**Comment by p0psicles** [comment]
Maybe register the V-select component in the local component, instead of global?

**Comment by Achaaab** [comment]
I met this issue when using the filter option : filterMultiselectDropdownItems
```
[Vue warn]: Unknown custom element: <v-select> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <VgtFilterRow>
       <VgtTableHeader>
         <VueGoodTable>
         ...
```

**Comment by underwear** [comment]
I look forward when they fix it :)

**Comment by TheJaredWilcurt** [comment]
@ghost @hmqk1995 @p0psicles @Achaaab @underwear 

As of [v2.21.0](https://github.com/xaksis/vue-good-table/releases/tag/v2.21.0) `Vue-Select` is no longer a dependency of Vue-Good-Table.

If you were using this feature (`filterMultiselectDropdownItems`), there is a migration guide for how to add Vue-Select to your project and get the same functionality back by using a custom filter slot.

* [Docs for using custom filter slot](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)
* [Docs for migrating and adding Vue-Select back in to your table](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)

Closing this issue.
