### ISSUE TITLE
Expanded state of row not maintained if a row is inserted before it

### ISSUE THREAD

**Issue by robgaston1** [xaksis/vue-good-table#715]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.19.2
What browser?
Chrome
### Expected Behavior
What did you expect to happen?
If you have rows expanded in a grouped table, vue-good-table will keep them expanded if you add a row to the end. However, we have use cases that require us to insert a row in the middle of the table, not just always at the end. 
### Actual Behavior
What actually happened?
If you had one row in a table that was expanded, and then added a row, then the original row that was expanded becomes row 2 and collapses. The newly added row that at index 0 automatically expands because it takes the place of the first row. 
### Steps to Reproduce the Problem
Please detail your steps here

1. Try out the fiddle, it has steps (as above) on the page

### jsfiddle
you can see [this issue in action here](https://jsfiddle.net/indyrob_js/4Lvxf0ck/43/)

**Comment by xaksis** [comment]
Should be fixed now with v2.19.5
