### ISSUE TITLE
10 per page but is actually one less (9)

### ISSUE THREAD

**Issue by epochslee** [xaksis/vue-good-table#719]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [  ] Enhancement Request
- [  ] Question

### Specs
What version are you using?
2.19.2

What browser?
Chrome

### Expected Behavior
What did you expect to happen?
To show 10 rows but it's always 1 less.

### Actual Behavior
What actually happened?
If I select 20, it'll be 19. If I select 50, it's 49.

### Steps to Reproduce the Problem
Please detail your steps here

1.
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
hey @epochslee, please upgrade to v2.19.3. This has already been fixed.
