### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by Sjoerrdd** [xaksis/vue-good-table#72]
Hello,
I'm getting this error:
Uncaught Error: Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "C:\\Users\\Gebruiker\\Desktop\\paste\\node_modules\\vue-good-table\\.babelrc" at 0, attempted to resolve relative to "C:\\Users\\Gebruiker\\Desktop\\paste\\node_modules\\vue-good-table"
    at C:\Users\Gebruiker\Desktop\paste\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17

(#48 doesn't work for me)

**Comment by VitorLuizC** [comment]
Almost the same is happening to me, but instead of transform-runtime, babel-preset-stage-2 is unknow.
<details>
  <summary>Error Message</summary>
  <code>
    <pre>
Module build failed: Error: Couldn't find preset "stage-2" relative to directory "/Users/vit
orcavalcanti/Projects/Convenia/colaboradores/node_modules/vue-good-table"
    at /Users/vitorcavalcanti/Projects/Convenia/colaboradores/node_modules/babel-core/lib/tr
ansformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/vitorcavalcanti/Projects/Convenia/colaboradores/
node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/vitorcavalcanti/Projects/Convenia/colaboradores/no
de_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/vitorcavalcanti/Projects/Convenia/colaboradores/no
de_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/vitorcavalcanti/Projects/Convenia/colaboradores/node_modul
es/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/vitorcavalcanti/Projects/Convenia/colaboradores/node_modules
/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/vitorcavalcanti/Projects/Convenia/colaboradores/node_modules/babel-c
ore/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/vitorcavalcanti/Projects/Convenia/colaboradores/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/vitorcavalcanti/Projects/Convenia/colaboradores/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/vitorcavalcanti/Projects/Convenia/colaboradores/node_modules/babel-loader/lib/index.js:175:20)
    </pre>
  </code>
</details>

**Comment by kyvinh** [comment]
I got rid of those errors by simply adding thoses packages:
`npm install --save-dev babel-plugin-transform-runtime`
`npm install --save-dev babel-preset-stage-2`

**Comment by VitorLuizC** [comment]
These errors stopped to me after apply vue-good-table as a plugin instead of as component.

This throws me those errors
```vue
<script>
  import { VueGoodTable } from 'vue-good-table'

  export default {
    components: { VueGoodTable }
  }
</script>
```

This works fine
```js
import Vue from 'vue'
import VueGoodTable from 'vue-good-table'

...

Vue.use(VueGoodTable)
```

**Comment by Sjoerrdd** [comment]
Thanks :)

**Comment by Yezuz05** [comment]
I get this error 
Couldn't find preset "env" relative to directory "C:\\xampp\\htdocs\\schollege2\\node_modules\\vue-good-table"
    at C:\xampp\htdocs\schollege2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19

after doing this
npm install --save-dev babel-plugin-transform-runtime
npm install --save-dev babel-preset-stage-2

**Comment by kyvinh** [comment]
@Yezuz05 Try this:
`npm install babel-preset-env --save-dev`

**Comment by Yezuz05** [comment]
@kyvinh Thanks a lot it works now

**Comment by xaksis** [comment]
closing this.

**Comment by unsama** [comment]
Error: Cannot find module '!!../../node_modules/css-loader/index.js?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-a440e668","scoped":true,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./Pagination.vue' from 'C:\Users\fahad khatri\Desktop\RAfinal\ra_admin_final\node_modules\vue-good-table\dist'

**Comment by unsama** [comment]
first time i use vue-good-table and this error is show compilation
`Error: Cannot find module '!!../../node_modules/css-loader/index.js?{"minimize":false,"sourceMap":false}!../../node_modules/vue-loader/lib/style-compiler/index.js?{"vue":true,"id":"data-v-a440e668","scoped":true,"hasInlineConfig":false}!../../node_modules/vue-loader/lib/selector.js?type=styles&index=0!./Pagination.vue' from 'C:\Users\fahad khatri\Desktop\RAfinal\ra_admin_final\node_modules\vue-good-table\dist'`
