### ISSUE TITLE
column search example

### ISSUE THREAD

**Issue by johnantoni** [xaksis/vue-good-table#723]
Hi, all the examples show search on individual columns but the code examples show a global search.

Was this removed or is there some example code somewhere?

Thanks

**Comment by xaksis** [comment]
@johnantoni hey, have you looked at the docs?
https://xaksis.github.io/vue-good-table/guide/configuration/search-options.html#enabled
It has a live example there.

closing.

**Comment by johnantoni** [comment]
found it, thanks https://xaksis.github.io/vue-good-table/guide/configuration/column-filter-options.html#filteroptions
