### ISSUE TITLE
Disable row selection if a condition is met

### ISSUE THREAD

**Issue by cesarlinux** [xaksis/vue-good-table#725]
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using?
2.19.5

### Expected Behavior
What did you expect to happen?
There's a way to disable or not allow the row selection if a condition is met? 

1. if the age of a person is under 18 the row is not selectable.
2. if the status is distinct to "done" the row can be selectable to later deletion.

### Actual Behavior
What actually happened?
All rows are selectable

### jsfiddle
[my jsfiddle](https://jsfiddle.net/gjtosk8w/2/)

**Comment by xaksis** [comment]
This has now been implemented: https://github.com/xaksis/vue-good-table/pull/759

closing.
