### ISSUE TITLE
route to new page when button at end of row is clicked?

### ISSUE THREAD

**Issue by jdl2206** [xaksis/vue-good-table#727]
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using? 2.19.5

What browser? Chrome

### Expected Behavior
Nice component!
Is it possible to add this type of code below in a table cell so when the user clicks on a button at the end of each row, it routes the user to another page and passes params?

The current table has a column with a button at the end of every row which routes it to DataWarehouseReportData
<router-link :to="{name: 'DataWarehouseReportData', params: { selectedReport: report }}">
                          <button class="btn btn-primary">Run Report</button>
                        </router-link>

I'd like to do the same thing using vue-good-table. Another option would be to route the user to the DataWarehouseReportData when the user clicks or double-clicks on the row but I didn't see a way to do that with a router-link.

### Actual Behavior
What actually happened?

### Steps to Reproduce the Problem
Please detail your steps here

1.
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by titusdecali** [comment]
Please check other issues before posting as this question has been asked multiple times already.
You can reference this issue for an example of how to add buttons using custom-templates
https://github.com/xaksis/vue-good-table/issues/399

**Comment by xaksis** [comment]
thanks, @titusdecali. 
closing.
