### ISSUE TITLE
Editable table which supports specifying rows/columns/cells for editing

### ISSUE THREAD

**Issue by PythonPhilipp** [xaksis/vue-good-table#729]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using? latest

What browser? Firefox latest, Chrome latest

### Expected Behavior
What did you expect to happen? Editable table which supports specifying rows/columns/cells for editing

### Actual Behavior
What actually happened? Did not find a solution to make the Vue.js App editable

### Steps to Reproduce the Problem
Please detail your steps here

1. Downloaded and installed Node.js https://nodejs.org/en/download/
2. Downloaded and installed Vue.js https://vuejs.org/v2/guide/installation.html#NPM
3. Setup a new project https://cli.vuejs.org/guide/creating-a-project.html#vue-create
4. Integrated the getting started example https://xaksis.github.io/vue-good-table/guide/#basic-example

How do I specify cells to be editable in the table?

I would like to receive, edit and send back data by using Axios https://vuejs.org/v2/cookbook/using-axios-to-consume-apis.html

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
Hey @PythonPhilipp this is currently not possible as a default functionality. But you can certainly create custom rows to accomplish this: https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template

closing.
