### ISSUE TITLE
Can't sort a date column

### ISSUE THREAD

**Issue by mgattelli** [xaksis/vue-good-table#73]
Hi @xaksis 

Thanks for upgrading the date-fns version, it works!

Now I'm having another problem when sorting a date column.
`[Vue warn]: Error in render function: "TypeError: 3 arguments required, but only 2 present"`
this is the error that I am seeing in the console.

I was trying to debug in order to find where the problem is but this time is a little bit harder.

**Comment by xaksis** [comment]
ah could be a bug! let me see.

**Comment by xaksis** [comment]
fixed. v1.12.5 sorry i missed the parse function in sort. 

closing. please re-open if you have more questions or concerns

**Comment by mgattelli** [comment]
Great @xaksis 
Thanks!
