### ISSUE TITLE
Unnecessary delay when using dropdown column filter

### ISSUE THREAD

**Issue by mgiuffrida** [xaksis/vue-good-table#732]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.19.5

What browser?
Chrome, Firefox

### Expected Behavior
Selecting a filter item from a dropdown or multi-select dropdown should immediately update the table.

### Actual Behavior
The table only updates after 400ms.

### Steps to Reproduce the Problem
Please detail your steps here

1. Create a basic table with one column having `filterOptions`, e.g.:

```js
        filterOptions: {
          enabled: true,
          placeholder: '',
          filterValue: '',
          filterMultiselectDropdownItems: ['TestA', 'TestB', 'TestC'],
        },
```

2. Click the filter dropdown and select an item

### jsfiddle
The [suggested base](https://jsfiddle.net/aks9800/57a2a4ce/) throws a ton of errors and never loads :-\

**Comment by xaksis** [comment]
Hey @mgiuffrida the reason for the delay is that the dropdown change actually uses the same mechanism of filtering as typing in the filterable column. So the event is debounced. Having said that, you're correct in that the table should skip the debounce if it is filtering via a dropdown. Will fix in a future release.

**Comment by TheJaredWilcurt** [comment]
`filterMultiselectDropdownItems` was using Vue-Select, a 3rd party library for handling multi-select. That library (and this feature) have been removed from Vue-Good-Table (as [v2.21.0](https://github.com/xaksis/vue-good-table/releases/tag/v2.21.0)) and replaced with a custom slot, where you can place any markup or components you want for filtering, including Vue-Select.

* [Docs for using the new feature](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)
* [Docs for migrating and adding Vue-Select back in to your table](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters)

The need for removing debounce from custom column filters may still be needed however, so I'm leaving this issue open.

**Comment by TheJaredWilcurt** [comment]
@mgiuffrida This should be fixed in the next release
