### ISSUE TITLE
initialSortBy value is updated when sort order changes.

### ISSUE THREAD

**Issue by henritoivar** [xaksis/vue-good-table#733]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [] Enhancement Request
- [] Question

### Specs
What version are you using? 2.19.2

What browser? Chrome

### Expected Behavior
What did you expect to happen?
initalSortBy should not be mutated from within VueGoodTable

### Actual Behavior
What actually happened?
Whenever i change the sort on VueGoodTable my local variable is updated.

### Steps to Reproduce the Problem
Please detail your steps here
```
 <VueGoodTable
                :columns="columns"
                :rows="invoices"
                @on-row-click="viewInvoice"
                :pagination-options="{
                    setCurrentPage: query.page,
                    perPage: query.limit,
                    enabled: true
                  }"
                :sort-options="{
                    initialSortBy: query.sort
                  }"
                :isLoading.sync="loading"
                :totalRows="total"
                mode="remote"
                @on-page-change="onPageChange"
                @on-sort-change="onSortChange"
                @on-column-filter="onColumnFilter"
                @on-per-page-change="onPerPageChange"
                styleClass="vgt-table condensed"
                class="vgt-table--card"
        />
    </div>
```
1. When i change the sort, then my local query.sort object is updated. This should not happen.

**Comment by p0psicles** [comment]
Make it a call back function
