### ISSUE TITLE
Nested Vue-good-table

### ISSUE THREAD

**Issue by sharmistha-mandal** [xaksis/vue-good-table#735]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?
2.19.1

What browser?
Any

### Expected Behavior
What did you expect to happen?
I am trying to create nested vue-good-table on click of varients buttons, if variant array has objects , it will display the data as nested table.
 
### Actual Behavior
What actually happened?
Currently is expanding the rows because i am using group options. But how to display it as table with thead. Can i use any slots for it if yes, which slots? 

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
https://jsfiddle.net/ucpjwh8r/4/

**Comment by xaksis** [comment]
hey @sharmistha-mandal unfortunately, nested tables is not something VGT officially supports. However, you could technically use the row-template slot for it. https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template
Just put another table within one of the columns?
