### ISSUE TITLE
How to get the value from html element, for example textbox in a row.

### ISSUE THREAD

**Issue by karkb16** [xaksis/vue-good-table#736]
https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#html
How to get the value from html element, for example textbox in a row.

- [ ] Bug
- [ ] Enhancement Request
- [x] Question

### Specs
What version are you using?

What browser?

### Expected Behavior
What did you expect to happen?

### Actual Behavior
What actually happened?

### Steps to Reproduce the Problem
Please detail your steps here

1.
1.
1.

### jsfiddle
https://jsfiddle.net/korikarthik/xjhc4wLm/1/

**Comment by p0psicles** [comment]
You can use the field slots and templates for that. There you can directly bind a Vue method to an event. Or bind a ref attribute to the element

**Comment by p0psicles** [comment]
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template

**Comment by karkb16** [comment]
Thank you for your quick response. I'll check.

**Comment by xaksis** [comment]
closing.
