### ISSUE TITLE
Only last custom template renders without props in cell

### ISSUE THREAD

**Issue by titusdecali** [xaksis/vue-good-table#738]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
2.20.0

What browser?
Chrome 84.0.4147.105 (Official Build) (64-bit)

### Expected Behavior
All custom templates should prevent rendering of field cell values unless explicitly interpolated

### Actual Behavior
Only the last v-if before the v-else in a custom template renders without field props in the relevant cell, while if you have two custom templates in a row, the first one will display prop text values even when you only want to show a button.

Since we can explicitly interpolate values on our own, I think any custom template `v-if`s should prevent rendering of values, regardless of the number used. In my case, I need multiple buttons in a single row, but currently can't find a way to have multiple custom templates without the field prop values also being injected.

Here's a fiddle that shows CANCEL ORDER renders just a button, while VIEW MESSAGE shows the value 16 next to it.

Is there a way to manually hide a prop value in a cell?

### jsfiddle
**https://jsfiddle.net/synapse709/wc3uzf8d/**

**Comment by xaksis** [comment]
hey @titusdecali I think you misunderstand how row templates work. Each template is a row and your condition evaluates for every cell. This means your conditional logic will need to be part of the same if + else-if + else flow. 
In other words, if matches cell 1, else if matches cell 2, else normal. Your corrected fiddle would be: 
```js
<span
  v-if="props.column.field === 'cancelYn' && props.row.cancelYn === 'N'"
  >취소 불가
</span>
<span v-else-if="props.column.field === 'age' && props.row.age === 16">
  <button
    size="small"
    variant="danger"
    variant-type="normal"
    @click="
      showModal({
        title: '인쇄소 메시지',
        message: props.row.comment
      })
    "
    >VIEW MESSAGE</button>
</span>
<span
  v-else-if="props.column.field === 'name' && props.row.name === 'Jane'">
  <button>
    CANCEL ORDER
  </button>
</span>
<span v-else>
  {{ props.formattedRow[props.column.field] }}
</span>
```
Notice how within the template, each span is part of the same logic flow. starting with an if, followed by else-if, followed by else. In your fiddle, you are telling vue to render "View Message" button, but then also render the formatted value if the cell does not match the last condition which is not what you want.

closing.

**Comment by titusdecali** [comment]
Thanks for the concise explanation and quick reply ^^
