### ISSUE TITLE
Sorting broken with mixed data types

### ISSUE THREAD

**Issue by WoLpH** [xaksis/vue-good-table#744]
### Issue Type

- [x] Bug

### Specs
What version are you using?
2.19.1

What browser?
Google Chrome

### Expected Behavior
A working sort

### Actual Behavior
Errors because the values are expected to be strings

### Steps to Reproduce the Problem
Please detail your steps here

1. Open the jsfiddle
2. Click on the column to sort

### jsfiddle
https://jsfiddle.net/fe5ast61/

**Comment by xaksis** [comment]
Hey @WoLpH. This isn't a bug. There's no column type called 'mixed'. you can see the supported data types here:
https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#type

**Comment by p0psicles** [comment]
I think you have the option of sanitizing your data, and go with the default string sort or number. Or use a sortFn function, and cast there. Although option 1 would win in performance.

**Comment by WoLpH** [comment]
Personally I would think that defaulting to a string type cast would be good. You should still be able to disable it for performance sake, but having a library that works with everything out of the box is a good thing :)
