### ISSUE TITLE
filterMultiselectDropdownItems

### ISSUE THREAD

**Issue by dinarozenberg** [xaksis/vue-good-table#747]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [x] Question

### Specs
What version are you using?

What browser?
chrome
### Expected Behavior
What did you expect to happen?
hi last few days i used in my table in this your filter option : "filterMultiselectDropdownItems".
suddenly its not work 
and i am  also see that it isnt  apper in the guide
is this option yet work?

### Actual Behavior
What actually happened?
 only "filterDropdownItems" option work
### Steps to Reproduce the Problem
Please detail your steps here

1.i used filterMultiselectDropdownItems and its work fine
1.i runed command 'npm install' and 'npm update'
1.filterMultiselectDropdownItems  stop to work

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by dinarozenberg** [comment]
hi i added this code 
<template slot="column-filter" slot-scope="{column}">
            <v-select
                :options="dataArr"
                multiple
            />
        </template>

the multi-select work
but not filter the column 
what is the problem now???

![image](https://user-images.githubusercontent.com/37103267/90609897-5d8a0500-e20d-11ea-8869-95f2a3f48243.png)

**Comment by robgaston1** [comment]
@dinarozenberg I didn't look specifically at your code but recently there was a change to the `vue-good-table`. The change was to remove the built in multi-select filter and provide a slot instead. It sounds like you may have updated from a version that still included the built-in multi-select to the latest version that no longer has the filter. 

There are instructions in the docs on how to implement the multi-select filter on your own using the provided slot: https://xaksis.github.io/vue-good-table/guide/advanced/#upgrading-from-versions-2-20-0-2-21-0
