### ISSUE TITLE
Trigger unique button instance within row

### ISSUE THREAD

**Issue by titusdecali** [xaksis/vue-good-table#750]
### Issue Type
- [x] Question

### Specs
What version are you using?
2.20.0

Basic question here, no issues with VGT.

I want to show/hide individual row buttons within a custom template when text is added to an input field in the same custom template.

Currently, I'm firing a method when the user inputs something in the input box, however the showSaveButton data value triggers the button to be shown in every row.

Is there a way to trigger a unique instance of each data property (showSaveBtn) so that only the button in that specific row is shown?

I could probably make this into a new component (it's already a library component) and then trigger state within it, but would like to avoid that.

**Template:**
```
  <span
            v-else-if="
              props.column.field == 'trackingNo' && props.row.trackingYn === 'Y'
            "
          >
            <FormulateInput
              v-model="props.row.trackingNo"
              type="text"
              name="trackingNo"
              class="mb-0"
              @input="showSaveOption(props.row.orderCd)"
            />
            <transition name="modal-fade">
              <BaseButton
                v-show="showSaveBtn"
                :key="props.row.idx"
                class="mt-1 float-left w-100"
                variant="primary"
                size="small"
                >저장하기</BaseButton
              >
            </transition>
          </span>
```

**Data:**
    `  showSaveBtn: false,`

**Method:**
```
    showSaveOption(orderCd) {
      this.showSaveBtn = true
      console.log(orderCd)
    },
```

Gif of triggering all row buttons
![triggeringAllButtons](https://user-images.githubusercontent.com/4532534/90836929-9223cb00-e38b-11ea-98b1-82dfa08a4099.gif)

**Comment by xaksis** [comment]
hey @titusdecali, as you correctly identified this doesn't have much to do with VGT but more about logic. If you had this arrangement `formulateInput` and `Basebutton` in a v-for list, how would you make sure that the input only triggers its corresponding trigger?

Right now you have one global `showSaveBtn`. if that is set to true, it will obviously make all basebuttons visible.

One way to do this would be to only show the button when the corresponding trackingNo has a value: 
```html
<transition name="modal-fade">
    <BaseButton
       v-show="props.row.trackingNo"
       :key="props.row.idx"
       class="mt-1 float-left w-100"
       variant="primary"
       size="small">저장하기</BaseButton>
</transition>
```
so above will only be visible if the row's trackingNo has a value.

closing.
