### ISSUE TITLE
On cell click - get cell unique id/index

### ISSUE THREAD

**Issue by rosenfeldalon** [xaksis/vue-good-table#753]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Specs
What version are you using?
2.21.0

Will be great to have the option to add to **onCellClick** event the option to get the **cell's specific ID** or **index**, for now, I managed to cross the three available params: _row name, column name and cell value_ from the event and compare to my data, but it's a long loop to go over when the data is large.

If there is an existing better way I'll love to know.

`onCellClick(params) {
    // params.row - row object 
    // params.column - column object
    // params.rowIndex - index of this row on the current page.
    // params.event - click event
  }` 

Other than that, great simple to use features - thanks!

**Comment by xaksis** [comment]
hey @rosenfeldalon the params.row object contains the data you need right? Any reason why you need to loop through your data again? 
You should be able to just do `params.row[params.column.field]` to get the cell data?

closing. let me know if this doesn't solve your problem and I'll re-open.

**Comment by rosenfeldalon** [comment]
I know the value, sure, but what if I have multiple cells in one row with the same value, I don't know which cell was clicked, therefor I advised adding a unique ID/index to the cell data you provide on cell click event.
