### ISSUE TITLE
Reset all column filter

### ISSUE THREAD

**Issue by zaingithub** [xaksis/vue-good-table#754]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
v2.21.0

What browser?
chrome

### Expected Behavior
I want to create button to reset all column filter, so the table data are not filtered.

### Actual Behavior
On first time i click my button, it works (the data not filtered).

But when i try to select any filter, then click my button again, it doesn't work (the data still filtered since the column field filter is reset).

### Steps to Reproduce the Problem
Please detail your steps here

My Table options :

`                          <div slot="table-actions" class="mr-2">
                            <button data-toggle="tooltip" data-placement="top" title="Reset semua filter data dari table" @click="deFilterAll()"class="btn btn-primary btn-sm">
                              <i class="fa fa-undo"></i> Reset All Filter
                            </button>
                          </div>`

My Method function :

`        deFilterAll: function() {
          var vm = this;
          var table   = vm.$refs.myTable;
          table.columns.forEach((column, i) => {
            if(column.filterOptions) {
              table.$set(table.columnFilters, column.field, undefined);
              table.$set(column.filterOptions, 'filterValue', undefined);
              table.$emit('filter-changed', table.columnFilters);
            }
          });
          table.$emit('filter-changed', table.columnFilters);
        },`

### jsfiddle
none

**Comment by robgaston1** [comment]
If you put a `ref` attribute on the table, you can invoke the `reset` function, which is exposed from `vue-good-table`. 

`<vue-good-table
    :columns="columnHeaders"
    :rows="tableRows"
    ref="myTable"
/>`

Then when you want to clear all the filters, you can call:
`this.$refs.myTable.reset`
somewhere in a method in your script section.

**Comment by xaksis** [comment]
closing.
