### ISSUE TITLE
don't work customFilter/slot="column-filter"

### ISSUE THREAD

**Issue by v-nakon** [xaksis/vue-good-table#755]
### don't work customFilter/slot="column-filter"

- [x] Bug
- [x] Question

### Specs
What version are you using?
"vue-good-table": "^2.21.0"
What browser?
all browsers
### Expected Behavior
What did you expect to happen?
i want to add a filter component to a table. will add select, datepicker components in the future.
used slot="column-filter",but nothing happened.
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-headers

### jsfiddle
https://jsfiddle.net/57ycg36z/3/

**Comment by oleg-b-i** [comment]
The same problem. Version 2.19
Custom filter doesn't work.

`                <el-date-picker
                        v-if="props.column.filterOptions.customFilter"
                        @input="handleCustomFilter"
                        type="date"
                        placeholder="Pick a day">
                </el-date-picker>

                    {
                        label: 'Date',
                        field: 'datetime',
                        filterOptions: {
                            customFilter: true
                        }
                    }`

Any advice from author?

**Comment by xaksis** [comment]
Hey @v-nakon this is possibly because your other columns don't contain a `filterOptions` object? At least that's the case with your jsfiddle. 

try the following:
```html
<div v-if="props.column.filterOptions && props.column.filterOptions.customFilter"
        @input="handleCustomFilter">
```

closing for now. If this doesn't solve your problem, re-open and post any errors that you see in console so we can debug further.

**Comment by oleg-b-i** [comment]
> Hey @v-nakon this is possibly because your other columns don't contain a `filterOptions` object? At least that's the case with your jsfiddle.
> 
> try the following:
> 
> ```
> <div v-if="props.column.filterOptions && props.column.filterOptions.customFilter"
>         @input="handleCustomFilter">
> ```
> 
> closing for now. If this doesn't solve your problem, re-open and post any errors that you see in console so we can debug further.

**Comment by oleg-b-i** [comment]
> Hey @v-nakon this is possibly because your other columns don't contain a `filterOptions` object? At least that's the case with your jsfiddle.
> 
> try the following:
> 
> ```
> <div v-if="props.column.filterOptions && props.column.filterOptions.customFilter"
>         @input="handleCustomFilter">
> ```
> 
> closing for now. If this doesn't solve your problem, re-open and post any errors that you see in console so we can debug further.

It doesn't work for me

**Comment by xaksis** [comment]
are you sure you have the filters enabled?

```js
filterOptions: {
         enabled: true, // <-- this
        customFilter: true,
},
```

**Comment by oleg-b-i** [comment]
> are you sure you have the filters enabled?
> 
> ```js
> filterOptions: {
>          enabled: true, // <-- this
>         customFilter: true,
> },
> ```

It was't enabled but when i add this prop it's just start to show me standart text input field instead of the datepicker, also i tried another elements like checkbox, and it's still shows <input type="text" />

`            <template slot="column-filter" slot-scope="props">
                <el-date-picker
                        v-if="props.column.filterOptions && props.column.filterOptions.customFilter"
                        type="date"
                        placeholder="Pick a day">
                </el-date-picker>
            </template>

                   {
                        label: 'Date',
                        field: 'datetime',

                        filterOptions: {
                            enabled: true,
                            customFilter: true
                        },
                    },`

**Comment by v-nakon** [comment]
> > are you sure you have the filters enabled?
> > ```js
> > filterOptions: {
> >          enabled: true, // <-- this
> >         customFilter: true,
> > },
> > ```
> 
> It was't enabled but when i add this prop it's just start to show me standard text input field instead of the my datepicker, also i tried another elements like checkbox and so on, and it's still shows `<input type="text" />`

you must update to the latest version "vue-good-table": "^ 2.21.0"

**Comment by oleg-b-i** [comment]
> > > are you sure you have the filters enabled?
> > > ```js
> > > filterOptions: {
> > >          enabled: true, // <-- this
> > >         customFilter: true,
> > > },
> > > ```
> > 
> > 
> > It was't enabled but when i add this prop it's just start to show me standard text input field instead of the my datepicker, also i tried another elements like checkbox and so on, and it's still shows `<input type="text" />`
> 
> you must update to the latest version "vue-good-table": "^ 2.21.0"

Now it works! Thanks!!!
