### ISSUE TITLE
Make column filter input type Number

### ISSUE THREAD

**Issue by dashtydit** [xaksis/vue-good-table#756]
### Issue Type (delete the irrelevant ones) 

- [x] Bug
- [x] Enhancement Request
- [x] Question

### Specs
What version are you using?
2.21.0

What browser?
Chrome

### Expected Behavior
Change filter input type from 'text' to 'number' when setting the 'type' column option to 'number'.

### Actual Behavior
The input type stays as 'text'

**Comment by xaksis** [comment]
hey @dashtydit, you can use `custom column filters` to use whatever input type you want to use for filters.
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters

closing.
