### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by can-keklik** [xaksis/vue-good-table#757]
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using?
2.21.0

I was wondering if you can provide steps to build the component. I tried these:

vue build src/index.js 
vue build src/index.js -n vue-good-table -t lib

They yielded some eslint dependency errors first. I resolved them by installing the dependencies globally. Now I'm getting some linting errors like:

> src/components/VgtTableHeader.vue
> 17:7  error  The 'columns' variable inside 'v-for' directive should be replaced with a computed property that returns filtered array instead. You should not mix 'v-for' with 'v-if'  vue/no-use-v-if-with-v-for
> 

I edited nothing. It is just the latest. 

It is either a misconfiguration on my machine or I'm doing it wrong. My sole purpose is to get it compiled into dist/.

Thanks in advance.

**Comment by p0psicles** [comment]
Yarn bundle
