### ISSUE TITLE
rowStyleClassFn - Execute a method after loading

### ISSUE THREAD

**Issue by epochslee** [xaksis/vue-good-table#761]
### Issue Type (delete the irrelevant ones) 
- [x] Question

### Specs
What version are you using?
2.19.3

What browser?
Chrome

### Expected Behavior
What did you expect to happen?
Would like to execute a function after the rowStyleClassFn has finished. Right now, I have something in mounted() but it seems mounted() is already done before rowStyleClassFn comes into play.

I'm basically trying to enable or disable some checkboxes depending a column's value. Is there another easy way to do this?

**Comment by xaksis** [comment]
hey @epochslee rowStyleClassFn is a function you control so you can call another function right after?
you can enable/disable checkboxes by using the `vgtSelected` property on any row. Here's an example:
https://jsfiddle.net/aks9800/keLjcssn/241/
