### ISSUE TITLE
Add pagination option to hide "Rows per page"

### ISSUE THREAD

**Issue by vjik** [xaksis/vue-good-table#762]
### Issue Type

- [x] Enhancement Request

### Specs
What version are you using?

2.21.0

**Comment by p0psicles** [comment]
You want to disable pagination?

**Comment by xaksis** [comment]
@vjik you can actually customize the pagination however you like: https://xaksis.github.io/vue-good-table/guide/advanced/#custom-pagination by using your own pagination elements.

closing.
