### ISSUE TITLE
We can now automatically refresh the database after deletion action.

### ISSUE THREAD

**Issue by maronkoders** [xaksis/vue-good-table#766]
### Issue Type (delete the irrelevant ones) 
- [x] Enhancement Request

One needs to add the following function to the methods object , and call this function in your XHR response function ,parsing the id or ids of the removed records
`
 removeItems: function () {
      const item = this.jobs.findIndex((p) => p.slug === arguments[1]);
      this.jobs.splice(item, 1);
      console.log("remaining jobs", this.jobs);
      if (this.jobs.length === 0) {
        this.defaultMessage = NO_JOBS;
      }
    },
`

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
Hey @marcelcremer this looks like a use-case specific implementation and not related to VGT itself. going to close this.

**Comment by marcelcremer** [comment]
@xaksis close, but you most likely wanted to ping @maronkoders =)

Have a nice day!

**Comment by xaksis** [comment]
whoops @marcelcremer sorry!

**Comment by maronkoders** [comment]
That is great man.i will definitely do that

Regards
Brian Thomas
