### ISSUE TITLE
How do I do this

### ISSUE THREAD

**Issue by Yezuz05** [xaksis/vue-good-table#77]
Please how do I know which row is clicked or can I somehow access the values in a row that was clicked.

**Comment by xaksis** [comment]
hey @Yezuz05 sorry, the documentation is a bit incomplete here, the `onClick` property lets you add an on click handler on your row. You can do :onClick="myMethod" where myMethod is defined as one of the methods in your component: 
```javascript
myMethod(row, index) {
  console.log(row) // this is the row that was clicked
  console.log(index) // this is the index of the row that was clicked.
} 
```
closing. Please re-open if you have more questions.
