### ISSUE TITLE
Method to redraw table

### ISSUE THREAD

**Issue by alfligno** [xaksis/vue-good-table#771]
Don't you have a redraw method?

**Comment by xaksis** [comment]
@alfligno not sure what you mean by redraw @alfligno the table should reflect the state of your rows/columns as they change. If you really want to re-render the entire component for some reason, you can put a v-if on the component and use a setTimeout to make it unmount and mount again.

**Comment by alfligno** [comment]
For nested object it somehow does not make any changes.
But I already have a solution. forcing the list to be refreshed by making changes on the filters will do

**Comment by p0psicles** [comment]
Your talking about vue reactivity. 
Use Vue.set() to update your data

**Comment by tomascoox** [comment]
Also has a situation where the table does not reflect what's inside my object. We have an input field which users set to for instance -4 and that updates the stockinventory-field. So after POST I want the table to reflect the new values in mainobject which is used to populate tablerows in the first place. i will try the methods suggested here.

**Comment by alfligno** [comment]
> Also has a situation where the table does not reflect what's inside my object. We have an input field which users set to for instance -4 and that updates the stockinventory-field. So after POST I want the table to reflect the new values in mainobject which is used to populate tablerows in the first place. i will try the methods suggested here. The field with -4 should go back to 0 or empty.

I suggest to use `this.$set` as what @p0psicles suggest, the method I use is my own derivation on the issue and it may not work :)

**Comment by tomascoox** [comment]
We tested that. Not sure if it was implemented correctly though. Then I myself choose the v-if route and that worked great. A small blink on the table but nothing annoying. Don't ask me what I named the toggling-variable. 😝

**Comment by alfligno** [comment]
> We tested that. Not sure if it was implemented correctly though. Then I myself choose the v-if route and that worked great. A small blink on the table but nothing annoying. Don't ask me what I named the toggling-variable. 😝

I guess we are on the same boat. Toggling will do, just use some spare variable XD, which is named *change*
