### ISSUE TITLE
how to   clear checkbox selected  rows , hava a event function?

### ISSUE THREAD

**Issue by lifeblood** [xaksis/vue-good-table#772]
how to   clear checkbox selected  rows , hava a event function?

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by epochslee** [comment]
I'd like to know too. When a checkbox is checked, there's a 'clear' link. How can we execute that same behavior?

**Comment by xaksis** [comment]
Use the `vgtSelected` properties on your rows to select/unselect rows. See the solution suggested by @hyzami as an example: https://github.com/xaksis/vue-good-table/issues/783#issuecomment-771637988
