### ISSUE TITLE
font-size .vgt-input .vgt-select

### ISSUE THREAD

**Issue by mrkazu** [xaksis/vue-good-table#773]
When clicking on the search bar safari zooms in on the page when using mobile. Same thing when clicking on the select dropdowns. The fix is to set the font-size 16px instead on 14px on .vgt-input .vgt-select, but i can only change this in the node_modules/vue-good-table/dist/vue-good-table.css. 

However this gets reseted every time i update  vue-good-table.
I tried using custom css and sett the .vgt-input .vgt-select to font-size 16 but no luck.
Anyone has any tips?
thank you

### Specs
What version are you using?
2.21.1

What browser?
Safari IOS

### Expected Behavior
What did you expect to happen?
not to zoom in

### Actual Behavior
zooms in

### Steps to Reproduce the Problem
font-size 14px

**Comment by mrkazu** [comment]
ok, so i found a fix for this. my problem was that i tried to do this in styles
`<style scoped>.vgt-input {font-size: 16px;</style>`

but the fix is to do this form a custom css file that you import to your projects main.js file
`import '@/main.css'`

in the main.css file add
`#Phonenumbers .vgt-input {
    font-size: 16;
}
#Phonenumbers .vgt-select {
    font-size: 16px;
}`

then you simply add this to your <vue-good-table>
`<vue-good-table id="Phonenumbers"</vue-good-table>`

**Comment by xaksis** [comment]
@mrkazu you can also use the deep selector to change any css within the component: 
https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

closing.
