### ISSUE TITLE
Records and row numbers in table seem not to match with page number

### ISSUE THREAD

**Issue by yu-takahasi** [xaksis/vue-good-table#779]
When you do the following steps, you can see records not actually for page 1 in the table:

1. Display 100 or more records beforehand. At the time, make sure the perPage is 10.

2. Move to **page 3**.

3. Change the perPage to 50.
   After this, you can see the records for **page 2**, 
   but the **page number** displayed at the header is **1**.
   Also, the line number starts from **101**.

I'm wondering if the previous page number is used for line number calculation and others.

line number for the first row 
   = (**3** - 1) * 50 - 0 - 1
   = **101**

### Issue Type

- [x] Bug?

### Specs
version 2.19.3

### What browser?
Chrome

### Expected Behavior
The table should display records for page 1.
Also, line numbers should start from 1.

**Comment by xaksis** [comment]
v2.21.6 should fix this.
