### ISSUE TITLE
Make Checkbox Select All, not only on current page.

### ISSUE THREAD

**Issue by zaingithub** [xaksis/vue-good-table#783]
Hi, when i have 1000 rows data, and using pagination with 50 data per page, when i check on select all, the selection is not for all 1000 rows, but only 50 datas on the current page. 

How to make it checked for all data?

**Comment by Zac-Zajdel** [comment]
Hi @zaingithub. I have ran into a similar scenario and my advice may be of some assistance. 

As we paginate results, we are returning a total number of items that we can paginate through that is displayed to the user in the top right of the table.

I have implemented a feature where the user can mass-select multiple items that go outside of the scope of the paginated result set. To do so, I would suggest display some button that allows the user to select n number of items from the total items returned and then send the serverParams object to the backend that should include any columnFilters or search terms. 

This way we can then grab the same item count the user sees on the front-end but then we can actually obtain those items on the backend to do whatever manipulation you deem necessary for your particular use case.

It is a little hard to explain without showing but if you need any clarification, please let me know.

Happy Coding, 
Zac

**Comment by hyzami** [comment]
Function for inverted selection over all records 

    invertSelectAll(){
      var r = this.$refs['table'].filteredRows[0].children;
      r.forEach(item=>{
        if(item.vgtSelected){
          this.$set(item,'vgtSelected', false);
        }else{
          this.$set(item,'vgtSelected', true);
        }
      },this);
      }
