### ISSUE TITLE
Filter on outfocus

### ISSUE THREAD

**Issue by GTerigi** [xaksis/vue-good-table#784]
- [x] Question

Hi
I'm deploying a little app for a business consultant where he needs to make A LOT of queries (simulated by the filter on the columns).
I'm using the table in remote mode, and I'm dealing with 600000+ rows per query, so it's a little inconvenient to filter at every keyup stroke, and this business consultant is quite old and he forgot's to hit enter after he's done writing inside the filter.

The best solution for me is to fire the filter only on outfocus or blur event, but I tried on my machine and it seems that is behavior is alike as keyup. 
There's a way to simulate the outfocus/blur event and then filter or is not possible?

I'm using vue-good-table 2.21.1

Thanks for your help!

**Comment by xaksis** [comment]
hey @GTerigi! the best way to do this would be using custom filters: https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters

This way, You can handle the filtering yourself using whatever event you want to trigger the filter on.

closing.
