### ISSUE TITLE
Dynamic children rows based on getters data

### ISSUE THREAD

**Issue by arokke** [xaksis/vue-good-table#785]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
Version 2.21.1

Edge chromium based (Version 87.0.664.66 (64-bit))

### Expected Behavior & actual

(Vuejs 2.x)
In a grouped table setting, I would like to dynamically display groups (children rows) based on store getters.
Unfortunately I'm unable to make it work. I'm sure it's silly.

**the HTML** 
![htmltemplate](https://user-images.githubusercontent.com/19796142/103234511-299fb880-4940-11eb-9592-db034cc2881f.PNG)

**the script**
![script](https://user-images.githubusercontent.com/19796142/103234533-37553e00-4940-11eb-9df1-f3480bcb641d.PNG)

The idea is to have 4 groups of rows: assetAccounts, liabilityAccounts, expenseAccounts and incomeAccounts.

The getters return correct and structured data. the fields are correctly named. I'm unsure on how to properly enter the Children parameter.

I tried:

- children: "assetAccounts"
- children: ["assetAccounts"]
- children: [{id: assetAccounts.id, accountname: assetAccounts.name, balance: assetAccount.balance}]
- children: [{id: "assetAccounts.id", accountname: "assetAccounts.name", balance: "assetAccount.balance"}]

Getters return data: 
![gettersdata](https://user-images.githubusercontent.com/19796142/103234383-da598800-493f-11eb-9bbb-29ebc90d7306.PNG)

Any help is appreciated.
Thank you very much!!

**Comment by arokke** [comment]
doing `children: this.$store.getters.assetAccounts,` seems to work. However I have now 2 calls to the store, (1) children (2) in computed value, since I have to re-use the information elsewhere. does not look efficient. What am I missing ?

![calltogetter](https://user-images.githubusercontent.com/19796142/103235965-b730d780-4943-11eb-95ae-4754df92c398.PNG)

**Comment by xaksis** [comment]
hey @arokke you just have to do refer to your computed value with `this`. Vue 101 :) 
```
{
 //...
  children: this.assetAccounts,
}
```

closing.

**Comment by arokke** [comment]
ahhh, I made a silly mistake. Computed is loaded after data(). no wonder it cannot iterate.

Thank you for the pointer @xaksis :)
