### ISSUE TITLE
Replace default search icon

### ISSUE THREAD

**Issue by SirWindfield** [xaksis/vue-good-table#786]
### Issue Type (delete the irrelevant ones) 

- [ ] Bug
- [ ] Enhancement Request
- [x] Question

How do I replace the default search icon with another one (for example from feathericons or fontawesome)? It appears that the element is a simple `div` and not a slot (like other customizable components):

https://github.com/xaksis/vue-good-table/blob/2ae61d1625b7f868183fcadb4ee8c98e3e5d51c9/src/components/VgtGlobalSearch.vue#L4-L6

**Comment by xaksis** [comment]
Hey @SirWindfield you can use your own input element for global search and style it however you want: 
https://xaksis.github.io/vue-good-table/guide/configuration/search-options.html#externalquery

closing.

**Comment by SirWindfield** [comment]
I missed this one, thank you very much!

**Comment by xaksis** [comment]
you got it, @SirWindfield. Happy holidays!

**Comment by SirWindfield** [comment]
Happy holidays!
