### ISSUE TITLE
Pre-checking checkboxes 

### ISSUE THREAD

**Issue by MUHAMMADSiyab** [xaksis/vue-good-table#787]
### Pre-checking checkboxes (select all)

Is there any way to pre-check all checkboxes?

**Comment by xaksis** [comment]
Hey @MUHAMMADSiyab . Yeah, just add `vgtSelected` property to your rows. 
Check the following issue for reference: 
https://github.com/xaksis/vue-good-table/issues/592

closing.

**Comment by hyzami** [comment]
Second option is to call after data load function like this

preselectAll(){   
      var r = this.$refs['table'].filteredRows[0].children;
      r.forEach(item=>{this.$set(item,'vgtSelected', true);},this);
    },
