### ISSUE TITLE
Column filter enabled, don't show group headers when filtering

### ISSUE THREAD

**Issue by SirWindfield** [xaksis/vue-good-table#788]
- [x] Question

I have a grouped table (which was the primary reason why I chose this project). I now introduced a column filter on one of my columns. Filtering works but it does display empty groups as well. Is there an option to disable this? So that only groups that have rows that match the filter are getting shown?

**Comment by cory-weiner** [comment]
Same issue.

**Comment by SirWindfield** [comment]
Thanks!
