### ISSUE TITLE
Empty States inside tr makes it hard to render a td

### ISSUE THREAD

**Issue by mcat** [xaksis/vue-good-table#79]
I'm trying to create a nice looking empty state for my table and I'm having trouble doing so. 

It looks like vue has trouble rendering `<td>` elements inside `<tr>` elements. 

I'm able to use a `<div>` however divs don't work with colspan so I can't do things like get my empty state to be horizontally centered in the table. 

Instead of putting the empty slots inside of a `<tr>` like they are currently:
```html
<tr v-if="columns.length === 0">
    <slot name="emptystate"></slot>
</tr>
<tr v-else-if="processedRows.length === 0">
    <slot name="emptystate"></slot>
</tr>
```

What if they lived in a div outside the table like this:

```html
<div class="table-empty" v-if="columns.length === 0">
    <slot name="emptystate"></slot>
</div>

<div class="table-empty" v-else-if="processedRows.length === 0">
    <slot name="emptystate"></slot>
</div>
```

**Comment by xaksis** [comment]
@mcat good catch. I'll look into it tonight.

**Comment by mcat** [comment]
Thanks @xaksis!

**Comment by mcat** [comment]
Saw the fix @xaksis Looks great and works great, thank you!

**Comment by xaksis** [comment]
awesome! closing this.
