### ISSUE TITLE
pressing 'enter' in searchbar refresh page

### ISSUE THREAD

**Issue by zayanimed97** [xaksis/vue-good-table#796]
Hello, 
when using the searchbar the "enter" key refreshes the page which isn't what I need to do.
After investigating a little it appears the problem is in this line:

`<form v-if="searchEnabled" role="search"> `

'enter' Keypress submits the form so the page is refreshed so I suggest a preventDefault on the submit.
Please if there is a workaround i'm all ears.

Thank you.

**Comment by xaksis** [comment]
Ah! This was due to a recent accessibility update. Will fix!

**Comment by zayanimed97** [comment]
Great, Thank you.
