### ISSUE TITLE
Multicolumn sort works incorrect

### ISSUE THREAD

**Issue by andrew-svirin** [xaksis/vue-good-table#799]
Multicolumn sort reset after clicking any column for sort.

**Comment by xaksis** [comment]
@andrew-svirin Seems to work fine here: https://jsfiddle.net/aks9800/4p5h3sfu/
could you create a jsfiddle to demonstrate this?

closing till a reproducible fiddle is created.

**Comment by andrew-svirin** [comment]
Hi, @xaksis 
Thank you for quick answer.

When i setup default value for multicolumn sort, then on table there are multiple blue arrows visible.
But when i clicking any of sortable column, then reaction like there were not any predefined sort values.
![image](https://user-images.githubusercontent.com/16819743/104849241-63396300-58f1-11eb-9fbc-6b636cd8283e.png)
![image](https://user-images.githubusercontent.com/16819743/104849282-7e0bd780-58f1-11eb-996e-b7d251f1cea0.png)
