### ISSUE TITLE
How use on Laravel 5.5

### ISSUE THREAD

**Issue by serobalino** [xaksis/vue-good-table#80]
I want to use this marvel with laravel mix and all its backend, but it gives me an error someone already has it, help please

**Comment by serobalino** [comment]
I try
`npm install babel-plugin-transform-runtime babel-preset-stage-2 --save-dev`

in a component assets/js/components/ucomponent.vue
`<script>
    import VueGoodTable from 'vue-good-table';
    Vue.use(VueGoodTable);
    export default {.......`

**Comment by xaksis** [comment]
@serobalino can you paste what the error is?

Also, have you taken a look at the issue below: 
https://github.com/xaksis/vue-good-table/issues/72

**Comment by serobalino** [comment]
excellent works perfectly, now I need to change the language of the date format. Any advice?

**Comment by xaksis** [comment]
hey @serobalino, I'm going to close this issue, do you mind creating a new one for your question about date language? thanks.
