### ISSUE TITLE
table width in vuepress

### ISSUE THREAD

**Issue by shriaviator** [xaksis/vue-good-table#800]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
v2.21.2

What browser?
chrome: Version 87.0.4280.141 (Official Build) (64-bit) windows

### Expected Behavior
What did you expect to happen?
table width to be 100 percent 
### Actual Behavior
What actually happened?
Table width is element width

### Steps to Reproduce the Problem
Please detail your steps here

1 registered  vue-good-tables in a component . using default instructions in a vuepress project 

2.deployed to github pages ,observed both in dev and deploy tabled width  is element width

git hub repo : https://github.com/shriaviator/vuepress-project-one.git

Live sample: https://shriaviator.github.io/vuepress-project-one/guide/using-vue.html
Note:runs normally in a vanilla vue project
### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
This is because vuepress is adding additional styles to the table (check in dev console): 
```css
table {
    border-collapse: collapse;
    margin: 1rem 0;
    display: block;
    overflow-x: auto;
}
```
You need to reset/override those table styles set by vuepress.

closing.
