### ISSUE TITLE
Custom template for <tr>?

### ISSUE THREAD

**Issue by ooo2003003v2** [xaksis/vue-good-table#802]
Hello there. I am have a problem completing my responsive ui. 
I need to create a custom template in the <tr> level. 
Is it passible to use a custom template for <tr> in the current version?

**Comment by xaksis** [comment]
hey @ooo2003003v2 please go over the documentation. It should be able to answer most of the basic questions: 
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template

closing.
