### ISSUE TITLE
Custom filter doesn't work

### ISSUE THREAD

**Issue by oleg-b-i** [xaksis/vue-good-table#806]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.21.3
What browser?
Chrome
### Expected Behavior
What did you expect to happen?
Show custom filter
### Actual Behavior
What actually happened?
Error in console
### Steps to Reproduce the Problem
Please detail your steps here

1.Creating custom filter:

```
<vue-good-table
                ref="dataTable"
                :columns="columns"
                :rows="rows"
                :line-numbers="true"
                :select-options="{ enabled: true, selectOnCheckboxOnly: true, }"
                :pagination-options="{ enabled: true, perPage: 50 }"
                @on-cell-click="onCellClick">

            <template slot="column-filter" slot-scope="props">
                <my-custom-filter
                        v-if="props.column.filterOptions.myFilter"
                        />
            </template>

            <template slot="table-row" slot-scope="props">
                <span v-if="props.column.field == 'studio_id'">
                  <span>{{props.row.studio_name}}</span>
                </span>
            </template>


            <div slot="table-actions">
                <button class="btn btn-success m-3" @click="addRow()">Add new</button>
                <button class="btn btn-info m-3" @click="editParams()">Edit parameters</button>
                <button class="btn btn-danger m-3" @click="deleteRow()">Delete selected</button>
            </div>
        </vue-good-table>
```

After that creating it in one of the columns:

```
<script>
    import 'vue-good-table/dist/vue-good-table.css'

    import flatPickr from "flatpickr";
    import "flatpickr/dist/flatpickr.css";
    import "flatpickr/dist/themes/material_blue.css";



    export default {
        name: 'UaBenchmark',
        data(){
            return {
                components: {
                    flatPickr,
                },
                columns: [
                    {
                        label: 'Game',
                        field: 'game',
                        width: '10%',
                        filterOptions: {
                            enabled: true,
                            trigger: 'enter',
                        },
                    },
                    {
                        label: 'OS',
                        field: 'os_name',
                        width: '4%',
                    },
                    {
                        label: 'Studio',
                        field: 'studio_id',
                        width: '4%',
                        filterOptions: {
                            enabled: true,
                            trigger: 'enter',
                            filterDropdownItems: this.studios,
                            // filterFn: function(data, filterString) {
                            //     console.log(data);
                            //     console.log(filterString);
                            // }
                        },
                    },

                    {
                        label: 'Category',
                        field: 'cat_name',
                        width: '4%',
                    },
                    {
                        label: 'CPI FB',
                        field: 'cpi_fb',
                        width: '7%',
                        filterOptions: {
                            styleClass: 'class1',
                            enabled: true,
                            myFilter: true
                        },
                        formatFn: function(value){
                            return value + '€';
                        },
                    },
                    {
                        label: 'Start',
                        field: 'start_date',
                        width: '5%',
                        type: 'date',
                        filterable: true,
                        dateInputFormat: 'MM/dd/yyyy', // expects 2018-03-16
                        dateOutputFormat: 'MM/dd/yyyy',
                        filterOptions: {
                            enabled: true,
                            placeholder: "Filter start",
                            // filterFn: this.dateRangeFilter
                        }
                    },

                    {
                        label: 'End',
                        field: 'end_date',
                        width: '5%',
                        type: 'date',
                        filterable: true,
                        dateInputFormat: 'MM/dd/yyyy', // expects 2018-03-16
                        dateOutputFormat: 'MM/dd/yyyy',
                        filterOptions: {
                            enabled: true,
                            placeholder: "Filter end",
                            // filterFn: this.dateRangeFilter
                        }
                    },

                    {
                        label: 'Best creative link',
                        field: 'best_creative_link',
                        width: '4%',
                        sortable: false,
                        // formatFn: this.formatDoneOk,
                        // filterOptions: {
                        //     enabled: true,
                        //     filterDropdownItems: [
                        //         { value: '1', text: 'yes' },
                        //         { value: '0', text: 'no' },
                        //     ],
                        // },
                    },
                    {
                        label: 'Keywords',
                        field: 'keywords',
                        width: '10%',
                        sortable: false,
                        filterOptions: {
                            enabled: true,
                            trigger: 'enter',
                        },
                        // formatFn: this.formatDoneOk,
                        // filterOptions: {
                        //     enabled: true,
                        //     filterDropdownItems: [
                        //         { value: '1', text: 'yes' },
                        //         { value: '0', text: 'no' },
                        //     ],
                        // },
                    },
                    {
                        label: 'Spend',
                        field: 'spend',
                        width: '3%',
                        formatFn: function(value){
                            return value + '€';
                        },
                    },
                    {
                        label: 'Impression FB',
                        field: 'impression_fb',
                        width: '3%',
                    },
                    {
                        label: 'Click FB',
                        field: 'click_fb',
                        width: '3%',
                    },
                    {
                        label: 'CTR FB',
                        field: 'ctr_fb',
                        width: '3%',
                        formatFn: function(value){
                            return value + '%';
                        },
                    },
                    {
                        label: 'Installs FB',
                        field: 'installs_fb',
                        width: '3%',
                    },
                    {
                        label: 'CVR',
                        field: 'cvr',
                        width: '3%',
                        formatFn: function(value){
                            return value + '%';
                        },
                    },
                    {
                        label: 'IPM',
                        field: 'ipm',
                        width: '3%',
                        formatFn: function(value){
                            return value + '%';
                        },
                    },
                    {
                        label: 'Base user/J FB',
                        field: 'base_user_j',
                        width: '3%',
                    },
                    {
                        label: 'Retention US D1',
                        field: 'retention_us_d1',
                        width: '3%',
                        formatFn: function(value){
                            return value + '%';
                        },
                    },
                    {
                        label: 'Retention US D3',
                        field: 'retention_us_d3',
                        width: '3%',
                        formatFn: function(value){
                            return value + '%';
                        },
                    },
                ],
                rows: [],
                os: [],
                cats: [],
                studios: [],
                dialogFormVisible: false,
                dialogParamsVisible: false,
                form: {},
                formLabelWidth: '120px',
                dateFilterValue: '',
            };
        },

        mounted: function(){
            var self = this;



            axios.post('/benchmark/data')
                .then(response => {
                    console.log(response.data);
                    self.rows = response.data.records
                    self.os = response.data.os
                    self.cats = response.data.cats
                    self.studios = response.data.studios

                    this.$set(this.columns[2].filterOptions, 'filterDropdownItems', self.studios);

                   document.querySelector("input[name=vgt-cpi_fb]").setAttribute('title', 'Enter data in format \"From - To\". Example: \"0.25 - 0.5\"');
                }).catch(error => {
                console.log(error)
            });

            let inputs = [
                'input[placeholder="Filter start"]',
                'input[placeholder="Filter end"]',
            ];
            inputs.forEach(function(input) {
                flatPickr(input, {
                    dateFormat: "d/m/Y",
                    // mode: "range",
                    allowInput: true
                });
            });


        },
        methods: {
            checkChange: function(){
              console.log(this.form)
            },
            addRow: function(){
                this.dialogFormVisible = true;
            },
            editParams: function(){
                this.dialogParamsVisible = true;
            },
            deleteParam: function(param, id){
                console.log(param, id);
            },
            deleteRow: function(){

                this.$confirm('This will permanently delete selected tasks. Continue?', 'Warning', {
                    cancelButtonText: 'Cancel',
                    confirmButtonText: 'OK',
                    type: 'warning',
                    center: true
                }).then(() => {
                    var selectedTasks = this.$refs['tasksTable'].selectedRows;
                    var self = this;

                    var arrToDelete = [];
                    _.each(selectedTasks,function(key,value){
                        arrToDelete.push(_.pick(key,'id'));
                    });

                    axios.post('/deleteTask', {'arrToDelete' : arrToDelete})
                        .then(response => {
                            self.rows = response.data
                        }).catch(error => {
                        console.log(error)
                    });

                    console.log(arrToDelete);

                    this.$message({
                        type: 'success',
                        message: 'Delete completed'
                    });

                }).catch(() => {
                    this.$message({
                        type: 'info',
                        message: 'Delete canceled'
                    });
                });


            },
  
        }
    };
</script>
```

After that getting error in console: 
app.js?id=4e7d3e93820ae2e7f650:304075 [Vue warn]: Error in render: "TypeError: Cannot read property 'myFilter' of undefined"
found in
---> <VgtFilterRow>
       <VgtTableHeader>
         <VueGoodTable>
           <UaBenchmark> at resources/js/components/ua-benchmark/List.vue
             <PassThrough> at resources/js/components/passThrough.vue
               <Vuerouter> at resources/js/components/router.vue
                 <Root>
warn @ app.js?id=4e7d3e93820ae2e7f650:304075
logError @ app.js?id=4e7d3e93820ae2e7f650:305334
globalHandleError @ app.js?id=4e7d3e93820ae2e7f650:305329
handleError @ app.js?id=4e7d3e93820ae2e7f650:305289
Vue._render @ app.js?id=4e7d3e93820ae2e7f650:306994
updateComponent @ app.js?id=4e7d3e93820ae2e7f650:307508
get @ app.js?id=4e7d3e93820ae2e7f650:307919
Watcher @ app.js?id=4e7d3e93820ae2e7f650:307908
mountComponent @ app.js?id=4e7d3e93820ae2e7f650:307515
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:312485
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:315385
init @ app.js?id=4e7d3e93820ae2e7f650:306566
createComponent @ app.js?id=4e7d3e93820ae2e7f650:309414
createElm @ app.js?id=4e7d3e93820ae2e7f650:309361
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
patch @ app.js?id=4e7d3e93820ae2e7f650:309911
Vue._update @ app.js?id=4e7d3e93820ae2e7f650:307387
updateComponent @ app.js?id=4e7d3e93820ae2e7f650:307508
get @ app.js?id=4e7d3e93820ae2e7f650:307919
Watcher @ app.js?id=4e7d3e93820ae2e7f650:307908
mountComponent @ app.js?id=4e7d3e93820ae2e7f650:307515
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:312485
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:315385
init @ app.js?id=4e7d3e93820ae2e7f650:306566
createComponent @ app.js?id=4e7d3e93820ae2e7f650:309414
createElm @ app.js?id=4e7d3e93820ae2e7f650:309361
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
patch @ app.js?id=4e7d3e93820ae2e7f650:309911
Vue._update @ app.js?id=4e7d3e93820ae2e7f650:307387
updateComponent @ app.js?id=4e7d3e93820ae2e7f650:307508
get @ app.js?id=4e7d3e93820ae2e7f650:307919
Watcher @ app.js?id=4e7d3e93820ae2e7f650:307908
mountComponent @ app.js?id=4e7d3e93820ae2e7f650:307515
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:312485
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:315385
init @ app.js?id=4e7d3e93820ae2e7f650:306566
createComponent @ app.js?id=4e7d3e93820ae2e7f650:309414
createElm @ app.js?id=4e7d3e93820ae2e7f650:309361
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
patch @ app.js?id=4e7d3e93820ae2e7f650:309911
Vue._update @ app.js?id=4e7d3e93820ae2e7f650:307387
updateComponent @ app.js?id=4e7d3e93820ae2e7f650:307508
get @ app.js?id=4e7d3e93820ae2e7f650:307919
Watcher @ app.js?id=4e7d3e93820ae2e7f650:307908
mountComponent @ app.js?id=4e7d3e93820ae2e7f650:307515
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:312485
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:315385
init @ app.js?id=4e7d3e93820ae2e7f650:306566
merged @ app.js?id=4e7d3e93820ae2e7f650:306749
createComponent @ app.js?id=4e7d3e93820ae2e7f650:309414
createElm @ app.js?id=4e7d3e93820ae2e7f650:309361
patch @ app.js?id=4e7d3e93820ae2e7f650:309911
Vue._update @ app.js?id=4e7d3e93820ae2e7f650:307387
updateComponent @ app.js?id=4e7d3e93820ae2e7f650:307508
get @ app.js?id=4e7d3e93820ae2e7f650:307919
Watcher @ app.js?id=4e7d3e93820ae2e7f650:307908
mountComponent @ app.js?id=4e7d3e93820ae2e7f650:307515
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:312485
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:315385
init @ app.js?id=4e7d3e93820ae2e7f650:306566
merged @ app.js?id=4e7d3e93820ae2e7f650:306749
createComponent @ app.js?id=4e7d3e93820ae2e7f650:309414
createElm @ app.js?id=4e7d3e93820ae2e7f650:309361
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
patch @ app.js?id=4e7d3e93820ae2e7f650:309911
Vue._update @ app.js?id=4e7d3e93820ae2e7f650:307387
updateComponent @ app.js?id=4e7d3e93820ae2e7f650:307508
get @ app.js?id=4e7d3e93820ae2e7f650:307919
Watcher @ app.js?id=4e7d3e93820ae2e7f650:307908
mountComponent @ app.js?id=4e7d3e93820ae2e7f650:307515
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:312485
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:315385
init @ app.js?id=4e7d3e93820ae2e7f650:306566
merged @ app.js?id=4e7d3e93820ae2e7f650:306749
createComponent @ app.js?id=4e7d3e93820ae2e7f650:309414
createElm @ app.js?id=4e7d3e93820ae2e7f650:309361
createChildren @ app.js?id=4e7d3e93820ae2e7f650:309489
createElm @ app.js?id=4e7d3e93820ae2e7f650:309390
patch @ app.js?id=4e7d3e93820ae2e7f650:309950
Vue._update @ app.js?id=4e7d3e93820ae2e7f650:307387
updateComponent @ app.js?id=4e7d3e93820ae2e7f650:307508
get @ app.js?id=4e7d3e93820ae2e7f650:307919
Watcher @ app.js?id=4e7d3e93820ae2e7f650:307908
mountComponent @ app.js?id=4e7d3e93820ae2e7f650:307515
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:312485
./node_modules/vue/dist/vue.common.dev.js.Vue.$mount @ app.js?id=4e7d3e93820ae2e7f650:315385
./resources/js/app.js @ app.js?id=4e7d3e93820ae2e7f650:339067
__webpack_require__ @ app.js?id=4e7d3e93820ae2e7f650:20
0 @ app.js?id=4e7d3e93820ae2e7f650:341945
__webpack_require__ @ app.js?id=4e7d3e93820ae2e7f650:20
(anonymous) @ app.js?id=4e7d3e93820ae2e7f650:63
(anonymous) @ app.js?id=4e7d3e93820ae2e7f650:66
Show 78 more frames
app.js?id=4e7d3e93820ae2e7f650:305338 TypeError: Cannot read property 'myFilter' of undefined
    at fn (app.js?id=4e7d3e93820ae2e7f650:280653)
    at normalized (app.js?id=4e7d3e93820ae2e7f650:306038)
    at Proxy.renderSlot (app.js?id=4e7d3e93820ae2e7f650:306134)
    at fn (app.js?id=4e7d3e93820ae2e7f650:279117)
    at normalized (app.js?id=4e7d3e93820ae2e7f650:306038)
    at Proxy.renderSlot (app.js?id=4e7d3e93820ae2e7f650:306134)
    at fn (app.js?id=4e7d3e93820ae2e7f650:272745)
    at normalized (app.js?id=4e7d3e93820ae2e7f650:306038)
    at Proxy.renderSlot (app.js?id=4e7d3e93820ae2e7f650:306134)
    at app.js?id=4e7d3e93820ae2e7f650:272313

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by YegorBY** [comment]
This code: v-if="props.column.filterOptions.myFilter" is executed for every column you defined in data.columns.
In your code, some of the column definitions lacks filterOptions declaration, which lead to it being evaluated as undefined, which doesnt have property myFilter. 
You can fix this by defining filterOptions for each column, and settings its property myFilter to false. This way v-if="props.column.filterOptions.myFilter" will be executed properly and give you expected result.
There is another problem with your code though. There is no input element inside <my-custom-filter v-if="props.column.filterOptions.myFilter"/>, which means it is an empty <div/>. You should add and <input/> element inside.
There are further problems with CustomFilters, for some reason, if you want to apply a filter to the data you entered by callin updateFilters() function, it will pass both a value type into the input as string and as an event, on which another fuction will be called:
 var escapeRegExp = function escapeRegExp(str) {
  return str.replace(/[\\^$*+?.()|[\]{}]/g, '\\$&');
}; resulting in failure. I will probably crate seperate issue regarding this.

**Comment by YegorBY** [comment]
Regarding previously said:
in the examples, input event defined as follows:
```
 <my-custom-filter
      v-if="column.filterOptions.customFilter"
      **@input="(value) => updateFilters(column, value)"**/>
```
value is considered to be a string, but input control provides a more complicated object, with control's actual value residing inside value.data property.

Column using this property is defined as:

```
{
  label: 'Name',
  field: 'name.displayName',
  filterOptions: {
    customFilter: true,
    slotFilterField: 'name.id',
    formatValue: function (value) {
      return valueArray.join(',');  
    } 
  }
}
```

You can redifine it as 
```
formatValue: function (value) {
      return value.data;  
    } 
```

**Comment by xaksis** [comment]
Thanks @YegorBY 
Closing.
