### ISSUE TITLE
Pagination rerender

### ISSUE THREAD

**Issue by andrew-svirin** [xaksis/vue-good-table#807]
It is not obvious, but then you have pagination and wanting to apply search or another filter criteria, then pagination can break and show wrong, so the hack for re-render pagination is :
```vue
this.$refs.paymentsTable.$refs.paginationBottom.changePage(1, false);
```
Where `paymentsTable` is ref on custom table 
```vue
        <vue-good-table
            ref="paymentsTable"
            ...
```

**Comment by xaksis** [comment]
v2.21.5 should take care of this.

closing.
