### ISSUE TITLE
Changing Per Page resets the pagination info but doesn't reset the current page

### ISSUE THREAD

**Issue by GeorgeLee134** [xaksis/vue-good-table#809]
### Issue Type 

- [x] Bug

### Specs
vue-good-table 2.21.0
VueJs 2.6.10

What browser? Chrome Version 88.0.4324.104 (Official Build) (64-bit)

### Expected Behavior

When changing the per page, the table resets to page one.

### Actual Behavior

When changing the per page, the table attempts to reset to page one, the pagination info shows page 1 of x but the results are for the page number you were on

### Steps to Reproduce the Problem

1. Navigate to Page 2
2. Set Rows per page to be 20

### jsfiddle
Please use [this example](https://jsfiddle.net/5zp1k2en/)

**Comment by xaksis** [comment]
v2.21.5 should fix this.

**Comment by GeorgeLee134** [comment]
@xaksis Using the jsFiddle with v2.21.7 it still seems broken

**Comment by xaksis** [comment]
oh strange! will investigate.

**Comment by xaksis** [comment]
The styles look pretty stupid too. Will take a look soon.

**Comment by GeorgeLee134** [comment]
Is that the big dropdown? as we noticed that and changed them back to how they used to look.

FYI I believe the issue happens when you do the following

1. Set page size to 20
2. Navigate to last page
3. Set page size to 10

You end up on the second page but with the navigation displaying the first page

**Comment by ctwillie** [comment]
Having the same problem. Is there a rough time frame for the fix?

**Comment by Michel-HaiRUn** [comment]
I'm in v2.21.11, and the problem still persist. i'm in remote mode
When i'm in page 2, and change the perPage, the display is in page one but my data is still in page 2 . The sort change as well display same issue
