### ISSUE TITLE
Introduce table grouping

### ISSUE THREAD

**Issue by Macavirus** [xaksis/vue-good-table#81]
Is there a way to add custom table rows, for instance, to display a summary of data?
My use case is similar to producing an Excel table, where all rows belonging to a category will get their own "summary row" showing information about the rows below them. The problem is this summary does not exist in the rows object, I would need to somehow create it in the code. In the example below, for instance, the row for MAMMALS and REPTILES does not exist in my rows object. Is this possible to do in vue-good-tables?

Expected input:

    data: {
        rows: [{
                code: 0101,
                desc: 'cats'
                price: 28.90
            },
            {
                code: 0102,
                desc: 'rats',
                price: 35.80
            },
            {
                code: 0201,
                desc: 'lizards',
                price: 7.50
            },
            {
                code: 0202,
                desc: 'snakes'
                price: 8.50
            }]
        }

And output:

| Code | Description | Price   |
|------|-------------|---------|
| 01   | MAMMALS     |         |
| 0101 | cats        | $28.90  |
| 0102 | rats        | $35.80  |
| 0103 | dogs        | $18.90  |
| 02   | REPTILES    |         |
| 0201 | lizards     | $7.50   |
| 0202 | snakes      | $8.50   |
|      |             |         |

**Comment by xaksis** [comment]
Hey @Macavirus! This currently isn't possible. 
It is a useful case but non-trivial to implement... I'll think about it. What is the expected behavior for sorting/filtering/paging in this case?

**Comment by Macavirus** [comment]
Agreed, it's not trivial.

I guess I would expect sorting to work per-section, leaving the summary rows locked at the bottom of each section. Filtering would probably be table-wide. 

Pagination would only need to not leave an "orphan" summary row on page 2, for example. That does mean that each page would not return an exact number, but +-1.

There was one other library I evaluated that could do one summary row at the bottom of the table, but that was it. So I suppose the best option is to do it manually and insert my own summary at the bottom of each table.

**Comment by cristijora** [comment]
@xaksis @Macavirus Maybe as an inspiration 
https://jsfiddle.net/75vst75d/1/

They basically render [a new table](https://github.com/ElemeFE/element/blob/dev/packages/table/src/table.vue#L82) below the main one and indeed this is not very trivial to implement

**Comment by ImpossivelPT** [comment]
Hi there guys, I'm also looking for the same solution. 
On our project we were using a rudimentar component that draw a table, and we made the total by rendering an extra row at the end, but in that case we had no sorting, so there where no problems.

I will follow for a solution, 

Thanks!

**Comment by xaksis** [comment]
@Macavirus @ImpossivelPT Sorry this took a while but the new major version 2.0 (which is now in beta) now allows grouped tables! you can check out a basic example here: 
https://jsfiddle.net/aks9800/0t820euy/
you can also create summary rows with totals: 
https://jsfiddle.net/aks9800/0t820euy/

to upgrade to 2.0, please use [the upgrade guide](https://github.com/xaksis/vue-good-table/wiki/Guide-to-upgrade-from-1.x-to-v2.0)

and you can see the [full documentation here](https://github.com/xaksis/vue-good-table/tree/new-build)

👍

**Comment by ImpossivelPT** [comment]
@xaksis thanks for the update!

**Comment by xaksis** [comment]
closing.
