### ISSUE TITLE
Prevent login animation on initial fetch of the table (server side mode)

### ISSUE THREAD

**Issue by florinfratica** [xaksis/vue-good-table#812]
### Issue Type

- [x] Question

### Specs
What version are you using?
2.21.0

### Question
The loading animation when a user interacts with the table is expected but the loading animation during the first load of the page is a little bit annoying for the users. Even if I disable the animation it would still show an empty table for 1-2 seconds then show the populated table.

How can I avoid this? Is there any way to set the initial table data when in remote mode (server side) and prevent fetching it remotely (only the initial data)?

**Comment by xaksis** [comment]
hey @florinfratica there is no loading animation included with VGT. Are you sure this isn't something your App is adding?

**Comment by florinfratica** [comment]
Hi, @xaksis.

Indeed the loading animation is something my app is adding. I added it because I don't want to display an empty table for the first few frames (although the animation isn't the best solution for my use case either).

I removed the animation and now the table is displayed empty until the API call is completed. Here is a gif with the behaviour to make it clearer:

![loading-data](https://user-images.githubusercontent.com/866326/107220899-95833f80-6a1b-11eb-9b37-16b06d7f85b0.gif)

As you can see, the table is empty for the first few frames because the API call that fetches table rows hasn't finished when the component is rendered.
So I am wondering if there is any method to provide initial data from client side without having to do the API call (while filtering, sorting etc. would still be server side) in order to avoid displaying an empty table.

**Comment by florinfratica** [comment]
Setting the rows and totalRows options solved this issue.

The problem was that I was initializing the rows with an empty array and totalRows with 0.
