### ISSUE TITLE
How to set row background color dynamically for each row (using inline css)

### ISSUE THREAD

**Issue by dharmdeep** [xaksis/vue-good-table#816]
Hello,
Can someone help me with the custom style for each row? I need to set the background color of each row dynamically. I read the complete document with an example but did not found any solution for this. I found that a custom class is available.
```
       <vue-good-table
        :columns="columns"
        :rows="rows"
        styleClass="vgt-table">
        </vue-good-table>
```

 

But I need a custom style instead of a class like a background color that will be served from DB in the SST table.
Thanks

**Comment by chiragkasera** [comment]
I'm facing the same issue. Any help @xaksis would be appreciated. Thanks

**Comment by xaksis** [comment]
Hey @dharmdeep @chiragkasera `row-style-class` is what you need. it takes a function so you can assign style classes dynamically based on your row. It is in the docs:  https://xaksis.github.io/vue-good-table/guide/configuration/#row-style-class

closing.
