### ISSUE TITLE
selected property with emitSelectedRows returns unexpected result

### ISSUE THREAD

**Issue by MichaelHeydon** [xaksis/vue-good-table#823]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.21.6

What browser?
Chrome

### Expected Behavior
The `selected` property within `emitSelectedRows` is not the value of the checkbox as the documentation describes. Rather it is currently `this.selectedRowCount === this.totalRowCount`.

### Actual Behavior
Is there meant to be an additional `isAllSelected` or the like property within `emitSelectedRows` as well as `selected`?

### Steps to Reproduce the Problem
1. Just toggle the select all on/off to always retrieve false

**Comment by xaksis** [comment]
hey @MichaelHeydon, I'm not sure what `emitSelectedRows` you're referring to. There are separate events on the table that you can listen to for selected row change and all selected:

- on-select-all https://xaksis.github.io/vue-good-table/guide/configuration/table-events.html#on-select-all
- on-selected-rows-change https://xaksis.github.io/vue-good-table/guide/configuration/table-events.html#on-selected-rows-change

closing.

**Comment by MichaelHeydon** [comment]
Sorry, I should have referred to the actual event, not that within `Table.vue`. As within `Table.vue`: 
```
emitSelectedRows() {
      this.$emit('on-select-all', {
        selected: this.selectedRowCount === this.totalRowCount,
        selectedRows: this.selectedRows,
      });
    },
```
So `selected` is currently returning the row count, not  _whether the select-all checkbox is checked or unchecked_ as the documentation describes.
