### ISSUE TITLE
Support multi lang

### ISSUE THREAD

**Issue by machadodev** [xaksis/vue-good-table#826]
- [x] Enhancement Request

Hey guys.

Currently we can only override parts of interface text.

"`Showing ${first} to ${last} ${this.ofText} ${this.total} entries`"
You end up with mixed lang texts and a lot of properties being passed to set these props up.

Does someone know if there's a way to set a lang specific text to the component?
If there isn't, is there anyone working on it? 

I could make a PR, but I'd like to know if there's any work in progress.

Ty.

![Screenshot from 2021-03-04 13-22-15](https://user-images.githubusercontent.com/15857625/109995058-afe3cc80-7cec-11eb-83e1-53fe9f40ef1c.png)

**Comment by xaksis** [comment]
@machadodev the above code only executes if you don't provide your own info function.
you can use your own function for this information instead of passing properties in whatever language you want: 
https://xaksis.github.io/vue-good-table/guide/configuration/pagination-options.html#infofn

closing.

**Comment by machadodev** [comment]
My bad.
I'm using v2.21.4

I just checked releases and **infoFn** is available on **v2.21.5**.
I'll update it.

Thank you for the quick reply! :)

**Comment by xaksis** [comment]
Ah! Makes sense. 👍
