### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by seanhakbb** [xaksis/vue-good-table#828]
### Issue Type (delete the irrelevant ones) 

- [ ] Bug
- [x] **Enhancement Request**
- [ ] Question

### Expected Behavior
What did you expect to happen?
- Be able to set types on filter dropdown

### Actual Behavior
What actually happened?
- Values are always gets converted to string. This is only relevant for remote mode I'm guessing.

#### Example
filterDropdownItems: [{ value: 1, text: 'Landlord', type: 'Number' }, { value: 2, text: 'Tenant', type: 'Number' }, { value: 3, text: 'Admin', type: 'Number' }  ]

#### Suggested support for the same "types" found in the "columns" object:

number - right aligned
decimal - right aligned, 2 decimal places
percentage - expects a decimal like 0.03 and formats it as 3.00%
boolean - right aligned
date - expects a string representation of date eg '20170530'. You should also specify dateInputFormat and dateOutputFormat

**Comment by xaksis** [comment]
@seanhakbb dropdown filters are regular HTML elements that do not support types. However, VGT does let you customize the filters however you want: https://xaksis.github.io/vue-good-table/guide/advanced/#custom-column-filters
So you can customize your filters to support types if you want.

closing.
