### ISSUE TITLE
Search placeholder doesn't work

### ISSUE THREAD

**Issue by teledemic** [xaksis/vue-good-table#829]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.21.7

What browser?
Firefox

### Expected Behavior
Setting searchOptions -> placeholder does nothing. I can see at https://github.com/xaksis/vue-good-table/blob/2e1112569f1c705c7b3b19d6a08491f7aaf92ea2/src/components/VgtGlobalSearch.vue#L15 that it is being set to null rather than using the passed prop `globalSearchPlaceholder`.

**Comment by xaksis** [comment]
@teledemic you're absolutely right. A recent PR broke this. will fix.

**Comment by xaksis** [comment]
released v2.21.8 Thank you!

**Comment by teledemic** [comment]
Looks good - thanks for the quick turnaround!
