### ISSUE TITLE
Failed to import component in my project

### ISSUE THREAD

**Issue by ahallez** [xaksis/vue-good-table#83]
I added these lines to my index.js file:
`import VueGoodTable from 'vue-good-table';
Vue.use(VueGoodTable);
`
When loading the application, I get this error message:
`SyntaxError: 'import' and 'export' may only appear at the top level (2:0) while parsing C:\ScoreExpress\loopback\node_modules\vue-good-table\src\index.js while parsing file: C:\ScoreExpress\loopback\node_modules\vue-good-table\src\index.js`

Any idea what I'm doing wrong?

**Comment by xaksis** [comment]
@ahallez vue-good-table uses ES6, in order to use it like the way you've described, you'd need to have a transpiler in your build process. Are you using one (eg babel) in your build process?

**Comment by cristijora** [comment]
@ahallez @xaksis This might be due to js linting setup.
There are some linters (I think standard) which don't allow you to make imports after some statements.
Make sure all your imports are before any statements.

**Comment by xaksis** [comment]
closing this.
