### ISSUE TITLE
Search functionality does not work when using mode="remote".

### ISSUE THREAD

**Issue by ctwillie** [xaksis/vue-good-table#832]
### Issue Type

- [x] Question

### Specs
vue-good-table 2.21.1
VueJs 2.6.12
Browser: Version 88.0.4324.190 (Official Build) (64-bit)

### Expected Behavior
Enabling searchOptions when using remote mode will allow you to search table.

### Actual Behavior
Enabling searchOptions when using remote mode does not allow you to search table.

### Steps to Reproduce the Problem
1. Create a standard vue-good-table table with searchOptions ```enabled: true```. Searching works perfectly fine. 
1. Convert table to use ```mode="remote"```. Remote mode works fine, but searching does nothing.

**Comment by p0psicles** [comment]
I also just recently started using remote mode. But how I understand, you pass filters, sort ordering through params to your backend. 

I think you should not rely on a single search field for this, but use a specific column filter.

**Comment by xaksis** [comment]
Hey @ctwillie, as mentioned in [the documentation](https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html#why-remote-mode) remote mode leaves the task of searching and filtering to you so you can request it from your backend. 
Think about the functionality, you're getting table data from the backend 1 page at a time, if you search you need to search the entire set of rows not just what you just fetched so it doesn't make sense for search to just filter/search what you fetched. Instead, it just emits an event with the right params. You can then use this event to get the right set of (matching) rows from your backend.

Closing!
