### ISSUE TITLE
Refresh Data with axios

### ISSUE THREAD

**Issue by denizsult** [xaksis/vue-good-table#846]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.21.9

What browser?
Chrome
### Expected Behavior
What did you expect to happen?

When I add data to the table with Axios, I want the data in the table to be refreshed.

### Actual Behavior
What actually happened?
The same data remains.

**Comment by p0psicles** [comment]
This is more likely a Vue user issue. You need to make sure that Vue reactivity is triggered. So you probably need something like `Vue.set(myrootObject, 'vgtRows`, axiosData)`

**Comment by denizsult** [comment]
Thanks a lot anyway. I solved.
