### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by power-media** [xaksis/vue-good-table#875]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
2.21

What browser?
Irrelevant

### Expected Behavior
What did you expect to happen?
Relates to documentation: https://xaksis.github.io/vue-good-table/guide/advanced/remote-workflow.html#provide-handlers-for-user-events
There is explained the method to support column sorting: 
` onSortChange(params) {
      this.updateParams({
        sort: [{
          type: params.sortType,
          field: this.columns[params.columnIndex].field,
        }],
      });
      this.loadItems();
    },`

### Actual Behavior
What actually happened?
It does not work, what works is:
` onSortChange(params) {
      this.updateParams({
        sort: params,
      });
      this.loadItems();
    },`

### Steps to Reproduce the Problem
Please detail your steps here

1.Just follow mentioned documentation page
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by xaksis** [comment]
ha! It totally depends on what you're sending to your backend and what the backend expects. This is just a hypothetical example. If your system supports multiple sort, send array. If it supports single sort, send object and so on.

closing.

**Comment by power-media** [comment]
@xaksis , Thanks for reply. I fully followed the documentation, and the problem occurred purely at the frontend.
