### ISSUE TITLE
Enhancement tfoot slots

### ISSUE THREAD

**Issue by rolexta** [xaksis/vue-good-table#877]
### Add empty slot for tfoot
- [x] Enhancement Request

Just provide an empty slot for developer to put their own custom tfoot

**Comment by xaksis** [comment]
You can do this a few different ways - add an extra row to the data and style the row however you want. or use the https://xaksis.github.io/vue-good-table/guide/configuration/#table-actions-footer-slot to add whatever you need.

closing.

**Comment by handhikadj** [comment]
@xaksis add an extra row to the data is extremely unintuitive.
how is it so hard to add an empty `tfoot` slot?
