### ISSUE TITLE
Overflow of vertical space / z-index?

### ISSUE THREAD

**Issue by dyerrington** [xaksis/vue-good-table#880]
### Issue Type (delete the irrelevant ones) 

- [x] Bug (likely not a bug)
- [x] General Question

### Specs
What version are you using?
2.21.10

What browser?
- Chrome
- Safari

### Expected Behavior
What did you expect to happen?
I'm creating a control to help users delete multiple records or update their status using a bootstrap button select element.  I want the element displaying the menu items to expand over the table rows.

### Actual Behavior
What actually happened?
When adding interactive elements in the column template that expand beyond the height of the table, the z-index seems to expand below the table and overflow out of sight.

### Steps to Reproduce the Problem
Add this element to a column template:

```html
              <vue-good-table
                  :columns="columns"
                  :rows="rows">

              <template slot="table-column" slot-scope="props">
                  <span v-if="props.column.field =='remove'">
                    <div class="btn-group" role="group">
                      <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                      </button>
                      <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1" style="z-index: 10;">
                        <li><a class="dropdown-item" href="#" style="z-index: 9999;">Dropdown link</a></li>
                        <li><a class="dropdown-item" href="#" style="z-index: 9999;">Dropdown link</a></li>
                      </ul>
                    </div>
                  </span>
            </template>
           ...
```

![image](https://user-images.githubusercontent.com/2257834/132144054-454f0b47-264f-43ab-a8e7-2953b1e9ea1e.png)

**Comment by xaksis** [comment]
hey @dyerrington sorry for the delay. Does bootstrap button select element have an 'attach-to-body' property? What's happening is that the js/css is attaching the dropdown element to the button itself. It is a [known issue](https://stackoverflow.com/questions/31829312/bootstrap-dropdown-clipped-by-overflowhidden-container-how-to-change-the-conta) and not related to VGT specifically.

closing.
