### ISSUE TITLE
dateInputFormat for Unix timestamps?

### ISSUE THREAD

**Issue by notreallymyself** [xaksis/vue-good-table#882]
### Issue Type
- [x] Question

### Specs
What version are you using?
v2.21.10

What browser?
Chrome / Firefox

### Expected Behavior
I have columns in a database that contain Unix timestamps, I was hoping I could convert these to regular dates/datetime using the 'dateInputFormat' & 'dateOutputFormat' option while defining a column

### Actual Behavior
I didn't find the right dateInputFormat value to pass on the documentation, in order to specify that I'm using unix timestamps as an input, it is not clear whether this is supported or not

### Steps to Reproduce the Problem
Please detail your steps here

1. Only step is to use Basic Example from the docs, from my tests only d/m/y/etc formatting is supported

**Comment by xaksis** [comment]
If you look at datefns input formats, you will see millisecond timestamp: `T` or seconds timestamp `t`. I think one of these should work for `dateInputFormat` depending on what you're getting from your db.
https://date-fns.org/v2.17.0/docs/parse

closing. let me know if this doesn't work.
