### ISSUE TITLE
How many rows can it handle ?

### ISSUE THREAD

**Issue by WordpressArtist** [xaksis/vue-good-table#883]
- [x] Question

### Specs
What version are you using?
2.21.10

I google but cannot find how many records can vue-good-table can handle ?..
i have almost 5-10k records can it handle that much records ??

right now i have 100s of records working fine but when i push live client will add lots of data upto 5-8 thousands..

Thank you

**Comment by TheJaredWilcurt** [comment]
Depends on:

* The computer running the code
* The browser
* How many columns
* How many custom components you've got rendering in the cells and how complex they are
* etc.

There is no "answer" to this. as it is highly dependent on a wide number of factors.

In general, you should use paging and only show a portion of the records at a time. It would be better to store your data in a database, and to request a page of 100 records at a time. Then let users use the pagination, filters, and sorting, to interact with the table, which in turn modifies the url you are using to get data from the backend.

**Comment by xaksis** [comment]
@WordpressArtist if you have several thousand rows of data, you should use pagination no matter what table you use - it is not only better for UX but also technically rendering that many UI elements will slow down any device. Virtual recyclable doms are one way to solve this but VGT doesn't support that.
