### ISSUE TITLE
Dynamicly transfrorm label to textarea when user click on label

### ISSUE THREAD

**Issue by timur900** [xaksis/vue-good-table#90]
Hi. I like your project , but i have the problem. I should create table where third element column dynamicly changed when it was clicked and transform to textarea where user can enter information. How can i do this ?PS sorry for my language ? i know this is just scary but i try do this better/

**Comment by xaksis** [comment]
hey @timur900 
your english is totally fine! 

first, *update to v1.14.3*. after that... I created a jsfiddle for you to see how you can do it: 
https://jsfiddle.net/aks9800/5pvh4r9p/4/

closing this for now. comment if this doesn't solve your problem, and i'll re-open the issue.
