### ISSUE TITLE
How to work with Multi Dimensional Array Object

### ISSUE THREAD

**Issue by keyurptl** [xaksis/vue-good-table#93]
Thanks for such great plugin. 

It works for single dimension array. But my question is how it work in multi Dimension array. 

https://www.screencast.com/t/nCaAFfCADpv

Please check above SS My data is something like that. Array inside each row so how can i access value for that.

**Comment by adrienbucci** [comment]
Did you find a way?

**Comment by xaksis** [comment]
@keyurptl I'm not exactly sure what you want to do, my guess is your data has nested array and you want to reference things within an array? the field property of a column can take - a string (representing the property name, ex: 'company'), a dot notation string (like 'company.createdAt') or a function. What do you want the columns to be? If you mean you want to have groupings within the table like: 
```
company A
------------------------------------
project  | project date | project owner

company B
-------------------------------------
project  | project date | project owner
```
that kind of grouping is currently not supported by the plugin. Let me know what you want your table to look like.

**Comment by adrienbucci** [comment]
Hi dear,

Thanks for the awesome work, as well.

I was asking because I was thinking about having this kind of result:

Company A:
Address 1 street bla bla bla
Address 2 street pi pa po

Company B:
Address 3 street bla bla bla
Address 4 street pi pa po

and so on


Parsed from a Json like this:

company A : {
'name': 'tatz',
'addresses': [
{
   'name': 'address 1',
   'address': 'bla bla bla',
},
{
   'name': 'address 2',
   'address': 'pi pa po',
}
]
}

etc

Do you know what I mean ?

Please let me know :)

Thanks,

Adrien

2017-10-19 20:31 GMT+02:00 xaksis <notifications@github.com>:

**Comment by xaksis** [comment]
ah yeah, so that kind of grouping is currently not possible with vue-good-table. I will try and look into it when I get some free time though.

**Comment by xaksis** [comment]
closing. will be addressed together with https://github.com/xaksis/vue-good-table/issues/81

**Comment by keyurptl** [comment]
Hello Thanks for support and  Sorry for late reply.  I want something like this . 
Like There is list of user and also displaying all projects which is assigned to that user. So how can i provide filter for project list.

https://www.screencast.com/t/vm65S7VOT

https://www.screencast.com/t/TSVILmw2IzP 

Above is the user list which I am displaying. 

So what actually is  there user array and inside user array child array of project so I want to refrear that child array key as field name.   And I have also generated for Search in Multidimensional array here. #100

**Comment by keyurptl** [comment]
@adrienbucci No I am looking for solution.

**Comment by adrienbucci** [comment]
@keyurptl 
Yes, I understand, we're facing the same need.
Hop our great @Xaksis will manage with something :)

**Comment by keyurptl** [comment]
@adrienbucci okay Thanks.  And   @xaksis  Let me know when this will be manageable. I am  eagerly  waiting for check that.

**Comment by uzianhar** [comment]
hallo, sorry for late. I'm facing this while I'm using this for vue 3.
I found my own solution with slot props, I can modify the table-row and adding button for that.
I'm glad for this project, advance enough for datatable rather else.

I don't know this method right, but it's works for me, and may be reference for other.


<vue-good-table :columns="columnsUser" :rows="listUser" :line-numbers="true" :is-loading="loading"
                        :search-options="{ enabled: true }" :pagination-options="{ enabled: true }"
                        styleClass="vgt-table striped bordered"> 
                                            
                        <template #table-row="props">
                        
                            <span v-if="props.column.field == 'status'" style="text-transform:capitalize">
                                {{ props.row.status }}
                            </span>
                            
                            <span v-if="props.column.field == 'google_id'">
                                <button class="btn btn-danger btn-sm" @click="delUser(props.row.google_id)"><i
                                        class="fa fa-trash"></i></button>
                            </span>
                            
                        </template>
                        
                    </vue-good-table>
