### ISSUE TITLE
Error on component import 

### ISSUE THREAD

**Issue by nmfarshad** [xaksis/vue-good-table#95]
After npm install importing the module using below code throws this error 
import VueGoodTable from 'vue-good-table';

Module build failed: Error: Couldn't find preset "env" relative to directory "D:\\wamp64\\www\\dashui2\\node_modules\\vue-good-table"

What am I doing wrong please advice !

**Comment by xaksis** [comment]
hey @nmfarshad, this has been solved earlier. You need: 
`npm install babel-preset-env --save-dev`

please take a look here for details: https://github.com/xaksis/vue-good-table/issues/72

closing for now,
