### ISSUE TITLE
OnClick and LineNumbers Props not setting

### ISSUE THREAD

**Issue by cr1t** [xaksis/vue-good-table#96]
Hi

I'm using the control like this in the example
http://jsfiddle.net/w4zku52c/

Setting LineNumbers to true and onclick prop not working.

**Comment by xaksis** [comment]
@cr1t strange, i'll look into it shortly.

**Comment by xaksis** [comment]
@cr1t this seems to be an issue only for the generated file... using the plugin normally seems to be working fine. i'll continue debugging

**Comment by xaksis** [comment]
ah okay... it wants you to use snake case for html attributes which is probably the correct way of doing it anyway: 
```html
<vue-good-table
      :columns="columns"
      :rows="rows"
      :line-numbers="true"
      :paginate="true"
      :on-click="onClickFn"/>
```
should work. closing this for now.

**Comment by nwaughachukwuma** [comment]
Hi @xaksis, is it possible to get column index on-click? It will be very useful. Thanks
