### ISSUE TITLE
Is i can render defaults with slot="table-row"?

### ISSUE THREAD

**Issue by Hellek** [xaksis/vue-good-table#98]
Hi! How can i want to use inside this something like

```
<td v-if="props.row.order_id">
<a :href="'/order/' + props.row.order_id">{{ props.row.order_id }}</a>
</td>
<td v-else>{{ render_other }}</td>
```
I need this cause column counts comes dinamically and i can't hardcode this

I tried to use `field: () => {...} for this and html: true`
But theare another problem property
`:defaultSortBy="{field: 'order_id', type: 'desc'}"`
stop sorting by default

**Comment by xaksis** [comment]
I can't say that i'm 100% sure what you want to do here @Hellek 
can you create a jsfiddle to show me what you want to do?
you can use the following fiddle as your base: 
https://jsfiddle.net/aks9800/mn27rd7b/

**Comment by Hellek** [comment]
I cant show it on jsfiddle cause i don't understand how i can code it.
I just trying to find solution. I need wrap text to link if it's a special label, like
if (field == "page_id") {
    <td><a href="/page_id">page_id</a></td>
} else {
    <td>field</td>
}
I guess that better way to do this use slots, but i dont understand how do it with this plugin

**Comment by xaksis** [comment]
@Hellek 

here's one way to conditionally render your template within td: 
https://jsfiddle.net/aks9800/mn27rd7b/1/

go through that and let me know if that makes sense?

**Comment by Hellek** [comment]
So what if i have 20 columns? Or columns from user to user varies? Hardcoding of columns a bad idea.
Is there way to use something like this
```
<div id="app">
  <vue-good-table :columns="columns" :rows="rows">
    <template  slot="table-row" slot-scope="props">
      <td v-if="props.row.age < 6" class="right-align">Child</td>
      <td v-else>{{ other_porps_renders_as_defaults_without_hardcoding }}</td>
    </template>
  </vue-good-table>
</div>
```

**Comment by Hellek** [comment]
```
<div id="app">
  <vue-good-table :columns="columns" :rows="rows">
    <template  slot="table-row" slot-scope="props">
      <td v-if="props.row.age > 20" class="right-align">{{ props.row.age }}</td>
    </template>
  </vue-good-t
```
This erase all other fileds. Not rewrite just age by IF condition

**Comment by xaksis** [comment]
@Hellek if you look through the documentation, you'll find https://github.com/xaksis/vue-good-table#additional-columns
which explains how to add just the custom column you want, every other column is rendered as default.

**Comment by Hellek** [comment]
OK, I'll try again explain a problem.
I have 20 columns, and want change a view of one of them by field condition. For this example i use order_id. If i use this
```
<td v-if="props.row.order_id">
    <a :href="'/order/' + props.row.order_id">{{ props.row.order_id }}</a>
</td>
```
inside slot="table-row", table will contain just this one row, but i expect that table must render as original, but order_id <td> will contain not raw value, but value inside wrapper. In this example it's <a> tag

**Comment by Hellek** [comment]
@danielbruni 
For now i do this like that
```
field: (rowObj) => {
     return <a :href="'orders/' + rowObj.id">rowObj.id</a>
}
```
Looks that i want, but "default sorting by id field" droped, and more, sorting by this field not sort rows as before. I don't understand why it's happens.

Another thing. I want to filter dates as date() objects, but show with my custom formatting. Let's say, that Today id 10 jan of 2017, when I filter by desc i expect to see something like this
12 jan (2017)
11 jan (2017)
Today (2017)
09 jan (2017)
09 jan (2016)

But i see something like
09 jan (2017)
09 jan (2016)
11 jan (2017)
12 jan (2017)
Today (2017)
Because new sorting algo think that it's strings, that's why 09 is first and Today is last
