### ISSUE TITLE
How can i extend "field" types?

### ISSUE THREAD

**Issue by Hellek** [xaksis/vue-good-table#99]
For example, i want to auto-mask phone numbers like +0 (000) 000 0000. Or in my case i need show dates like dd.mm.YY but if it's closest dates i need to show (yesterday, today, tomorrow) and it's must work with sorting like:
(today + 3 days)
(today + 2 days)
Tomorrow
Tomorrow
Today
(today - 2 days)

**Comment by xaksis** [comment]
@Hellek 'field' property takes a function which is supplied rowObject as a parameter so you can do something like 
```javascript
  {
    field: fieldFn
  }
  
  // in methods
  fieldFn(rowObj) {
    // do something with the row object
  }
```
you can use your custom method to do what you want. I'm going to close this for now, comment back if this doesn't solve your problem and i'll re-open it.
